- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
Vector elasticsearch sink can use a record field value to be used as the elasticsearch index. Config generator generates a transform block which determines the index name, and sets it as the value of `write_index` field. As a side effect, this field is  getting sent to elastiocsearch as part of the log record.
This PR attempts to disable sending this field to elasticsearch by using `encoding.except_fields = ["write_index"]` config.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3071
> LOG-3071: Elasticsearch output: Remove 'write_index' field from log record

- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- test/functional/normalization/audit_logs_format_test.go
Added a `"level: "default"` field in the audit logs to get rid of the `'Unknown Severity'` error in vector logs while sending audit logs to Google Cloud Logging.
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-2961
> LOG-2961: Fix 'Unknown Severity' error for audit logs in Google Cloud Logging

- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/normalization/audit_logs_format_test.go
Enabled vector functional tests for audit logs.
Fixed a bug related to host audit log `@timestamp` field.
/cc 
/assign 
/cherry-pick release-5.5
- JIRA: https://issues.redhat.com/browse/LOG-2960
> LOG-2960: Enable functional audit log tests for vector

- controllers/forwarding/forwarding_controller.go
- internal/collector/collector.go
- internal/collector/service_monitor.go
- internal/constants/constants.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/reconciler.go
- internal/reconcile/service_monitor.go
- internal/runtime/monitoring.go
This PR:
* fixes ServiceMonitor order of reconciliation to try to Get before Create
* Refactors  ServiceMonitor code out of k8shandler/collection.go to decouple from ClusterLoggingRequest
* https://issues.redhat.com/browse/LOG-2919
> LOG-2919: fix order of reconcilation for ServiceMonitor

- internal/k8shandler/forwarding.go
The processing of the forwarder pipelines introduced in #1587 contains a bug where custom output pipelines are overwritten by the newly-created outputs for LokiStack. This PR fixes this issue by adding the LokiStack outputs to the set of already existing outputs.
/cherry-pick release-5.5
- JIRA: [LOG-3090](https://issues.redhat.com//browse/LOG-3090)
> LOG-3090: Do not overwrite custom outputs when using LokiStack as log output

- bundle/manifests/metadata-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- config/rbac/metadata_reader_clusterrole.yaml
Since vector version 0.23, the serviceaccount associated with vector needs permission to list kubernetes nodes.
This change is listed as a breaking change in the upgrade guide.
This PR adds appropriate permissions to `logcollector` service account.
Reference: https://vector.dev/highlights/2022-07-07-0-23-0-upgrade-guide/#kubernetes-logs-list-watch-nodes
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:  https://issues.redhat.com/browse/LOG-3094
> LOG-3094: Add list 'nodes' permission to logcollector serviceaccount

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/rbac/cluster-logging-operator_clusterrole.yaml
- controllers/clusterlogging/clusterlogging_controller.go
- controllers/forwarding/forwarding_controller.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/collection.go
- internal/k8shandler/reconciler.go
- main.go
- test/framework/functional/framework.go
- test/framework/functional/message_templates.go
- test/functional/normalization/audit_logs_format_test.go
- test/functional/normalization/message_format_test.go
- test/helpers/types/types.go
- test/matchers/log_format.go
This PR:
* add support to vector to include openshift.cluster_id in the log payload
* Enables some audit functional testing for vector
* https://issues.redhat.com/browse/LOG-2720
> LOG-2720: Add clusterID to data model for vector

- Makefile
Occasionally the `ci/prow/lint` check fails because `golangci-lint` does not complete inside its own timeout (which is one minute). This PR extends the timeout to three minutes to allow slow lint runs to succeed as well.
> Extend lint timeout to avoid occasional CI failures

- internal/generator/fluentd/output/syslog/cert-key.go
- internal/generator/fluentd/output/syslog/syslog.go
- test/framework/e2e/syslog_conf.go
Implement support for client-side certificate and key for the remote_syslog fluentd plugin
/cc @vimalk78 
- Depending on PR(s): https://github.com/ViaQ/logging-fluentd/pull/42
- JIRA: https://issues.redhat.com/browse/LOG-2843
> LOG-2843: tls.key and tls.cert not in fluentd real configuration when forwarding logs using syslog tls

- test/e2e/consoleplugin/smoke_test/consoleplugin_test.go
Failing in tests using cluster claims, probably based on bad assumptions.  
Keeping the initial part of the test that verifies the plugin is created.
> NO-JIRA: Remove flaky part of console test.

- bundle/metadata/properties.yaml
This PR:
Updates the max supported OCP version to 4.12
https://issues.redhat.com/browse/LOG-3123
> LOG-3123: fix OCP max version

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/rbac/cluster-logging-operator_clusterrole.yaml
- internal/collector/fluentd/visitors.go
- internal/collector/vector/visitors.go
- internal/generator/fluentd/conf_test.go
- internal/k8shandler/collection.go
- internal/tls/profile.go
- internal/tls/tls.go
- internal/tls/tls_test.go
This PR enables cluster-logging-operator to pull `.spec.tlsSecurityProfile` of `APIServer` resource in `config.openshift.io/v1`, and generate TLSProfile for the collector. 
The TLSProfile is added to  a file `openssl.cnf`,a nd the path is added to environment variable `OPENSSL_CONF`.
/cc 
/assign 
/cherry-pick 
- Github issue: https://issues.redhat.com/browse/LOG-3002
> LOG-3002: Configure cluster-logging-operator to honor the global tlsSecurityProfile

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
This PR:
* fixes the warning of unused parameters
* https://issues.redhat.com/browse/LOG-3074
> LOG-3074: remove unsed paramenter to fix logs

- bundle/metadata/properties.yaml
* updates maxOpenShiftVersion to 4.12
https://issues.redhat.com/browse/LOG-3119
> LOG-3119: Update max OCP to 4.12

- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
When the vector collector pods start, there are healthchecks that run for every sink, including Cloudwatch.  The healthcheck for cw fails due to a validation error: Value '{{ group_name }}' at 'logGroupNamePrefix'  must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]
Since we use template syntax for this field, the healthcheck will always fail because it is run before any events actually flow through Vector.   We are disabling healthcheck for this sink
/cc @vimalk78 @jcantrill 
- https://issues.redhat.com/browse/LOG-3093
> LOG-3093: Healthcheck fails for vector cloudwatch forwarding

- test/e2e/logforwarding/fluent/fluent_secure_test.go
- test/e2e/logforwarding/fluent/fluent_test.go
- test/e2e/logforwarding/loki/forward_to_loki_test.go
This PR:
* modifies several e2e scripts to only call cleanup/must-gather upon test failure
* https://issues.redhat.com/browse/LOG-3141
cc @vparfonov  you have an open PR for splunk which needs to ensure the same.
> LOG-3141: Only call cleanup and must-gather upon test failure

- internal/collector/vector/visitors.go
- test/framework/functional/vector/deploy.go
vector uses `VECTOR_LOG` as the env variable to control logging. The env variable used in CLO now, `LOG` is deprecated.
/cc 
/assign 
/cherry-pick 
- JIRA:  https://issues.redhat.com/browse/LOG-3122
> LOG-3122: Use correct env variable for vector logging

- internal/collector/collector.go
- internal/collector/fluentd/run_script.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/sources_test.go
- test/framework/functional/framework.go
Updated fluentd `run.sh` to add logic to detect correct prometheus bind address
When the cluster is dual stack, the collector pod will have an ipv4 address and an ipv6 address. Downward API will add a `status.podIPs` field in the pod, use these array of values. If one of the IPs is an ipv6 address, use `[::]` as the bind address, if no IP is an ipv6 address and all ips are ipv4, use `0.0.0.0` as the bind address.
sample logs from dual stack cluster
```
POD_IPS: 10.131.0.34,fd01:0:0:4::22, PROM_BIND_IP: [::]
```
sample logs from ipv4 only cluster
```
POD_IPS: 10.217.0.220, PROM_BIND_IP: 0.0.0.0
```
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-3055
> LOG-3055: Detect correct prometheus bind address

- apis/logging/v1/clusterlogging_types.go
The `managementState` attribute in the cluster-logging-operator has a `string` type so it converts an empty value received from the apiserver to `""` but an empty string is not a valid value for this field server-side, so if the operator tries to write the same resource it read back to the apiserver this generates an error.
This PR fixes this issue by omitting the value from the serialized output when it is empty.
/cherry-pick release-5.5
This was based on a discussion on Slack, so there's no JIRA issue for this. I can create one though.
> Fix serialization of empty managementState value

- test/functional/normalization/audit_logs_format_test.go
- test/functional/normalization/eventrouter_test.go
- test/functional/normalization/message_format_test.go
Make clusterid optional until fluentd changes merge
* https://issues.redhat.com/browse/LOG-3112
> LOG-3112: Temp make clusterid optional until fluentd changes merge

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_collection_resources
- must-gather/collection-scripts/gather_elasticsearch_operator_resources
- must-gather/collection-scripts/gather_install_resources
- must-gather/collection-scripts/gather_logstore_resources
- must-gather/collection-scripts/gather_visualization_resources
- test/e2e/collection/cleanup.sh
- test/e2e/logforwarding/cleanup.sh
This PR:
* modifies must-gather scripts to conditional fetch resources based upon what is deployed
* Removes some fetches based upon resources already being gathered (e.g. pod logs)
* Removes obsolete constructs (e.g. DS/fluentd, containerName: fluentd)
* https://issues.redhat.com/browse/LOG-3159
> LOG-3159: must-gather based upon whats deployed

- internal/collector/collector.go
This PR:
* removes the time mount which is a holdover from pre-CRIO to fix issues on RHCOS9
* https://issues.redhat.com/browse/LOG-3117
> LOG-3117: Remove unused volume to support RHCOS9

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
Vector is missing the field 'sequence', which was added to fluentd as a way to deal with a lack of actual nanoseconds precision.   We are confident this addition to the existing lua script will not penalize us, but we should be aware of any performance degradation.
/cc @vimalk78 @syedriko 
- https://issues.redhat.com/browse/LOG-3106
> LOG-3106: Vector add sequence field to elasticsearch output

- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/collection.go
- internal/k8shandler/finalizer.go
- internal/k8shandler/logstore.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/visualization.go
The `ClusterLoggingRequest` struct contains a `cluster` variable that is used as a "cache" for the current ClusterLogging CR that is reconciled. The variable is meant to be written only once during the start of reconciliation and only with a result from the `getClusterLogging` function, so that migrations are correctly applied. These migrations are currently only applied in-memory inside the CLO and never written back to the apiserver.
The `Update` and `UpdateStatus` functions write the updated resource back into the variable passed to them, which causes a resource without applied migrations to be in the variable after the call happened.
This PR changes the code for updating status information on the ClusterLogging CR to use an modified copy of the CR and not write the result back into …
> LOG-3157: Do not use global variable when updating CR status

- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/collection.go
- internal/k8shandler/logstore.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/visualization.go
The `ClusterLoggingRequest` struct contains a `cluster` variable that is used as a "cache" for the current ClusterLogging CR that is reconciled. The variable is meant to be written only once during the start of reconciliation and only with a result from the `getClusterLogging` function, so that migrations are correctly applied. These migrations are currently only applied in-memory inside the CLO and never written back to the apiserver.
The `Update` and `UpdateStatus` functions write the updated resource back into the variable passed to them, which causes a resource without applied migrations to be in the variable after the call happened.
This PR changes the code for updating status information on the ClusterLogging CR to use an modified copy of the CR and not write the result back into …
> LOG-3049: Do not use global variable when updating CR status

- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
- internal/generator/fluentd/output/syslog/passphrase.go
- internal/generator/fluentd/output/syslog/syslog.go
A fix for the fix for [LOG-2843](https://issues.redhat.com//browse/LOG-2843), added support for client key passphrase missed in the original fix.
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-2843
> LOG-2843, take two. Added client key passphrase

- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
Cloned from v5.6 bug
When the vector collector pods start, there are healthchecks that run for every sink, including Cloudwatch. The healthcheck for cw fails due to a validation error: Value '{{ group_name }}' at 'logGroupNamePrefix' must satisfy regular expression pattern: [.-_/#A-Za-z0-9]
Since we use template syntax for this field, the healthcheck will always fail because it is run before any events actually flow through Vector. We are disabling healthcheck for this sink
/cc @vimalk78 @jcantrill
- 5.6 bug - https://issues.redhat.com/browse/LOG-3175
- 5.5 cloned issue - https://issues.redhat.com/browse/LOG-3093
> [release-5.5] LOG-3175: Vector healthcheck fails for cloudwatch forwarding

- hack/testing-olm/assertions
- hack/testing-olm/test-367-logforwarding.sh
Sometimes got exceptions with `oc wait --for=delete` in case deleting going to fast command this PR replace it with periodic `oc get` command 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> Fix issue with waiting on delete CL and CLF instance

- test/functional/normalization/audit_logs_format_test.go
- test/helpers/types/types.go
This PR:
* fixes additional audit log functional tests to make clusterid optional until we can merge the fluent changes
* https://issues.redhat.com/browse/LOG-3112
* blocks https://github.com/ViaQ/logging-fluentd/pull/50
> LOG-3112: fix fluentd audit tests for clusterID

- internal/collector/service.go
- internal/collector/service_monitor.go
- internal/k8shandler/collection.go
- internal/reconcile/service.go
- internal/utils/comparators/services/comparator.go
- internal/utils/comparators/services/comparator_test.go
This PR:
* refactors collector service reconciliation to try to get a service before trying to create
* Adds events to service reconciliation
* https://issues.redhat.com/browse/LOG-3176
> LOG-3176: refactor service reconciliation to get before create

- apis/logging/v1/cluster_log_forwarder.go
- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
Rebase of previous work by Calvin L.
Added optional Elasticsearch.Version field to types.
Added suppress_type_name = true -- if forwarding is greater than ES 7.x or is empty (zero value int)
Can forward both to default and external Elasticsearch store at the same time with a ClusterLogForwarder custom resource.
A version must now be specified in the output spec, if using ES v6.x or below
This PR addresses an issue with forwarding logs using vector to Elasticsearch 8.x (ES). Forwarding logs to ES 8.x produced the following error in the logs: Action/metadata line [1] contains an unknown parameter [_type].
To fix the error, in the vector.toml config file, [sinks - <ES>] section, suppress_type_name = true needs to be added for ES versions 7.x and higher. However, we cannot suppress the type …
> LOG-2769: Support Elasticsearch 8.x as an output using vector

- test/framework/e2e/framework.go
This PR:
* Reduces the default timeout to 5 min. to expedite e2e job termination
* https://issues.redhat.com/browse/LOG-3191
> LOG-3021: Reduce default timeout to 5 min

- .gitignore
- Makefile
This PR:
* adds a make target to generate coverage report
* https://issues.redhat.com/browse/LOG-694
> LOG-694: Add make target to generate coverate

- Dockerfile.e2e
This PR tries to fix the permission errors seen here https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-logging-operator/1712/pull-ci-openshift-cluster-logging-operator-master-functional/1583124432551940096
> try to fix src e2e permissions

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manager/manager.yaml
This PR:
* modifies the CSV to ref "latest" in bundle/manifest to allow us to re-enable proper bundle creation in CI https://github.com/openshift/release/pull/31572 .  Current e2e and productization of the bundle already has logic to replace the images so this change should not regress bundle
> fix CSV to re-enable proper bundle building in CI

- internal/k8shandler/serviceaccount.go
- internal/reconcile/service_account.go
This PR:
* Refactors reconcile of serviceaccount which will block https://issues.redhat.com/browse/LOG-1068
* https://issues.redhat.com/browse/LOG-3211
> LOG-3211: Refactor reconcile of serviceaccount

- test/framework/functional/message_templates.go
- test/functional/normalization/audit_logs_format_test.go
- test/functional/normalization/eventrouter_test.go
This PR:
* Updates functional testing to require clusterID after completing the operator and image implementation
* https://issues.redhat.com/browse/LOG-2715
> LOG-2715: Require clusterID for all collector impl

- internal/collector/config.go
- internal/collector/fluentd/visitors.go
- internal/collector/vector/visitors.go
This PR
-  disables adding generated openssl.cnf file to secret and configmap
-  disables adding env variable `OPENSSL_CONF` which points to the openssl.cnf file.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> Disable adding OPENSSL_CONF for tlsSecurityProfile

- must-gather/collection-scripts/gather
This PR:
* fixes an empty logging must-gather by reverting changes introduced in previous commit
* https://issues.redhat.com/browse/LOG-3213
> LOG-3213: fix empty logging must-gather

- internal/constants/constants.go
- internal/k8shandler/collection.go
- olm_deploy/scripts/operator-install.sh
For some reason the olm operator has begun adding the label 'podSecurityLabelSync' = true to the openshift-logging namespace.   This results in our pod security labels being overwritten.  These new labels prevent our pods from starting.
This change adds the "false" sync label so that our privileged policy is maintained.  
Note:  This should not need to be done according to the IMPORTANT section in our docs, as well as several internal resources
/cc @syedriko @vimalk78 
- JIRA:   https://issues.redhat.com/browse/LOG-3194
- OLM Controller change: https://issues.redhat.com//browse/OLM-2695
- Docs:  https://docs.openshift.com/container-platform/4.11/authentication/understanding-and-managing-pod-security-admission.html
> LOG-3194: Add pod security sync label

- internal/metrics/alerts/fluentd.go
This PR:
fixes the cardinality issue for the alart when there is a many-to-many for both evaluations
* https://issues.redhat.com/browse/LOG-3245
* forward port of https://github.com/openshift/cluster-logging-operator/pull/1738
> LOG-3245: fix cardinality issue with FluentdQueueLengthIncreasing

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
This is a correction of the logic from [LOG-2769](https://issues.redhat.com//browse/LOG-2769).   We are adding 'suppress_type_name = true' only if the version is specified and is 8 or greater.
/cc @syedriko @vimalk78 
- https://issues.redhat.com/browse/LOG-3224
- original PR:  https://issues.redhat.com/browse/LOG-2769
> LOG-3224: ES suppress type fix 

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
This PR:
* fixes json parsing by vector when structuredType is not defined.  It sends message field as-is
* https://issues.redhat.com/browse/LOG-3195
> LOG-3195: fix json parsing by vector when structuredtypename not defined

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/ingress.go
This PR:
* fixes an unused parameter warning for fluentd by removing the parameter
* https://issues.redhat.com/browse/LOG-3074
> LOG-3074: fix unused parameter warning

- must-gather/collection-scripts/gather_cluster_logging_operator_resources
This PR fix command for getting product version, now it will use regexp to grep CSV name. This is need because CSV can be different dependent of build `clustrerlogging | cluster-logging`
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-2962: fix command for getting product version: using regexp to grep CSV name

- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
This PR:
* fixes json parsing by vector when structuredType is not defined.  It sends message field as-is
* https://issues.redhat.com/browse/LOG-3284
> LOG-3284: fix json parsing by vector when structuredtypename not defined

- bundle/manifests/cluster-logging_scheduling.k8s.io_v1_priorityclass.yaml
- config/default/kustomization.yaml
- config/scheduling/cluster-logging_scheduling.k8s.io_v1_priorityclass.yaml
- config/scheduling/kustomization.yaml
- internal/collector/collector.go
- internal/runtime/priorityclass.go
- main.go
Update priority class value to be closer to system-cluster-critical
* https://issues.redhat.com/browse/LOG-3287
* backport of https://github.com/openshift/cluster-logging-operator/pull/1725
> LOG-3287: replace priorty class with system-node-critical

- internal/generator/vector/output/security/passphrase.go
- internal/generator/vector/output/splunk/splunk_test.go
- Fixed vector config template for Passphrase.
- Added Unit tests for reproducing, and fixing  the problem.
/cc @vparfonov 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3298
> LOG-3298: Fix Passphrase config template

- internal/generator/vector/elements/elements.go
- internal/generator/vector/pipelines.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/normalization/multiline_exception_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1796
> LOG-1796:Add multi-line exception detection for Vector collector

- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
- test/functional/outputs/loki/application_logs_test.go
- test/functional/outputs/loki/audit_logs_test.go
'tag' is un-documented as a label key, nor is it part of viaq data model   It needs to be removed from Loki output.  Our Loki output needs to be aligned with our ES logstore output, which does not contain 'tag'. 
/cc @syedriko @vimalk78 
- JIRA task: https://issues.redhat.com/browse/LOG-3242
- Loki labelKeys: https://github.com/openshift/cluster-logging-operator/blob/master/apis/logging/v1/output_types.go#L233
- Viaq data model:  https://viaq.github.io/documentation/data_model/public/data_model.html
> LOG-3242: remove loki tag label from fluentd

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- test/functional/outputs/loki/audit_logs_vector_test.go
'tag' is un-documented as a label key, nor is it part of viaq data model   It needs to be removed from Loki output.  Our Loki output needs to be aligned with our ES logstore output, which does not contain 'tag'. 
This vector task aligns with the same already merged for fluentd.
/cc @syedriko @vimalk78 
- JIRA task: https://issues.redhat.com/browse/LOG-3241
- Loki labelKeys: https://github.com/openshift/cluster-logging-operator/blob/master/apis/logging/v1/output_types.go#L233
- Viaq data model:  https://viaq.github.io/documentation/data_model/public/data_model.html
> LOG-3241: remove tag label from loki vector

- apis/logging/v1/cluster_log_forwarder_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/cmd/forwarder-generator/main.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/reconciler.go
- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
- internal/pkg/generator/forwarder/generator.go
- test/framework/e2e/framework.go
- test/framework/functional/framework.go
This PR:
* fixes the issue where OutputDefaults are applied generically to all ES output types instead of only the managed Elasticsearch offering.
* https://issues.redhat.com/browse/LOG-3228
> LOG-3228: fix applying OutputDefault to unmanaged Elasticsearch logStores

- test/framework/e2e/syslog_conf.go
Removed the omstdout module from rsyslog config, it's a debugging aid and the module is not always present in rsyslog.
/cc @vimalk78 
> Removed omstdout from rsyslog config

- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/service_account.go
- internal/utils/comparators/scc/comparator.go
- internal/utils/comparators/scc/comparator_test.go
This PR:
* sets the log collector security context spec so the logging SCC is more likely to apply versus others
* adds reconcile logic for the collector SCC other then just "create"
* Add SCC comparator and tests
* https://issues.redhat.com/browse/LOG-3302
* forward port of https://github.com/openshift/cluster-logging-operator/pull/1759
> LOG-3302: fix collector security context spec

- Dockerfile
- Dockerfile.in
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manager/manager.yaml
This PR:
* fixes pod security changes reverted in https://github.com/openshift/cluster-logging-operator/commit/a9f435e8810116e4ecd6cfa5e3a3e7b9ae7f8a22
* fixes the USER in the Dockerfile to address CLO not starting
* https://issues.redhat.com/browse/LOG-3396
> LOG-3396: fix pod security changes that were removed

- Dockerfile
- Dockerfile.in
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/rbac/cluster-logging-operator_clusterrole.yaml
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/scc.go
- internal/k8shandler/collection.go
- internal/reconcile/scc.go
- internal/utils/comparators/scc/comparator.go
- internal/utils/comparators/scc/comparator_test.go
- internal/utils/comparators/scc/suite_test.go
This PR:
* sets the log collector security context spec so the logging SCC is more likely to apply versus others
* adds reconcile logic for the collector SCC other then just "create"
* Add SCC comparator and tests
* https://issues.redhat.com/browse/LOG-3235
> LOG-3235: fix collector security context spec

- controllers/clusterlogging/clusterlogging_controller.go
- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/status.go
- internal/visualization/console/plugin.go
Revert "[LOG-2999](https://issues.redhat.com//browse/LOG-2999):Add watcher for Elasticsearch object"
This reverts commit 218e39bf382bd3bcb8ddfa42fa3ec45f1effbe60.
This PR:
* fixes the crash by reverting the PR which  fails when EO is not installed
* https://issues.redhat.com/browse/LOG-3406
> LOG-3406: fix CLO crash when EO is not deployed

- controllers/clusterlogging/clusterlogging_controller.go
- main.go
This PR:
* fixes the crash by adding the console plugin to the watch for CL
* sets a sync period to 3 minutes which is the maximum time to notice changes in the console plugin
* https://issues.redhat.com/browse/LOG-3321
cc @alanconway
> LOG-3321: fix crash when console is not enabled

- Makefile
- controllers/clusterlogging/clusterlogging_controller.go
- main.go
This PR:
fixes the crash by adding the console plugin to the watch for CL
sets a sync period to 3 minutes which is the maximum time to notice changes in the console plugin
* https://issues.redhat.com/browse/LOG-3407
* backport of https://github.com/openshift/cluster-logging-operator/pull/1794
cc @alanconway
> LOG-3407: fix crash when console is not enabled

- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/logstore_lokistack.go
- internal/k8shandler/reconciler.go
- internal/migrations/logstore_lokistack_test.go
- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
- internal/runtime/logging.go
- test/runtime/logging.go
This PR:
fixes a merge issue where we always validate against an empty spec which causes logging to never deploy
Links
https://issues.redhat.com/browse/LOG-3228
forward pick of #1801
> LOG-3228: fix validation on empty spec

- must-gather/collection-scripts/common
- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_collection_resources
- must-gather/collection-scripts/gather_elasticsearch_operator_resources
- must-gather/collection-scripts/gather_install_resources
- must-gather/collection-scripts/gather_logstore_resources
- must-gather/collection-scripts/gather_visualization_resources
`oc` commands in must-gather were getting client throttled because `oc` commands could not create the kube cache.
```
I0103 09:08:12.495844      18 cached_discovery.go:92] failed to write cache to /.kube/cache/discovery/10.217.4.1_443/imageregistry.operator.openshift.io/v1/serverresources.json due to mkdir /.kube: permission denied
```
-  Added a kube cache folder to /must-gather and use this in oc commads with --cache-dir flag.
- Added BEGIN/END log statements in gather scripts which prints timestamped echo statements to monitor time taken by each step
-  Fixed small errors in gather scripts
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-3446
>  LOG-3446: Fix k8s client throttling in must-gather scripts

- internal/reconcile/scc.go
- internal/reconcile/scc_test.go
This PR:
* fixes updating by Updating the current SCC to desired
* https://issues.redhat.com/browse/LOG-3302
> LOG-3302: Update scc to desired

- internal/consoleplugin/reconciler.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/reconciler.go
- internal/migrations/logstore_lokistack_test.go
- internal/migrations/migrate_clusterlogforwarder.go
This is the 5.5 fix.  Same general idea as the 5.6 fix: [LOG-3269](https://issues.redhat.com//browse/LOG-3269)
- Adds a name to custom inputs which will now prevent the invalid pipeline error.  
- Adds loki function for getting input type from name, in order for loki labels to work properly.
/cc @vimalk78 @syedriko 
- https://issues.redhat.com/browse/LOG-3474
> LOG-3474:  fix custom input in clf spec when using loki

- internal/k8shandler/reconciler.go
Same issue and fix as 5.6, this fixes the degraded pipeline status when adding default to an existing CLF pipeline.  Also, the collector pod was restarting every 8-10 seconds.  This resolves.
/cc @vimalk78 @syedriko
- https://issues.redhat.com/browse/LOG-3469
> LOG-3469: [release-5.5] fix collector restarting and degraded pipeline status

- internal/utils/utils.go
- test/framework/e2e/certificates/certificates.go
- test/framework/e2e/elasticsearch.go
- test/framework/e2e/fluentd.go
- test/framework/e2e/framework.go
- test/framework/functional/framework.go
- test/helpers/loki/receiver.go
Two corrections for the functional and e2e tests:
- fixed a race condition during generation of certificates due to multiple instances of the certificate generation script running against the same directory
- Added a uid for the loki user to the security context of the loki receiver, this fixes the "container has runAsNonRoot and image has non-numeric user (loki), cannot verify user is non-root" issue happening in vector CI.
/assign @cahartma
> Addressed race condition during cert generation, fixed loki uid for vector CI

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- test/functional/normalization/flatten_labels_test.go
This PR:
* replaces dots with underscores for namespace_labels when writing to Elasticsearch
* https://issues.redhat.com/browse/LOG-3463
* replaces https://github.com/openshift/cluster-logging-operator/pull/1811
> LOG-3463: fix namespace_labels when writing to Elasticsearch

- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
- internal/generator/fluentd/output/syslog/passphrase.go
- internal/generator/fluentd/output/syslog/syslog.go
A fix for the fix for [LOG-2843](https://issues.redhat.com//browse/LOG-2843), added support for client key passphrase missed in the original fix.
- JIRA: https://issues.redhat.com/browse/LOG-3533
> [release-5.5] LOG-2843, take two. Added client key passphrase

- internal/consoleplugin/reconciler.go
This PR:
* removes the command from the console plugin deployment to rely upon the entrypoint in the image
* https://issues.redhat.com/browse/LOG-3447
> LOG-3447: Remove console plugin command from deployment

- controllers/clusterlogging/clusterlogging_controller.go
- internal/consoleplugin/feature_map.go
- internal/consoleplugin/feature_map_test.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/visualization_test.go
This PR fixes the issue where we were not passing the version to the consumer to properly deploy the log view plugin
* https://issues.redhat.com/browse/LOG-3447
> LOG-3447: Pass the version to the consumer

- bundle/metadata/properties.yaml
This PR:
* updates the max OCP version to 4.14
* https://issues.redhat.com/browse/LOG-3584
> LOG-3585: Bump bundle OCP max version property to 4.14

- internal/collector/service_account.go
- internal/collector/trust_bundle.go
- internal/utils/comparators/scc/comparator.go
- internal/utils/comparators/scc/comparator_test.go
Collector gets restarted if collector is started without waiting for waiting for trusted ca-bundle config map to get created.
Modified the reconcile logic to wait for trusted ca-bundle to get created.
Log Collector SCC desires 4 volumes `"configMap"`,`"emptyDir"`,`"projected"`,`"secret"`, but CRC container adds another volume for `"hostpath"`.
The SCC comparator does a reflect comparison, which fails because there is one extra Volume.
Fixed the SCC comparator to check for desired volumes only.
/cc 
/assign 
/cherry-pick 
- JIRA:  https://issues.redhat.com/browse/LOG-3609
> LOG-3609: Fix collector restart after creation

- Dockerfile
- Dockerfile.in
- go.mod
- origin-meta.yaml
This PR:
* Updates to project to use golang 1.18
* https://issues.redhat.com/browse/LOG-2854
> LOG-2854: Update go version to 1.18

- internal/constants/constants.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/reconciler.go
- internal/migrations/logstore_lokistack_test.go
- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
- internal/pkg/generator/forwarder/generator.go
The fix was created in migration and with minor updates to the logic surrounding 'default' outputRef for both ES and Loki.   Mainly adding a map to the migration and subsequent normalization (validate), indicating if the ES output was created by our default migration.  This allows us to handle verify with the context of migration.  This is the initial and least impactful change to a refactor of the migration and validation logic to come in: [LOG-3247](https://issues.redhat.com/browse/LOG-3247) when we remove degraded status.
Expected:  
If you use 'default' as an output, it will either correct the ES output, or if its Loki, it will inform the user the name is reserved.  Any other output named 'default' should now invalidate as expected. 
This should also fix the issue in …
> [release-5.6] LOG-3437: fix for invalidate or migrate default output

- internal/certificates/certificates.go
- internal/utils/utils.go
- test/framework/e2e/elasticsearch.go
- test/framework/e2e/fluentd.go
- test/framework/e2e/framework.go
- test/framework/functional/framework.go
- test/helpers/loki/receiver.go
A cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1831 (and another commit it depends on) onto release-5.6 so the fix is seen in vector CI, which runs on top of release-5.6
/cc @jcantrill
/assign @vimalk78
> [release-5.6 cherrypick] Addressed race condition during cert generation, fixed loki uid for vector CI

- must-gather/collection-scripts/gather_logstore_resources
This PR will extend the current capabilities of the must-gather and capture LokiStack instance CR only if present. 
The current must-gather captures Clusterlogging and ClusterLogforwarder instances but not the LokiStack.
> Extending to gather Lokistack instance CR

- bundle/metadata/properties.yaml
This PR updates the max OCP version to 4.15
> bump maxOCPVersion to 4.15

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/source/audit_logs.go
- internal/generator/fluentd/sources_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/sources_test.go
This PR:
- updates `fluentd` config to collect logs from `/var/log/oauth-server/audit.log`
- updates `vector` config to collect logs from `/var/log/oauth-server/audit.log`
- updates corresponding unit tests 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3499
> LOG-3499: add /var/log/oauth-server/audit.log to the log collection path

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/source/audit_logs.go
- internal/generator/fluentd/sources_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/sources_test.go
This PR:
- fixes the path used by oauthapi audit logs (https://github.com/openshift/cluster-logging-operator/pull/1438)
- manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1857
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> [release-5.4] LOG-3499: add /var/log/oauth-server/audit.log to the log collection path

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/source/audit_logs.go
- internal/generator/fluentd/sources_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/sources_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1857
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> [release-5.5] LOG-3499: add /var/log/oauth-server/audit.log to the log collection path

- Makefile
- docs/reference/operator/api.adoc
- internal/generator/fluentd/output/http/bearer-token-file.go
- internal/generator/fluentd/output/http/ca-file.go
- internal/generator/fluentd/output/http/cert-key.go
- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
- internal/generator/fluentd/output/http/userpass.go
- internal/generator/fluentd/outputs.go
- internal/generator/utils/utils.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
- test/framework/functional/common/loglevel.go
- test/framework/functional/output_http.go
- test/framework/functional/vector/deploy.go
- test/functional/outputs/http/forward_to_http_test.go
*  Generate fluentd conf for http output
*  Added unit tests
* Added functional tests to send logs from fluentd to vector over http
* Added functional tests to send logs from fluentd to fluentd over http
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-3312
> LOG-3312: Support http output for fluentd

- internal/collector/collector.go
This PR:
- add volume mount for OAuth Server logs (`/var/log/oauth-server/`), this is additional fix for #1857 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-3499: add volume mount for /var/log/oauth-server/

- internal/constants/constants.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/reconciler.go
- internal/logstore/lokistack/logstore_lokistack.go
- internal/logstore/lokistack/logstore_lokistack_test.go
- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
- internal/pkg/generator/forwarder/generator.go
- internal/visualization/console/plugin.go
- test/functional/normalization/flatten_labels_test.go
This is the 5.7 version of the fix below, which was implemented in 5.6.2
The fix was created in migration and with minor updates to the logic surrounding 'default' outputRef for both ES and Loki. Mainly adding a map to the migration and subsequent normalization (validate), indicating if the ES output was created by our default migration. This allows us to handle verify with the context of migration. This is the initial and least impactful change to a refactor of the migration and validation logic to come in: [LOG-3247](https://issues.redhat.com/browse/LOG-3247) when we remove degraded status.
Expected:
If you use 'default' as an output, it will either correct the ES output, or if its Loki, it will inform the user the name is reserved. Any other output named 'default' should now invalidate …
> [master] LOG-3645-default-output-migration-fix

- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/daemonset.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/sources.go
- internal/generator/fluentd/sources_test.go
- internal/generator/logging.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/metrics.go
- internal/generator/vector/outputs.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/pkg/generator/forwarder/generator.go
- internal/tls/profile.go
- internal/tls/tls.go
This PR passes TLS min version and ciphersuites from the TLSSecurityProfile to the log collectors and the log file metric exporter.
Depends on corresponding PRs in vector and log-file-metric-exporter repos.
- Depending on PR(s): https://github.com/ViaQ/vector/pull/129, https://github.com/ViaQ/log-file-metric-exporter/pull/26
- JIRA: https://issues.redhat.com/browse/LOG-3398
> LOG-3398: Apply TLSSecurityProfile settings to TLS listeners in log collectors

- apis/logging/v1/cluster_log_forwarder.go
- internal/collector/collector.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- test/client/test.go
- test/framework/functional/builders.go
- test/framework/functional/builders_test.go
- test/framework/functional/cluster_log_forwarder.go
- test/framework/functional/elasticsearch.go
- test/framework/functional/framework.go
- test/framework/functional/output_elasticsearch.go
- test/framework/functional/output_kafka.go
- test/framework/functional/write.go
- test/functional/normalization/flatten_labels_test.go
- test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go
- test/functional/outputs/kafka/forward_to_kafka_test.go
This PR:
Adds fluentd support for Elasticsearch 8
Add functionality to functional framework to utilize secrets
Allows fluentd to verify es version on startup which may lead to transient error messages
* forward port of https://github.com/openshift/cluster-logging-operator/pull/1858
> [master] LOG-2544: Add support for Elasticsearch v8 for fluentd

- docs/README.adoc
- docs/features/logforwarding/outputs/google-cloud-forwarding.adoc
- docs/features/logforwarding/outputs/send-logs-to-fluentd-http.adoc
Fluent Forward protocol sends fluentd tags along with logs, and receiving fluentd can
use this tag information to dispatch the logs to labels as per fluentd conf.
With vector not supporting fluent forward, and vector having no concept of dispatching using
tags, an alternative is to use http paths to function as tags. Fluentd http sink can convert
http endpoint path information to create fluentd tags. This example uses different http path
for each log type and the same is used in receiving fluentd to dispatch each log type separately.
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2575
> LOG-2575: Added documentation for fluent forward workaround

- internal/visualization/console/reconciler.go
This PR:
- removes the command from the console plugin deployment to rely upon the entrypoint in the image
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3716
> LOG-3716:Remove console plugin command from deployment

- internal/k8shandler/fluentd.go
- internal/k8shandler/vector.go
This PR:
- add volume mount for OAuth Server logs (`/var/log/oauth-server/`), this is additional fix for #1865
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3731
> [release-5.4] LOG-3731: add volume mount for /var/log/oauth-server/

- internal/generator/fluentd/inputes_to_pipeline_test.go
- internal/generator/fluentd/inputs_to_pipeline.go
- test/framework/functional/cluster_log_forwarder.go
- test/functional/outputs/multiple/multiple_test.go
- test/helpers/generator.go
This PR:
* fixes parsed JSON messages not being sent to all outputs
* https://issues.redhat.com/browse/LOG-3640
> LOG-3640: fix structured logs not being forwarded to all outputs

- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
This PR: 
- fix generated an invalid parameter `encoding "application/x-ndjson"` -> `content_type  "application/x-ndjson"`. Refer to https://docs.fluentd.org/output/http
- 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3762
> LOG-3762: replace 'encoding' with 'content_type' parameter according to fluentd http plugin docs

- apis/logging/v1/clusterlogging_types.go
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_clusterloggings.yaml
- config/crd/bases/logging.openshift.io_clusterloggings.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
- config/samples/logging_v1_clusterlogging.yaml
This PR:
* updates the manifest annotations to hide deprecated fields
* sets vector as the default collector
* removes storage class from the CR sample
* https://issues.redhat.com/browse/LOG-3754
> LOG-3754: Update manifest annotations to hide deprecated fields

- internal/constants/features.go
- internal/generator/generator.go
- internal/generator/options.go
- internal/generator/options_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/outputs.go
- internal/k8shandler/collection.go
- internal/k8shandler/deprecated.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_features_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
This PR:
* Adds functionality to enable a preview feature gate for TLS Security Profile
* Adds an option for consumption by the collector config generator
* https://issues.redhat.com/browse/LOG-3569
cc @syedriko
> LOG-3569: Add functionality to enable TLS Security feature gate

- hack/gen-olm-artifacts.py
Missing semicolon introduced in https://github.com/openshift/cluster-logging-operator/pull/1900
/cc jcantrill
> Fix syntax error in gen-olm-artifacts.py

- hack/gen-olm-artifacts.py
Manual backport of https://github.com/openshift/cluster-logging-operator/pull/1900
/cc jcantrill
> [release-5.6] Fix namespace metadata in gen-olm-artifacts.py

- controllers/clusterlogging/clusterlogging_controller.go
- controllers/forwarding/forwarding_controller.go
- internal/constants/constants.go
- internal/k8shandler/clusterloggingrequest.go
This PR get rid some not needed error messages in log: 
- `error deleting grafana configmap` in case config map not found;
- `Operation cannot be fulfilled on $something the object has been modified; please apply your changes to the latest version and try again`, to fix this adds some checking on message in error, more info here https://github.com/kubernetes/kubernetes/issues/28149 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-3482: get rid of some senseless messages in log

- internal/generator/fluentd/inpute_to_pipeline_test.go
- internal/generator/fluentd/inputs_to_pipeline.go
- test/framework/functional/cluster_log_forwarder.go
- test/framework/functional/cluster_log_forwarder_test.go
- test/framework/functional/elasticsearch.go
- test/functional/outputs/forward_to_logstash_test.go
- test/functional/outputs/multiple/multiple_test.go
- test/helpers/generator.go
This PR:
* fixes parsed JSON messages not being sent to all outputs
* https://issues.redhat.com/browse/LOG-3767
> LOG-3767: fix structured logs not being forwarded to all outputs

- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
This PR adds ability to remove `collector-config` secret on deleting Vector Collector instance
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3811
> LOG-3811: remove collector-config secret on deleting Vector Collector instance

- internal/visualization/console/feature_map.go
- internal/visualization/console/feature_map_test.go
This PR:
* fixes the console plugin to enable alerts for OCP v4.13 or greater
* https://issues.redhat.com/browse/LOG-3769
cc @periklis
> LOG-3769: fix enablement of console alerts

- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
- internal/generator/fluentd/output/http/passphrase.go
This PR adds ability to generate `tls_private_key_passphrase`  in the TLS section configuration for fluentd http output plugin.
https://docs.fluentd.org/output/http#tls_private_key_passphrase 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3827
> LOG-3827: generate tls_private_key_passphrase for fluentd http output plugin

- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/tls.go
This PR adds the ability to skip SSL certificate verification for the Elasticsearch output plugin in Fluentd. This feature can be useful in cases where you need to connect to an Elasticsearch cluster with a self-signed SSL certificate or with an invalid certificate due to an expired or mismatched domain.
To enable this feature, need to set option `insecureSkipVerify=true`.
E.g.
```
spec:
outputs:
- name: elasticsearch
tls:
insecureSkipVerify: true
type: elasticsearch
url: https://localhost:9200
```
In `fluentd.conf` file should appear:
`ssl_verify false`
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3838
> LOG-3838: add ability to skip certificates verification for ES output

- apis/logging/v1/clusterlogging_types.go
- bundle/manifests/logging.openshift.io_clusterloggings.yaml
- config/crd/bases/logging.openshift.io_clusterloggings.yaml
- test/e2e/logforwarding/http/forward_to_http.go
This PR:
* fixes the inability to upgrade an existing deployment because of a validation error on collection.type
* https://issues.redhat.com/browse/LOG-3809
> LOG-3809: fix upgrading to 5.7 because of metadata

- internal/collector/config.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
In this PR:
- It was discovered that this solution #1922 was not working as intended, as the `collector-config` secret was not being deleted when the `Cluster Logging instance` was deleted, so this changes was reverted 
- added a reference to the `Cluster Logging instance` in the `collector-config` secret. This ensures that when the Cluster Logging instance is deleted, the Kubernetes garbage collector will also delete the `collector-config` secret.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3811
> LOG-3811: Ensure collector-config secret is deleted with Cluster Logging instance

- hack/gen-olm-artifacts.py
Manual backport of https://github.com/openshift/cluster-logging-operator/pull/1900
/cc jcantrill
> [release-5.5] Fix namespace metadata in gen-olm-artifacts.py

- docs/features/collection.adoc
- internal/generator/vector/elements/elements.go
- internal/generator/vector/pipelines.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/normalization/multiline_exception_test.go
This PR adds support for generating vector config for detecting and handling multiline exceptions. This requires a new transform for detecting and handling multiline exceptions., which is added in PR https://github.com/ViaQ/vector/pull/132
- Enabled Multiline Exception functional test for vector
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-3497
> LOG-3497: Generate vector config for Detect Multiline Exceptions

- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
Before this PR, when vector forwarded logs to a syslog endpoint, the scheme of the endpoint URL defaulted to 'tcp' (including 'tls') unless it was 'udp'. No error was produced for an invalid URL scheme.
With this PR, a URL scheme that is not 'tcp', 'tls' or 'udp', results in the status of the corresponding ClusterLogForwarder output set to False with an error message:
```
metadata:
name: instance
spec:
outputs:
- name: rsyslog
syslog:
facility: local0
rfc: RFC5424
severity: informational
type: syslog
url: xyz://rsyslogd.syslog.svc.cluster.local:24224
...
status:
outputs:
rsyslog:
- lastTransitionTime: "2023-04-14T21:27:26Z"
message: 'invalid URL scheme: xyz'
reason: Invalid
status: "False"
type: …
```
> LOG-3948: [Vector] No error message shown on collector pods when the syslog output url is wrong in CLF

- docs/features/tls_security_profile.adoc
- internal/generator/vector/elements/elements.go
- internal/generator/vector/outputs.go
- internal/generator/vector/outputs_test.go
- internal/generator/vector/sources_to_pipelines_test.go
This PR:
* fixes TLS Security Profile to always be applied to the default loki logstore regardless of the feature gate
* https://issues.redhat.com/browse/LOG-3935
> LOG-3935: always enable TLS Security for default loki

- internal/generator/fluentd/output/kafka/kafka.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/kafka/sasl.go
- internal/generator/vector/output/kafka/sasl.go
This PR:
- fix the ability to enable passphrase settings for Kafka Fluentd Plugin
- add the ability to set the SCRAM mechanism for SSL for Kafka Fluentd Plugin
- a few typos in the codebase.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3314
> LOG-3314: add Passphrase Settings and SCRAM Mechanism for SSL to Kafka Fluentd Plugin

- apis/logging/v1/clusterlogging_types.go
- bundle/manifests/logging.openshift.io_clusterloggings.yaml
- config/crd/bases/logging.openshift.io_clusterloggings.yaml
Currently, the `spec.visualization.kibana.replicas` field in the Kibana spec is mandatory, which means that if Kibana is not available, it can cause errors. 
With this PR,  `spec.visualization.kibana.replicas` field can be set to null or omit it entirely when Kibana is not needed. This will prevent the Kubernetes API server from raising errors when trying to validate the Kibana spec.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com//browse/LOG-3985
> LOG-3985: make spec.visualization.kibana.replicas optional on Kibana spec type

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/outputs.go
- internal/generator/vector/outputs_test.go
- internal/logstore/lokistack/logstore_lokistack.go
This PR:
* fixes applying a TLSProfile to the default loki store by properly evaluating the output names we create
* https://issues.redhat.com/browse/LOG-3935
> LOG-3935: fix how TLSProfile evaluates default loki names

- internal/generator/fluentd/helpers/tls.go
- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/outputs.go
- internal/generator/fluentd/outputs_test.go
- internal/generator/fluentd/sources.go
- internal/generator/tls.go
- internal/generator/tls_test.go
- internal/generator/vector/outputs.go
This PR:
* sets the TLS profile for fluent to default loki regardless of feature gate
* https://issues.redhat.com/browse/LOG-4012
* blocked by #1969 
* blocked by https://github.com/ViaQ/logging-fluentd/pull/80
cc @IshwarKanse 
/hold
> LOG-4012: use TSL profile for fluent to loki

- internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go
- test/client/test.go
- test/helpers/fluentd/receiver.go
- test/helpers/fluentd/receiver_test.go
This PR makes sure the ConfigMap, Service and Pod for the fluentd receiver are created before the test invokes on it.
There are also corrections for the curl command line and for an unrelated typo.
The test failure looks as follows:
```
[oc exec -i -n test-syrcw7it Pod/receiver -- curl -fsS -X POST -key cakey.pem --cacert cacert.pem -d json={"hello":"world"} https://receiver.test-syrcw7it.svc:24225/test.tag]
curl: (6) Could not resolve host: cakey.pem
curl: (7) Failed to connect to receiver.test-syrcw7it.svc port 24225: Connection refused
command terminated with exit code 7
```
`curl: (6) Could not resolve host: cakey.pem` was due to `-key` missing another dash. It was not clear to me where cakey.pem and cacert.pem were expected to come from, so I reworked the certs.
`curl: (7) Failed to …
> Fix for a race condition in fluentd/receiver_test

- internal/telemetry/cloteleminfo.go
This PR addresses the issue that the `prometheus` metrics output for the metric `log_forwarder_output_info` did not include the outputs of `splunk` and `google cloud logging`. With this change, the outputs are present in the metrics.
/cc @cahartma @syedriko 
/cherry-pick release-5.7
- JIRA: https://issues.redhat.com/browse/LOG-3932
> LOG-3932: No log_forwarder_output_info for splunk and google logging

- internal/k8shandler/reconciler.go
Regression fix to remove daemonset when no default logStore and no forwarder
/cc @Clee2691 @syedriko
- this is the 5.6 version of the fix for:  https://issues.redhat.com/browse/LOG-4030
> [release-5.6] LOG-4030: Remove collector daemonset when no logStore or forwarder

- internal/k8shandler/reconciler.go
- internal/k8shandler/visualization.go
Critical bug fix for 5.7
The logging-view-plugin will not be deployed unless visualization is added to clusterlogging CR
/cc @Clee2691 @syedriko
- JIRA: https://issues.redhat.com/browse/LOG-4039
> LOG-4039: logging-view-plugin not deployed when visualization is nil

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This changes the generated bundle to include a skipRange attribute that limits direct updates to only be able from 5.4 onwards.
- JIRA: https://issues.redhat.com/browse/LOG-3837
> LOG-3837: Update skipRange to allow updating from 5.4 onwards

- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/kafka/sasl.go
This PR fix configuration for Kafka output plugin adding new line after `ssl_client_cert_key_password` config parameter to prevent such behavior:
```
sasl_over_ssl true
ssl_client_cert_key_password "#{File.exists?('/var/run/ocp-collector/secrets/kafka-fluentd/passphrase') ? open('/var/run/ocp-collector/secrets/kafka-fluentd/passphrase','r') do |f|f.read end : ''}"scram_mechanism "PLAIN"
```
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3314
> LOG-3314: fix config generation for Kafka output

- internal/collector/fluentd/run_script.go
This pull request addresses the issue where the `run.sh` script displays an incorrect `chunk_limit_size` value if it is changed. Script show correct value when setting the `chunk_limit_size` via the env variable `BUFFER_SIZE_LIMIT`, but shows wrong if do it, as described in the [OpenShift documentation](https://docs.openshift.com/container-platform/4.12/logging/config/cluster-logging-collector.html). 
The new code uses the `awk` command to search for the `chunk_limit_size` value in the `fluentd.conf` file, if the value is not found in the `fluentd.conf` file, the script shows the default value from the `$BUFFER_SIZE_LIMIT` environment variable.
```
chunk_limit_size=$(awk '/chunk_limit_size/{print $2; exit}' $FLUENT_CONF)
if [[ -z "$chunk_limit_size" ]] || [[ "$chunk_limit_size" == …
```
> LOG-3330: fix run.sh script to displays correct chunk_limit_size value if it is changed

- internal/metrics/telemetry/cloteleminfo.go
Similar to [LOG-3932](https://issues.redhat.com/browse/LOG-3932), this PR address the issue that the `prometheus` metrics output for the metric, `log_forwarder_output_info`, did not include the output of `HTTP`. With this change, `HTTP` is present in the metrics.
- Related Github PR: https://github.com/openshift/cluster-logging-operator/pull/1957
- JIRA: https://issues.redhat.com/browse/LOG-3997
> [release-5.7] LOG-3997: Add http to log_forwarder_output_info metrics

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/pipelines.go
- internal/generator/vector/sources_to_pipelines_test.go
This PR fixes the `CrashLoopBackOff` problem for the collector container when the `ClusterLogForwarder` spec's pipeline name contained spaces. This fix sanitizes pipeline names replacing spaces `" "`, dashes `-`, and dots `.` with underscores `_`. 
Example:
`pipeline with space` -> `pipeline_with_space`
`pipeline.with space.dot` -> `pipeline_with_space_dot`
In addition to the above fix, I refactored most vector output's `ComponentIDs` to use the vector helper function, `FormatComponentID()` instead of `strings.ToLower()`, to improve code readability.
- JIRA: https://issues.redhat.com/browse/LOG-3945
> [release-5.7] LOG-3945: Collector pods in CrashLoopBackOff with spaces in pipeline name

- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go
- internal/validations/clusterlogforwarder/validations.go
This PR:
- It introduces the ability to apply the `tls.insecureSkipVerify=true` configuration even if the certificate is not added to the secret. When using a TLS connection, our API will no longer require a certificate to be provided through K8s Secret if the `tls.insecureSkipVerify` option is set to `true`. The following configuration will be added to the Vector config:
```
tls.verify_certificate = false
tls.verify_hostname = false
```
- adds a unit test to verify the correct configuration when 'tls.insecureSkipVerify=true' is set for the Splunk output
- adds validation to check for cases where a non-empty TLS config is provided, but the URL is not secure. The validation will fail if the given URL has a non-secure scheme (e.g., …
> LOG-3445: Apply 'tls.insecureSkipVerify=true' configuration even if certificate not added to the secret

- Makefile
- internal/collector/collector.go
- internal/collector/config.go
- internal/collector/service.go
- internal/constants/constants.go
- internal/factory/daemonset.go
- internal/factory/daemonset_test.go
- internal/factory/service.go
- internal/k8shandler/collection.go
- internal/runtime/core.go
- internal/runtime/daemonset.go
- internal/runtime/runtime.go
- internal/runtime/service.go
- internal/utils/utils.go
- version/version.go
This PR adds Kubernetes common labels to the deployed objects in our application. These labels will help with grouping and filtering resources in Kubernetes.
<table>
<thead>
<tr>
<th>
```
K8s Object
```
</th>
<th>
```
Name
```
</th>
<th>
```
Before the changes
```
</th>
<th>
```
With this PR
```
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
```
DaemonSet
```
</td>
<td>
```
collector
```
</td>
<td>
```
{
"component": "collector",
"logging-infra": "collector",
"provider": "openshift"
}
```
</td>
<td>
```
{
"app.kubernetes.io/component": "collector",
"app.kubernetes.io/instance": "instance",
"app.kubernetes.io/managed-by": "cluster-logging-operator",
"app.kubernetes.io/name": "fluentd | vector",
"app.kubernetes.io/part-of": "cluster-logging",
"app.kubernetes.io/version": "5.7.0",
"component": …
```
> LOG-3830: Add common labels to CLF objects 

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/pipeline_to_output.go
- internal/generator/fluentd/pipeline_to_output_test.go
- test/functional/normalization/json_parsing_test.go
- test/functional/normalization/loglevel/conainer_logs_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
Two quick fix issues found with fluentd json parsing feature: 
1. Currently when a `structuredTypeKey` is not found, and a `structuredTypeName` is not specified, the log message is still parsed into structured object, but the index is not created AND the original message is not deleted.    This fixes the issue so that the messages are not parsed in that scenario.
2.  When the key `time` is included in the json message, fluentd was dropping that element from the new `structured` field.  This change will ensure the element remains and is now included in the `structured` elements
/cc @Clee2691 @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-3249
> [release-5.7] LOG-3249: Fix log parsing and index logic in fluentd

- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
- internal/generator/fluentd/output/http/passphrase.go
This PR fixes the issue with reading the TLS passphrase directly from the K8s configmap, which was causing security concerns. The fix involves reading the passphrase from a file instead of the configmap. 
/cc @cahartma 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3827
> LOG-3827:Read TLS passphrase from file instead of K8s configmap for fluentd http output plugin

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/pipeline_to_output.go
- internal/generator/fluentd/pipeline_to_output_test.go
- test/functional/normalization/json_parsing_test.go
- test/functional/normalization/loglevel/conainer_logs_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
5.6 version of the fix for fluentd json parsing feature
1. Currently when a structuredTypeKey is not found, and a structuredTypeName is not specified, the log message is still parsed into structured object, but the index is not created AND the original message is not deleted. This fixes the issue so that the messages are not parsed in that scenario.
2. When the key time is included in the json message, fluentd was dropping that element from the new structured field. This change will ensure the element remains and is now included in the structured elements
/cc @Clee2691 @syedriko
- https://issues.redhat.com/browse/LOG-4090
- 5.7 fix: https://issues.redhat.com/browse/LOG-3249
> [release-5.6] LOG-4090: Fix log parsing and index logic in fluentd

- apis/logging/v1/output_types.go
- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/syslog/syslog.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
Made the URL field mandatory for Kafka output, as per original design
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4009
> LOG-4009: TLS configuration for multiple Kafka brokers is not created in Vector

- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
- internal/validations/clusterlogforwarder/validate_http_content_type_headers.go
- internal/validations/clusterlogforwarder/validate_http_content_type_headers_test.go
- internal/validations/clusterlogforwarder/validations.go
This PR allows users to overcome limitations in CLO API's to provide various content type for logs data output.
For the Fluentd HTTP plugin, users can now assign the content type for log forwarding seamlessly, by configuring the [HTTP header](https://docs.fluentd.org/output/http#headers) "Content-Type," the value provided is automatically assigned to the [`content_type`](https://docs.fluentd.org/output/http#content_type) parameter within the plugin.
For example:
```
metadata:
name: instance
spec:
outputs:
- http:
headers:
k1: v1
Content-Type: application/json
method: POST
name: my-http-storage
type: http
url: https://my-logstore.com/logs/app-logs
pipelines:
- inputRefs:
- application
name:  to-http …
```
> LOG-3784: value provided in HTTP header 'Content-Type' for Fluentd HTTP plugin is automatically assigned to the 'content_type' parameter

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- docs/reference/operator/api.adoc
- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/syslog/syslog.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
- Kafka output validation now looks at both the URL and the brokers Kafka output fields
- Vector TLS config for the Kafka output is generated if there is a TLS/HTTPS URL among the specified Kafka endpoints
Cherrypick of https://github.com/openshift/cluster-logging-operator/pull/1981
/cc @Clee2691
- JIRA: https://issues.redhat.com/browse/LOG-4163
> LOG-4163: [release-5.7] TLS configuration for multiple Kafka brokers is not created in Vector

- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- internal/validations/clusterlogforwarder/suite_test.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go
- internal/validations/clusterlogforwarder/validations.go
This PR:
- It introduces the ability to apply the `tls.insecureSkipVerify=true` configuration even if the certificate is not added to the secret. When using a TLS connection, our API will no longer require a certificate to be provided through K8s Secret if the `tls.insecureSkipVerify` option is set to `true`. The following configuration will be added to the Vector config:
```
tls.verify_certificate = false
tls.verify_hostname = false
```
- adds a unit test to verify the correct configuration when 'tls.insecureSkipVerify=true' is set for the Splunk output
- adds validation to check for cases where a non-empty TLS config is provided, but the URL is not secure. The validation will fail if the given URL has a non-secure scheme (e.g., …
> [release-5.6]LOG-4146: Proceede tls.insecureSkipVerify=true configuration even if certificate not added to the secret

- internal/generator/vector/conf_test.go
- internal/generator/vector/pipelines.go
- internal/generator/vector/sources_to_pipelines_test.go
Add a namespace for the transforms generated for the CLF pipelines to avoid user-specified pipeline names clashing with names of "reserved" transforms, such as "infrastructure", "application", "audit", "drop_journal_logs", etc.
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4121
> LOG-4121: Vector fails to run when configuring syslog forwarding for audit log

- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go
- internal/validations/clusterlogforwarder/validations.go
(manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/2005)
This PR:
- It introduces the ability to apply the `tls.insecureSkipVerify=true` configuration even if the certificate is not added to the secret. When using a TLS connection, our API will no longer require a certificate to be provided through K8s Secret if the `tls.insecureSkipVerify` option is set to `true`. The following configuration will be added to the Vector config:
```
tls.verify_certificate = false
tls.verify_hostname = false
```
- adds a unit test to verify the correct configuration when 'tls.insecureSkipVerify=true' is set for the Splunk output
- adds validation to check for cases where a non-empty TLS config is provided, but the URL is not secure. The validation will fail if the given URL …
> [release-5.7]LOG-3445: Apply 'tls.insecureSkipVerify=true' configuration even if certificate not added to the secret

- internal/metrics/telemetry/cloteleminfo.go
This PR is a cherry-pick of [LOG-3932](https://github.com/openshift/cluster-logging-operator/pull/1957). This ports the changes foward to `release-5.7`
- JIRA: https://issues.redhat.com/browse/LOG-4098
> LOG-4098: Manual cherry-pick of LOG-3932

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- docs/reference/operator/api.adoc
- internal/generator/vector/output/loki/loki.go
- test/functional/outputs/loki/application_logs_vector_test.go
This PR:
* fixes CLF loki label keys to replace slash with underscore
https://issues.redhat.com/browse/LOG-4095
> LOG-4095: fix loki labelKeys that contain slash

- internal/metrics/telemetry/cloteleminfo.go
This is a forward port of [LOG-3932](https://github.com/openshift/cluster-logging-operator/pull/1957) & [LOG-3997](https://github.com/openshift/cluster-logging-operator/pull/1964)
- Adds `log_forwarder_output_info` for `http`, `splunk`, and `googleCloudLogging`
/cc @syedriko @cahartma 
- JIRA:
- https://issues.redhat.com/browse/LOG-4173
- https://issues.redhat.com/browse/LOG-4174
> LOG-4173 & LOG-4174: manual forward ports of telemetry

- internal/migrations/migrate_clusterlogging.go
- internal/migrations/migrate_clusterlogging_test.go
This PR:
* modifies migration to always prefer the deprecated collection.logs.* over collection.*
* This breaks any users that have both collection.logs.* over collection.* defined
* https://issues.redhat.com/browse/LOG-4185
cc @alanconway @libander @anpingli
> LOG-4185: Always prefer collection.logs.* over collection.

- controllers/logfilemetricsexporter/logfilemetricsexporter_controller.go
This PR fixes the issue where when creating an invalid `log-file-metric-exporter` the operator raises the error: `Unsupported event type: 'Error'`
/cc @syedriko @vparfonov 
- JIRA: https://issues.redhat.com/browse/LOG-4210
> LOG-4210: CLO raises 'Unsupported event type: 'Error''

- internal/k8shandler/reconciler.go
- internal/telemetry/cloteleminfo.go
- internal/telemetry/cloteleminfo_test.go
- internal/utils/safemap.go
- internal/utils/safemap_test.go
- main.go
This PR introduces the usage of `sync.Map` to provide concurrent-safe access to a map instead of manually managing locks with a standard map in existed `StringMap` and `Float64Map` structs
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4188
> LOG-4188: Use sync.Map type from GoLang standard library

- internal/metrics/logfilemetricexporter/daemonset.go
- internal/metrics/logfilemetricexporter/factory.go
- internal/metrics/logfilemetricexporter/metric_exporter.go
This PR adds Kubernetes common labels to the Log Files Metric Exporter pods and daemonset. These labels will help with grouping and filtering resources in Kubernetes.
/cc @Clee2691 
/cherry-pick 
- Bugzilla:
- JIRA:
> Add common labels for Log Files Metric Exporter

- internal/k8shandler/reconciler.go
- internal/metrics/telemetry/cloteleminfo.go
- internal/metrics/telemetry/cloteleminfo_test.go
- internal/utils/safemap.go
- internal/utils/safemap_test.go
- main.go
This PR introduces the usage of `sync.Map` to provide concurrent-safe access to a map instead of manually managing locks with a standard map in existed `StringMap` and `Float64Map` structs
(manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/2041)
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> [release-5.7]LOG-4222: Use sync.Map type from GoLang standard library

- controllers/forwarding/forwarding_controller.go
- internal/k8shandler/reconciler.go
This PR adds a check that ensures the `ClusterLogging` resource is in the appropriate `Management` state before proceeding with reconciliation `ClusterLoggingForwarder`.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4177
> LOG-4177: checking is ClusterLogging in Management state before perform reconcile

- internal/k8shandler/reconciler.go
- internal/metrics/telemetry/cloteleminfo.go
- internal/metrics/telemetry/cloteleminfo_test.go
- internal/utils/safemap.go
- internal/utils/safemap_test.go
- main.go
This PR introduces the usage of sync.Map to provide concurrent-safe access to a map instead of manually managing locks with a standard map in existed StringMap and Float64Map structs
(manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/2041)
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-4222: Use sync.Map type from GoLang standard library

- test/e2e/logforwarding/loki/forward_to_loki_test.go
- test/helpers/loki/receiver.go
This PR:
* adds cleanup of test resources to attempt to address:
```
Error Trace:	/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/loki/forward_to_loki_test.go:111
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/loki/forward_to_loki_test.go:92
Error:      	Received unexpected error:
pods "loki-receiver" already exists
Test:       	TestLogForwardingToLokiWithVector
```
* https://issues.redhat.com/browse/LOG-4181
> LOG-4181: fix loki e2e flake by adding test cleanup

- PROJECT
- apis/logging/v1alpha1/groupversion_info.go
- apis/logging/v1alpha1/log_file_metrics_exporter_types.go
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_logfilemetricexporters.yaml
- config/crd/bases/logging.openshift.io_logfilemetricexporters.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
- internal/metrics/logfilemetricexporter/factory.go
- internal/metrics/logfilemetricexporter/factory_test.go
This PR fixes Openshift's UI console to display information about the `LogFileMetricExporter` custom resource as well as allowing users to set the resource requirements and tolerations through the form view [LOG-4252](https://issues.redhat.com/browse/LOG-4252).
[LOG-4253](https://issues.redhat.com/browse/LOG-4253): This PR also fixes duplicate tolerations.
- https://issues.redhat.com/browse/LOG-4252
- https://issues.redhat.com/browse/LOG-4253
- https://issues.redhat.com/browse/LOG-3819
> Fixed LogFileMetricExporter UI information & tolerations

- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/constants/constants.go
- internal/metrics/logfilemetricexporter/factory.go
- internal/metrics/logfilemetricexporter/factory_test.go
Refactored default tolerations to have a single and immutable definition
/cc @Clee2691 
This is a follow-up to https://github.com/openshift/cluster-logging-operator/pull/2063
> Refactored default tolerations to have a single and immutable definition

- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/passphrase.go
This PR addresses the issue where `Fluentd` is unable to send logs to an `Elasticsearch` cluster when a passphrase is applied to the private key provided. 
The issue was resolved by adding the necessary configuration to the `Fluentd` Elasticsearch plugin, `Fluentd` now properly handles passphrase-protected private keys when establishing a connection with Elasticsearch.
E.g.:
`client_key_pass "#{File.exists?('/var/run/ocp-collector/secrets/es-secret/passphrase') ? open('/var/run/ocp-collector/secrets/es-secret/passphrase','r') do |f|f.read end : ''}"
`
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4258
> LOG-4258: Fluentd able to send logs to an Elasticsearch when using passphrase for the private key provided

- test/e2e/collection/fluentd/container_security_test.go
The use of the flag `--skip-headers` is deprecated in newer versions of `oc`. This PR removes this flag from `test/e2e/collection/fluentd/container_security_test.go` in the branch release-5.5, which will unblock PRs in openshift/release that run rehearsal e2e and smoke tests on release-5.5
Reference: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#removed-klog-flags
> [release-5.5] Remove --skip-headers oc flag from container_security_test.go

- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/gcl/gcl_test.go
This PR fix TLS configuration for [AWS Cloudwatch logs](https://vector.dev/docs/reference/configuration/sinks/aws_cloudwatch_logs/#tls) and [GCP Stackdriver](https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_logs/#tls), by removing `enabled = true` because this is lead to error after upgrading Vector to the new version
/cc @syedriko 
/cherry-pick 
- Depending on PR(s): #1988 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4242
> LOG-4242: remove 'enabled = true' from TLS config for Cloudwatch and GCL outputs

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_test.go
- test/functional/outputs/loki/application_logs_vector_test.go
This provides an additional fix with labels that have more then one dot and slash
* https://issues.redhat.com/browse/LOG-4095
> LOG-4095: fix labels with more then one dot

- internal/k8s/loader/load.go
- internal/validations/clusterlogging/suite_test.go
- internal/validations/clusterlogging/validate_clusterlogging_spec.go
- internal/validations/clusterlogging/validate_clusterlogging_spec_test.go
- internal/validations/clusterlogging/validations.go
- internal/validations/errors/errors.go
This PR:
* adds ClusterLogging validation in support of multi-clusterlogforwarder
* https://issues.redhat.com/browse/LOG-4239
> LOG-4239: Add ClusterLogging validation for multi clusterlogforwarder

- internal/k8shandler/collection.go
- internal/metrics/logfilemetricexporter/metric_exporter.go
- internal/network/service.go
- internal/network/service_test.go
The PR, adds the ability to set the value of the "component" label in k8s service selector. 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4283
> LOG-4283: fix 'component' label value

- internal/k8s/loader/load.go
- internal/validations/clusterlogforwarder/validate_clusterlogging_dependency.go
- test/e2e/logforwarding/splunk/forward_to_splunk_test.go
- Clarify CL-CLF dependency error message, it was not clear what the issue is.
- Fix race in e2e/logforwarding/splunk where CLF validation fails if CLF is created before CL:
```
{"_ts":"2023-07-13T19:59:19.412603726Z","_file:line":"test/helpers.go:122","_level":"3","_component":"e2e-framework_","_message":"begin: Recreate","object":"logging.openshift.io/v1/namespaces/openshift-logging/clusterlogforwarders/instance"}
{"_ts":"2023-07-13T19:59:19.412596876Z","_file:line":"test/helpers.go:122","_level":"3","_component":"e2e-framework_","_message":"begin: Recreate","object":"logging.openshift.io/v1/namespaces/openshift-logging/clusterloggings/instance"}
{"_ts":"2023-07-13T19:59:19.55473952Z","_file:line":"test/helpers.go:129","_level":"3","_component":"e2e-framework_","_message":"end  : …
```
> Clarify CL-CLF dependency error message, fix race in e2e/logforwarding/splunk

- test/framework/e2e/framework.go
Yet another race condition fix, this time with a log generator pod getting created in a newly created namespace which does not yet have its `sa/default` set up:
```
[ClusterLogForwarder] Forwards logs
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go:19
when the output is a CLO managed elasticsearch and no explicit forwarder is configured should default to forwarding logs to the spec'd logstore [BeforeEach]
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go:43
using vector collector
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go:70
Timed out waiting for the …
```
> De-raced test/e2e/logforwarding/elasticsearchmanaged

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
For Google Cloud Logging CLF API,  implement the "Exactly one of billing_account_id, folder_id, organization_id, or project_id must be set" rule.
/cc @vimalk78
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4324
> LOG-4324: Clarify GCL CLF API verification

- test/e2e/logforwarding/loki/forward_to_loki_test.go
- test/e2e/logforwarding/splunk/forward_to_splunk_test.go
- test/framework/e2e/framework.go
Addressed the following race:
```
--- FAIL: TestLogForwardingToLokiWithFluentd (26.95s)
test.go:107: test namespace: test-pmqwyblw
test.go:107: test namespace: test-pm3cossz
forward_to_loki_test.go:119: 
Error Trace:	/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/loki/forward_to_loki_test.go:119
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/logforwarding/loki/forward_to_loki_test.go:82
Error:      	Received unexpected error:
ClusterLogForwarder unexpected condition: conditions:
- lastTransitionTime: "2023-07-14T20:45:42Z"
message: 'validation failed: ClusterLogForwarder named "instance" depends on a missing
ClusterLogging instance'
reason: Invalid
status: "False"
type: Ready
Test:       	TestLogForwardingToLokiWithFluentd
```
, improved how a …
> De-race e2e forward_to_loki and forward_to_splunk

- apis/logging/v1/clusterlogging_types.go
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
Hide ClusterLogging deprecated fields in UI form view
* https://issues.redhat.com/browse/LOG-3880
> LOG-3880: Hide deprecated fields in UI form view

- internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go
This PR introduces a modification to the URL security check logic by skipping the check if a URL is not provided in the configuration, it because output URL is not necessary for certain output types, such as Amazon CloudWatch or Google Cloud Logging.
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-4302: skip checking URL on is secure if URL not provided in config

- internal/factory/daemonset.go
- internal/factory/daemonset_test.go
This PR:
* removes the critical-pod annotation that causes a warning in the logs and is/was removed in kube v1.16+
* https://issues.redhat.com/browse/LOG-3959
> LOG-3959: remove obsolete critical-pod annotation

- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
Generate "pipeline_$i" names for anonymous CLF pipelines.
/cc @Clee2691 
/cherry-pick release-5.7
- JIRA: https://issues.redhat.com/browse/LOG-4330
> LOG-4330: [release-5.8] Anonymous pipelines in ClusterLogForwarder no longer work after upgrading OpenShift Logging to 5.7

- internal/collector/cloudwatch.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/generator/fluentd/output/cloudwatch/aws.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/output/security/security_test.go
- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
- internal/generator/fluentd/suite_test.go
Fix fluentd so it no longer uses ENV vars for sts credentials.
A change to the fluentd code resulted in regression of multiple role_arn authentication, when forwarding to cloudwatch. The change was introduced in logging 5.6, while implementing vector sts for cloudwatch. A similar change will need to be made for vector, once we figure out an authentication workaround.
/cc @Clee2691 @syedriko @vparfonov
- v5.7:  https://issues.redhat.com/browse/LOG-4368
- v5.6   https://issues.redhat.com/browse/LOG-4084
> [release-5.7] LOG-4368: Fix fluentd sts cloudwatch multiple roles

- internal/collector/cloudwatch.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/generator/fluentd/output/cloudwatch/aws.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/splunk/splunk_test.go
Fix fluentd so it no longer uses ENV vars for sts credentials.
A change to the fluentd code resulted in regression of multiple role_arn authentication, when forwarding to cloudwatch.    The change was made in logging 5.6, while implementing vector sts for cloudwatch.   This will need to be fixed forward in 5.7 and 5.8 as well.       A similar change will need to be made for vector, once we figure out an authentication workaround.
/cc @Clee2691 @syedriko @vparfonov 
- https://issues.redhat.com/browse/LOG-4084
> LOG-4084: Fix fluentd sts cloudwatch auth using multiple roles

- internal/collector/cloudwatch.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/generator/fluentd/output/cloudwatch/aws.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/output/security/security_test.go
- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
- internal/generator/fluentd/suite_test.go
Fix forward from 5.6,5.7
Fix fluentd so it no longer uses ENV vars for sts credentials.
A change to the fluentd code resulted in regression of multiple role_arn authentication, when forwarding to cloudwatch. The change was introduced in logging 5.6, while implementing vector sts for cloudwatch. A similar change will need to be made for vector, once we figure out an authentication workaround.
/cc @Clee2691 @syedriko @vparfonov
- v5.8:  https://issues.redhat.com/browse/LOG-4371
- v5.7:  https://issues.redhat.com/browse/LOG-4368
- v5.6:  https://issues.redhat.com/browse/LOG-4084
> LOG-4371: Fix for fluentd sts cloudwatch using multiple roles

- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
Generate "pipeline_$i" names for anonymous CLF pipelines.
This is a manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/2092.
/cc @Clee2691
- JIRA: https://issues.redhat.com/browse/LOG-4120
> LOG-4120: [release-5.7] Anonymous pipelines in ClusterLogForwarder no longer work after upgrading OpenShift Logging to 5.7

- internal/k8s/loader/load.go
- internal/migrations/migrate_visualization.go
- internal/migrations/migrate_visualization_test.go
This PR introduce ability to initialize `spec.visualization` with ocp-console plugin, if `LogStore` was defined as `lokistack` and the visualization not defined
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4240
> LOG-4240: initialize spec.visualization with ocp-console plugin, if spec.LogStore was defined as lokistack and the visualization not defined

- bundle/manifests/logging.openshift.io_clusterloggings.yaml
- config/crd/kustomization.yaml
- config/crd/singleton-patch.yaml
- hack/testing-olm/test-010-deploy-via-olm-minimal.sh
This PR addresses the issue of creating multiple `ClusterLogging` instances. This is the removal of the singleton patch.
/cc @cahartma @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-4310
> LOG-4310: Creating CL with 'name != instance' gets error

- controllers/logfilemetricsexporter/logfilemetricsexporter_controller.go
- internal/auth/rbac.go
- internal/auth/rbac_test.go
- internal/auth/securitycontextconstraint.go
- internal/auth/service_account.go
- internal/auth/suite_test.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/reconciler.go
- internal/metrics/logfilemetricexporter/daemonset.go
- internal/metrics/logfilemetricexporter/daemonset_test.go
- internal/metrics/logfilemetricexporter/factory.go
- internal/metrics/logfilemetricexporter/metric_exporter.go
- internal/metrics/logfilemetricexporter/metric_exporter_test.go
- internal/utils/comparators/scc/comparator_test.go
- internal/utils/utils.go
This PR:
- Fixes LFME resource cleanup
- Remove creation of a "virtual" LFME resource when `ClusterLogging` CR is created without a LFME CR
- Remove dependence of LFME on a `ClusterLogging` instance
/cc @cahartma @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-4397
> LOG-4397: LFME pods are not removed

- hack/testing-olm/test-1343-minimal-multi-clf.sh
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
This PR:
* fixes SA permissions match the enhancement to only allow ClusterRoleBindings to define log types to be collected
*  https://issues.redhat.com/browse/LOG-4433
cc @Clee2691
> LOG-4433: fix only clusterrolebindings are allowed to collect logs

- test/helpers/loki/receiver.go
- test/helpers/loki/receiver_test.go
This PR:
* Updates the loki test image to 2.8.4
* Modifies the ingestion rates and limits to address e2e loki test flake
* https://issues.redhat.com/browse/LOG-4181
> LOG-4181: fix loki test flake caused by rate limiting

- bundle/manifests/logging.openshift.io_logfilemetricexporters.yaml
- config/crd/kustomization.yaml
- controllers/logfilemetricsexporter/logfilemetricsexporter_controller.go
- internal/validations/logfilemetricsexporter/suite_test.go
- internal/validations/logfilemetricsexporter/validate_name.go
- internal/validations/logfilemetricsexporter/validate_name_test.go
- internal/validations/logfilemetricsexporter/validations.go
This PR adds validation for the name of `LogFileMetricExporter` resources and namespaces during reconciliation. Additionally, it introduces an enhancement to perform additional checking for the resource name during resource creation using `Kustomize` and a `Custom Resource Definition (CRD)`.
- In the reconciliation logic:
* Added validation logic to ensure that the name of `LogFileMetricExporter` resources equals to `instance`.
* Implemented checks to ensure that namespaces name equals to `openshift-logging`.
- In the `LogFileMetricExporter CRD` updated, the definition to include validation constraints for the `metadata.name` field ensures that only valid resource name `instance` is accepted
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: …
> LOG-4451: add validations name for logfilesmetricexporter: should be named instance and be in openshift-logging namespace

- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
This PR overrides the default name of the log field to used to retrieve the timestamp to send to Splunk HEC to the `@timestamp`. 
https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#timestamp_key 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4413 
> LOG-4413: Overrides the name of the log field used to retrieve the timestamp to send to Splunk HEC

- internal/generator/vector/conf.go
- internal/generator/vector/conf_test/complex.toml
- internal/generator/vector/conf_test/complex_es_no_ver.toml
- internal/generator/vector/conf_test/complex_es_v6.toml
- internal/generator/vector/conf_test/es_pipeline_w_spaces.toml
- internal/generator/vector/global.go
Added expire_metrics_secs=60 [seconds] to vector global options, in order to cap grows of the metrics' memory footprint.
/cc @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4171
> LOG-4171: add expire_metrics_secs to vector global options

- internal/generator/vector/conf.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/global.go
Added expire_metrics_secs=60 [seconds] to vector global options, in order to cap grows of the metrics' memory footprint.
/cc @cahartma
- Depending on PR(s): https://github.com/openshift/cluster-logging-operator/pull/2135
- JIRA: https://issues.redhat.com/browse/LOG-4171
> [release-5.7] LOG-4171: add expire_metrics_secs to vector global options

- controllers/forwarding/forwarding_controller.go
- internal/collector/daemonset.go
- internal/factory/resource_names.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/errors/errors.go
- internal/validations/errors/errors_test.go
This PR fixes not reconciling on permission change:
* Adds a periodic requeue of CLF because we can not efficiently watch ClusterRoleBindings
* Removes collector DaemonSet when permissions are not allowed
* https://issues.redhat.com/browse/LOG-4431
cc @xperimental @Clee2691 @cahartma
> LOG-4431: fix collector not reconciling on permission change

- Dockerfile
- internal/utils/utils.go
A previous change to our Dockerfile removed the /usr/share/logging directory.   This caused an issue in midstream that required the same changes.    I've also removed the only function I found that used that directory.
/cc @Clee2691 @syedriko @vparfonov 
- upstream change:  https://github.com/openshift/cluster-logging-operator/pull/2123/files
- midstream fix:  https://gitlab.cee.redhat.com/openshift-logging/log-collection-midstream/-/merge_requests/2208
> Cleanup from previous Dockerfile update

- internal/k8s/loader/load.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/logstore/lokistack/logstore_lokistack.go
- internal/logstore/lokistack/logstore_lokistack_test.go
- internal/migrations/migrate_clusterlogforwarder.go
- internal/migrations/migrate_clusterlogforwarder_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
This PR removes retrieval of the service account token for multi-CLF when reconciling the collection.
For the legacy case, when forwarding to the internal default lokistack store, migration of lokistack now includes adding the service account token as a secret.
/cc @cahartma @syedriko @vparfonov 
- JIRA: https://issues.redhat.com/browse/LOG-4446
> LOG-4446: CLO raises many error messages 'Could not find ServiceAccount token secret' after creating multiple-CLF

- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
This PR:
* fixes the case where depeloyment was successful when no clusterrolebinding existed.
* adds to #2129
* https://issues.redhat.com/browse/LOG-4450
> LOG-4450: fix failed to validate when permission is absent

- internal/validations/clusterlogforwarder/validate_name.go
- internal/validations/clusterlogforwarder/validate_name_test.go
This PR:
* restricts the CLF name to one that will result in admisable kubernetes objects (e.g. service) 
* https://issues.redhat.com/browse/LOG-4470
> LOG-4470: fix unallowed clf name

- internal/cmd/functional-benchmarker/config/options.go
- internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go
- internal/cmd/functional-benchmarker/stats/types.go
* explitly use loader image that broke benchmark tool
* forward port of https://github.com/openshift/cluster-logging-operator/pull/2144
> Fix benchmark image being used

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/loki/loki_test.go
- test/functional/outputs/loki/application_logs_vector_test.go
This PR fixes using loki custom label keys for vector:
* quoting template values to ensure valid VRL path
* replaces dash in keys for compatibility with fluent loki plugin
* https://issues.redhat.com/browse/LOG-4460
> LOG-4460: fix loki custom labelKeys for vector

- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/clusterloggingrequest_test.go
- internal/k8shandler/reconciler.go
This PR fixes ownership for legacy CLF so that when ClusterLogging is removed the collectors are as well.  No collectors should exist when there is legacy CLF without legacy CL
* https://issues.redhat.com/browse/LOG-4410
cc @Clee2691
> LOG-4410: fix resource ownership for legacy CLF

- internal/visualization/console/feature_map.go
- internal/visualization/console/feature_map_test.go
This PR adds the `dev-alerts` feature to the logging view plugin for OCP 4.14
/cc @jcantrill
- JIRA: https://issues.redhat.com/browse/LOG-4477
> LOG-4477: add dev-alerts feature for OCP 4.14

- apis/logging/v1/conditions.go
- controllers/forwarding/forwarding_controller.go
- internal/k8shandler/reconciler.go
This PR fixes the status section of `ClusterLogForwarders` (CLF)s for the legacy mode. When a CLF is defined without a `ClusterLogging` instance, it will now add the appropriate validation error to the CLF's status section after reconciliation.
Additionally, the status `CollectorDeadEnd` is removed.
/cc @cahartma @syedriko @vparfonov 
- JIRA: https://issues.redhat.com/browse/LOG-4488
> LOG-4488: CLF status is inaccurate for legacy mode

- must-gather/collection-scripts/gather
Updated fix for must-gather fix already merged in:  https://github.com/openshift/cluster-logging-operator/pull/2143
Jira: https://issues.redhat.com/browse/LOG-4404
> Updated fix for LOG-4404 must-gather

- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- test/functional/normalization/eventrouter_test.go
This PR additionally fixes eventrouter normalization to assume deployment based upon  openshift docs template: https://docs.openshift.com/container-platform/4.13/logging/cluster-logging-eventrouter.html 
https://issues.redhat.com/browse/LOG-4178
Events are parsed as expected when podman begins with "eventrouter-"
> LOG-4178: fix vector eventrouter collection to rely on template name

- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/config.go
- internal/collector/fluentd/visitors.go
- internal/collector/vector/run_script.go
- internal/collector/vector/utils.go
- internal/collector/vector/visitors.go
- internal/factory/resource_names.go
- internal/factory/resource_names_test.go
- internal/generator/fluentd/conf.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/forwarder/generator.go
- internal/generator/vector/conf.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/conf_test/complex_custom_data_dir.toml
- internal/generator/vector/global.go
- internal/k8shandler/forwarding.go
- internal/pkg/generator/forwarder/generator.go
- test/framework/functional/fluentd/deploy.go
- test/framework/functional/framework.go
- test/framework/functional/vector/deploy.go
This PR:
- Adding a Run Script for Vector:
A run script for Vector is being added. This script will enable pre-run tasks, such as creating custom directories for persisting Vector state. This can be useful for setting up Vector environment or configuration before it starts processing data.
- Making Paths for Vector Checkpoints Unique:
To ensure uniqueness for Vector checkpoints files, the PR proposes adding the namespace name and the name of the CLF (Cloud Logging Framework) to the path. This means that the path to the checkpoints file will include both the namespace and CLF name, making it easier to manage and identify Vector instances for different namespaces and CLFs.
For example, the path to a Vector checkpoint file could look like this:` …
> LOG-4481: make unique paths for Vector checkpoints file according to multiple-CLFs installation

- apis/logging/v1/output_types.go
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/constants/constants.go
- internal/constants/features.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/conf_test/complex_otel.toml
- internal/generator/vector/normalize/schema/otel/transform.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/pipelines.go
- internal/k8shandler/forwarding.go
- test/framework/functional/cluster_log_forwarder.go
- test/functional/normalization/schema/otel_test.go
- test/functional/normalization/schema/suite_test.go
- test/helpers/schema/otel/types.go
- test/helpers/types/types.go
This PR is a continuation of the effort by Jatin Suri to support transforming the log record formats to the OpenTelemetry semantic.
This feature is:
- Locked behind a feature-gate
- Applies only to `application` logs
- Can only be defined for `HTTP` outputs under the `HTTP` output spec
| Original| New	|
|---|---|
| @timestamp |	timeUnixNano |
| level	|severityText |
| N/A	|	severityNumber |
| file	|resources.logs.file.path |
| hostname	|resources.host.name |
| kubernetes.container_name	|resources.container.name |
| kubernetes.container_id	|resources.container.id |
| kubernetes.container_image	|resources.container.image.name |
| N/A	|resources.container.image.tag |
| kubernetes.pod_name	|resources.k8s.pod.name |
| kubernetes.pod_id	|resources.k8s.pod.uid |
| kubernetes.pod_ip …
> LOG-4231: CLO operator support for optional OTEL data model

- internal/generator/generator.go
- internal/generator/vector/elements/elements.go
- internal/generator/vector/inputs.go
- internal/utils/comparators/servicemonitor/comparator.go
In this PR, we aim to resolve an issue causing configuration discrepancies during reconciliation, ultimately leading to unnecessary collector pod restarts. The root of the problem lies in the behavior of the `Go range function`, which does not guarantee the same ordering in each call for the same map (see: https://go.dev/blog/maps). This unpredictability can result in occasional variations in configuration generation when processing the `Routes map` [(source),](https://github.com/openshift/cluster-logging-operator/pull/2164/files#diff-6b7baf71ad4874089f6aa160edf27cdd8914a23a5d8db2fad126e352db8459daR11) impacting the stability of the system. Although this change in ordering means nothing for `Vector`, it significantly influences MD5 hash calculations, that we use for detecting changes in …
> LOG-4487: sort Map of Routes for predictable configuration generation during reconciliation

- internal/constants/features.go
- internal/k8shandler/visualization.go
- internal/k8shandler/visualization_test.go
- internal/visualization/console/plugin.go
Users migrating from Elasticsearch to LokiStack as the OpenShift Logging log store want to keep the flexibility to keep the existing stack while migrating to the new one. As per LokiStack installations being decoupled from ClusterLogging resources, this PR enables standalone OCP console installations via an ephemeral annotation `logging.openshift.io/ocp-console-migration-target` set to the LokiStack name w/o changing the `spec.logStore.Type` to `lokistack`. e.g.:
```yaml
kind: ClusterLogging
metadata:
name: instance
annotations:
logging.openshift.io/ocp-console-migration-target: "lokistack-dev"
spec:
managementState: Managed
logStore:
type: elasticsearch
retentionPolicy:
application:
maxAge: 1d
infra:
maxAge: 7d
audit:
maxAge: 7d
elasticsearch: …
```
> LOG-3856: Add standalone ocp console support for LokiStack migration

- Dockerfile
This PR:
* Updates CLO Dockerfile to use ubi minimal
* https://issues.redhat.com/browse/LOG-4532
> LOG-4532: update Dockerfile to ubi minimal

- must-gather/collection-scripts/gather_cluster_logging_operator_resources
Additional updates for must-gather fix original changes: https://github.com/openshift/cluster-logging-operator/pull/2143
This change adds additional vector toml files by appending the "name_" to the filename.   We are also now collecting the  "oc get lfme -o yaml" for each namespace that contains an instance.   They are being gathered in a file called "lfme.yaml"
/cc @syedriko @vparfonov 
Original
- https://issues.redhat.com/browse/LOG-4404
More fixes:
- https://issues.redhat.com/browse/LOG-4534
> LOG-4534 add multi toml and lfme to must-gather

- internal/k8s/loader/load.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
Added a CLF validation step to prevent deployment of HTTP Receivers with fluentd. The following diagnostic is produced:
```
$ oc -n openshift-logging get clf/instance -oyaml
status:
inputs:
http-input:
- lastTransitionTime: "2023-09-25T21:56:15Z"
message: ReceiverSpecs are only supported for the vector log collector
reason: Invalid
status: "False"
type: Ready
```
/cc @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4537
> LOG-4537: Collector pods stuck in ContainerCreating state when receiver.http is enabled in CLF

- Makefile
- internal/generator/vector/conf_test/complex.toml
- internal/generator/vector/conf_test/complex_custom_data_dir.toml
- internal/generator/vector/conf_test/complex_es_no_ver.toml
- internal/generator/vector/conf_test/complex_es_v6.toml
- internal/generator/vector/conf_test/complex_otel.toml
- internal/generator/vector/conf_test/es_pipeline_w_spaces.toml
- internal/generator/vector/global.go
- test/functional/inputs/http/http_input_test.go
- test/functional/misc/suite_test.go
- test/functional/misc/vector_api_cli_test.go
Enables vector GraphQL API for the vector CLI to work against a running vector instance, to improve ergonomics of troubleshooting.
/cc @cahartma
- Depending on PR(s): https://github.com/ViaQ/vector/pull/152
- JIRA: 
https://issues.redhat.com/browse/LOG-4556
https://issues.redhat.com/browse/OBSDA-482
> LOG-4556: Enable vector API and CLI

- files/dashboards/fluentd/openshift-logging-dashboard.json
This PR:
* fixes that "FluentD Buffer Availability" can show us the buffer usage based on the most highest usage value.
If "fluentd_output_status_buffer_available_space_ratio" metrics returns 100 and 50, "max" aggregation operator(current) always show us 0%(100-100) buffer usage, not 50%(100-50) buffer usage. It's not helpful to detect collector pods in high buffer usage. So it should change it to "min" aggregation operator for showing us values based on the most highest usage of buffer.
N/A
> LOG-4555: Show FluentD Buffer Usage in metrics dashboard instead of availability

- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
This PR fixes writing to the default LokiStack `Fluentd` collector, by set CA from `logcollector` `ServiceAccount`
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4559
> LOG-4559: fix writing to default lokistack with Fluentd collector

- apis/logging/v1/cluster_log_forwarder_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- docs/reference/operator/api.adoc
- test/e2e/flowcontrol/flowcontrol_test.go
- test/functional/flowcontrol/application_test.go
This PR drops support of GroupLimit in the flow control epic by:
* disabling JSON serialization of the field
* removing it from the CRD and generated API docs
GroupLimit applies per instance of the collector so it can be misleading from an API perspective.  We agreed we need to revisit how to convey applying it to a group of pods that may be dispersed across several nodes.  Leaving the implementation to facilitate future corrections
* https://issues.redhat.com/browse/LOG-4362
cc @alanconway
> LOG-4362: remove GroupLimit from flow control

- internal/k8s/loader/load.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding_test.go
- internal/migrations/clusterlogforwarder/drop_unreferenced_outputs.go
- internal/migrations/clusterlogforwarder/drop_unreferenced_outputs_test.go
- internal/migrations/clusterlogforwarder/migrate_clusterlogforwarder.go
- internal/migrations/clusterlogforwarder/migrate_clusterlogforwarder_test.go
- internal/migrations/clusterlogforwarder/suite_test.go
- internal/migrations/migrations.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
- test/matchers/condition.go
This PR:
* Adds CLF migration to drop outputs which are not referenced by pipelines to be consistent with previous release
* Adds validation to reject CLF that have unreferenced outputs
* Adds CLF conditions identifying when an output is not considered during reconciliation
* Adds matchers for conditions into the test package
* https://issues.redhat.com/browse/LOG-4411
> LOG-4411: fix vector config for unreferenced output

- internal/generator/vector/conf_test/complex.toml
- internal/generator/vector/conf_test/complex_custom_data_dir.toml
- internal/generator/vector/conf_test/complex_es_no_ver.toml
- internal/generator/vector/conf_test/complex_es_v6.toml
- internal/generator/vector/conf_test/complex_otel.toml
- internal/generator/vector/conf_test/es_pipeline_w_spaces.toml
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
For the kubernetes_logs vector source, override the (very large) default for the newly introduced rotate_wait_ms variable.
/cc @cahartma 
- PRs: https://github.com/ViaQ/vector/pull/154 // needs this to merge first
- JIRA: https://issues.redhat.com/browse/LOG-3949
> LOG-3949: Vector not releasing deleted file handles

- internal/generator/vector/conf_test.go
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
For the kubernetes_logs vector source, override the (very large) default for the newly introduced rotate_wait_ms variable.
This is a manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2185
/cc @cahartma 
- Depending on PR(s): https://github.com/openshift/cluster-logging-operator/pull/2185
- JIRA: https://issues.redhat.com/browse/LOG-4575
> LOG-4575: Vector not releasing deleted file handles

- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
Fix for CLF with an HTTP receiver validation failure, now HTTP receivers are treated as audit log sources.
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4574
> LOG-4574: Input permission validation failure with an HTTP receiver as input in a multiple-CLF

- internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch.go
- internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch_test.go
Set invalid condition when using parse `json` with without setting `structuredTypeKey` or `structuredTypeName`
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4441
> LOG-4441: set invalid condition when using parse json with without setting structuredTypeKey or structuredTypeName

- internal/k8shandler/collection.go
Make CLF the owner of the Services and Secrets associated with HTTP receivers so they are GC'd once the CLF defining the corresponding HTTP receivers is deleted.
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4577
> LOG-4577: Resources created after enabling receiver.http are not cleaned up after CLF is deleted

- internal/constants/constants.go
- internal/generator/vector/output/splunk/splunk.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
Added CLF validation for the hecToken in the Splunk secret
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-4580
> LOG-4580: Add validation for secret used with the Splunk output in CLF

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR modifies the manifest to only allow install mode of "all namespaces"
* https://issues.redhat.com/browse/LOG-4607
> LOG-4607: fix install mode to only AllNamespaces

- internal/generator/vector/metrics.go
On an IPv4-only cluster, vector fails to start because its metrics endpoint attempts to create an IPv6 socket. This PR adds a an IPv6 socket creation check and selects the right listen-to address.
/cc @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4589
> LOG-4589: vector fails to start on a node with IPv6 disabled

- internal/generator/vector/helpers/helpers.go
- internal/generator/vector/metrics.go
- internal/generator/vector/outputs.go
- internal/generator/vector/sources.go
Detect the correct "listen on all local interfaces" address and use it for HTTP receivers and Prometheus metrics. Further development of https://github.com/openshift/cluster-logging-operator/pull/2200.
/cc @xperimental 
- JIRA: https://issues.redhat.com/browse/LOG-4608
> LOG-4608: [httpserver] Connection refused on IPv6 cluster

- files/dashboards/fluentd/openshift-logging-dashboard.json
Backport of #2172 to 5.6
- JIRA: [LOG-4579](https://issues.redhat.com//browse/LOG-4579)
> LOG-4579: Show FluentD Buffer Usage in metrics dashboard instead of availability

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This reverts commit b2384abf1c686ba7574c9fe337fcb356ef512ca5.
This PR reverts the prior change after testing that existing deployments can successfully upgrade to 5.8.  The implications here is existing deployments will need to adjust there operatorgroup to take full advantage of mCLF.  Additionally it may be new deployments must explicitly choose "all namespaces" or will need to edit the operatorgroup in the future if they do not
* https://issues.redhat.com/browse/LOG-4650
> Revert "LOG-4607: fix install mode to only AllNamespaces"

- Makefile
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/conf_test/complex.toml
- internal/generator/vector/conf_test/complex_custom_data_dir.toml
- internal/generator/vector/conf_test/complex_es_no_ver.toml
- internal/generator/vector/conf_test/complex_es_v6.toml
- internal/generator/vector/conf_test/complex_otel.toml
- internal/generator/vector/conf_test/es_pipeline_w_spaces.toml
- internal/generator/vector/filter/apiaudit/policy.vrl.tmpl
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- test/framework/e2e/framework.go
- test/functional/collection/namespace_filtering_test.go
- test/functional/filters/apiaudit/vrl/suite_test.go
- test/functional/inputs/http/http_input_test.go
- test/functional/normalization/audit_logs_format_test.go
The kubeapi-server webhook serializes audit Events without "apiVersion" or "kind" fields.
The audit filter was using these fields to identify API-audit log records.
Instead check for presence and type of "auditID" and "verb" which are always present.
Other changes:
- Don't overwrite "level" field for API audit events, users will expect this field.
- test/functionl/vector.go make vector the default collector default if no build tags are set.
> LOG-4681: kubeAPIAudit policies don't work on audit logs from auditWebhook

- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/outputs.go
- internal/generator/fluentd/pipeline_to_output.go
- test/functional/pipelines/pipelines_test.go
This PR addresses the issue where conflicts between output and pipeline names have been occurring due to label generation. The root cause of this problem is that FluentD requires labels to be unique. We will prefix the label with 'OUTPUT_' for labels which conflict with pipeline names. This adjustment ensures that output labels are unique and distinct from pipeline names.
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4383
> LOG-4383: resolve conflict between outputs and pipelines name

- internal/collector/daemonset.go
- internal/constants/constants.go
- internal/k8shandler/collection.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/service.go
- internal/network/service.go
This PR addresses removing stale `HTTP` input services when the `ClusterLogForwarder` (CLF) is modified. 
Originally when the `inputs.receiver.http` was removed from the CLF and updated, NOT deleted and recreated, any previously defined `HTTP` input services were not garbage collected. 
The approach was to label all `HTTP` input services with `http-input-service` and upon CLF reconciliation, check if the service is defined in the CLF as well as if the reconciling CLF owns the specific service. If the service is not defined, remove it.
/cc @syedriko @vparfonov 
- JIRA: https://issues.redhat.com/browse/LOG-4612
> LOG-4612: Service/secret is not deleted when the inputs.receiver.http is removed

- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR addresses the fact that no error is raised when a pipeline references a non-existing/ non-defined filter.
/cc @vparfonov @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-4655
> LOG-4655:No error in CLF when the filterRefs refers to a non-existing filter

- internal/collector/fluentd/run_script.go
This PR addresses the issue with collector pods crashing due to `Fluentd` binding an IPv6 address that include brackets (`[::]`) for `prometheus` monitoring. `Fluentd v1.14.6` worked with the mentioned IPv6 address but `Fluentd v5.8.0` changed the way IPv6 addresses are handled.
/cc @syedriko @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4706
> LOG-4706: Fluentd CrashLoopBackOff on single stack IPv6 and dual stack clusters

- controllers/clusterlogging/clusterlogging_controller.go
- controllers/forwarding/forwarding_controller.go
This PR attempts to fix the `cluster logging operator` from reconciling dozens of times after a `ClusterLogForwarder` (CLF) was defined. After applying a CLF YAML, the resulting created daemonset's status was updating many time resulting in dozens of reconcile requests to the CLF. The proposed change is to ignore the daemonset's status changes and only reconcile on spec changes.
/cc @jlarriba @syedriko @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4741
> LOG-4741: cluster-logging-operator reconciling dozens of times

- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
For vector forwarding to a syslog destination, generate the dedot transform that adds openshift.sequence to the log message.
/cc @cahartma 
/cherry-pick release-5.8
- JIRA: https://issues.redhat.com/browse/LOG-4786
> LOG-4786: Label 'openshift.sequence' is missing when forwarding logs over syslog with vector

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/generator/fluentd/output/http/http_test.go
- internal/generator/helpers/optional_pair.go
- internal/generator/helpers/optional_pair_test.go
- internal/generator/helpers/suite_test.go
- internal/generator/utils/utils.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/elements/keyval.go
- internal/generator/vector/output/buffer.go
- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/gcl/gcl_test.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/request.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/outputs_test.go
* Adds buffer and request settings to all outputs for vector in order to achieve some parity to prior releases
* Modifies http api timeout to be an int instead of string of an int
* https://issues.redhat.com/browse/LOG-4536
* backport of #2203
> LOG-4536: add request and buffer settings to address memory consumption

- internal/generator/framework/generator.go
- test/matchers/diff.go
- test/matchers/generator_element.go
- test/matchers/generator_element_test.go
This PR:
* adds test matchers to assist in testing conf generation and to make it possible for assertions to be consistent across the test base
* https://issues.redhat.com/browse/LOG-4813
cc @cahartma @syedriko
> LOG-4813: Add matcher to help test conf generation

- internal/collector/vector/run_script.go
In preparation for upstream vector v0.34.0, explicitly specify vector config file as /etc/vector/vector.toml. The default config file from v0.34.0 on is /etc/vector/vector.yaml.
- JIRA: https://issues.redhat.com/browse/LOG-4823
> LOG-4823: Explicitly specify vector config file as /etc/vector/vector.toml

- internal/generator/vector/conf/outputs.go
- internal/generator/vector/helpers/secrets.go
- internal/generator/vector/helpers/tls_options.go
- internal/generator/vector/input/inputs.go
- internal/generator/vector/normalize/throttle.go
- internal/generator/vector/output/common/throttle.go
- internal/generator/vector/output/metrics/prometheus.go
- internal/generator/vector/source/metrics.go
This PR:
* Moves metrics and throttle templates to separate files
* Moves metrics templates to output package since that is what it is
* Refactors TLS Options logic into separate helper function
* Refactors Secret retrieval into helper function
* https://issues.redhat.com/browse/LOG-4812
* Blocks [LOG-4743](https://issues.redhat.com//browse/LOG-4743)
cc @syedriko @cahartma
> LOG-4812: Refactor metrics templates and helper functions

- must-gather/collection-scripts/gather_cluster_logging_operator_resources
Add back quoting the variable to preserve whitespace
/cherry-pick release-5.8
https://issues.redhat.com/browse/LOG-4792
> LOG-4792 Quick fix must-gather to preserve white-spaces

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- internal/constants/constants.go
- internal/constants/features.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward.go
- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/syslog/syslog.go
- internal/k8shandler/visualization_test.go
- internal/visualization/console/config.go
- internal/visualization/console/plugin.go
- internal/visualization/console/reconciler.go
- internal/visualization/console/reconciler_test.go
- test/e2e/consoleplugin/smoke_test/consoleplugin_test.go
Korrel8r proxy is enabled whenever Loki view is.
Points to fixed service korrel8r in namespace korrel8r.
Keeping it simple, the role of enabling korrel8r will likely move out of CLO,
and become part of the new observability operator in future.
/cc @jcantrill
/cc @xperimental
/cc @gbernal
> LOG-4846: Adjust CLO to include the korrel8r proxy in the logging view plugin

- controllers/clusterlogging/clusterlogging_controller.go
- internal/hostedcontrolplane/hostedcontrolplane.go
- internal/hostedcontrolplane/hostedcontrolplane_test.go
- internal/hostedcontrolplane/suite_test.go
NOTE: Using unstructured objects for HCP because of dependency problems with the hypershift API package.
See https://issues.redhat.com/browse/HOSTEDCP-336.
> LOG-4445: Forwarder must use hosted clusterID on HCP cluster.

- internal/generator/vector/output/loki/loki.go
This PR addresses forwarding to an internal `LokiStack` where in the legacy case, if the `pipelines.outputs` is not default it will not apply the `logcollector-token` secret's `token` and `ca.crt`. For a CLF named instance it will add the `logcollector` service account token to be used.
- JIRA: https://issues.redhat.com/browse/LOG-4852
> LOG-4852: Vector collector Pods no longer picks up the log collector SAs Secret as a fallback

- internal/generator/vector/input/viaq_receiver_http_audit.toml
- internal/generator/vector/input/viaq_receiver_syslog.toml
- internal/generator/vector/source/http_receiver.go
- internal/generator/vector/source/syslog_receiver.go
This change enables TLS on the Vector aggregator Syslog source using the the same secret key names and meanings as all the other TLS  outputs we support.
/cc @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-4848
> LOG-4848: Enable TLS on tcp connections for rsyslog server

- internal/generator/vector/source/kubernetes_logs.go
The [unit test](https://github.com/openshift/cluster-logging-operator/blob/6c69c486d3bd1ebb12828ba6b6af0ca1082497a7/internal/generator/vector/source/kubernetes_logs_test.go#L72) for `LabelSelectorFrom` expects the labels to be sorted by key. The underlying data structure is a `map[string]string` which does not sort the keys, so the result of the test depends on chance. This PR changes the implementation of `LabelSelectorFrom` to explicitly sort the map keys before creating the selector.
> Sort labels in LabelSelectorFrom as expected in test

- test/framework/functional/vector/deploy.go
Fix for upcoming vector v0.34.1, explicitly specify TOML config file because the default config format in the newer vector is now YAML.
- JIRA: https://issues.redhat.com/browse/LOG-4823
> LOG-4823: Update vector to upstream tag v0.34.1

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR:
* adds infrastructure annotations
@cahartma is it correct that we can claim aws token support?  We can use the tokens as provided by the CloudCredentialsOperator?
@syedriko is it correct we can claim FIPS compliance based upon the following definition? 
```
Whether the opperator accepts the [FIPS-140](https://issues.redhat.com/browse/FIPS-140) configuration of the underlying platform and works on nodes that are booted into FIPS mode. In this mode, the operator and any workloads it manages (operands) are solely calling the RHEL cryptographic library submitted for [FIPS-140](https://issues.redhat.com/browse/FIPS-140) validation.
```
* https://issues.redhat.com/browse/LOG-4604
> LOG-4604: Add infrastructure annotations

- apis/logging/v1/input_receiver_types.go
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/input/viaq_test.go
- internal/generator/vector/source/syslog_receiver.go
- internal/validations/clusterlogforwarder/inputs/validate.go
- internal/validations/clusterlogforwarder/inputs/validate_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
QA found an issue when udp was selected and tls was automatically applied. tls cannot work on udp protocol, so this was causing confusion. After a conversation, we decided that the udp protocol case is not required at the moment because OpenStack (the first user of the syslog receiver) will always send the logs via tls-encrypted tcp.
This PR removes the option to configure a protocol for the syslog receiver, as it will always use tcp.
- JIRA: https://issues.redhat.com/browse/LOG-4929
> LOG-4929: do not allow to choose protocol for syslog receiver

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- docs/features/logforwarding/outputs/splunk-forwarding.adoc
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
- test/framework/functional/cluster_log_forwarder.go
- test/framework/functional/framework.go
- test/framework/functional/output_splunk.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
- test/functional/outputs/splunk/suite_test.go
This PR adds the ability for users to configure `vector` to define an `index` for the `Splunk` output dynamically using a `meta-data` key such as `kubernetes.namespace_name` or a single static value such as `my-index`.
They are captured in new fields on the `ClusterLogForwarder` when specifying the Splunk output, named `indexKey` and `indexName`. Only one of the fields can be defined at once.
- JIRA: https://issues.redhat.com/browse/LOG-3651
> LOG-3651: [Vector] Add ability to change the Splunk's index within the ClusterLogForwarder

- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/security/security.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
This PR:
* fixes output config to allow configuration of tls.insecureSkipVerify without requiring a secret
* Refactors tls config to common function where possible
* https://issues.redhat.com/browse/LOG-4963
> LOG-4963: fix outputs to allows specifying insecureSkipVerify without

- docs/features/logforwarding/custom-tenants/custom-tenant-support.adoc
- docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc
This PR adds information on supporting custom tenants along with an example for `Elasticsearch` using `json` parsing to defined a custom index.
- JIRA: https://issues.redhat.com/browse/LOG-4844
> LOG-4844: Custom Tenant Spike

- must-gather/README.md
- must-gather/collection-scripts/common
- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_elasticsearch_operator_resources
For [LOG-4817](https://issues.redhat.com/browse/LOG-4817) the best solution is to remove this file from the 'oc get' under '/cluster-logging/clo' directory.   There is already a list of sanitized secrets listed under each namespace.   
The other changes are from PR 2257 below, are aligning docs and directory structure to be used with the 'omc' tool.
/cc @vparfonov @Clee2691 
- https://github.com/openshift/cluster-logging-operator/pull/2257
> Remove raw secrets from must-gather and update dir structure

- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR adds checks for a secure (HTTPS) URL and given TLS configuration. Throwing an error in the status section indicating that the options used are invalid together. The specific error being addressed is: "invalid configuration: provided not secure URL along with TLS configuration."
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4893
> LOG-4893: add validation for checking if provided not secure URL along with TLS configuration

- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR add's:
- validation if no secret for CloudWatch and Splunk outputs CLF status will report about invalid state
- few tests for checking validation code for Splunk output 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5021
> LOG-5021: add validation if no secret for CloudWatch and Splunk outputs

- internal/collector/collector.go
- internal/collector/daemonset.go
- internal/factory/resource_names.go
- internal/generator/fluentd/conf.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/forwarder/generator.go
- internal/generator/vector/conf.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/sources.go
- internal/k8shandler/collection.go
- internal/k8shandler/forwarding.go
- internal/pkg/generator/forwarder/generator.go
This PR addresses the issue with HTTP receiver input services being endlessly reconciled when multiple `ClusterLogForwarders` spec an HTTP receiver input with the same name. A new function is added to generate unique input names for the service.
- JIRA: https://issues.redhat.com/browse/LOG-5009
> LOG-5009: HTTP receiver service in endless reconcile when multiple CLFs spec an HTTP input with the same receiver name

- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR add's:
- validation if no secret for CloudWatch and Splunk outputs CLF status will report about invalid state
- few tests for checking validation code for Splunk output
manual cherry-pick for #2324  
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com//browse/LOG-5021
> LOG-5021: add validation if no secret for Cloudwatch and Splunk output

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
[LOG-5034](https://issues.redhat.com//browse/LOG-5034) was created to remove the annotation which creates a required "role_arn" at install of our logging operator.   This will remove us from the "token enabled" list in the operator hub, but the resulting required field is more confusing than not being included in the list. 
This can be backported once verified.
Ultimately, we need to come up with a better solution to the epic requiring this "role_arn at install" feature.  re:  https://issues.redhat.com/browse/LOG-4154
- https://issues.redhat.com/browse/LOG-5034
- https://issues.redhat.com/browse/LOG-4154
> LOG-5034: Remove required field from install on STS and ROSA

- controllers/forwarding/forwarding_controller.go
This PR addressing to fixing issue with reconciling (deleting) collector in case removing `ClusterLogForwarding` instance. 
Since the CLF instance is already removed, we can't take `instance.Namespace`  and `instance.Name`, so added logic to take this values from other source.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5035
> LOG-5035: fix deleting collector procedure in case removing CLF instance

- internal/generator/vector/helpers/secrets.go
- internal/generator/vector/helpers/secrets_test.go
- internal/generator/vector/helpers/suite_test.go
This PR:
* fixes the case where outputs which define no secret still generate config with the legacy token secret
* Adds a function for secret special handling of generated default loki outputs
* https://issues.redhat.com/browse/LOG-4962
* forward port of #2307 
cc @xperimental @Clee2691
> LOG-4962: fix outputs with no secret adding bearer token

- internal/validations/clusterlogforwarder/outputs/splunk.go
- internal/validations/clusterlogforwarder/outputs/splunk_test.go
- internal/validations/clusterlogforwarder/outputs/suite_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
This PR addressing to fix collector crashes when the `splunk.IndexKey` parameter contains symbols not allowed by Vector's template syntax, which adheres to VRL path expressions. 
Implements stricter validation for `splunk.IndexKey` to ensure it conforms to VRL path rules:
- only alphanumeric characters and underscores `(a-zA-Z0-9_)` are allowed.
- segments containing other characters must be quoted (e.g., `kubernetes.labels."test-logging"`).
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5047
> LOG-5047: Fix Vector collector crash for invalid splunk.IndexKey symbols

- Dockerfile
The oc client used during must-gather needed to be updated to something compiled on rhel9.   I've changed the Dockerfile to pull the oc binary from a different cli image.   Also need to update midstream dockerfile.
/cc @Clee2691 @vparfonov 
- https://issues.redhat.com/browse/LOG-4403
> LOG-4403: Updating to oc.rhel9 binary for FIPS must-gather issue

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/collector_alerts.yaml
This PR introduces three new Prometheus alerts to notify about the deprecation of `fluentd`, `elasticsearch`, and `kibana`.
/cc @cahartma @vparfonov @xperimental 
- JIRA: https://issues.redhat.com/browse/LOG-5055
> LOG-5055: Add deprecation alerts

- apis/logging/v1/input_receiver_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/migrations/clusterlogforwarder/migrate_inputs.go
- internal/migrations/clusterlogforwarder/migrate_inputs_test.go
This PR makes `spec.inputs[0].receiver.type` an optional field instead of a required one. This change is necessary to prevent potential failures during updates from version 5.8.x to version 5.9. Additionally, it introduces a migration feature that sets `receiver.type` according to the given configuration if it is not already set, allowing for `http` or `syslog` configurations.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5053
> LOG-5053: make  spec.inputs[0].receiver.type optional to prevent failing on update to the CLO 5.9

- apis/logging/v1/cluster_log_forwarder.go
- apis/logging/v1/input_receiver_types.go
- internal/collector/collector.go
- internal/collector/daemonset.go
- internal/collector/deployment.go
- internal/constants/constants.go
- internal/generator/vector/input/receiver.go
- internal/generator/vector/input/viaq.go
- internal/generator/vector/source/http_receiver.go
- internal/generator/vector/source/syslog_receiver.go
- internal/k8shandler/collection.go
- internal/logstore/lokistack/logstore_lokistack.go
- internal/validations/clusterlogforwarder/inputs/validate.go
- internal/validations/clusterlogforwarder/inputs/validate_test.go
This is a change mandated by concision in the yaml, as we had a lot of "syslog" mandatory definitions. Due to the limitations on kubebuilder:default (it does not work on fields whose "parent" is empty), we had to go back to the original "GetPort()" funcs.
The change was requested for syslog receiver, but the necessary changes were also implemented in http receiver, as it would not have made any sense to have "syslog" optional but "http" mandatory.
I have also used this change to assign the IsSyslogReceiver, IsHttpReceiver and IsAuditHttpReceiver funcs to the Receiver struct, as it they "belong" naturally to a Receiver.
/cc @jcantrill @anpingli 
- JIRA: https://issues.redhat.com/browse/LOG-5002
> LOG-5002: input.receiver.syslog should be an optional field

- internal/metrics/telemetry/cloteleminfo.go
- internal/metrics/telemetry/cluster_log_forwarder.go
This PR adds in the `http` and `syslog` input receiver types to the metrics provided by `log_forwarder_input_info`.
/cc @cahartma @vparfonov
- JIRA: https://issues.redhat.com/browse/LOG-5043
> LOG-5043: No input.type httpreceiver in log_forwarder_input_info

- internal/metrics/telemetry/cloteleminfo.go
- internal/metrics/telemetry/cluster_log_forwarder.go
This PR adds in the `http` input receiver type to the metrics provided by `log_forwarder_input_info`.
- JIRA: https://issues.redhat.com/browse/LOG-5043
> [release-5.8] LOG-5043: No input.type httpreceiver in log_forwarder_input_info

- internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go
- internal/cmd/functional-benchmarker/stats/loss_stats.go
- internal/cmd/functional-benchmarker/stats/statistics.go
- internal/cmd/functional-benchmarker/stats/types.go
- internal/cmd/functional-benchmarker/stats/types_test.go
- test/framework/functional/output_http.go
This reverts commit c8236e85e453f927b94bce81e1acecc0d52da8ec.
This PR:
* reverts https://github.com/openshift/cluster-logging-operator/pull/2243
because it causes the receiver to introduce duplicate logs (why???)
Reverting for testing consistency with 5.7 
cc @alanconway @cahartma
> Revert "LOG-4809: reduce stream file size for functional-benchmarker"

- internal/metrics/telemetry/cluster_log_forwarder.go
- internal/migrations/clusterlogforwarder/migrate_inputs.go
- internal/migrations/clusterlogforwarder/migrate_inputs_test.go
This PR fixes the `CrashLoopBackOff` that occurs when a receiver input spec defines a `receiver.type` but not a `receiver.receiverTypeSpec` such as `http` or `syslog`.
- JIRA: https://issues.redhat.com/browse/LOG-5116
> LOG-5116: CLO CrashLoopBackOff when inputs.receiver does not spec a receiverTypeSpec

- internal/generator/vector/filter/prune/filter.go
- internal/generator/vector/filter/prune/filter_test.go
- internal/generator/vector/filter/prune/suite_test.go
- internal/generator/vector/pipeline/adapter_test.go
- internal/generator/vector/pipeline/adapter_test_prune_inOnly_filter.toml
This PR fixes the issue that quoted fields containing a `.` wouldn't be pruned .
Example:
```
.foo.bar."baz.test.field-111/222"
```
- JIRA: https://issues.redhat.com/browse/LOG-5117
> LOG-5117: Pruning field doesn't work when the specified field contains non-alphanumeric and non-underscores.

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_drop_filter.toml
- internal/generator/vector/conf/complex_es_no_ver.toml
- internal/generator/vector/conf/complex_es_v6.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/complex_otel.toml
- internal/generator/vector/conf/complex_prune_filter.toml
- internal/generator/vector/output/config_strategy.go
- internal/generator/vector/output/factory_test_loki_no_throttle.toml
- internal/generator/vector/output/factory_test_loki_with_throttle.toml
This PR reverts #2220 which introduces significant log loss.  The intent is to do more testing to determine if rotate_wait setting may have resolved  high memory consumption
* https://issues.redhat.com/browse/LOG-5123
> LOG-5123: revert LOG-4536 due to log loss

- internal/validations/clusterlogforwarder/outputs/azuremonitor.go
- internal/validations/clusterlogforwarder/outputs/azuremonitor_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR implements a rule to prevent LogType names from starting with an underscore (_). 
`_invalidName` : not valid name
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5121
> LOG-5121: Prevent LogType names from starting with underscores (_) for Azure log forwarder

- Makefile
- api/logging/v1/cluster_log_forwarder.go
- api/logging/v1/clusterlogforwarder_types_test.go
- api/logging/v1/conditions.go
- internal/controller/clusterlogging/clusterlogging_controller.go
- internal/controller/forwarding/forwarding_controller.go
- internal/k8s/loader/load.go
- internal/k8shandler/forwarding.go
- internal/validations/clusterlogforwarder/validate_clusterlogging_dependency.go
- test/client/clf.go
- test/e2e/logforwarding/miscellaneous/forward_miscellaneous_test.go
- test/matchers/condition.go
- test/matchers/lasttransitiontime.go
When the Forwarder is enabled, make sure that
clusterLogging.Spec.Collection is non nil to avoid nil pointer exceptions from occurring.
Fixes https://github.com/openshift/cluster-logging-operator/issues/2312
Fixes https://github.com/openshift/cluster-logging-operator/issues/2314
Fixes https://github.com/openshift/cluster-logging-operator/issues/2315
* https://issues.redhat.com/browse/LOG-5006
* https://issues.redhat.com/browse/LOG-5007
> Catch nil ptr exceptions with enabled Forwarder and empty Collection

- api/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/validations/clusterlogforwarder/conditions/set_conditions.go
- internal/validations/clusterlogforwarder/outputs/splunk.go
- internal/validations/clusterlogforwarder/outputs/splunk_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
After discussion about implementation difficulties, we have deprecated splunk.Fields.   They have indexKey or indexName to use instead.  The functionality has never been implemented in 2 years since the splunk forwarding was added.   
- https://issues.redhat.com/browse/LOG-5049
- https://issues.redhat.com/browse/LOG-4558
> LOG-5049: Deprecated non-working splunk fields and add validation

- api/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/k8shandler/forwarding.go
- test/functional/normalization/schema/otel_test.go
This PR disables the API for the `OTEL` schema option under the `http` sink for vector. It also disables the feature gate that was required to enable it.
- JIRA: https://issues.redhat.com/browse/LOG-5125
> LOG-5125: Disable API and feature gate for OTEL

- internal/metrics/telemetry/cloteleminfo.go
This PR adds `azureMonitor` as an output metric to the `log_forwarder_output_info` metric.
- JIRA: https://issues.redhat.com/browse/LOG-5130
> LOG-5130: metric log_forwarder_output_info doesn't include azureMonitor

- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
This PR fixes a nil pointer exception during service account validation for custom CLFs if they spec a receiver input without a `receiverTypeSpec`.
- JIRA: https://issues.redhat.com/browse/LOG-5140
> LOG-5140: CLO panic when input.receiver.syslog is not defined.

- internal/generator/vector/output/config_strategy.go
- internal/generator/vector/output/config_strategy_test.go
- internal/validations/clusterlogforwarder/outputs/tuning_test.go
- test/functional/outputs/http/forward_to_http_test.go
This PR fixes the collector pods `CrashLoopBackOff` when `maxRetryDuration` or `minRetryDuration` was spec'd for tuning. When a CLF spec'd 2 as the duration it would convert it to 2e-09s. A `time.Duration` is default to nanoseconds and must be converted to `seconds` first.
- JIRA: https://issues.redhat.com/browse/LOG-5148
> LOG-5148: The integer values are converted to float values

- internal/logstore/lokistack/logstore_lokistack.go
- internal/logstore/lokistack/logstore_lokistack_test.go
- internal/migrations/clusterlogforwarder/migrate_clusterlogforwarder.go
- internal/migrations/clusterlogforwarder/migrate_clusterlogforwarder_test.go
This PR fixes the issue where the default outputs (Elasticsearch & LokiStack) did not take into account the tuning parameters if a user defined them in the outputs.
- JIRA: https://issues.redhat.com/browse/LOG-5143
> LOG-5143: The tune option can not be appled when output name is default.

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This reverts commit c151979504a09f3bd6ea7acf14960fb6c7bdbe3c.
This PR reverts "Observability" category which is breaking downstream builds
> Revert "Add to the observability list in operatorhub"

- Makefile
- bundle.Dockerfile
Correct the range of supported ocp versions
- https://issues.redhat.com/browse/LOG-5145
> LOG-5145: Correct the range of supported ocp versions

- internal/generator/vector/conf/complex_otel.toml
- internal/generator/vector/output/common/request.go
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
This PR:
* Revert http output types to rely upon the defaults because the override was unintentionally added
* Removes unused http batch templates
* https://issues.redhat.com/browse/LOG-5163
cc @Clee2691
> LOG-5163: Rely upon http output timeout default

- api/logging/v1/cluster_log_forwarder_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
This PR fixes the invalid configuration for `compression` in a `vector.toml` when an output spec's `''` as the compression.
- JIRA: https://issues.redhat.com/browse/LOG-5158
> LOG-5158: The invalid compression value, '', in vector.toml

- cmd/main.go
This quick fix adds a call to the controller-runtime SetLogger() to resolve an error in the CLO.   A recent update to the runtime now requires this call.
Following the fix, we are now seeing a series of runtime "info" logs generated for every watched resource.  Additionally, there are several "Reconciler errors" produced for various reasons, as well as a Warning about the CLF reconciler.   
I will create a new task to clean up the remaining messages (if possible).   Also, there've been several concerns raised with a confusion between log verbosity level and log priorty level.   Additional work will be required to refactor the levels.
- https://issues.redhat.com/browse/LOG-5136
> Add call to runtime SetLogger to resolve error

- internal/validations/clusterlogforwarder/validate_collector_compatibility.go
- internal/validations/clusterlogforwarder/validate_collector_compatibility_test.go
- internal/validations/clusterlogforwarder/validations.go
This PR adds the ability to verify that the chosen output types are fully supported by the selected collectors. This feature safeguards against potential errors and inconsistencies that could arise from incompatible configurations.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5161
> LOG-5161:  Enhance configuration validation to ensure compatibility with selected collectors and output types

- docs/features/logforwarding/outputs/azure-monitor-log-forwarding.adoc
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> LOG-4606: create dev doc for Azure Monitor log forwarding integration

- config/docs/templates/apis/asciidoc/members.tpl
- config/docs/templates/apis/asciidoc/pkg.tpl
- docs/reference/operator/api.adoc
This PR is to update the API doc templates to help remove roadblocks to publishing our documentation in the OCP docs set.
I have updated things like headings, metadata, and formatting for now as a first step to minimize additional work for tech writers, but there is more to do and will likely require additional follow up PRs.
This change should also be updated in older branches, but I can do that manually and regenerate the API docs as I go, rather than auto-CPing.
- https://issues.redhat.com/browse/OBSDOCS-845
> Updates to API template to meet docs standards

- config/docs/templates/apis/asciidoc/members.tpl
- config/docs/templates/apis/asciidoc/pkg.tpl
- docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2389 and regen of 5.6 API docs for inclusion in product docs.
/hold
> [release-5.6] Updates to API template to meet docs standards

- config/docs/templates/apis/asciidoc/members.tpl
- config/docs/templates/apis/asciidoc/pkg.tpl
- docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2389 and regen of 5.7 API docs for inclusion in product docs.
> [release-5.7] Updates to API template to meet docs standards

- config/docs/templates/apis/asciidoc/members.tpl
- config/docs/templates/apis/asciidoc/pkg.tpl
- docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2389 and regen of 5.8 API docs for inclusion in product docs.
> [release-5.8] Updates to API template to meet docs standards

- internal/metrics/dashboard/openshift-logging-dashboard.json
This PR:
* fixes the collector dashboard  source metrics to use `vector_component_received_bytes_total`
https://issues.redhat.com/browse/LOG-5200
> LOG-5200: fix source collected bytes metric

- api/logging/v1/filter_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- docs/features/logforwarding/filters/drop-filter.adoc
- docs/features/logforwarding/filters/prune-filter.adoc
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
- internal/validations/clusterlogforwarder/validate_collector_compatibility.go
- internal/validations/clusterlogforwarder/validate_filters.go
- internal/validations/clusterlogforwarder/validate_filters_test.go
- test/framework/functional/cluster_log_forwarder.go
- test/framework/functional/cluster_log_forwarder_test.go
- test/framework/functional/framework.go
- test/framework/functional/output_cloudwatch.go
- test/functional/filters/drop/drop_filter_test.go
- test/functional/filters/prune/prune_filter_test.go
- test/functional/outputs/azuremonitor/forward_to_azuremonitor_test.go
- test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
- test/helpers/azuremonitor/mockoon.go
This PR ensures a fixed set of fields are not pruned from any log records and are required fields.
These fields are:
1. `.log_type`
2. `.message`
3. `.hostname` [^1]
[^1]: Only applies if a pipeline references `GoogleCloudLogging` as a destination, the `.hostname` field cannot be pruned from the log record.
> [!NOTE]  
> See upstream docs and API docs for more information.
This PR also refactors the `CloudWatch` functional test to make it easier to deploy.
- JIRA: https://issues.redhat.com/browse/LOG-5132
> LOG-5132: Identify fields that should be omitted from pruning

- internal/generator/vector/output/syslog/syslog.go
- internal/validations/clusterlogforwarder/outputs/tuning.go
- internal/validations/clusterlogforwarder/outputs/tuning_test.go
This PR adds in a validation to reject `syslog` sinks from setting `maxWrite` as a tuning option as it is not supported. This also adds `acknowledgement` support for future implementation.
- JIRA: https://issues.redhat.com/browse/LOG-5214
> LOG-5214: maxWrite, delivery is ignore when output is syslog

- internal/k8shandler/logstore.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/service.go
- internal/logstore/elasticsearch/reconcile.go
- internal/logstore/elasticsearch/status.go
This PR fixes the errors arising from using `client.Client` to list services because of the change in namespaces watched. `client.Reader` is needed to list objects from specific namespaces because it bypasses the cache.
- JIRA: https://issues.redhat.com/browse/LOG-5216
> LOG-5216: CLO raises many 'error removing stale http input services'

- api/logging/v1/input_receiver_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/migrations/clusterlogforwarder/migrate_inputs.go
- internal/migrations/clusterlogforwarder/migrate_inputs_test.go
- internal/migrations/migrations.go
This PR addressed to fix issue during migration CLF with not properly configured `Type` in `ReceiverSpec`
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5053
> LOG-5053: ensure inputs has right setted type before clfSpec migration 

- config/docs/templates/apis/asciidoc/members.tpl
The `summary` setting was causing docs to be cut off mid sentence when generating API docs. This PR removes that setting.
/cherry-pick release-5.8
/cherry-pick release-5.7
/cherry-pick release-5.6
> Update templates to fix truncated docs

- internal/validations/clusterlogforwarder/validate_filters.go
- internal/validations/clusterlogforwarder/validate_filters_test.go
This PR adds a `nil` check for drop and prune filters during validation and will raise a validation error if the appropriate `FilterTypeSpec` is not defined.
- JIRA:
1. https://issues.redhat.com/browse/LOG-5322
2. https://issues.redhat.com/browse/LOG-5323
> LOG-5322 & LOG-5323 segfaults if PrunfilterSpec or DropTestsSpec not spec'd

- internal/controller/forwarding/forwarding_controller_test.go
- internal/validations/clusterlogging/validate_clusterlogging_spec.go
- internal/validations/clusterlogging/validate_clusterlogging_spec_test.go
- internal/validations/clusterlogging/validations.go
This PR address to align validation feature with current documentation. During validation for `ClusterLogging` we will check is `ClusterLogForwarder`  in the same namespace named the same exist if not, exception will throw. 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5062
> LOG-5062: align validation with documentation

- internal/generator/vector/input/viaq.go
- internal/generator/vector/input/viaq_infrastructure_container.toml
This PR:
* Excludes the collection of logging infra for infrastructure container inputs(with the exception of collector container)
* Collector containers will be part of a separate issue
https://issues.redhat.com/browse/LOG-5309
> LOG-5309: Exclude log infra when collecting infra containers

- cmd/main.go
- version/cluster.go
This PR:
* refactors the retrieval of cluster version out of the CLO controller code
* Preps removal of CL controller
* https://issues.redhat.com/browse/LOG-5382
> LOG-5382: Refactor retrieval of cluster version

- docs/features/log_level.adoc
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/fluentd/visitors.go
- internal/collector/vector/visitors.go
- internal/constants/features.go
- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/collection.go
- internal/validations/clusterlogforwarder/validate_annotations.go
- internal/validations/clusterlogforwarder/validate_annotations_test.go
- internal/validations/clusterlogforwarder/validations.go
This PR enables configuration of the log level for the Vector collector through an annotation in the `ClusterLogForwarder` resource.
This introduces a new annotation: `observability.openshift.io/log-level`.
The log level can be set to one of `trace`, `debug`, `info`, `warn`, `error`, `off`.
Vector's default log level is `info`.
```
apiVersion: "logging.openshift.io/v1"
metadata:
name: instance
annotations:
observability.openshift.io/log-level: "debug"
spec:
...
```
- JIRA: https://issues.redhat.com/browse/LOG-5372
> LOG-5372: Enable log level for vector

- hack/testing-olm/test-1343-minimal-multi-clf.sh
This PR:
* extends the wait time for the multi-clf test to 90s as it appears the pods comeup but the wait times out prematurely
cc @Clee2691 @cahartma @vparfonov
> extend wait for multi-clf test

- Makefile
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_test.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
This PR addresses an issue with improperly formatted timestamp fields in audit log records. The problem occurs with records such as `type=BPF msg=audit(1713260779.116:5146): prog-id=2650 op=LOAD`, where the timestamp field lacks proper formatting. To resolve this issue, a remap transformation has been added: `.@timestamp = parse_timestamp(.@timestamp,"%+")`. This transformation ensures that the timestamp field is correctly parsed and formatted, resolving the formatting issue observed in the audit log records.
Changes Made:
- added remap transformation to parse and format the timestamp field in audit log records.
- added functional test to confirm the fix and ensure that the timestamp field is correctly formatted after applying the …
> LOG-4672: ensure timestamp field has correct format for Splunk

- go.mod
- go.sum
Run `go mod tidy` to enable downstream builds on 1.21.9
/cc @jcantrill
> NO-JIRA: Fix building with go1.21.9

- internal/controller/forwarding/forwarding_controller.go
- internal/validations/errors/errors.go
- internal/validations/errors/errors_test.go
This PR addresses the behavior of the reconciliation process, specifically focusing on error handling: the reconciler should skip all errors and leave the collector instance unchanged, only removing it in the event of a `Not authorized to collect` error.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4910
> LOG-4910: remove collector daemonset only if 'Not authorized to collect' error occurs

- cmd/main.go
- internal/metrics/dashboard/dashboards.go
- internal/metrics/dashboard/dashboards_test.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR introduces a new watcher for `grafana-dashboard-cluster-logging` ConfigMap resources to enable their reconciliation within our operator. With this enhancement, our operator can now react to changes/removing in ConfigMap objects, ensuring that the system remains synchronized and operates effectively in response to ConfigMap modifications.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5308
> LOG-5308: add watcher for grafana-dashboard-cluster-logging configMap to support it reconciliation

- config/overlays/stable/deployment_patch.yaml
- internal/cmd/functional-benchmarker/config/options.go
- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_drop_filter.toml
- internal/generator/vector/conf/complex_es_no_ver.toml
- internal/generator/vector/conf/complex_es_v6.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/complex_otel.toml
- internal/generator/vector/conf/complex_prune_filter.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/input/application.toml
- internal/generator/vector/input/application_exclude_container_from_infra.toml
- internal/generator/vector/input/application_excludes_container.toml
- internal/generator/vector/input/application_includes_container.toml
- internal/generator/vector/input/application_with_excludes.toml
- internal/generator/vector/input/application_with_includes.toml
- internal/generator/vector/input/application_with_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_matchLabels.toml
- internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_throttle.toml
- internal/generator/vector/input/infrastructure.toml
- internal/generator/vector/input/infrastructure_container.toml
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/source/kubernetes_logs_no_includes_excludes.toml
- internal/generator/vector/source/kubernetes_logs_with_includes.toml
This PR fixes `rotate_wait_ms` to `rotate_wait_secs` as this was implemented in upstream `vector:0.37.0`. This also changes CLO to use `vector:6.0` in the deployment patch & functional benchmarker.
- JIRA: https://issues.redhat.com/browse/LOG-5474
> LOG-5474: Fix CLO rotate_wait_ms to rotate_wait_secs

- config/docs/templates/datamodels/asciidoc/members.tpl
Expands on https://github.com/openshift/cluster-logging-operator/pull/2417 - to prevent truncated fields in API ref generation.
> Correction to prevent appended field descriptions.

- Makefile
Fixes `make deploy` by removing the `deploy-elasticsearch-operator` target which does not exist anymore.
/cc @cahartma
> Fix deploy Make target

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
Add the latest CLO container image to the bundle annotation, to accommodate the new `--all-images` flag.  Original attempt was to add to annotations in CPaaS, but they are currently converted to labels.   Since we have instructions upstream on utilizing the quay image with must-gather, this should be sufficient for now.
- JIRA: https://issues.redhat.com/browse/LOG-5108
- Enhancement proposal: https://groups.google.com/a/redhat.com/g/aos-logging/c/_-YYN3-2dOc/m/wzX3SWQFAwAJ
> [release-5.9] LOG-5108: Add must-gather annotation to csv

- internal/generator/vector/helpers/helpers.go
- internal/generator/vector/input/receiver_syslog_tls_from_configmap.toml
- internal/generator/vector/input/source_test.go
- internal/generator/vector/output/common/tls/tls.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/http/http_with_tls_using_configmaps.toml
This PR:
* Modifies TLS source and sink generation to retrieve certain tls config from configmaps
* https://issues.redhat.com/browse/LOG-5558
> LOG-5558: Add support for tls from configmap

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
Reverts openshift/cluster-logging-operator#2498
Failing cpaas build pipelines as "Registry not allowed"
> Revert "[release-5.9] LOG-5108: Add must-gather annotation to csv"

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
The new `namespace` label is missing on the Prometheus rules in the bundle (see #2490).
/cc @vparfonov
> LOG-5429: Update bundle after change to Prometheus rules

- internal/auth/rbac_test.go
- internal/factory/daemonset_test.go
- internal/factory/deployment_test.go
- internal/runtime/runtime.go
- internal/runtime/runtime_test.go
This PR:
* Drops labeling all resources using runtime functions with pod security labels which are only relevant to namespaces
* https://issues.redhat.com/browse/LOG-5568
> LOG-5568: Remove pod security labels from resource init

- Makefile
This PR enables dummy make targets to allow adding CI jobs to run these tests when we are ready
> Add dummy make targets to enable functional/e2e testing in CI

- controllers/clusterlogging/clusterlogging_controller.go
- internal/consoleplugin/coo_compatibility.go
- internal/consoleplugin/coo_compatibility_test.go
- internal/consoleplugin/reconciler.go
This is a backport of #2509 to `release-5.6`.
- Depending on PR(s): #2509
- JIRA: [LOG-5465](https://issues.redhat.com//browse/LOG-5465)
> LOG-5465: Do not deploy logging ConsolePlugin if already managed by COO

- api/observability/v1/output_types.go
This PR makes splunk token required given it is required by the splunk sink
ref: https://issues.redhat.com/browse/LOG-5606
> LOG:5606: fix splunk auth to be required

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/collector_alerts.yaml
- docs/administration/collector-metrics-and-alerts.adoc
- internal/metrics/dashboard/openshift-logging-dashboard.json
In this PR: 
- removed the alert related to the `Fluentd` collector: `FluentdQueueLengthIncreasing`
- updated metrics configuration to focus on `Vector` collector, removed dependencies on `Fluentd`
- all metrics now used the `app_kubernetes_io_instance` label, this should help accurate determination of the CLF instance
- update documentation with actual metrics and alerts
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5042
> LOG-5042: Refactor Collector Alerts/Metrics according to changes in 6.0 version

- version/cluster.go
`OPERATOR_CONDITION_NAME` is being injected by operator lifecycle manager into operator's deployments so that operators can know the name of the relevant `OperatorCondition` CR for cases when operators want to report some conditions or block their upgrades.
It seems like logging operator has a function which reads `OPERATOR_CONDITION_NAME`, but the function is never used. I suspect that there was previously reliance on `OperatorCondition` which is gone, but this function was left behind.
/cc jcantrill
/assign alanconway
- Bugzilla:
- JIRA:
> Remove unused function

- Makefile
This PR adds a missing piece to the https://github.com/openshift/cluster-logging-operator/commit/81eb85dc3b0432e90044225c79932b6e78c409a0 commit and removes the `--collector-impl=vector` command line argument from the functional-benchmarker invocation in the Makefile. `--collector-impl` was removed in the aforementioned commit and now the test-functional-benchmarker-vector make target fails with the "flag provided but not defined: -collector-impl" error.
This issue came up during testing of https://github.com/ViaQ/vector/pull/173.
/cc @Clee2691 
- JIRA:
https://issues.redhat.com/browse/LOG-5647
https://issues.redhat.com/browse/LOG-5384
> LOG-5384: Drop support for fluentd collector, fix the Makefile

- internal/metrics/dashboard/openshift-logging-dashboard.json
This PR fixes expiration for buffer usage calculation, result should not multiply value by 100 because it will be done automatically by dashboard 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5646
> LOG-5646: fix buffer usage calculation

- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- config/rbac/role.yaml
- internal/controller/kubebuilder_rbac.go
- internal/controller/observability/clusterlogforwarder_controller.go
While running the CLO on a test cluster I noticed that it still produced two errors regarding RBAC for the `apiservers` and `securitycontextcontraints` resources. It looks as if the verbs needed to watch these resources were missing.
This is a follow-up fix for #2521 .
> Include missing verbs in RBAC configuration

- Makefile
- internal/api/observability/secrets.go
- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_insecure_skipverify.toml
- internal/generator/vector/output/kafka/kafka_multi_brokers_with_tls_single_topic.toml
- internal/generator/vector/output/kafka/kafka_sasl_scram_with_tls.toml
- internal/generator/vector/output/kafka/kafka_sasl_with_tls_single_topic.toml
- test/functional/filters/prune/prune_filter_test.go
- test/runtime/observability/cluster_log_forwarder.go
- test/runtime/observability/cluster_log_forwarder_test.go
This PR:
* Refactors the functional prune filter test to use the observability API
* Fixes kafka TLS config to include enable=true
https://issues.redhat.com/browse/LOG-5664
> LOG-5664: refactor function prune filter test for observability API

- Makefile
- test/functional/outputs/syslog/forward_to_syslog_test.go
- test/functional/outputs/syslog/rfc3164_test.go
- test/functional/outputs/syslog/rfc5424_test.go
- test/runtime/observability/cluster_log_forwarder.go
This PR enables most of the syslog output functional tests. There are a couple tests that need revisting once API changes are finalized, mainly the `tag` and `log source` information.
- JIRA: https://issues.redhat.com/browse/LOG-5716
> LOG-5716: Enable syslog output functional tests

- cmd/main.go
This PR:
* seeds the dashboards for greenfield installs that was broken as part of #2464 
https://issues.redhat.com/browse/LOG-5747
> LOG-5747: fix seeding of dashboards for green installations

- api/observability/v1/clusterlogforwarder_types.go
- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- test/runtime/observability/cluster_log_forwarder_test.go
When using `+kubebuilder:validation:Required` to mark a field of the CRD as required it can not be combined with `omitempty`. If `omitempty` is present then the `Required` is silently ignored.
This PR removes `omitempty` from all attributes having the `+kubebuilder:validation:Required` annotation in the comment, which adds new required fields to the generated CRD.
> Remove omitempty on required fields

- Makefile
- test/functional/outputs/multiple/forward_to_multiple_outputs_test.go
- test/functional/outputs/multiple/multiple_test.go
This PR refactors the multiple outputs functional tests to observability API
- JIRA: https://issues.redhat.com/browse/LOG-5740
- Blocked by: https://github.com/openshift/cluster-logging-operator/pull/2592
> LOG-5740: Enable multiple outputs test

- hack/testing-olm/test-030-collection.sh
- internal/collector/collector.go
- internal/collector/collector_test.go
- test/e2e/collection/security/container_security_test.go
This PR:
* Enables the e2e container security test for observability
* Fixes Audit OpenShift logs to mount the oauth audit files into the collector 
* https://issues.redhat.com/browse/LOG-5734
> LOG-5734: Refactor e2e container security test

- internal/collector/vector/run-vector.sh
- internal/collector/vector/utils.go
This PR moves the `run-vector.sh` startup script from a constant to a file that is injected into the executable using `go-embed`. This change makes the file more easily discoverable in the repository and syntax highlighting and linting tools also work better with a separate file instead of a string constant.
This is just a "code style" change.
> Move startup script to file and use go-embed

- api/observability/v1/clusterlogforwarder_types.go
- api/observability/v1/filter_types.go
- api/observability/v1/input_types.go
- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
This PR:
* adds validations to run on creation /edit
https://issues.redhat.com/browse/LOG-5748
cc @cahartma @Clee2691
> LOG-5748: Include additional API declarative validations

- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/cloudwatch_test.go
- internal/generator/vector/output/cloudwatch/cw_groupname_with_aws_credentials.toml
- internal/generator/vector/output/cloudwatch/cw_with_groupname.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_and_default_mintls_ciphers.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_spec.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_spec_insecure_verify.toml
- internal/generator/vector/output/cloudwatch/cw_with_url.toml
- internal/generator/vector/output/common/template/suite_test.go
- internal/generator/vector/output/common/template/template.go
- internal/generator/vector/output/common/template/template.vrl.tmpl
- internal/generator/vector/output/common/template/template_test.go
- test/framework/functional/output_cloudwatch.go
- test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
- test/runtime/observability/cluster_log_forwarder.go
This PR addresses missing fields when templating the `groupName` for `Cloudwatch`. This now allows a fallback value to be defined in case a field is missing.
The syntax allows for static values as well as path expressions enclosed in single curly brackets `{}`. There must be a fallback value when using path expressions and can be expressed with `||` followed by another path expression or a static value in quotes.
Examples:
- foo
- {.foo||"none"}
- foo_{.bar||"none"}
- foo_bar{.baz."foo/bar"||.foo||"missing"}
- JIRA: https://issues.redhat.com/browse/LOG-5745
> LOG-5745: Only container logs can be forwarded with groupName {{.kubernetesnamespace_name}} to CloudWatch

- internal/generator/vector/helpers/node.go
- internal/generator/vector/output/factory.go
- internal/generator/vector/output/otlp/group_by.go
- internal/generator/vector/output/otlp/otlp.go
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_test.go
- internal/generator/vector/output/otlp/suite_test.go
- internal/generator/vector/output/otlp/transform.go
- internal/generator/vector/pipeline/adapter.go
- test/framework/functional/constants.go
- test/framework/functional/output_otlp.go
- test/functional/outputs/otlp/forward_to_otlp_test.go
- test/functional/outputs/otlp/suite_test.go
- test/helpers/otlp/attributes.go
- test/helpers/otlp/types.go
- test/runtime/observability/cluster_log_forwarder.go
Based on previous PR for transforms https://github.com/openshift/cluster-logging-operator/pull/2590
Added the first functional test to send application logs to otel-collector container in the testnamespace.  Can read the log file and parse the attribute keys and values if necessary.   
All is still changing and will be dependent on what we decide is our "resource/stream" for each log_type, and which attributes we send (both in the resource.attributes and logRecord.attributes)
- Parent task:  https://issues.redhat.com/browse/LOG-5370
- Sub-task: https://issues.redhat.com/browse/LOG-5482 
- Other tasks:  https://issues.redhat.com/browse/LOG-5476 https://issues.redhat.com/browse/LOG-5477 https://issues.redhat.com/browse/LOG-5478 …
> LOG-5482 otlp output functional test 

- cmd/main.go
- internal/constants/constants.go
- internal/controller/clusterlogging/clusterlogging_controller.go
- internal/controller/event_filter.go
- internal/controller/forwarding/forwarding_controller.go
This PR addresses the migration of `logging.openshift.io` resources to the new `observability.openshift.io` API during the operator upgrade process.
When the operator starts, existing logging CLs and CLFs trigger a create event, prompting the operator to mark them with an annotation. This ensures that the controller will reconcile and migrate these resources to the new API.
- JIRA: https://issues.redhat.com/browse/LOG-5787
> LOG-5787: The migration process doesn't work.

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/filter/openshift/viaq/common.go
- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/cw_groupname_with_aws_credentials.toml
- internal/generator/vector/output/cloudwatch/cw_with_groupname.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_and_default_mintls_ciphers.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_spec.toml
- internal/generator/vector/output/cloudwatch/cw_with_tls_spec_insecure_verify.toml
- internal/generator/vector/output/cloudwatch/cw_with_url.toml
- internal/generator/vector/pipeline/adapter_test_drop_filter.toml
- internal/generator/vector/pipeline/adapter_test_kube_api_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_inNotIn_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_inOnly_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_notIn_only_filter.toml
All app logs in cloudwatch had their stream_name set to default.    This was caused by the `del(.file)` we are putting in each log_type filter.     I've created `._internal.file` to store the filename and modified the cloudwatch stream_name assignment.   
Two small changes, then the remaining files are .toml files for testing.
note: No records are dropped if either of these fields (.file, .message) is not present.  I am curious though, what other sinks could have been sending .file previously?  other output types?
https://issues.redhat.com/browse/LOG-5807
> LOG-5810: fix cloudwatch stream names

- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
This PR fixes the validation for `Cloudwatch's` `groupName`. 
This validation ensures that fallback values are included if `groupName` contains `{}` to indicate dynamic fields. 
A dynamic value MUST end with a static string not just another field.
Valid:
1. {.foo||"none"}
2. {.foo||.bar||"missing"}
3. {.kubernetes.namespace_name||.log_type||"foo"}
Invalid:
1. {.foo}
2. {.bar||.baz}
- JIRA: https://issues.redhat.com/browse/LOG-5745
> LOG-5745: Forwarding logs to cloudwatch with groupName {{.kubernetes.namespace_name}}, only container logs can be forwarded.

- must-gather/collection-scripts/gather_cluster_logging_operator_resources
Remove `toml` private data based on the example in [LOG-5151](https://issues.redhat.com//browse/LOG-5151).
This complements the PR for removing the RAW `secrets`: PR #2317.
/cc cahartma
/assign cahartma
/cherry-pick 5.9
/cherry-pick 5.8
- JIRA: https://issues.redhat.com/browse/LOG-5151
> [LOG-5151] Remove `toml` private data

- test/framework/functional/output_http.go
- test/framework/functional/read.go
- test/functional/outputs/http/forward_to_http_test.go
This PR:
Modifies the functional HTTP test to test using username and password
> update http functional test to test using password

- internal/validations/observability/outputs/cloudwatch.go
- internal/validations/observability/outputs/cloudwatch_test.go
- internal/validations/observability/outputs/validate.go
- internal/validations/observability/outputs/validate_test.go
- added validation to reject when CW outputs spec different IAM Role
- removed not needed code in favor of kubebuilder validation, introduced #2651
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5804
> LOG-5640: Add validation to reject when CW outputs spec different IAM Role

- api/observability/v1/clusterlogforwarder_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
The validation error can also be verified by trying to applying the CRD to the cluster.   I was not able to reproduce the `"CRD is not present"` errors, but I am assuming the first (validation) error is causing the requirementStatus to fail as well.
Also adding a shortname back into the CRD.  In case of upgrade scenario, user can now use `obsclf` (until we remove the old CRD)
- https://issues.redhat.com/browse/LOG-5862
> LOG-5862: Validation rule causing  error on install

- internal/api/observability/conditions.go
- internal/api/observability/filters.go
- internal/api/observability/forwarder.go
- internal/api/observability/input_types.go
- internal/api/observability/output_types.go
- internal/api/observability/pipelines.go
- internal/controller/observability/clusterlogforwarder_controller.go
- internal/validations/observability/filters/validate.go
- internal/validations/observability/inputs/validate.go
- internal/validations/observability/pipelines/validate.go
Added `removeStaleStatuses` to prune conditions for any resource that may no longer be listed (name change for example).   
I tried to create a test for this, but am not just going to push the fix.   I may come back to this later.   
I also changed the input validation to use SetCondition() like the others, and added name to the other messages to be consistent between all Condition types.
- https://issues.redhat.com/browse/LOG-5842
> LOG-5842 Forwarder validation failing on old conditions

- internal/migrations/observability/api/convert_test.go
- internal/migrations/observability/api/filters.go
- internal/migrations/observability/api/filters_test.go
- internal/migrations/observability/api/pipelines.go
- internal/migrations/observability/api/pipelines_test.go
- test/functional/inputs/http/http_input_test.go
Fix filter name generated during migration process according to specification, must match to the: 
`^[a-z][a-z0-9-]*[a-z0-9]$`
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5846
> LOG-5846: fix filter name after migration according to spec

- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/tcp_with_defaults.toml
- internal/generator/vector/output/syslog/xyz_defaults.toml
This PR removes the `payload_key` config if it is not defined by the user.
- JIRA: https://issues.redhat.com/browse/LOG-5790
> LOG-5790: Allow syslog templating in CLF API syntax

- docs/reference/log6x-clf-cr-samples.adoc
[OBSDOCS-1220](https://issues.redhat.com//browse/OBSDOCS-1220) - Single source CR testing.
Created an asciidoc file to test single sourcing CR config samples for common use cases. Appropriate use of tagged regions should enable CR samples from this file to be included in the product docs individually, creating lower maintenance overhead, and ensuring all CR samples are properly validated.
> OBSDOCS-1220 - Single source CR testing.

- internal/migrations/observability/api/output_test.go
- internal/migrations/observability/api/outputs.go
This PR fixes migrating TLS settings for outputs. When the secret for that output specs the trusted ca bundle, tls cert & key, or passphrase, the TLS settings will be set accordingly.
- JIRA: https://issues.redhat.com/browse/LOG-5880
> LOG-5880: output ca-bundle.crt,tls.key,tls.crt,passphrase are not migrated to 6.0

- internal/migrations/observability/api/output_test.go
- internal/migrations/observability/api/outputs.go
This PR fixes migrating a syslog output that doesn't spec an `RFC` value. It will default to `RFC5424`. Additonally, this PR refactors migration to default values for `facility` & `severity` if none are specified as specified by the API.
- JIRA: https://issues.redhat.com/browse/LOG-5890
> LOG-5890: Migrating syslog output failed due to syslog.rfc: Unsupported value

- internal/api/initialize/init_lokiStack.go
- internal/api/initialize/init_lokiStack_test.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
During a discussion I noticed that there is a case, when we need to explicitly pass the default label keys through to the Loki output: when a per-tenant provides custom keys, `ignoreGlobal=false` and there are no global overrides.
This PR adds this case to the implementation.
> Fix per-tenant label keys not using global default keys

- internal/controller/clusterlogging/clusterlogging_controller.go
- internal/controller/forwarding/forwarding_controller.go
- internal/migrations/observability/api/convert.go
- internal/migrations/observability/api/convert_test.go
- internal/migrations/observability/api/permissions.go
- internal/migrations/observability/api/permissions_test.go
This PR adds the required `logcollector` service account permissions upon migration of a legacy CL and/or CLF.
The `logcollector` service account is permitted to collect all 3 log types:
1. application
2. audit
3. infrastructure
- JIRA: https://issues.redhat.com/browse/LOG-5885
> LOG-5885: New CLF raises ClusterRoleMissing after migration

- api/logging/v1/clusterlogging_types.go
This PR fixes migration of a CL resource by adding `omitempty` to `pruneNamespacesInterval`. The problem was the `retentionPolicy` and marshaling of the object. 
- JIRA: https://issues.redhat.com/browse/LOG-5899
> LOG-5899: The migration doesn't work when the default log store is logging-managed elasticsearch

- internal/collector/cloudwatch.go
- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/collector/common/path.go
- internal/constants/constants.go
This PR:
* fixes using CW output with token from projected SA
* Removes volumemount from container for projected SA since it should not require explicit mounting
https://issues.redhat.com/browse/LOG-5801
> LOG-5801: fix cloudwatch with roleARN from projected SA

- internal/api/observability/tuning.go
- internal/api/observability/tuning_test.go
This PR fixes Kafka tune settings for `delivery` and `maxWrite` so they generate in the `vector.toml`
- JIRA: https://issues.redhat.com/browse/LOG-5920
> LOG-5920: 'maxWrite' and 'delivery' tuning options are missing under collector config for kafka

- internal/migrations/observability/api/convert_test.go
- internal/migrations/observability/api/outputs/managedlogstores/managed_logstores.go
- internal/migrations/observability/api/outputs/managedlogstores/managed_logstores_test.go
This PR:
* fixes the secret for default ES after migration to use the same secrets used in 5.9
https://issues.redhat.com/browse/LOG-5922
> LOG-5922: fix the default ES secret

- cmd/main.go
- internal/metrics/telemetry/collector.go
- internal/metrics/telemetry/collector_test.go
- internal/metrics/telemetry/servicemonitor_test.go
- internal/metrics/telemetry/telemetry.go
- internal/metrics/telemetry/telemetry_test.go
This PR implements telemetry metrics for the new cluster-logging-operator release. The `log_file_metric_exporter_info` metric is compatible with telemetry in previous releases, but the telemetry metrics for the ClusterLogForwarder have been changed:
- `log_forwarder_input_type` shows usage information about input types.
- `log_forwarder_output_type` shows usage information about output types.
- `log_forwarder_pipelines` counts the number of pipelines in a forwarder.
The input and output metrics now create a series per used input/output type, so that Prometheus aggregations can be used more easily when querying the metrics, for example to show the percentage of different output types used in clusters.
This PR is an alternative implementation to #2680, which implements a set of metrics …
> LOG-5131: Implement telemetry metrics

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_custom_topic.toml
- internal/generator/vector/output/kafka/kafka_insecure_skipverify.toml
- internal/generator/vector/output/kafka/kafka_multi_brokers_with_tls_single_topic.toml
- internal/generator/vector/output/kafka/kafka_no_security.toml
- internal/generator/vector/output/kafka/kafka_sasl_plaintext_single_topic.toml
- internal/generator/vector/output/kafka/kafka_sasl_scram_with_tls.toml
- internal/generator/vector/output/kafka/kafka_sasl_with_tls_single_topic.toml
This PR removes the `healthchecks` for the Kafka sink as we do not claim to support `healthchecks`.
- JIRA: https://issues.redhat.com/browse/LOG-5921
> LOG-5921: 'Could not generate topic for healthcheck' warnings on collector when forwarding to kafka topics

- must-gather/collection-scripts/gather
This PR:
* updates the must-gather to not treat "openshift-logging" NS differently from other CLF namespaces
cc @vparfonov @Clee2691
> fix must-gather treatment of clf for openshift-logging ns

- internal/controller/logfilemetricsexporter/logfilemetricsexporter_controller.go
- internal/controller/observability/clusterlogforwarder_controller.go
This PR adds code to the operator's controllers, so that changes on deleted and "soon to be deleted" resources do not cause reconciliation runs (or even loops) anymore.
/cc @cahartma
> Fix reconcile errors when resource is deleted

- api/observability/v1/clusterlogforwarder_types.go
- api/observability/v1/filter_types.go
- api/observability/v1/input_types.go
- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/reference/operator/api_logging_v1alpha1.adoc
- docs/reference/operator/api_observability_v1.adoc
This PR adds `operator-sdk` markers to all fields in the new API improving the UI in the OpenShift Console "form view" for creating a new ClusterLogForwarder instance.
I've also tried to improve the formatting of the field comments for display in the console, especially for comments containing multiple paragraphs and lists.
/cc @cahartma
> Improve descriptors for OpenShift Console CLF creation form

- internal/collector/input_service.go
- internal/constants/constants.go
- internal/metrics/service_monitor.go
- internal/network/service.go
I noticed that I did not get any collector metrics anymore in the dashboard after a recent update. This PR should fix the selector used in the ServiceMonitor for picking up the collector metrics.
I have added a new label describing the "service type" of the created Service resources. It looked to me as if we have two types: metrics and input services.
/cc @cahartma
- JIRA: LOG-5906
> LOG-5906: Fix metrics ServiceMonitor label selector

- internal/generator/vector/helpers/helpers.go
- internal/generator/vector/output/azuremonitor/azm_common_dollar.toml
- internal/generator/vector/output/azuremonitor/azuremonitor.go
- internal/generator/vector/output/azuremonitor/azuremonitor_test.go
- internal/generator/vector/output/common/security.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/loki/with_custom_labels.toml
- internal/generator/vector/output/splunk/splunk_test.go
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- test/framework/functional/cluster_log_forwarder.go
- test/framework/functional/elasticsearch.go
- test/framework/functional/framework.go
- test/framework/functional/output_elasticsearch.go
- test/framework/functional/output_splunk.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
- test/functional/outputs/syslog/forward_to_syslog_test.go
This PR fixes vector config generation where fields configured with `$` were expecting and environment variable. Instead it now escapes `$` with `$$`.
- JIRA: https://issues.redhat.com/browse/LOG-5602
> LOG-5602: Vector forwarding auth issue when password contains $

- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- config/samples/logging_v1alpha1_logfilemetricexporter.yaml
- config/samples/observability_v1_clusterlogforwarder.yaml
- test/e2e/logfilesmetricexporter/invalid.yaml
- test/e2e/logfilesmetricexporter/valid.yaml
This PR updates the example files distributed with the CSV. They are used as a starting point when creating a new resource in the OpenShift Console.
I have opted for a "application and infrastructure logs to local LokiStack" configuration for the ClusterLogForwarder. I think ideally we synchronize this with what we list as the "recommended configuration" in the documentation. I've already tried to use the naming conventions we had for the resources in the 5.y docs.
This PR also enables a new feature in the OpenShift Console: It now shows a "ClusterLogForwarder required" warning in the operator details when no resource has been created yet, prompting the user to create one. This button unfortunately does not use the same example file, but we could keep it synchronized manually. Currently I …
> Update example resources distributed with CSV

- docs/administration/upgrade/to_v6.0.adoc
As per current config, it is preposed to use secret "logcollector-token" secret to retrieve service-ca.crt but configmap named openshift-service-ca.crt which is part of RHOCP aldready holds the same service CA certificate. It is better to use this as it is provided by platform by default and it also holds updated service CA, if the service-ca operator rotates the certificate.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: NA
> Updated LokiStack CR to use configmap openshift-service-ca.crt for CA certificate

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_drop_filter.toml
- internal/generator/vector/conf/complex_es_no_ver.toml
- internal/generator/vector/conf/complex_es_v6.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/complex_otel.toml
- internal/generator/vector/conf/complex_prune_filter.toml
- internal/generator/vector/input/viaq_audit.toml
- internal/generator/vector/input/viaq_audit_host.toml
- internal/generator/vector/input/viaq_audit_kube.toml
- internal/generator/vector/input/viaq_audit_openshift.toml
- internal/generator/vector/input/viaq_audit_ovn.toml
- internal/generator/vector/source/audit_logs.go
This PR modifies audit sources:
* with max read bytes
* ignore files older then one hour
* release rotated files after 5s
https://issues.redhat.com/browse/LOG-5866
> LOG-5866: tune audit sources to release file handles

- internal/generator/vector/output/azuremonitor/azm_tuning.toml
- internal/generator/vector/output/azuremonitor/azuremonitor_test.go
- internal/generator/vector/output/cloudwatch/cloudwatch_test.go
- internal/generator/vector/output/cloudwatch/cw_with_tuning.toml
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/elasticsearch/es_with_tune.toml
- internal/generator/vector/output/gcl/gcl_test.go
- internal/generator/vector/output/gcl/gcl_with_tuning.toml
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/http/http_with_tuning.toml
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/kafka/kafka_tuning.toml
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/output/loki/with_tuning.toml
- internal/generator/vector/output/otlp/otlp.go
- internal/generator/vector/output/otlp/otlp_test.go
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/splunk/splunk_test.go
- internal/generator/vector/output/splunk/splunk_tune.toml
- test/helpers/outputs/adapter/fake/adapter.go
- test/helpers/outputs/adapter/fake/config_strategy.go
This PR adds the appropriate tuning sections for the `OTLP` output. In addition, it adds unit tests for the tuning section for all output types.
- JIRA: https://issues.redhat.com/browse/LOG-5909
> LOG-5909: Some configurations in otlp.tuning are not added into vector.toml

- internal/controller/observability/collector.go
- internal/metrics/logfilemetricexporter/factory.go
- internal/metrics/logfilemetricexporter/factory_test.go
- internal/metrics/logfilemetricexporter/metric_exporter.go
- internal/metrics/logfilemetricexporter/metric_exporter_test.go
- internal/metrics/service_monitor.go
- internal/metrics/service_monitor_test.go
Fixes an issue with the selector used for the LFME's ServiceMonitor.
/cc @cahartma
- JIRA: [LOG-5972](https://issues.redhat.com//browse/LOG-5972)
> LOG-5972: Fix ServiceMonitor for LogFileMetricExporter

- api/observability/v1/input_types.go
- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- test/e2e/collection/apivalidations/syslog_valid_url_tcp.yaml
- test/e2e/collection/apivalidations/syslog_valid_url_tls.yaml
- test/e2e/collection/apivalidations/syslog_valid_url_udp.yaml
- test/e2e/collection/apivalidations/syslog_valid_url_udps.yaml
This PR removes all `kubebuilder:default` markers except for the `managementState` which is present in all ClusterLogForwarder instances in an effort to fix creation of CLF resources using the OpenShift Console form view.
/cc @cahartma
- JIRA: [LOG-5978](https://issues.redhat.com//browse/LOG-5978)
> LOG-5978: Remove default values from API definition

- internal/collector/collector.go
- internal/collector/secrets.go
- internal/constants/annotations.go
- internal/utils/comparators/daemonsets/comparator.go
- internal/utils/comparators/daemonsets/comparator_test.go
- internal/utils/comparators/deployments/comparator.go
- internal/utils/comparators/deployments/comparator_test.go
This PR:
* adds pod annotation template with hash of secrets
* should cause the collector to reload when the secrets change
https://issues.redhat.com/browse/LOG-5525
> LOG-5525: Trigger collector reload on update

- internal/api/initialize/init_resources.go
- internal/api/initialize/init_resources_test.go
- internal/api/initialize/initializations.go
This PR:
* defaults the collector resources (e.g. memory,cpu) when the collector or collector resources are undefined
* defaults values as suggested by vector [upstream](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#resource-limits)
https://issues.redhat.com/browse/LOG-4745
cc @cahartma @xperimental @Clee2691
> LOG-4745: Default collector resources when undefined

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/collector_alerts.yaml
This PR:
* removes the collector error alerts until they can be replace with a version that is reliable and created based upon concrete requirements
https://issues.redhat.com/browse/LOG-3432
> LOG-3432: Remove collector error alerts

- Dockerfile
This PR removes the `compat-openssl11` package from the built Docker image. As the `oc` binary is also built on RHEL9 this should no longer be necessary. This PR brings the upstream Dockerfile in sync with the midstream one.
/cc @cahartma
- JIRA: [LOG-5983](https://issues.redhat.com//browse/LOG-5983)
> LOG-5983: Remove compat-openssl11 library from Docker image

- internal/api/observability/configmap.go
- internal/api/observability/secrets.go
This sorts the slices returned by `Names()` for both secrets and configmaps so that the ordering is stable.
/cc @cahartma
- JIRA: [LOG-5993](https://issues.redhat.com//browse/LOG-5993)
> LOG-5993: Sort names of secrets / configmaps so that order is stable

- Dockerfile
This PR brings the changes that we did to fix the issue in midstream back to upstream.
/cc @vparfonov @cahartma
- JIRA: [LOG-5943](https://issues.redhat.com//browse/LOG-5943)
> LOG-5943: Copy correct oc binary into container in multi-arch builds

- Makefile
- bundle.Dockerfile
- bundle/manifests/cluster-logging-operator_monitoring.coreos.com_v1_prometheusrule.yaml
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- bundle/metadata/properties.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
- config/prometheus/kustomization.yaml
- config/prometheus/operator_alerts.yaml
- Add notice on the operator install view to inform users on OCP 4.17 that the 5.8 operator version will be removed from the catalog on November 2025.
- Add alert informing users about the removal.
**Operator Install Page**
**Alerts**
/cc @jcantrill
> LOG-6103: Adapt support statements for 4.17

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/input/audit.toml
- internal/generator/vector/input/audit_host.toml
- internal/generator/vector/input/audit_kube.toml
- internal/generator/vector/input/audit_openshift.toml
- internal/generator/vector/input/audit_ovn.toml
- internal/generator/vector/source/audit_logs.go
This PR modifies audit sources:
* with max read bytes
* ignore files older then one hour
* release rotated files after 5s
https://issues.redhat.com/browse/LOG-6034
Forward port of #2768
> LOG-6034: tune audit sources to release file handles

- internal/api/initialize/init_resources.go
- internal/api/initialize/init_resources_test.go
We've had a few reports of OOM issues during testing of pre-release 6.0, mainly lokistack and the new otlp output (all log_types).    Best solution, we've decided to double the memory limit only, while leaving the other defaults alone.    We need more feedback and possibly add otlp to benchmark functional tests.
One other option we can explore before GA is modifying the group_by MaxEvents in the otlp output. (and possibly allowing it to be configurable)
- https://issues.redhat.com/browse/LOG-6072
> LOG-6072: Increase default collector memory limit

- test/framework/common/log/buffered_log_writer.go
- test/framework/functional/framework.go
This PR:
* attempts to cleanup the CI test UI to only display minimal info while preserving logs to artifacts dir
> cleanup CI UI. write logs to artifact dir

- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
This PR modifies the regex that determines infrastructure namespaces so that namespaces containing, but not starting with, `kube` or `openshift` are treated as application namespaces. Only the namespace `default` is treated as infrastructure and any other namespace containing `default` is not.
- JIRA: https://issues.redhat.com/browse/LOG-6044
> LOG-6044: validation failure when adding a namespace which contains 'kube'

- internal/generator/vector/conf_test.go
- internal/generator/vector/conf_test/complex_threshold.toml
- internal/generator/vector/inputs.go
- internal/generator/vector/pipelines.go
/cc @cahartma @Clee2691  
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4671
> [release-5.8]LOG-4671:respect settings containerLimit.maxRecordsPerSecond to 0

- api/observability/v1/conditions.go
- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/features/logforwarding/outputs/redhat-managed-lokistack.adoc
- internal/api/initialize/init_lokiStack.go
- internal/api/initialize/init_lokiStack_test.go
- internal/api/initialize/process_pipelines.go
- internal/api/observability/forwarder.go
- internal/api/observability/forwarder_test.go
- internal/controller/observability/clusterlogforwarder_controller.go
- internal/controller/observability/collector.go
- internal/generator/vector/output/factory_test.go
- internal/generator/vector/output/otlp/otlp.go
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_test.go
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/otlp/otlp_with_auth_basic.toml
- internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml
- internal/generator/vector/output/otlp/otlp_with_auth_token.toml
- internal/generator/vector/output/otlp/transform.go
- internal/validations/observability/outputs/lokistack.go
- internal/validations/observability/outputs/lokistack_test.go
- internal/validations/observability/validate.go
- test/functional/outputs/otlp/forward_to_otlp_test.go
This PR enables the `ClusterLogForwarder` to write `OTEL` data to Red Hat managed `Lokistack`.
A new field, `dataModel`, is added to the `Lokistack` output in order to designate the type of data sent to `Lokistack`. It supports 2 values: `viaq` or `otel`. The field can be omitted and data sent will default to `viaq`.
The `OTLP` output generation now includes additional attributes in order to preserve UI plugin functionality and will be included in **ALL** `OTLP` outputs.
These attributes are:
1. `log_type`
2. `log_source`
3. `kubernetes_pod_name`
4. `kubernetes_container_name`
5. `kubernetest_namespace_name`
- JIRA: https://issues.redhat.com/browse/LOG-6085
- Enhancement proposal: https://github.com/openshift/enhancements/pull/1684
> LOG-6085: Enable CLF spec'd to write to LokiStack using OTEL semantics

- internal/constants/constants.go
- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/filter/multilineexception/filter.go
- internal/generator/vector/filter/openshift/viaq/filter.go
- internal/generator/vector/filter/openshift/viaq/normalize.go
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/otlp/otlp_with_auth_basic.toml
- internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml
- internal/generator/vector/output/otlp/otlp_with_auth_token.toml
- internal/generator/vector/output/otlp/transform.go
- internal/generator/vector/pipeline/adapter_test_drop_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_inNotIn_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_inOnly_filter.toml
- internal/generator/vector/pipeline/adapter_test_prune_notIn_only_filter.toml
- test/framework/functional/factory.go
- test/framework/functional/message_templates.go
- test/functional/filters/multilineexception/multiline_exception_test.go
- test/functional/normalization/message_format_test.go
- test/helpers/types/types.go
This PR introduces handling of `kubernetes_log` `stream` field (e.g., stdout, stderr). https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#line-fields
- moved the original `stream` field to `kubernetes.stream` to better align with the log event structure
- added `kubernetes.stream` to the group_by parameter of the Detect Multiline Exceptions filter, ensures that exception detection is correctly handled 
- included `kubernetes.stream `in the group_by parameter for the OTLP output, to improves the granularity of log data sent through OTLP by differentiating between different streams.
- modified the functional tests to verify that log events are handled correctly for both stdout and stderr outputs. 
/cherry-pick 
- Depending …
> LOG-6207: enable stream (stdout/stderr) information in logs for Vector

- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This PR:
* updates the provider in the manifest so the console will evaluate it as an official Red Hat operator
https://issues.redhat.com/browse/LOG-5587
> LOG-5587: fix provider so operator is evaluated as official

- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
- internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
This PR specifies these namespaces as infrastructure and validates them as such:
1. `default`
2. `kube`
3. `openshift`
4. `kube-*` - any namespace **starting** with `kube-`
5. `openshift-*` - any namespace **starting** with `openshift-`
A namespace like `kube1` or `openshift1` will not be validated as infrastructure namespaces nor any namespace containing the above keywords like `sample-kube-namespace`.
- JIRA: https://issues.redhat.com/browse/LOG-6044
> LOG-6044: validation failure when adding a namespace which contains `kube` or `openshift`

- internal/validations/observability/validate_permissions.go
- internal/validations/observability/validate_permissions_test.go
This is a manual port of #2835
This PR specifies these namespaces as infrastructure and validates them as such:
1. `default`
2. `kube`
3. `openshift`
4. `kube-* - any namespace starting with kube-`
5. `openshift-* - any namespace starting with openshift-`
A namespace like `kube1` or `openshift1` will not be validated as infrastructure namespaces nor any namespace containing the above keywords like `sample-kube-namespace`.
- JIRA: https://issues.redhat.com/browse/LOG-6204
> LOG-6204: Manual port of LOG-6044 to release-6.0

- bundle/manifests/cluster-logging-operator-telemetry_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/kustomization.yaml
- config/prometheus/telemetry_rules.yaml
This PR introduces recording rules to reduce the possible number of metrics being sent to telemetry for a single installation of Cluster Logging Operator.
This also needs review from the monitoring team, I'll ping them separately.
/cc @jcantrill
/assign @cahartma
- JIRA: [LOG-5131](https://issues.redhat.com//browse/LOG-5131), [MON-4051](https://issues.redhat.com/browse/MON-4051)
> LOG-5131: Add recording rules for telemetry collection

- api/logging/v1alpha1/log_file_metrics_exporter_types.go
- internal/controller/logfilemetricsexporter/logfilemetricsexporter_controller.go
This PR initializes the `Reason` and `Message` fields in the `Ready Condition` of the `LogFileMetricsExporter` instance, ensuring a smooth transition to version 6.x.  
/cc @Clee2691 @cahartma @xperimental 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6201
> LOG-6201: avoid empty Reason and Message fields in Ready Condition

- internal/generator/vector/output/gcl/gcl.go
- internal/generator/vector/output/gcl/gcl_with_custom_logid.toml
- internal/generator/vector/output/gcl/gcl_with_tls.toml
- internal/generator/vector/output/gcl/gcl_with_token.toml
- internal/generator/vector/output/gcl/gcl_with_tuning.toml
This PR normalizes log severity levels for the `GCL` sink based on GCL's standard referenced below.
The severity level of `audit` logs is `INFO`.
Ref: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity
- JIRA: https://issues.redhat.com/browse/LOG-6296
> LOG-6296: GCP expects certain severity value strings

- Makefile
- bundle.Dockerfile
- bundle/metadata/properties.yaml
Fixes the supported OpenShift versions for version 6.1
/cc @cahartma 
- JIRA: [LOG-6333](https://issues.redhat.com//browse/LOG-6333)
> LOG-6333: Fix supported OpenShift versions

- internal/validations/observability/validate_permissions.go
- internal/validations/observability/validate_permissions_test.go
This PR reverts: https://github.com/openshift/cluster-logging-operator/pull/2837. We have determined that users should not create namespaces starting with `openshift` or `kube`.
/cherry-pick release-6.0
- JIRA: https://issues.redhat.com/browse/LOG-6342
> Revert "LOG-6204: Manual port of LOG-6044 to release-6.0"

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/input/audit.toml
- internal/generator/vector/input/audit_host.toml
- internal/generator/vector/input/audit_kube.toml
- internal/generator/vector/input/audit_openshift.toml
- internal/generator/vector/input/audit_ovn.toml
- internal/generator/vector/source/audit_logs.go
This PR:
* bumps the max_line_bytes for audit logs
* bumps the max_read_line_bytes for audit logs
https://issues.redhat.com/browse/LOG-5998
> LOG-5998: fix max_line_bytes for audit logs

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/input/application.toml
- internal/generator/vector/input/application_exclude_container_from_infra.toml
- internal/generator/vector/input/application_excludes_container.toml
- internal/generator/vector/input/application_includes_container.toml
- internal/generator/vector/input/application_with_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_matchLabels.toml
- internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_throttle.toml
- internal/generator/vector/input/audit.go
- internal/generator/vector/input/infrastructure.toml
- internal/generator/vector/input/infrastructure_container.toml
- internal/generator/vector/input/journal.go
- internal/generator/vector/input/meta.go
- internal/generator/vector/input/receiver.go
- internal/generator/vector/input/source.go
This PR correctly aligns the `log_type` of `infrastructure` container logs when `infrastructure` namespaces are included in `application` input types.
Infrastructure namespaces are defined as:
1. `default`
2. `kube-*`
3. `openshift-*`
- JIRA: https://issues.redhat.com/browse/LOG-6354
> LOG-6354: Infra namespaces spec'd as app inputs have log_type set to 'application'

- internal/api/observability/conditions.go
- internal/api/observability/conditions_test.go
- internal/controller/observability/clusterlogforwarder_controller.go
This PR fixes an issue where substring collisions were occurring in the suffix matching logic for condition and pipeline names. Previously, the logic used `strings.HasSuffix()` to check if `condition.Type` ends with any of the pipeline names. This approach caused unintended collisions when one name was a substring of another. For example, if both `abc-app-logs` and `app-logs` were included in names, then `condition.Type` ending with `abc-app-logs` would incorrectly match `app-logs` as well. Fix this by adding more strict checking on name equality. 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6352
> LOG-6352: fix pruning condition, avoid infinity loop

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/collector_alerts.yaml
- docs/administration/collector-metrics-and-alerts.adoc
This PR changes the collector's alerting rules `message` field to `description` according to the [style guide](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide).
- JIRA: https://issues.redhat.com/browse/LOG-6126
> LOG-6126: Alerting rules for log-collection contains message instead of description

- bundle/metadata/properties.yaml
Updates the maximum OpenShift version to match the supported versions range.
/cc @cahartma
- JIRA: [LOG-6347](https://issues.redhat.com//browse/LOG-6347)
> LOG-6347: Update maximum OpenShift version to match supported range

- must-gather/collection-scripts/gather
The must-gather code[1] gathers LokiStack only when "lokistack" wasn't found in the result of "oc get crd".
It means that LokiStack isn't gathered even if it exists.
[1] https://github.com/openshift/cluster-logging-operator/blob/b8e2d71d573fca3717c232d3778aa021f63fc15d/must-gather/collection-scripts/gather#L94
The current line should use && instead of ||. This change is important because, in bash, if the left expression of || is true, the right expression is not evaluated. By using &&, the right expression will be evaluated if LokiStack exists, ensuring that the information is gathered correctly.
Here is an example to demonstrate this point:
```
$ bash -c 'echo first expression || echo second expression'
first expression  # <--- second expression is not evaluated
$ bash -c 'echo first …
```
> LOG-6277: Fix LokiStack is not gathered even if it exists.

- bundle/metadata/properties.yaml
This PR updates the maximum OpenShift version the operator is installable on to match the last version of OpenShift we officially [support](https://access.redhat.com/support/policy/updates/openshift_operators) for it.
/cc @cahartma 
- JIRA: [LOG-6375](https://issues.redhat.com//browse/LOG-6375)
> LOG-6375: Update maximum OpenShift version to match supported versions (5.6)

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/reference/operator/api_observability_v1.adoc
- internal/generator/vector/output/http/http.go
- internal/generator/vector/output/http/http_test.go
- internal/generator/vector/output/http/http_with_proxy.toml
-------
Add a 'proxy' field to HTTP output configuration to enable use of a proxy.e! -->
/cc @jcantrill
- JIRA: [LOG-6069](https://issues.redhat.com//browse/LOG-6069)
> LOG-6069: Enable http/https proxy support for HTTP output.

- internal/generator/fluentd/output/http/http.go
- internal/generator/fluentd/output/http/http_test.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
- internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go
This PR:
- fix Fluentd configuration generation in case `InsecureSkipVerify: true` by adding `tls_verify_mode none`
- Improve validation procedure for HTTP output, now will be fired error in case not secure URL and TLS settings 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6376
> LOG-6376: skip tls validation if it set in config for HTTP output

- internal/api/initialize/process_pipelines.go
- internal/api/initialize/process_pipelines_test.go
quick fix to handle nil exception when a named input is of type audit.   exception was being thrown since input.Receiver was nil
- https://issues.redhat.com/browse/LOG-6449
> [release-6.1] Handle input spec nil exception

- internal/api/initialize/process_pipelines.go
- internal/api/initialize/process_pipelines_test.go
Description
Manual cherrypick of the 6.1 version:   https://github.com/openshift/cluster-logging-operator/pull/2888
quick fix to handle nil exception when a named input is of type audit. exception was being thrown since input.Receiver was nil
Links
https://issues.redhat.com/browse/LOG-6441
> [release-6.0] Handle input spec nil exception 

- internal/api/initialize/process_pipelines.go
- internal/api/initialize/process_pipelines_test.go
Manual cherry pick from 6.1 the quick fix to handle nil exception when a named input is of type audit.  Occurs while migrating internal lokistack output
- https://issues.redhat.com/browse/LOG-6468
- release-6.2 clone:   https://issues.redhat.com/browse/LOG-6449
- PR:  https://github.com/openshift/cluster-logging-operator/pull/2888
> [master] LOG-6468: Fix input spec nil exception violation

- internal/collector/collector.go
- internal/collector/collector_test.go
It would seem we removed the `oauth-server` log volume from our mounts beginning in v6.      The file is still included in the config file "includes", but the volume is never mounted.  This is a regression bug.
- https://issues.redhat.com/browse/LOG-6484
> [release-6.1] LOG-6484: collector missing oauth server volume mount

- internal/generator/vector/output/syslog/rfc3164_with_defaults.toml
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- internal/generator/vector/output/syslog/tcp_with_defaults.toml
- internal/generator/vector/output/syslog/tcp_with_tuning.toml
- internal/generator/vector/output/syslog/tls_with_field_references.toml
- internal/generator/vector/output/syslog/xyz_defaults.toml
- test/framework/e2e/syslog_conf.go
- test/framework/functional/vector/deploy.go
- test/functional/outputs/syslog/forward_to_syslog_test.go
- test/functional/outputs/syslog/rfc3164_test.go
This PR addressed to align Syslog Output with syslog specification RFC3164 and RFC5424 
Format: `<PRI>TIMESTAMP HOSTNAME TAG: MESSAGE`
Example:`<34>Oct 11 22:14:15 mymachine su[1234]: 'su root' failed for lonvick on /dev/pts/`
|   | journal |  application | infrastructure | note |
| ------------- | ------------- |------------- | ------------- |  ------------- |
|AppName  | SYSLOG_IDENTIFIER* | namespacePodContainer  | .log_source  | |
| ProcId | _PID*  | N/A | .auditID (if available) | |
| MsgId | N/A | N/A  | N/A  | will have no effect in settings |
| Payloadkey | .message  | .message  | .message  | |
| Severity | N/A  | .level  | information (6) | |
| Facility | N/A  | user (1)  | security(13) | |
*If `ProcId` available, it will aggregate with `AppName` in the `.tag` field: …
> LOG-6236: Align syslog output implementation with spec RFC3164 and RFC5124

- internal/collector/collector.go
- internal/collector/collector_test.go
Manual cherrypick of issue from LOG-6484.  Already fixed in 6.0 and 6.1.   No Jira.
We removed the `oauth-server` log volume from our mounts beginning in v6.      
> [master] Add missing oauth-server volume mount

- test/e2e/logforwarding/lokistack/forward_to_lokistack_test.go
- test/e2e/logforwarding/lokistack/lokistack_suite_test.go
- test/framework/e2e/auth.go
- test/framework/e2e/framework.go
- test/framework/e2e/lokistack.go
This PR adds an E2E test for `lokistack`. This test ensures that `Lokistack` can receive both `OTEL` and  `Viaq` formatted data when spec'd for either one.
- JIRA: https://issues.redhat.com/browse/LOG-5481
> LOG-5481: Write RH lokistack OTEL test

- internal/collector/collector.go
Duplicate mount name, resulted in `oauth-apiserver` volumeMount to fail collecting the `audit.log` file for this directory/mount.
/cc @Clee2691 @vparfonov @xperimental
- https://issues.redhat.com/browse/LOG-6543
> [release-6.0] LOG-6543: Fix oauth apiserver mount

- internal/collector/collector.go
Duplicate mount name, resulted in `oauth-apiserver` volumeMount to fail collecting the `audit.log` file for this directory/mount.
/cc @Clee2691 @vparfonov @xperimental
- https://issues.redhat.com/browse/LOG-6533
> [release-6.1] LOG-6533: fix audit log oauth-apiserver mount

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/reference/operator/api_observability_v1.adoc
Fixed some of the tables content which was broken due to special characters.
The content was broken due to the "pipes" which were creating new table lines.
Have fixed the content presentation in the document sections. The table was broken due to the "||" characters. Inserted the backslash to prevent it.
The goal here was to change the documentation only, not the service definition which now has the backslashes in the description.
> Observability output types - doc update

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/reference/operator/api_observability_v1.adoc
This PR:
* updates the LokiStack output type api to require setting the target namespace of the loki deployment
* Modifies the comments to no longer imply the operator defaults anything
https://issues.redhat.com/browse/LOG-6573
> LOG-6573: Require namespace for LokiStack target

- cmd/main.go
- internal/controller/logfilemetricsexporter/logfilemetricsexporter_controller.go
- internal/controller/observability/collector.go
- internal/metrics/logfilemetricexporter/factory_test.go
- internal/metrics/logfilemetricexporter/metric_exporter.go
- internal/metrics/logfilemetricexporter/metric_exporter_test.go
- internal/reconcile/scc.go
- internal/reconcile/scc_test.go
This PR fixes a potential race condition related to the creation of `SecurityContextConstraint`. The issue can occur because an instance may be created during the initialization of `Collector` and `LogFileMetricExporter`. By using a non-cached client, we can avoid unpredictable behavior, as the uncached reader will always retrieve the actual state of the object from the API, bypassing cached objects.
Need to say that this issue does not always reproduce. During my testing, I was unable to reproduce it on my cluster setup.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6418
> LOG-6418: Use uncached reader for reconciliation SCC to avoid unexpected behavior

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/input/application.toml
- internal/generator/vector/input/application_exclude_container_from_infra.toml
- internal/generator/vector/input/application_excludes_container.toml
- internal/generator/vector/input/application_includes_container.toml
- internal/generator/vector/input/application_with_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_matchLabels.toml
- internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_throttle.toml
- internal/generator/vector/input/audit.go
- internal/generator/vector/input/infrastructure.toml
- internal/generator/vector/input/infrastructure_container.toml
- internal/generator/vector/input/journal.go
- internal/generator/vector/input/meta.go
- internal/generator/vector/input/receiver.go
- internal/generator/vector/input/source.go
This is a manual port of [PR2862](https://github.com/openshift/cluster-logging-operator/pull/2862) to `release-6.1`.
- JIRA: https://issues.redhat.com/browse/LOG-6373
> LOG-6373: Port LOG-6354 to release-6.1

- internal/generator/vector/output/syslog/rfc3164_with_defaults.toml
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- internal/generator/vector/output/syslog/tcp_with_defaults.toml
- internal/generator/vector/output/syslog/tcp_with_tuning.toml
- internal/generator/vector/output/syslog/tls_with_field_references.toml
- internal/generator/vector/output/syslog/xyz_defaults.toml
- test/framework/e2e/syslog_conf.go
- test/framework/functional/vector/deploy.go
- test/functional/outputs/syslog/forward_to_syslog_test.go
- test/functional/outputs/syslog/rfc3164_test.go
manual cherry-pick for https://github.com/openshift/cluster-logging-operator/pull/2830
/cherry-pick 
- Bugzilla:
- JIRA:
> [release-6.0]LOG-6236: Align syslog output implementation with spec RFC3164 and RFC5124

- internal/collector/vector/run-vector.sh
This PR removes the deletion of the buffer lock files in `vector`'s startup script.
- JIRA: https://issues.redhat.com/browse/LOG-6348
> LOG-6348: Collector startup script removes buffer lock files breaking locking code of vector

- internal/generator/vector/output/factory_test_loki_with_throttle.toml
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/with_custom_bearer_token.toml
- internal/generator/vector/output/loki/with_custom_labels.toml
- internal/generator/vector/output/loki/with_default_labels.toml
- internal/generator/vector/output/loki/with_default_tls.toml
- internal/generator/vector/output/loki/with_insecure.toml
- internal/generator/vector/output/loki/with_insecure_nocert.toml
- internal/generator/vector/output/loki/with_sa_token.toml
- internal/generator/vector/output/loki/with_tenant_id.toml
- internal/generator/vector/output/loki/with_tls.toml
- internal/generator/vector/output/loki/with_tuning.toml
- internal/generator/vector/output/loki/with_username_password.toml
- test/e2e/logforwarding/lokistack/forward_to_lokistack_test.go
- test/functional/outputs/loki/application_logs_vector_test.go
- test/functional/outputs/loki/audit_logs_vector_test.go
This PR adds the "OTel sematic" stream labels to log outputs for any `Loki` output which includes `LokiStack`. This ensures forward compatibility so that both `Viaq` and `OTel` stream labels can be used to query for logs.
If users configure a custom set of label keys, only the matching `OTel` equivalent labels are added to the stream labels.
The following stream labels are added:
1. `openshift_log_type`
2. `k8s_namespace_name` 
3. `k8s_pod_name`    
4. `k8s_container_name`
5. `k8s_node_name`
/cc @cahartma @vparfonov @xperimental 
- JIRA: https://issues.redhat.com/browse/LOG-6508
> LOG-6508: Emit stream labels following OTel Semantic Conventions

- cmd/main.go
- internal/metrics/dashboard/dashboards.go
- internal/runtime/runtime.go
- internal/runtime/runtime_test.go
This PR:
* Adds labels version, managedby to the collector dashboard configmap
* Modifies logic to only delete the dashboard on operator exit if the label set matches those expected by the operator
* Resolves the issue where the old version of the operator deleted the dashboard on_exit after the new version of the operator updated it
https://issues.redhat.com/browse/LOG-6280
> LOG-6280: Only cleanup dashboard when owned by 'this' operator version

- test/e2e/collection/security/container_security_test.go
This PR updates the collector container security: sysctl test to account for multiple possible outputs when the `sysctl` command is unavailable or the executable file is not found.
By adding the `Or` matcher with `ContainSubstring` to handle variations in error messages:
`sysctl: no such file`
`executable file '/usr/sbin/sysctl' not found in $PATH`
This is need because this test fail if run in on latest (4.18.x) OpenShift version. 
/cherry-pick 
- Bugzilla:
- JIRA:
> NO-JIRA: enhance 'sysctl' test to handle multiple expected outputs

- internal/generator/vector/output/factory_test_loki_with_throttle.toml
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/with_custom_bearer_token.toml
- internal/generator/vector/output/loki/with_custom_labels.toml
- internal/generator/vector/output/loki/with_default_labels.toml
- internal/generator/vector/output/loki/with_default_tls.toml
- internal/generator/vector/output/loki/with_insecure.toml
- internal/generator/vector/output/loki/with_insecure_nocert.toml
- internal/generator/vector/output/loki/with_sa_token.toml
- internal/generator/vector/output/loki/with_tenant_id.toml
- internal/generator/vector/output/loki/with_tls.toml
- internal/generator/vector/output/loki/with_tuning.toml
- internal/generator/vector/output/loki/with_username_password.toml
- test/functional/outputs/loki/application_logs_vector_test.go
- test/functional/outputs/loki/audit_logs_vector_test.go
This is a manual port of [PR#2926](https://github.com/openshift/cluster-logging-operator/pull/2926) to `release-6.1`.
- JIRA: https://issues.redhat.com/browse/LOG-6579
> [release-6.1] LOG-6579: Manual port of LOG-6508 to release 6.1

- internal/generator/vector/output/factory_test_loki_no_throttle.toml
- internal/generator/vector/output/factory_test_loki_with_throttle.toml
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/with_custom_bearer_token.toml
- internal/generator/vector/output/loki/with_custom_labels.toml
- internal/generator/vector/output/loki/with_default_labels.toml
- internal/generator/vector/output/loki/with_default_logcollector_bearer_token.toml
- internal/generator/vector/output/loki/with_default_tls.toml
- internal/generator/vector/output/loki/with_insecure.toml
- internal/generator/vector/output/loki/with_insecure_nocert.toml
- internal/generator/vector/output/loki/with_tenant_id.toml
- test/functional/outputs/loki/application_logs_vector_test.go
- test/functional/outputs/loki/audit_logs_vector_test.go
This is a manual port of https://github.com/openshift/cluster-logging-operator/pull/2926 to `release-5.9`.
This only adds functionality to `vector` and **NOT** `fluentd` because `fluentd` is deprecated.
- JIRA: https://issues.redhat.com/browse/LOG-6581
> [release-5.9] LOG-6581: Manual port of LOG-6508 to release-5.9

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/outputs_test.go
- internal/generator/vector/pipelines_to_output_test.go
- test/functional/outputs/loki/application_logs_vector_test.go
- test/functional/outputs/loki/audit_logs_vector_test.go
This is a manual port of https://github.com/openshift/cluster-logging-operator/pull/2926 to `release-5.8`.
This only adds functionality to `vector` and **NOT** `fluentd` because `fluentd` is deprecated.
/cc @cahartma @vparfonov
- JIRA: https://issues.redhat.com/browse/LOG-6582
> [release-5.8] LOG-6582: Manual port of LOG-6508 to release-5.8

- api/observability/v1/output_types.go
- docs/features/logforwarding/outputs/syslog-forwarding.adoc
- test/functional/outputs/syslog/rfc5424_test.go
Add document with description how to configure Log Forwarding to the Syslog receiver 
/cherry-pick 
- Depending on PR(s): https://github.com/openshift/cluster-logging-operator/pull/2830
- Bugzilla:
- JIRA:
> LOG-6236: add docs about how to forwarding log to Syslog

- internal/api/observability/pipelines.go
- internal/validations/observability/outputs/validate.go
- internal/validations/observability/outputs/validate_test.go
This PR:
* validates each output is referenced by a pipeline or fails
* this will keep the operator from deploying a collector with configuration not accepted by vector
https://issues.redhat.com/browse/LOG-6585
cc @vparfonov @cahartma
> LOG-6585: Fail validition if output is unreferenced

- must-gather/README.md
- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_collection_resources
- must-gather/collection-scripts/gather_logstore_resources
Collect some resources missing in Logging 6 must-gather, and collect them with `oc adm inspect` for being compatible with `omc` tool.
Separated `namespaces` and `cluster_resources` for clarity and because different data is collected from them. Not adding `$multi` to `namespace_resources` when it's already `$LOGGING_NS`.
Collect `console` Cluster Operator if the UIPlugin is present.
/assign @xperimental 
/cherry-pick release-6.1 release-6.0
- JIRA: https://issues.redhat.com/browse/LOG-6422
> LOG-6422: adding missing resources in Logging 6 must-gather

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc
This PR:
- adds better description when reviewing the fields using `$ oc explain obsclf.spec.outputs.elasticsearch.index` for when log forwarding to the Red Hat Managed Elasticsearch for knowing about the limitation with the name of the indices
- add same information to the internal documentation 
/cc @cahartma 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6623
> LOG-6623: better description for 'obsclf.spec.outputs.elasticsearch.index' when log forwarding to the Red Hat Managed Elasticsearch

- internal/controller/observability/clusterlogforwarder_controller.go
Use `Patch()` instead of `Update()` should prevent conflicts during updating.
/cc @cahartma 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6539
> LOG-6539: use Patch() instead of Update() in updateStatus func

- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- internal/generator/vector/output/syslog/tls_with_field_references.toml
- internal/generator/vector/output/syslog/udp_with_every_setting.toml
- test/functional/outputs/syslog/rfc3164_test.go
- test/functional/outputs/syslog/rfc5424_test.go
This change:
* Restricts syslog.(severity|facility) to the template pattern supported elsewhere in the API
* Removes the capability to use the 5.x syslog template notation (e.g. `$$.message.foo`)
* Updates tests to validate changes
* https://issues.redhat.com/browse/LOG-6661
> LOG-6661: fix inconsistency for syslog facillity and severity templating

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
Manual cherry-pick for: https://github.com/openshift/cluster-logging-operator/pull/2957
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> [master]LOG-6623: better description for 'obsclf.spec.outputs.elasticsearch.index' when log forwarding to the Red Hat Managed Elasticsearch

- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- test/e2e/collection/apivalidations/api_validations_test.go
- test/e2e/collection/apivalidations/lokistack-empty-tuning.yaml
- test/e2e/collection/apivalidations/lokistack-snappy-compression-otel.yaml
/cc @cahartma 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6532
> LOG-6532: fix validation rule for Loki Tuning to allow it to be empty without failing validation

- internal/controller/observability/clusterlogforwarder_controller.go
This PR reverts https://github.com/openshift/cluster-logging-operator/pull/2955
- JIRA: https://issues.redhat.com/browse/LOG-6761
- Related JIRA: https://issues.redhat.com/browse/LOG-6539
> Revert "LOG-6539: use Patch() instead of Update() in updateStatus func"

- internal/api/observability/pipelines.go
- internal/validations/observability/outputs/validate.go
- internal/validations/observability/outputs/validate_test.go
This PR is a backport of https://github.com/openshift/cluster-logging-operator/pull/2940, in which the validation will fail if outputs are not referenced by any pipeline.
- JIRA: https://issues.redhat.com/browse/LOG-6759
- Related JIRA: https://issues.redhat.com/browse/LOG-6585
> LOG-6759: Collectors in crashloopbackoff when defined an output that not used in the pipeline

- api/observability/v1/input_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This PR adds information about the supported `input receiver` types when using `oc explain`.
1. When using `oc explain obsclf.spec.inputs.receiver`:
Output:
```
...
FIELDS:
...
type	<string> -required-
Type of Receiver plugin.
Supported Receiver types are:
1. http
- Currently only supports kubernetes audit logs (log_type = "audit")
2. syslog
- Currently only supports node infrastucture logs (log_type =
"infrastructure")
```
2. When using `oc explain obsclf.spec.inputs.receiver.http`:
Output:
```
...
FIELDS:
format	<string> -required-
Format is the format of incoming log data.
The current supported format is `kubeAPIAudit`.
```
- JIRA: https://issues.redhat.com/browse/LOG-6850
> LOG-6850: syslog input missing from 'obsclf.spec.inputs.receiver'

- internal/generator/fluentd/fluent_conf_test/exclude.conf
- internal/generator/fluentd/output/fluentdforward/fluentdforward.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/fluentdforward/output_conf_forward_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
When the target server DNS record changes during runtime, the change is not picked by the forwarder. With this change the cached DNS record expires and renews each 30 seconds.
https://docs.fluentd.org/output/forward#expire_dns_cache
/cc 
/assign 
/cherry-pick 
https://issues.redhat.com/browse/LOG-6812
> LOG-6812: Set dns cache to expire

- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- config/rbac/role.yaml
This PR:
* fixes the operator permissions to allow it to update securitycontextconstraints
https://issues.redhat.com/browse/LOG-6816
> LOG-6816: fix operator permissions to update SCC

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This PR adds descriptions for the `RFC` and `enrichment` types for the `syslog` output when using `oc explain`.
When using `oc explain obsclf.spec.outputs.syslog`
```
...
FIELDS:
...
enrichment	<string>
Enrichment is an additional modification to the log message before
forwarding it to the receiver.
Supported values are:
1. None
- Adds no additional enrichment to the record
2. KubernetesMinimal
- Adds namespace_name, pod_name, and container_name to the beginning of
the message body (e.g. namespace_name=myproject, container_name=server,
pod_name=pod-123, message={"foo":"bar"}).
This may result in the message body being an invalid JSON structure.
...
rfc	  <string> -required-
The RFC to which the generated messages conform to.
Supported values are:
1. RFC3164
2. RFC5424
...
```
/cc …
> LOG-6869: Improve description for rfc and enrichment in syslog

- api/logging/v1/clusterlogging_types.go
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_clusterloggings.yaml
- config/crd/bases/logging.openshift.io_clusterloggings.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR adds the supported values for the `ClusterLogging`'s `collection` and `visualization` specs.
Output:
```
FIELDS:
...
type	<string> -required-
The type of Visualization to configure
Supported values are:
1. ocp-console
2. kibana
```
Output:
```
FIELDS:
...
type	<string>
The type of Log Collection to configure
Supported values are:
1. vector
2. fluentd
```
- JIRA: https://issues.redhat.com/browse/LOG-6855
> LOG-6855: Not listed the types for different fields in the clusterLogging

- must-gather/README.md
- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_monitoring
- must-gather/collection-scripts/monitoring_common.sh
Gathering OpenShift alerts in Logging must-gather, based on the script in "standard" must-gather.
/cherry-pick release-6.2 release-6.1 release-6.0
- JIRA: [OBSDA-760](https://issues.redhat.com//browse/OBSDA-760)
> OBSDA-760: Gathering OpenShift alerts in Logging must-gather

- Dockerfile
- olm_deploy/operatorregistry/Dockerfile
This PR
* updates the golang builder for development builds.
* unblocks updated CI which keeps reverting changes
https://issues.redhat.com/browse/LOG-6723
cc @vparfonov @cahartma @Clee2691
> LOG-6723: Update golang to v1.23

- api/observability/v1/output_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- test/e2e/collection/apivalidations/api_validations_test.go
- test/e2e/collection/apivalidations/lokistack-empty-tuning.yaml
- test/e2e/collection/apivalidations/lokistack-snappy-compression-otel.yaml
back-port https://github.com/openshift/cluster-logging-operator/pull/2956
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6878
> [release-6.2]LOG-6878: fix validation rule for Loki Tuning to allow it to be empty without failing validation 

- hack/logsamples/otlp_audit_ovn.json
- hack/logsamples/viaq_audit_ovn.json
- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/filter/openshift/viaq/audit.go
- internal/generator/vector/output/lokistack/lokistack_otel.toml
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/otlp/otlp_with_auth_basic.toml
- internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml
- internal/generator/vector/output/otlp/transform.go
- test/framework/functional/write.go
- test/functional/outputs/otlp/audit_test.go
- test/helpers/types/otlp/attributes.go
backport of #3006 
/cc @Clee2691 @cahartma  
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6996
> [release-6.1]LOG-6996: fix audit ovn and auditd log forwarding

- Makefile
All camel case flags (e.g. -noColor) are replaced with kebab case flags (e.g. -no-color) in Ginkgo 2.0. The camel case versions continue to work but emit a deprecation warning.
- JIRA:
> NO-JIRA: replace deprecated Ginkgo command line flags

- api/observability/v1/clusterlogforwarder_types.go
- api/observability/v1/filter_types.go
- api/observability/v1/output_types.go
- internal/generator/vector/helpers/helpers.go
- internal/generator/vector/helpers/helpers_test.go
- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_sink_payloadkey.toml
- internal/generator/vector/output/splunk/splunk_sink_with_custom_index.toml
- internal/generator/vector/output/splunk/splunk_sink_with_custom_index_dedot.toml
- internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields.toml
- internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields_and_source.toml
- internal/generator/vector/output/splunk/splunk_sink_with_tls.toml
- internal/generator/vector/output/splunk/splunk_sink_with_tls_and_static_index.toml
- internal/generator/vector/output/splunk/splunk_test.go
- internal/generator/vector/output/splunk/splunk_tune.toml
- test/framework/functional/output_splunk.go
- test/functional/filters/prune/prune_filter_test.go
- test/functional/outputs/splunk/forward_to_splunk_metadata_test.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
This PR addressed to extend the `ClusterLogForwarder` to support `Splunk` `metadata fields` when forwarding logs
so that we enable better integration with `Splunk`.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6860
- Enhancement proposal: https://github.com/openshift/cluster-logging-operator/pull/2979
> LOG-6860: Support Splunk Metadata keys in ClusterLogForwarder

- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
Add operator to "Observability" category in OperatorHub.  This should be possible now that "Observability" has been added to https://github.com/operator-framework/api/blob/master/pkg/validation/internal/standardcategories.go#L31
- JIRA: [OCPSTRAT-954](https://issues.redhat.com/browse/OCPSTRAT-954), [LOG-4691](https://issues.redhat.com/browse/LOG-4691)
> Add operator to "Observability" category in OperatorHub

- internal/generator/vector/output/lokistack/lokistack_otel.toml
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/otlp/otlp_with_auth_basic.toml
- internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml
- internal/generator/vector/output/otlp/otlp_with_auth_token.toml
- internal/generator/vector/output/otlp/transform.go
- test/e2e/logforwarding/lokistack/forward_to_lokistack_test.go
- test/framework/e2e/lokistack.go
This PR fixes `int` parsing errors in the loki distributor for audit logs that do not contain a `responseStatus.code`.
Additionally, this PR attempts to fix the `lokistack` e2e test flake by decreasing the lokistack size to `1x.demo` and increasing `ingestionRate` and `burst` size. 
It also sets a resource request for the collector so that it does not get `OOM` killed on master nodes.
- JIRA: https://issues.redhat.com/browse/LOG-7012
> LOG-7012: Parsing errors under Loki distributor for audit tenant when using Otel DataModel

- internal/generator/vector/output/lokistack/lokistack_otel.toml
- internal/generator/vector/output/otlp/otlp_all.toml
- internal/generator/vector/output/otlp/otlp_tuning.toml
- internal/generator/vector/output/otlp/otlp_with_auth_basic.toml
- internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml
- internal/generator/vector/output/otlp/otlp_with_auth_token.toml
- internal/generator/vector/output/otlp/transform.go
- test/framework/functional/factory.go
This PR fixes the parsing of `auditd` log messages that contain multiple `msg` keys in a single line, such as:: 
`type=USER_AUTH msg=audit(1617908892.234:123): pid=1023 uid=0 auid=1000 ses=1 msg='PAM:authentication grantors=pam_unix acct="user1" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'`
When using the `parse_key_value()` VRL function on such messages, the `msg` key is returned as an array. However, for our parsing logic, only the first msg entry is relevant — in this case:
`msg=audit(1617908892.234:123)`
This PR ensures that only the first `msg` value is used during parsing.
/assign @cahartma @jcantrill 
- JIRA: https://issues.redhat.com/browse/LOG-7014
> LOG-7014: fix parsing complex auditd logs for otlp mode

- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
- test/functional/outputs/syslog/rfc3164_test.go
- test/functional/outputs/syslog/rfc5424_test.go
This PR addresses several issues introduced during the migration from `Fluentd` to `Vector`, particularly related to how the`.message` field was merged into the log event. 
These issues include:
- Overwriting important system fields
- Duplication of data
- Corruption of log events due to improper structure
With this change, the `.message` field is replaced if it will valid JSON string, with structured data instead of being blindly merged. This enables correct handling of **nested fields** during the Syslog encoding process in Vector.
- Depending on PR(s): https://github.com/ViaQ/vector/pull/203
- JIRA:https://issues.redhat.com/browse/LOG-7009, https://issues.redhat.com/browse/LOG-7010, https://issues.redhat.com/browse/LOG-7008 …
> [release-5.9]LOG-7009: avoid merge data from .message field to the log event root

- test/e2e/collection/security/container_security_test.go
Update test to handle systems where the error message for a missing `sysctl`. The assertion now allows either of:
• "sysctl: no such file"
• "executable file `/usr/sbin/sysctl` not found"
This makes the test pass across different environments without relying on exact error message suffixes like `": No such file or directory"`.
Early test fail with:
```
[FAILED] Expected
<string>: executable file `/usr/sbin/sysctl` not found: No such file or directory
command terminated with exit code 255
To satisfy at least one of these matchers: [%!s(*matchers.ContainSubstringMatcher=&{sysctl: no such file []}) %!s(*matchers.ContainSubstringMatcher=&{executable file `/usr/sbin/sysctl` not found in $PATH []})]
In [It] at: /go/src/github.com/openshift/cluster-logging-operator/test/e2e/collection/security/co …
```
> NO-JIRA: make sysctl missing binary assertion more flexible

- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/syslog_test.go
This PR changes the log level from "error" to "debug" for the case with parsing `.message` as JSON, where the logged issue is not actually an error in this context. The previous log level caused unnecessary noise in the logs by treating non-critical behavior as an error. This change helps reduce log flooding while still preserving the ability to debug if needed
- JIRA: https://issues.redhat.com/browse/LOG-7232
> LOG-7232: Downgrade log level from error to debug for not errors in this context

- bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
- config/prometheus/collector_alerts.yaml
This PR introduces a new Prometheus alerting rule to detect an elevated rate of HTTP 403 Forbidden responses in the collector.
The associated [runbook](https://github.com/openshift/runbooks/pull/249) is pending PR review.
- JIRA: https://issues.redhat.com/browse/LOG-7023
- runbook: https://github.com/openshift/runbooks/pull/249
> LOG-7023: Add Prometheus alerting rule for collector 403 responses

- bundle/metadata/properties.yaml
Updates the maximum OpenShift version to match the supported range of Logging 6.3
/cc @jcantrill
- JIRA: [LOG-7266](https://issues.redhat.com//browse/LOG-7266)
> LOG-7266: Update maximum OpenShift version to match supported range

- internal/validations/observability/outputs/validate.go
- internal/validations/observability/outputs/validate_tech_preview.go
- internal/validations/observability/outputs/validate_tech_preview_test.go
This PR fixes validation for Lokistack outputs that spec a data model of `Otel`. The tech preview annotation must be present when data model is `Otel` otherwise the `ClusterLogForwarder` is invalid.
- JIRA: https://issues.redhat.com/browse/LOG-7279
> LOG-7279: Otel dataModel is enabled without the tech-preview annotation on CLF

- internal/generator/vector/output/syslog/rfc3164_with_defaults.toml
- internal/generator/vector/output/syslog/syslog.go
- internal/generator/vector/output/syslog/tcp_with_defaults.toml
- internal/generator/vector/output/syslog/tcp_with_tuning.toml
- internal/generator/vector/output/syslog/xyz_defaults.toml
- test/functional/outputs/syslog/forward_to_syslog_test.go
This pull request addresses an issue where the default value calculation for the Syslog `appname` field would fail. This failure occurred specifically when a Prune filter removed one or more of the following Kubernetes metadata fields: `.kubernetes.namespace_name`, `.kubernetes.pod_name`, or `.kubernetes.container_name`.
The `join([.kubernetes.namespace_name, .kubernetes.pod_name, .kubernetes.container_name])` VRL function would encounter an error in such scenarios, preventing the `appname` field from being correctly initialized.
To resolve this, an error check has been added. If the `join()` operation encounters an error (due to missing fields), the `appname` field will now be gracefully initialized with an empty string.
Similar things were added for Syslog tag field.
/cc @cahartma …
> LOG-7267: add fallback option if syslog appname calculation fail

- bundle/metadata/properties.yaml
Currently we pass in the maximum version as a number, which has worked for the previous releases, but stops working with 4.20, because it is parsed as `4.2`. This PR fixes this by changing the type to a string.
/cc @jcantrill
- JIRA: [LOG-7299](https://issues.redhat.com//browse/LOG-7299) [LOG-7266](https://issues.redhat.com//browse/LOG-7266)
> LOG-7299: Fix type of maximum OpenShift version

- internal/collector/collector.go
- internal/collector/collector_test.go
- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/conf/global.go
- internal/generator/vector/conf/global_test.go
- test/functional/misc/vector_api_cli_test.go
This PR adds a liveness probe to the Vector collector containers to improve pod health management.
The liveness probe periodically checks the Vector internal HTTP health endpoint (/health on port `24686`). If the probe fails repeatedly,   container will automatically restart.
Requires changes in Vector config to enable the `/health` endpoint:
```
[api]
enabled = true
address = "0.0.0.0:24686"
```
/cc @Clee2691 
- JIRA: https://issues.redhat.com/browse/LOG-7058
> LOG-7058: Add liveness probe to Vector collector container

- internal/generator/vector/output/splunk/splunk.go
- internal/generator/vector/output/splunk/splunk_sink.toml
- internal/generator/vector/output/splunk/splunk_sink_payloadkey.toml
- internal/generator/vector/output/splunk/splunk_sink_with_custom_index.toml
- internal/generator/vector/output/splunk/splunk_sink_with_custom_index_dedot.toml
- internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields.toml
- internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields_and_source.toml
- internal/generator/vector/output/splunk/splunk_sink_with_tls.toml
- internal/generator/vector/output/splunk/splunk_sink_with_tls_and_static_index.toml
- internal/generator/vector/output/splunk/splunk_tune.toml
- test/functional/outputs/splunk/forward_to_splunk_metadata_test.go
A "Timestamp not found" warning is generated in collector pods when forwarding logs to Splunk if a `payloadKey` is configured.
The `timestamp_key` was set to `@timestamp` at the root level of the log event. However, when a `payloadKey` is is configuration `@timestamp` field will be out of message.
The `timestamp_key` is now set to `_internal.timestamp` this is allowed to use transfer correct timestamp of log event not depended on `payloadKey` settings. 
/cc @cahartma @Clee2691  
- JIRA: https://issues.redhat.com/browse/LOG-7311
> LOG-7311:fix for timestamp warning in collector when forwarding logs to Splunk with payloadKey

- docs/features/kube-api-annotations.adoc
No Jira:  Add an initial doc to guide the continued effort to resolve customers using our new tech-preview features.  
/cc @Clee2691 @vparfonov 
- Original Issue https://issues.redhat.com/browse/LOG-7196
> Upstream guide for kubeapi tech-preview feature

- api/observability/v1/output_types.go
- api/observability/v1/zz_generated.deepcopy.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/output/kafka/kafka_test.go
- test/e2e/collection/apivalidations/api_validations_test.go
- test/e2e/collection/apivalidations/kafka_valid_url_and_brokers.yaml
Backport: https://github.com/openshift/cluster-logging-operator/pull/3071
- JIRA: https://issues.redhat.com/browse/LOG-7386
> [release-6.3]LOG-7386: add validation  that the kafka URLs should be tcp or tls

- api/observability/v1/filter_types.go
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- docs/contributing/how-to-add-new-output.md
- docs/features/logforwarding/filters/api-audit-filter.adoc
- docs/features/logforwarding/filters/drop-filter.adoc
- docs/features/logforwarding/filters/prune-filter.adoc
- docs/features/logforwarding/multiline-error-detection.adoc
- docs/features/logforwarding/outputs/cloudwatch-sts-forwarding.adoc
Updates the manifest and api description for the prune filter 'In' and 'NotIn' to also require '.log_source' field, matching the validation. 
> No JIRA: update prune filter description to match logic

- api/observability/v1/output_types.go
- bundle/manifests/cluster-logging.clusterserviceversion.yaml
- bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
- config/rbac/role.yaml
- docs/features/collection.adoc
- docs/features/network_policy.adoc
- docs/reference/operator/api_observability_v1.adoc
- internal/controller/observability/clusterlogforwarder_controller.go
- internal/controller/observability/collector.go
- internal/factory/network_policy.go
- internal/factory/network_policy_test.go
- internal/network/network_policy.go
- internal/network/network_policy_test.go
- internal/reconcile/networkpolicy.go
- internal/runtime/core.go
This PR adds a default `NetworkPolicy` to allow all ingress and egress traffic for the collector pods.
This ensures logging continues to function in hardened environments that use `AdminNetworkPolicy` (ANP). 
To be effective against a cluster-wide Deny rule, this policy requires a corresponding high-priority `ANP` that delegates traffic decisions (action: `Pass`) for the collector pods.
- JIRA: https://issues.redhat.com/browse/LOG-7572
> LOG-7572: NetworkPolicy for ClusterLogForwarder

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/filter/openshift/viaq/v1/filter.go
- internal/generator/vector/filter/openshift/viaq/v1/normalize.go
- internal/generator/vector/input/application.toml
- internal/generator/vector/input/application_exclude_container_from_infra.toml
- internal/generator/vector/input/application_excludes_container.toml
- internal/generator/vector/input/application_includes_container.toml
- internal/generator/vector/input/application_with_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_matchLabels.toml
- internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_throttle.toml
- internal/generator/vector/input/audit.toml
- internal/generator/vector/input/audit_host.toml
- internal/generator/vector/input/audit_kube.toml
- internal/generator/vector/input/audit_openshift.toml
- internal/generator/vector/input/audit_ovn.toml
- internal/generator/vector/input/infrastructure.toml
- internal/generator/vector/input/infrastructure_container.toml
- internal/generator/vector/input/infrastructure_journal.toml
- internal/generator/vector/input/internal.go
- internal/generator/vector/input/receiver_http_audit.toml
- test/functional/filters/prune/prune_filter_test.go
- test/functional/outputs/splunk/forward_to_splunk_metadata_test.go
- test/functional/outputs/splunk/forward_to_splunk_test.go
- test/helpers/splunk/splunk.go
This is a manual port of [LOG-7620](https://issues.redhat.com/browse/LOG-7620) to `release-6.3`.
This PR resolves a bug where the prune transform failed to remove the `.openshift.sequence` field from log events. The removal logic has been corrected to ensure this field is successfully pruned.
- JIRA: https://issues.redhat.com/browse/LOG-7805
> [release-6.3] Manual port of LOG-7620

- internal/generator/vector/conf/complex.toml
- internal/generator/vector/conf/complex_http_receiver.toml
- internal/generator/vector/conf/container.toml
- internal/generator/vector/filter/openshift/viaq/v1/normalize.go
- internal/generator/vector/input/application.toml
- internal/generator/vector/input/application_exclude_container_from_infra.toml
- internal/generator/vector/input/application_excludes_container.toml
- internal/generator/vector/input/application_includes_container.toml
- internal/generator/vector/input/application_with_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_excludes.toml
- internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_matchLabels.toml
- internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml
- internal/generator/vector/input/application_with_throttle.toml
- internal/generator/vector/input/infrastructure.toml
- internal/generator/vector/input/infrastructure_container.toml
- internal/generator/vector/input/internal.go
- test/functional/filters/prune/prune_filter_test.go
This is a manual port of [LOG-7622](https://issues.redhat.com/browse/LOG-7622) to `release-6.3`.
This PR resolves a bug where the prune transform failed to remove the `.kubernetes.container_iostream` field from log events. The removal logic has been corrected to ensure this field is successfully pruned.
- JIRA: https://issues.redhat.com/browse/LOG-7806
> LOG-7806: Manual port of LOG-7622 to release-6.3
