OWNERS
=> Creating OWNERS file

Makefile
Remove build info from compile to resolve downstream issue
=> remove ldflags with build info

files/curator-actions.yaml, files/curator-config.yaml, files/curator5-config.yaml, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/stub/handler.go, pkg/utils/utils.go
=> Curator work

vendor/github.com/petar/GoLLRB/doc/Sedgewick-LLRB.pdf
Addresses https://jira.coreos.com/browse/ART-162?focusedCommentId=50426&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-50426
=> Removing vendor pdfs

OWNERS
@jwforres  I assume you approve here?
=> update owner file

Dockerfile, Makefile
To satisfy @sosiouxme  https://jira.coreos.com/browse/ART-162?focusedCommentId=50773&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-50773
=> use multi-stage builds for images

Dockerfile, Makefile, manifests/01-namespace.yaml, manifests/02-service-account.yaml, manifests/03-role.yaml, manifests/04-role-binding.yaml, manifests/05-crd.yaml, manifests/05-deployment.yaml, manifests/image-references
This PR adds manifests to the image to resolve: https://jira.coreos.com/browse/LOG-198
=> LOG-198. Add manifests

manifests/10-service-monitor-fluentd.yaml, pkg/utils/utils.go
Resolve https://jira.coreos.com/browse/LOG-220
by adding the fluentd servicemonitor definition
=> LOG-220. Add fluentd ServiceMonitor definition

manifests/03-role.yaml, manifests/04-role-binding.yaml, pkg/k8shandler/visualization.go, pkg/utils/utils.go, test/e2e/clusterlogging_test.go
To address the lack of a created oauthclient
Current gaps: no top level config to pull cluster configuration from to get the default dns
=> Creating the oauth client for kibana redirects

hack/examples/cr.yaml, pkg/apis/logging/v1alpha1/types.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go
Resolves https://jira.coreos.com/browse/LOG-247
=> Adding managementState spec field

README.md, hack/deploy-setup.sh, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go, pkg/stub/handler.go, pkg/utils/utils.go
Addresses https://github.com/openshift/cluster-logging-operator/issues/39
=> Improved error handling

Makefile, README.md, hack/common, hack/deploy-image.sh, hack/deploy.sh
fix unexported env. vars. and remote registry integration
=> fix unexported env. vars. and remote registry integration

pkg/k8shandler/visualization.go, pkg/utils/utils.go
... when building oauth client and shared configmap
=> Updating to autogenerate route hosts and pull spec.host value 

files/rsyslog/00-global.conf, files/rsyslog/60-mmk8s.conf, files/rsyslog/crio.rulebase, files/rsyslog/k8s_container_name.rulebase, files/rsyslog/multiline-json.rulebase, hack/deploy-image.sh
add support for multiline crio for rsyslog
also add the rsyslog nodeSelector to the cr
set maxMessageSize 32767; do not report oversize messages
fix json-file regex to match in middle of string
remove unused rule
=> add support for multiline crio for rsyslog

manifests/03-role.yaml, pkg/k8shandler/visualization.go, pkg/utils/utils.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662397
Will require OLM role update (cc @jcantrill)
=> Create role and cluster role binding for reading sharing-config cm

pkg/apis/logging/v1alpha1/types.go, pkg/k8shandler/collection.go, pkg/k8shandler/visualization.go
Addresses https://jira.coreos.com/browse/LOG-318
=> Updating fluentd and rsyslog ds to tolerate noschedule taint for masters

pkg/k8shandler/logstore.go
Noticed this gap while trying to recreate https://bugzilla.redhat.com/show_bug.cgi?id=1664497
=> Adding check if redundancy policy has changed

pkg/k8shandler/certificates.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go, pkg/utils/utils.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1665378
/hold
=> Updating secrets for components if they need to be in case of regenerated certs

README.md, docs/configuration.md
This PR provides documentation on configuring cluster logging and the cluster logging operator
=> Configuration documentation

pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go, pkg/utils/types.go, pkg/utils/utils.go
Resolves https://jira.coreos.com/browse/LOG-321
=> Removing components when not specified in the CR

Dockerfile, Dockerfile.rhel7, Makefile, README.md, docs/unmanaged_configuration.md, hack/common, hack/test-e2e.sh, manifests/05-deployment.yaml, pkg/k8shandler/collection.go, pkg/k8shandler/visualization.go, pkg/utils/types.go, pkg/utils/utils.go, test/e2e/clusterlogging_test.go, test/e2e/utils.go
=> fix e2e-test for ci

pkg/k8shandler/visualization.go, pkg/stub/handler.go, pkg/utils/types.go, pkg/utils/utils.go
To address https://bugzilla.redhat.com/show_bug.cgi?id=1667315
=> Updating to only create if in managed state

pkg/k8shandler/certificates.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go, pkg/utils/utils.go
and update oauthclient if necessary
Fixes issue seen by Jeff
=> Persisting oauth secret to prevent unnecessary regen

hack/deploy-setup.sh, pkg/k8shandler/collection.go, pkg/utils/utils.go
Part of fix for https://bugzilla.redhat.com/show_bug.cgi?id=1672772
=> updating to use a single collector SA

hack/test-e2e.sh
use sa logcollector instead of separate for fluentd and rsyslog
=> use sa logcollector instead of separate for fluentd and rsyslog

docs/configuration.md
=> update config docs to include nodeSelector

pkg/k8shandler/logstore.go
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1671276
=> Fixing setting of node resources in ES CR

Makefile, pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go
Addresses:
* https://bugzilla.redhat.com/show_bug.cgi?id=1684376
Added unit tests to verify
=> Bug 1684376 - Adding check for difference in node count and resources for log store

scripts/cert_generation.sh
addresses https://bugzilla.redhat.com/show_bug.cgi?id=1684332 issue for 4.0
=> updating dns name generation for certs and updating hash alg

scripts/cert_generation.sh
Should address https://bugzilla.redhat.com/show_bug.cgi?id=1679841 for 4.0
=> increasing keysize to 4096 from 2048

OWNERS
=> update owner list

hack/cr-aws.yaml, hack/cr.yaml, pkg/k8shandler/curation.go, pkg/k8shandler/curation_test.go, pkg/k8shandler/logstore.go
Adding tests to verify as well
=> Expanding and adding default cronjob schedule

pkg/utils/types.go
This field will be required in 4.x
@jcantrill
=> Update OAuthClient to include GrantMethod

docs/configuration.md
Signed-off-by: Harpreet Kaur <harpreetkaur11139@gmail.com>
=> docs: Fix typo in docs/configuration.md

Dockerfile
This PR removes the CLO from the CVO build pipeline
cc @bparees
=> remove release operator label

pkg/apis/logging/v1alpha1/adapter.go, pkg/k8shandler/certificates.go, pkg/k8shandler/collection.go, pkg/k8shandler/collection_test.go, pkg/k8shandler/curation.go, pkg/k8shandler/curation_test.go, pkg/k8shandler/logging.go, pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go, pkg/k8shandler/status.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go, pkg/stub/handler.go, pkg/utils/factory.go, pkg/utils/utils.go
This change is to propose address https://jira.coreos.com/browse/LOG-357:
* introduction of a local struct to allow use of attaching methods
* Add code style based on golang conventions
* Improve readability and promote code reuse
=> refactor to introduce local struct

Dockerfile, Dockerfile.rhel7, controller-manifests/cluster-logging.package.yaml, controller-manifests/cluster-logging.v4.1.0.clusterserviceversion.yaml, controller-manifests/cluster-loggings.crd.yaml
This adds manifest dir for use by Marketplace
=> add manifest and update dockerfile for marketplace

pkg/k8shandler/curation.go, pkg/k8shandler/curation_test.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, pkg/k8shandler/logstore_test.go, pkg/k8shandler/rsyslog.go, pkg/k8shandler/rsyslog_test.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go, pkg/utils/pod.go
This bug fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1691444
By adding node selectors for the operands
Last commit is the only one of interest
=> 1691444 node selectors

files/rsyslog/65-viaq-formatting.conf, files/rsyslog/rsyslog.sh
rsyslog - allow disable of MERGE_JSON_LOG
=> rsyslog - allow disable of MERGE_JSON_LOG

pkg/k8shandler/curation_test.go, pkg/k8shandler/logging.go, pkg/k8shandler/logstore_test.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go, pkg/runtime/runtime.go
fix https://bugzilla.redhat.com/show_bug.cgi?id=1666674 for 4.x
=> 1666674 for 4x

pkg/utils/daemonset.go, pkg/utils/daemonset_test.go
fix https://bugzilla.redhat.com/show_bug.cgi?id=1688176 by using default
=> fix 1688176. Use the minreadyseconds default for daemonsets

pkg/k8shandler/visualization.go
This PR fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1693957 by partially reverting https://bugzilla.redhat.com/show_bug.cgi?id=1666674
=> bug 1693957. Partial revert of 1666674

Gopkg.lock, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go, pkg/k8shandler/rsyslog.go, pkg/k8shandler/visualization.go, pkg/utils/utils.go, vendor/github.com/openshift/elasticsearch-operator/pkg/apis/elasticsearch/v1/types.go, vendor/github.com/openshift/elasticsearch-operator/pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go, vendor/github.com/openshift/elasticsearch-operator/pkg/k8shandler/common.go, vendor/github.com/openshift/elasticsearch-operator/pkg/k8shandler/deployment.go, vendor/github.com/openshift/elasticsearch-operator/pkg/k8shandler/statefulset.go, vendor/github.com/openshift/elasticsearch-operator/pkg/k8shandler/util.go, vendor/github.com/openshift/elasticsearch-operator/pkg/k8shandler/util_test.go, vendor/golang.org/x/tools/internal/lsp/cache/view.go, vendor/golang.org/x/tools/internal/lsp/cmd/cmd.go, vendor/golang.org/x/tools/internal/lsp/diagnostics.go, vendor/golang.org/x/tools/internal/lsp/lsp_test.go, vendor/golang.org/x/tools/internal/lsp/server.go
Updating components to check for nodeselector change
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1694097
This must go after https://github.com/openshift/elasticsearch-operator/pull/114 and requires a `dep` update
=> Bug 1694097 - Check if nodeselectors have changed

pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/visualization.go, pkg/utils/resources.go
Adding checks for the different logging components to check if their resources have changed, warranting a rollout.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1695494
=> Bug 1695494 - Adding resource checks to all components

README.md, hack/common
goes with https://github.com/openshift/elasticsearch-operator/pull/125
=> the repo for use with UBI has moved

Dockerfile, Dockerfile.rhel7
Fix the package name in the manifest which is required by OLM CI build
=> fix name of file being copied in the manifest

manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml, manifests/4.1/image-references
Add oauth-proxy to the imagestream manifest
=> add oauth-proxy to imagestream manifest

hack/test-e2e.sh, manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml, test/e2e/clusterlogging_test.go
making sure fluentd tests run and fixing so that fluentd is correctly installed
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1709454
=> Bug 1709454: fixing missing RBAC for metadata-reader cluster role

manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml, manifests/4.2/cluster-loggings.crd.yaml, manifests/4.2/image-references, manifests/cluster-logging.package.yaml, manifests/latest
Should help https://github.com/openshift/cluster-logging-operator/pull/176 CI tests to pass
=> preparation for 4.2 merging into master

hack/deploy.sh, hack/test-e2e.sh
=> add support for passing in the elasticsearch-operator image

pkg/k8shandler/visualization.go
Getting rid of word "Invalid". This can look like an issue while
this is just a standard message about change in configuration that
is going to be aligned automatically.
=> Update log message wording

README.md
=> minor doc fixes

pkg/k8shandler/curation_test.go, pkg/k8shandler/pod.go, pkg/k8shandler/pod_test.go, pkg/k8shandler/visualization_test.go, pkg/utils/utils.go
See [LOG-411](https://jira.coreos.com/browse/LOG-411)
=> Force all CL components to be allocated to linux nodes

manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml, manifests/art.yaml, manifests/cluster-logging.package.yaml
This PR bumps CRV to 4.1.2 and adds art.yml file for future automation
=> bug 1717627. bump crv to 4.1.2

manifests/art.yaml
Fix art.yaml to point to the correct package file.
=> Bug 1717627: fix art.yml ref to package.yaml

manifests/art.yaml
Need to update the CSV name in the art.yaml file to match the actual name in the package file and the CSV name.
=> Bug 1717627: Update replacement search text to match csv name in art.yaml

files/rsyslog/65-viaq-formatting.conf, files/rsyslog/67-mmexternal.conf, files/rsyslog/parse_json_skip_empty.rulebase, files/rsyslog/rsyslog.sh
Exacuting undefined_field in the mmexternal plugin.
Depending on https://github.com/openshift/origin-aggregated-logging/pull/1671
=> LOG-372 - rsyslog - support improved undefined field handling

files/rsyslog/65-viaq-formatting.conf
should be `systemd.t.STREAM_ID` and
`systemd.t.SYSTEMD_INVOCATION_ID`
=> rsyslog - fix field names

files/rsyslog/65-viaq-formatting.conf, files/rsyslog/67-mmexternal.conf, files/rsyslog/rsyslog.sh
- Prioritizing mmnormalize/parse_json_skip_empty over mmexternal
- Removing stream field.
=> rsyslog configuration

pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go
When scaling up from 3 to 4 nodes the CLO was not preserving UUIDs that were generated and populated in the ElasticsearchCR by the EO resulting in an error message that the previously known UUID was removed.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1712721
=> Bug 1712721 - Ensure we preserve GenUUID for nodes when doing diffs

cmd/manager/main.go, pkg/k8shandler/clusterloggingrequest.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/curation_test.go, pkg/k8shandler/fluentd_test.go, pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go, pkg/k8shandler/oauthclient.go, pkg/k8shandler/oauthclient_test.go, pkg/k8shandler/rsyslog_test.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1724053
The reconcile process of updating oauthclient should GET a cluster level resource, not namespaced
=> Bug 1724053. Retrieve oauthclient as a cluster resource

pkg/k8shandler/fluentd.go, pkg/k8shandler/rsyslog.go
fluentd, rsyslog - Shorten the TerminationGracePeriod from 30 sec to 10 sec.
Sleep for the duration to wait for the collector pod is deleted,
then delete secret and service account.
=> Bug 1715370: Some orphaned logs sent to .operations.* index by mistake.

pkg/controller/clusterlogging/clusterlogging_controller.go
Allow configuration of logrus loglevel via env var
cc @richm @VladMasarik
=> Allow configuration of logrus loglevel via env var

files/rsyslog/rsyslog.sh, pkg/k8shandler/collection.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/rsyslog.go
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1746968 by moving the value to a downward API
=> Bug 1746968: Remove hostpath mount /etc/hostname and pass via env var

Gopkg.lock, vendor/github.com/openshift/elasticsearch-operator/hack/test-e2e.sh, vendor/github.com/openshift/elasticsearch-operator/manifests/elasticsearch-operator.package.yaml
vendored manifest was still pointed to 4.3
=> update vendored ES to 4.3

manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
fix #248 . bump skip range to 4.2 to 4.3
=> fix #248.  Set skip range to 4.2-4.3

manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1765261
=> Bug 1765261: Set minKubeVersion

hack/test-e2e.sh, hack/testing/test-020-olm-upgrade.sh
Skipping upgrade test for now until we can figure out why its failing
=> fix e2e tests and skip upgrade test for now

hack/lib/util/logs.sh, hack/test-e2e.sh
This adds a small script that gathers the fluentd logs from the nodes.
=> Gather fluentd logs in e2e runs

hack/common
1) use right version of repo file - look for all applicable versions
2) repo file location was moved
3) repo file format for certs/keys was changed
=> fix image building for devs

manifests/4.3/image-references
https://bugzilla.redhat.com/show_bug.cgi?id=1769005
=> Bug 1769005: Fix promtail image reference 

Dockerfile, Makefile, pkg/utils/utils.go
Asked to make the dir more obvious via chat in slack and discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1768042#c8
=> move the temp workdir as discussed for 1768042

cmd/manager/main.go, manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml, pkg/k8shandler/consoleexternalloglink.go, pkg/k8shandler/visualization.go
See https://jira.coreos.com/browse/LOG-452
=> Fix pods log link

hack/undeploy.sh, manifests/4.3/cluster-loggings.crd.yaml, manifests/4.3/collectors.crd.yaml, manifests/4.3/logforwardings.crd.yaml, pkg/controller/forwarding/forwarding_controller.go, pkg/k8shandler/reconciler.go
Enable CR status so operator can use status client
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1768688
=> Bug 1768688: Enable status for CRDs

hack/testing/utils, pkg/k8shandler/clusterloggingrequest.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go
Use the Status client since we should only update the status of a customresource
=> update status of clusterlogging using the status client

hack/deploy-eo.sh, hack/deploy.sh, hack/testing/utils, hack/vendor/olm-test-script/e2e-olm.sh
Remove the deploy dependency on test framework.  cc @richm
=> fix up deploy to not depend on bash test lib

pkg/apis/logging/v1alpha1/forwarding_types.go, pkg/controller/forwarding/forwarding_controller.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/forwarding_test.go, test/helpers/elasticsearch.go, test/helpers/fluentd.go, test/helpers/framework.go
Use the shared_key defined in the secret for fluent forward. Ref:
https://bugzilla.redhat.com/show_bug.cgi?id=1771813
=> Bug 1771813: Add shared_key from secret

manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml, pkg/apis/logging/v1alpha1/forwarding_types.go
Found discrepancy while reviewing documentation
=> correct pipeline inputSource

hack/common, hack/deploy-image.sh, hack/test-e2e.sh, hack/testing/assertions, hack/testing/test-020-olm-upgrade.sh, hack/testing/test-367-logforwarding.sh, hack/testing/utils
Attempt to reenable upgrade test
cc @shawn-hurley
=> enable upgrade test

hack/testing/assertions, hack/testing/test-020-olm-upgrade.sh, hack/testing/test-367-logforwarding.sh, hack/testing/utils, test/e2e/logforwarding/fluent/forward_to_fluent_test.go, test/helpers/framework.go
Fix LogForwarding timing issue and other minor test fixes
cc @ewolinetz @igor-karpukhin  I discovered an issue of sysctl setting not being applied by the node-tuning-operator but I'm hoping its not a larger issue and just the cluster I stood up.  Bumping the timing here as previously only gave ES 2minutes to come up
We should run this a couple of times if it works
=> fix lf timing issue

manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
Revert CSV changes from https://github.com/openshift/cluster-logging-operator/pull/312
=> Revert csv

manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1766343
Backport of 4.3
=>  Bug 1766343: Set the correct minKubeVersion for 4.2+ 

hack/testing/test-367-logforwarding.sh, pkg/logger/logger.go, test/e2e/logforwarding/cleanup.sh, test/helpers/clusterlogging.go, test/helpers/elasticsearch.go, test/helpers/framework.go
pick up changes from 4.3 branch
ref: #313
=> Allow logforwarding tests to cleanup from go invocation

hack/test-e2e.sh, hack/testing/test-010-deploy-via-olm-minimal.sh, hack/testing/test-020-olm-upgrade.sh, hack/testing/utils, manifests/4.3/0100_clusterroles.yaml, manifests/4.3/0110_clusterrolebindings.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1774864
=> Bug 1774864: Enable metrics for collector when LF enabled

hack/common
login_to_registry has to use a username/token to login to docker
=> fix deploy-image - add back login_to_registry

hack/test-e2e.sh, hack/testing/test-010-deploy-via-olm-minimal.sh, hack/testing/test-020-olm-upgrade.sh, hack/testing/utils, manifests/4.3/0100_clusterroles.yaml, manifests/4.3/0110_clusterrolebindings.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1776533
backport of https://github.com/openshift/cluster-logging-operator/pull/304
=> Bug 1776533: Enable metrics for collector when LF enabled

hack/vendor/olm-test-script/operatorgroup-template-global.yaml, hack/vendor/olm-test-script/operatorgroup-template.yaml, pkg/generators/forwarding/factory.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding.go, test/e2e/logforwarding/cleanup.sh, test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go, test/e2e/logforwarding/fluentlegacy/logforwarding_suite_test.go, test/files/secure-forward.conf
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1782566
=> Bug 1782566. Allow legacy secure-forward regardless of LogForward being enabled

hack/vendor/olm-test-script/operatorgroup-template-global.yaml, hack/vendor/olm-test-script/operatorgroup-template.yaml, pkg/generators/forwarding/factory.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding.go, test/e2e/logforwarding/cleanup.sh, test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go, test/e2e/logforwarding/fluentlegacy/logforwarding_suite_test.go, test/files/secure-forward.conf
Pull in latest from master to unblock https://github.com/openshift/release/pull/6442
=> Update6x to master

pkg/k8shandler/reconciler.go, pkg/utils/utils.go
Fixed missing error when requesting a proxy object for CLO. Minor refactoring.
=> Fixed missing error when requesting proxy

manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
Updated 4.4 cluster service version alm-exmple to incude retentionPolicy
=> Update alm-exmpla to include retentionPolicy

pkg/apis/logging/v1/clusterlogging_types.go, pkg/controller/clusterlogging/clusterlogging_controller.go, pkg/controller/collector/collector_controller.go, pkg/controller/forwarding/forwarding_controller.go, pkg/controller/proxyconfig/proxyconfig_controller.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/logstore.go, pkg/k8shandler/promtail.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/status.go, pkg/k8shandler/trustedcabundle.go, pkg/k8shandler/visualization.go, pkg/utils/utils.go, test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go, test/e2e/logforwarding/fluent/forward_to_fluent_test.go, test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go, test/e2e/utils.go, test/helpers/elasticsearch.go, test/helpers/framework.go
Code cleanup according to `golangci-lint` output:
* Removed unused entities
* Fixed missed error handlers
* Fixed variables declarations
=> Code cleanup

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go, scripts/cert_generation.sh
This PR resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1791336
=> Bug 1791336: Fix fluent metrics config to support ipv6

README.md, docs/fedora31.md
Signed-off-by: Alan Conway <aconway@redhat.com>
=> README update for Fedora 31 docker issues.

hack/deploy-image.sh
On slow networks wait time of 10 sec is less, increase to 30sec.
=> hack/deploy-image.sh : Increase wait time for port forwarding

hack/testing/test-999-fluentd-prometheus-metrics.sh, hack/testing/utils, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go
Additional fix to https://bugzilla.redhat.com/show_bug.cgi?id=1791336 to supersede https://github.com/openshift/cluster-logging-operator/pull/333
=> Bug 1791336: Fix fluent conf for metrics on ipv4 and ipv6

files/fluentd/run.sh, pkg/constants/constants.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/source.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go
Write fluent logs to stdout
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1796133
=> Bug 1796133: Exclude fluent/elasticsearch pod from log collection and write logs to STDOUT

pkg/controller/add_controllers.go, pkg/controller/kibanasecret/kibanasecret_controller.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/route.go, pkg/k8shandler/visualization.go
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1781492
@igor-karpukhin fyi this impacts your kibana CLO -> EO migration work
=> Bug 1781492: Updating so Kibana properly handles cert redeploys

pkg/k8shandler/consoleexternalloglink.go, pkg/k8shandler/visualization.go
<s>Instruct Kibana UI to use the .all index-pattern when displaying
logs from the pod.</s>
=> Bug 1776636: Provide external log link for pod

manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1799051
=> Bug 1799051: Add OLM annotations for ui hints

manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
this makes it so the ART substitution will actually find/replace this value: https://github.com/openshift/cluster-logging-operator/blob/master/manifests/art.yaml#L10
=> fix up the upgrade skip range

files/fluentd/run.sh, pkg/generators/forwarding/factory.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/certificates.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding.go, test/e2e/logforwarding/syslog/deleteme.go, test/e2e/logforwarding/syslog/syslog_cert_generation.sh, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go, test/e2e/logforwarding/sysloglegacy/logforwarding_suite_test.go, test/helpers/syslog.go
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1799024
@ahadas had to steal some of #356 to resolve this bug.
=> Bug 1799024: Enable legacy syslog support

files/fluentd/run.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1789076
Backport to 4.3
=> Bug 1789076:  Get ipv6 address during run.sh

manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1804166
=> Bug 1804166: Update minKubeVersion for 4.4

hack/testing/test-999-fluentd-prometheus-metrics.sh, hack/testing/utils, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go, scripts/cert_generation.sh
Bug 1794382: Fix fluent conf for metrics on ipv4 and ipv6
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1794382
backport of https://github.com/openshift/cluster-logging-operator/pull/333 and https://github.com/openshift/cluster-logging-operator/pull/345
=>  Bug 1794382: Fix fluent conf for metrics on ipv4 and ipv6

pkg/constants/constants.go, pkg/controller/add_controllers.go, pkg/controller/trustedcabundle/trustedcabundle_controller.go, pkg/k8shandler/collection.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/secret.go, pkg/k8shandler/trustedcabundle.go, pkg/k8shandler/visualization.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1800308
=> Bug 1800308: Updating to require trustbundle configmap

Makefile, hack/testing/assertions, hack/testing/test-010-deploy-via-olm-minimal.sh, hack/testing/test-020-olm-upgrade.sh, hack/testing/test-367-logforwarding.sh, hack/testing/test-999-fluentd-prometheus-metrics.sh, hack/testing/utils, manifests/4.4/0110_clusterrolebindings.yaml, manifests/4.4/0200_roles.yaml, manifests/4.4/0210_rolebindings.yaml, pkg/k8shandler/configmap.go, pkg/k8shandler/consoleexternalloglink.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1803196
=> Bug 1803196: Move shared config map to openshift-config-managed NS

manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1804169
=> Bug 1804169: set minKube version for 4.3

hack/build-image.sh, hack/common, hack/deploy.sh, hack/testing/test-010-deploy-via-olm-minimal.sh, hack/testing/test-020-olm-upgrade.sh, hack/testing/test-367-logforwarding.sh, hack/testing/test-999-fluentd-prometheus-metrics.sh
This PR removes all remaining `set -x` trails in this repository since obscures test logs and considered harmful.
=> Drop xtrace verbosity

Makefile
E2E test will use a local image for local testing
=> Added E2E-local target

manifests/4.5/image-references
This PR fixes image-references to point to es6
=> fix image-references to point to es6

pkg/apis/logging/v1alpha1/forwarding_types.go
Fix string "Secet" in "Secret"
=> Bug 1803390: Fix typo in OutputConditionType

files/fluentd/run.sh
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1808053#c3
=> Bug 1808053: Grab only public IPv6 fluentd address from node

pkg/k8shandler/collection.go, pkg/k8shandler/reconciler.go
This PR cleans up some inconsistencies in collector reconciliation
=> minor updates to collector reconciliation

pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, pkg/utils/resources.go, pkg/utils/resources_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1813810
=> Bug 1813810: Updating resource update policy and adding unit test to verify

hack/testing/test-010-deploy-via-olm-minimal.sh, hack/testing/test-020-olm-upgrade.sh, hack/testing/test-367-logforwarding.sh, hack/testing/test-999-fluentd-prometheus-metrics.sh, hack/testing/utils, pkg/k8shandler/logstore.go
This PR attempts to normalize the artifact directories so artifacts are separated by test
=> normalize artifact dirs to write to separate places

Dockerfile.e2e, Makefile, hack/test-e2e-olm.sh, hack/testing-olm/assertions, hack/testing-olm/test-010-deploy-via-olm-minimal.sh, hack/testing-olm/test-020-olm-upgrade.sh, hack/testing-olm/test-367-logforwarding.sh, hack/testing-olm/test-999-fluentd-prometheus-metrics.sh, hack/testing-olm/utils, olm_deploy/operatorregistry/Dockerfile, olm_deploy/operatorregistry/catalog-source.yaml, olm_deploy/operatorregistry/registry-deployment.yaml, olm_deploy/operatorregistry/service.yaml, olm_deploy/scripts/catalog-build.sh, olm_deploy/scripts/catalog-deploy.sh, olm_deploy/scripts/catalog-uninstall.sh, olm_deploy/scripts/operator-install.sh, olm_deploy/scripts/operator-uninstall.sh, olm_deploy/scripts/registry-init.sh, olm_deploy/scripts/wait_for_deployment.sh, olm_deploy/subscription/operator-group.yaml, olm_deploy/subscription/subscription.yaml
also adds e2e based on olm deployment
also leverages elasticsearch's olm deployment flow
=> add olm based deploy scripts for cluster logging operator

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1810710
backport of https://github.com/openshift/cluster-logging-operator/pull/394
@bparees
=> Bug 1810710: Make useable by buildah

deploy/crds/logging.openshift.io_clusterloggings_crd.yaml, manifests/4.5/cluster-loggings.crd.yaml, pkg/apis/logging/v1/clusterlogging_types.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/indexmanagement/index_management.go, test/helpers/elasticsearch.go
This PR further address https://github.com/openshift/enhancements/pull/261 and changes to remove dots from indexmanagement names
=> remove dots in index management types

hack/testing/test-050-collection.sh, hack/testing/test-367-logforwarding.sh, hack/testing/utils, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/collection/fluentd/flatten_labels_test.go, test/e2e/collection/fluentd/fluentd_suite_test.go, test/e2e/logforwarding/cleanup.sh, test/helpers/clusterlogging.go, test/helpers/elasticsearch.go, test/helpers/fluentd.go, test/helpers/framework.go, test/helpers/syslog.go
This PR flattens labels into array of key/value pairs to avoid key field explosion in ES
Ref: https://issues.redhat.com/browse/LOG-448
=> LOG-448 Convert pod labels to array of key=value

test/helpers/framework.go
Signed-off-by: Alan Conway <aconway@redhat.com>
=> Fix minor lint error.

hack/get-operator-sdk.sh
Signed-off-by: Alan Conway <aconway@redhat.com>
=> File missing from previous merge: hack/get-operator-sdk.sh

pkg/controller/add_controllers.go, pkg/controller/kibanasecret/kibanasecret_controller.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/route.go, pkg/k8shandler/visualization.go
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/351
To address: 
* https://bugzilla.redhat.com/show_bug.cgi?id=1822152
* https://bugzilla.redhat.com/show_bug.cgi?id=1822083
Dependent on https://github.com/openshift/cluster-logging-operator/pull/441 to fix failing tests
=> [release-4.3] Bug 1822152: Updating so Kibana properly handles cert redeploys

olm_deploy/operatorregistry/Dockerfile
Update dockerfile to get registry Binary from bin
=> Update dockerfile to get registry Binary from bin

.dockerignore, Makefile, hack/deploy-eo.sh, hack/deploy-image.sh, olm_deploy/scripts/catalog-build.sh
fix up make deploy to use catalog
=> fix up make deploy to use catalog

hack/build-image.sh, hack/common, hack/deploy-image.sh
Fix make deploy on a 4.4 for dev experience
=> fix make deploy for 4.4

Dockerfile
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1825275
=> Bug 1825275: Make useable by buildah

hack/testing-olm/assertions, pkg/k8shandler/visualization.go
Kibana CR generated by the CLO renamed from **instance** to **kibana**
=> Bug 1833142: Renamed kibana CR instance

pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
To address: 
- https://bugzilla.redhat.com/show_bug.cgi?id=1832662
- https://bugzilla.redhat.com/show_bug.cgi?id=1832652
=> Bug 1832662: Add resources, nodeselector and tolerations to KibanaCR

pkg/k8shandler/defaults.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
To address missing proxy resource reconcilation to Kibana CR:
https://bugzilla.redhat.com/show_bug.cgi?id=1832662
=> Bug 1832662: Add proxy resources to KibanaCR

hack/cr_invalid.yaml, hack/testing-olm/test-010-deploy-via-olm-minimal.sh, manifests/4.5/cluster-loggings.crd.yaml, pkg/controller/clusterlogging/clusterlogging_controller.go
Ensure that the metadata name is always `instance` using validation spec
=> Bug 1835268: validate metadata name in crd

test/e2e/logforwarding/syslog/forward_to_syslog_test.go
Temporarily disabling syslog tests to let syslog plugin changes get merged.
=> syslog LF : temporarily disable syslog tests

deploy/crds/logging.openshift.io_clusterloggings_crd.yaml, deploy/crds/logging.openshift.io_collectors_crd.yaml, pkg/k8shandler/collection_test.go, test/helpers/oc/exec_test.go, test/helpers/oc/get_test.go, test/helpers/oc/literal_test.go, test/helpers/oc/runner.go
Also fixed mis-formatted files and updated generated CRDs.
=> Fix lint errors (ignored return values)

pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
Fixed nil pointer error when removing Kibana CR
=> Bug 1836451: Fix for removing Kibana CR

pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1837253
=> Bug 1837253: Fix kibana proxy resource reconciliation

deploy/crds/logging.openshift.io_logforwardings_crd.yaml, manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml, manifests/4.5/logforwardings.crd.yaml, pkg/apis/logging/v1alpha1/forwarding_types.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/indexmanagement/index_management.go
To fix : https://bugzilla.redhat.com/show_bug.cgi?id=1833268
=> Bug 1833268: revert logs-* aliases to logs.*

cmd/manager/main.go
Removed duplicate configv1.AddToScheme()
=> Removed duplicate configv1.AddToScheme

pkg/constants/constants.go, pkg/k8shandler/certificates.go, pkg/k8shandler/certificates_test.go, pkg/utils/utils.go, test/helpers/framework.go
This PR extends the unit test coverage for the entire CLO certificate generation.
=> Add test for certificate generation

manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml, manifests/art.yaml
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1845539
Needs backport: release-4.5
=> Bug 1845539: Update skipRange constraint to 4.4.0

manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml, manifests/art.yaml
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1845539
**Needs backport:** release-4.5
=> Bug 1845539: Update olm.skipRange constraint to 4.4.0-0

pkg/k8shandler/collection.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, pkg/k8shandler/forwarding.go, test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go, test/e2e/logforwarding/fluent/forward_to_fluent_test.go, test/e2e/logforwarding/syslog/forward_to_syslog_test.go
blocked by https://github.com/openshift/origin-aggregated-logging/pull/1897
To address https://bugzilla.redhat.com/show_bug.cgi?id=1840274
=> Bug 1840274: creating init container to block waiting for es version 6+

manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1848186
**Needs backport:** release-4.5
=> Bug 1848186: Fix retention policy in CSV alm example manifest

hack/testing-olm/test-030-collection.sh, pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, test/e2e/collection/cleanup.sh, test/e2e/collection/fluentd/collector_only_test.go, test/e2e/collection/fluentd/flatten_labels_test.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1849188
**Needs backport:** release-4.5
=> Bug 1849188: Allow a collection only clusterlogging instance

manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
fix the upperbound of the skip range to be 4.6
=> fix the skip.range for 4.6

Makefile, hack/testing-olm/test-367-logforwarding.sh, manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/output_types.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/syslog_conf.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/collection/fluentd/collector_only_test.go, test/e2e/logforwarding/cleanup.sh, test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go, test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go, test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go, test/e2e/logforwarding/multiple_outputs/forward_to_multiple_outputs_test.go, test/e2e/logforwarding/syslog/forward_to_syslog_test.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go, test/helpers/framework.go, test/helpers/kafka.go, test/helpers/oc/runner.go, test/helpers/syslog.go
- updated template for new syslog parameters
- added test cases
Fixed LogForwarding artifacts collection
=> Update LF GA api for syslog rfc5424 parameters

go.mod, go.sum, manifests/4.6/logging.openshift.io_clusterloggings_crd.yaml, pkg/apis/logging/v1/clusterlogging_types.go, pkg/apis/logging/v1/zz_generated.deepcopy.go, pkg/k8shandler/defaults.go, pkg/k8shandler/logstore.go, pkg/k8shandler/logstore_test.go, test/helpers/clusterlogging.go, test/helpers/elasticsearch.go, vendor/github.com/openshift/elasticsearch-operator/pkg/apis/logging/v1/elasticsearch_types.go, vendor/github.com/openshift/elasticsearch-operator/pkg/apis/logging/v1/zz_generated.deepcopy.go, vendor/github.com/openshift/elasticsearch-operator/pkg/elasticsearch/client.go, vendor/github.com/openshift/elasticsearch-operator/pkg/utils/utils.go, vendor/github.com/openshift/elasticsearch-operator/test/utils/utils.go, vendor/modules.txt
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1856502
=> Bug 1856502: Added Elasticsearch proxy resources

hack/testing-olm/test-367-logforwarding.sh
Clean up buffers and position files between tests to attempt to make LF tests more repeatable
cc @periklis @vimalk78
=> cleanup fluent buffers and position files

olm_deploy/scripts/operator-install.sh, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/syslog_conf.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/logforwarding/syslog/forward_to_syslog_test.go
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1858811
/cc: @jcantrill @alanconway
=> Bug 1858811: syslog fixed support for tls protocol

files/fluentd/run.sh
This PR:
* cleans up fluent run.sh to remove code that is no longer used
Ref: https://issues.redhat.com/browse/LOG-668
=> LOG-668: Remove unused code in fluent run.sh

manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
This reverts commit 942711756f335c1dfdc9013ad4bad746f5e79720, reversing changes made to db722fe6879309b5263006c9e465fc5aa80937ea.
=> Bug 1852889: Revert "Merge pull request #608 from periklis/revert-minkubeversion-1-18-3"

pkg/k8shandler/fluentd.go
This PR provides an exhaustive description why the fluentd init container is bound to LogFowarding and/or a ClusterLogging logStore stanza.
Proof why needed: https://coreos.slack.com/archives/CB3HXM2QK/p1593617729192400
/cc @ewolinetz
=> Provide an exhaustive desciption for fluentd init container

Makefile, pkg/generators/forwarding/fluentd/output_fluentd_buffer.go, pkg/k8shandler/defaults.go, pkg/k8shandler/fluentd.go
=> Fix lint errors, refuse to build unlinted code.

files/fluentd/run.sh, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go, test/files/secure-forward.conf
This PR:
* Pulls in several changes in 4.6 to be compatible with 4.5 to address Performance changes related to 4.4
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1843461
=> Bug 1843461: Collector config changes to address performance versus 4.4

go.mod, pkg/apis/logging/v1/cluster_log_forwarder.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/source.go, pkg/k8shandler/forwarding.go
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1857673
/cc @jcantrill @alanconway
=> Bug 1857673: Fixed fluentd conf generation, namespace filtering

files/dashboards/openshift-logging-dashboard.json, manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml, pkg/k8shandler/dashboards.go, pkg/k8shandler/reconciler.go
This PR adds a new metrics dashboard called Openshift Logging
/cc @ewolinetz @lukas-vlcek
=> LOG-804: add metrics dashboard

Makefile, bundle/bundle.Dockerfile, bundle/manifests/0100_clusterroles.yaml, bundle/manifests/0110_clusterrolebindings.yaml, bundle/manifests/cluster-logging.v4.6.0.clusterserviceversion.yaml, bundle/manifests/crd-v1-singleton-patch.yaml, bundle/manifests/crd-v1beta1-clusterloggings-patches.yaml, bundle/manifests/image-references, bundle/manifests/kustomization.yaml, bundle/manifests/logforwardings.crd.yaml, bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml, bundle/metadata/annotations.yaml
Generated using `make generate-bundle`
To address changes required as part of https://issues.redhat.com/browse/OLM-1810
=> Updating CLO to use operator bundle

manifests/4.6/logforwardings.crd.yaml, manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/cluster_log_forwarder_types.go, pkg/apis/logging/v1/zz_generated.deepcopy.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_suite_test.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/generators/forwarding/fluentd/source.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding_test.go, test/e2e/logforwarding/fluent/forward_to_fluent_test.go, test/helpers/elasticsearch.go, test/helpers/fluentd.go, test/helpers/framework.go, test/helpers/kafka.go, test/helpers/syslog.go, test/helpers/types.go
Added cluster-wide tags for LogForwarding
=> LOG-825: Added cluster wide tags

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_legacy_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go
This PR:
* fixes warnings in the collector config which elude to config being dropped
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1866537
=> Bug 1866537: Fix collector config warnings

Makefile, internal/cmd/forwarder-generator/main.go, pkg/k8shandler/certificates.go, pkg/k8shandler/certificates_test.go, pkg/k8shandler/clusterloggingrequest.go, pkg/k8shandler/collection.go, pkg/k8shandler/collection_test.go, pkg/k8shandler/configmap.go, pkg/k8shandler/consoleexternalloglink.go, pkg/k8shandler/cronjob.go, pkg/k8shandler/curation.go, pkg/k8shandler/daemonset.go, pkg/k8shandler/deployment.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/forwarding_test.go, pkg/k8shandler/logstore.go, pkg/k8shandler/oauthclient.go, pkg/k8shandler/prometheus_rule.go, pkg/k8shandler/rbac.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/route.go, pkg/k8shandler/secret.go, pkg/k8shandler/secret_test.go, pkg/k8shandler/service.go, pkg/k8shandler/service_monitor.go, pkg/k8shandler/serviceaccount.go, pkg/k8shandler/trustedcabundle.go, pkg/k8shandler/visualization.go, pkg/k8shandler/visualization_test.go
This PR:
* Adds a development command to generate fluent config from the CLI
=> Add development command to generate logforwarder configuration

Makefile, hack/collector-only-45.yaml, hack/collector-only.yaml, hack/logforwarding.yml, hack/svt/README.md, hack/svt/test-svt.sh
This PR
* Adds a script to run SVT workload to verify log throughput performance
* Updates the makefile
This test will allow us to verify no regressions are introduces when  swapping around configuration or component deployment
Ref: https://issues.redhat.com/browse/LOG-831
=> LOG-831. Add scripts to run SVT workload

hack/testing-olm/test-367-logforwarding.sh, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/collection/fluentd/namespace_filtering_test.go, test/helpers/framework.go
- Cleaned up fluend buffers after test case
- Run cleanup.sh script to collect artifacts only if test case fails
fixes: https://issues.redhat.com/browse/LOG-914
=> LOG-914: CI test Improvements

.gitignore, Dockerfile, Dockerfile.patch, Makefile, art.repo
This PR reverts changes to the Dockerfile when developing locally
cc @periklis @blockloop @alanconway 
I'm still working on how to make it work with ART rpm repo
=> Modify make image to allow local builds

bundle/bundle.Dockerfile
Updating bundle labels per:
* https://docs.engineering.redhat.com/display/CFC/Migration
=> updating bundle labels to be used for nightly

Makefile, pkg/k8shandler/collection.go, pkg/k8shandler/collection_test.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/status.go
This PR:
* Modifies status creation to reduce the status updates and noise in the logs
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1877968
=> Bug 1877968: Reduce the chattiness of status updates and reconciliation

pkg/generators/forwarding/fluentd/source.go, pkg/generators/forwarding/fluentd/source_test.go
Generated `source` to scrape container logs if "infrastructure" logs are forwarded
Modified test case
=> Bug 1866531: Deploy source container template if infrastructire logs are forwarded

test/helpers/elasticsearch.go, test/helpers/fluentd.go, test/helpers/kafka.go
This PR
* Primarily updates a few places where we bail on things like etcd leader changes
* Replaces Poll with PollImmediate
to address additional CI flakes
=> Add more changes to Polling to assist CI flakes

hack/testing-olm/test-010-deploy-via-olm-minimal.sh, hack/testing-olm/test-999-fluentd-prometheus-metrics.sh
This PR skips artifact collection for a few tests that are written using bash
=> Skip artifact collection if success

bundle/manifests/cluster-logging.v4.6.0.clusterserviceversion.yaml, manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
Replace reference to OKD with OCP
https://bugzilla.redhat.com/show_bug.cgi?id=1881748
=> Bug 1881748: Replace OKD with OCP

docs/HACKING.md, manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml, manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml, olm_deploy/subscription/operator-group.yaml, pkg/apis/logging/v1/cluster_log_forwarder_types.go, pkg/k8shandler/reconciler.go, test/helpers/framework.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1884275
/cc @periklis
=> Bug 1884275: Revert CLF cluster scope

README.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Doc: add link to released version of installation

pkg/k8shandler/collection.go, pkg/k8shandler/curation.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go
This PR removes verbose status update messages.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1877968
=> Bug 1877968: Remove status update message

pkg/generators/forwarding/fluentd/generators.go, pkg/k8shandler/fluentd.go, pkg/utils/comparators/services/comparator.go
- Remove `pkg/logger/logger.go`
- Replace `pkg/logger/logger.go` with `github.com/ViaQ/logerr` 
=> LOG-745: Consistent logging: Remove pkg/logger/logger.go

go.mod, go.sum, vendor/github.com/ViaQ/logerr/log/logger.go, vendor/modules.txt
Bump to resolve seeing messages for v(3) logs that should not have been emitted
=> bump logerr to resolve chatty V(3) logs

Dockerfile, must-gather/collection-scripts/common, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_cluster_logging_operator_resources, must-gather/collection-scripts/gather_collection_resources, must-gather/collection-scripts/gather_curation_resources, must-gather/collection-scripts/gather_elasticsearch_operator_resources, must-gather/collection-scripts/gather_logstore_resources, must-gather/collection-scripts/gather_visualization_resources
- Fixed script syntax
```
./gather_collection_resources: line 66: syntax error near unexpected token `done'
./gather_collection_resources: line 66: `done'
```
- Added installation of the xz package to the Dockerfile
```
nice: 'xz': No such file or directory
```
- Fixed curator diagnostics
/cc @periklis 
=> Fixes in the must-gather scripts: syntax and curator diagnostics

Makefile
`-r` (`--no-run-if-empty`)  disables execution if output is empty,
remove '-r' from xargs options, output will never be empty
/cc 
/assign 
/cherry-pick 
- Depending on PR(s): N/A
- Bugzilla: N/A
- Github issue: N/A
- JIRA: N/A
- Enhancement proposal: N/A
=> Fix 'fmt' for Mac OS users

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_legacy_test.go, pkg/generators/forwarding/fluentd/source_test.go, pkg/generators/forwarding/fluentd/templates.go
This PR is a 4.5 backport of https://github.com/openshift/cluster-logging-operator/pull/650
https://bugzilla.redhat.com/show_bug.cgi?id=1874883
=> Bug 1874883: Fix collector warnings

manifests/4.7/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/4.7/logging.openshift.io_clusterloggings_crd.yaml, pkg/constants/constants.go, pkg/k8shandler/curation.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/logstore.go, pkg/k8shandler/visualization.go
fixed errors shown by `gosec` and `errcheck` linters
=> fixed gosec, errcheck lint errors

test/helpers/cmd/reader.go, test/helpers/cmd/reader_test.go
=> Fix cmd.Reader to include stderr text in returned errors.

hack/test-e2e-olm.sh
This PR adds artifact gathering for e2e setup to try and understand e2e CI falures
=> gather artifacts for e2e setup

docs/deploy-event-router.md, hack/eventrouter-template.yaml, hack/testing-olm/test-040-eventrouter.sh
Migration of the event router e2e test from OAL
=> Event router e2e test

docs/architecture/index.adoc, docs/architecture/index.html
Also minor format fixes, corrections and clarifications.
/cc @cvogel
/cc @jcantrill
=> Architecture page: Updates on flow control, error handling.

hack/test-e2e-olm.sh
This PR fixes an error in the artifact dir
=> fix var for gathering artifacts

must-gather/collection-scripts/gather_install_resources, must-gather/collection-scripts/gather_logstore_resources, must-gather/collection-scripts/gather_visualization_resources
Use fully qualified resource name for CRs in must gather
/cc jcantrill
/assign ewolinetz
https://bugzilla.redhat.com/show_bug.cgi?id=1897731
=> Bug 1897731: Use fully qualified resource name for CRs in must gather

go.mod, go.sum, vendor/github.com/ViaQ/logerr/internal/kv/kv.go, vendor/github.com/ViaQ/logerr/kverrors/kverrors.go, vendor/github.com/ViaQ/logerr/log/log.go, vendor/github.com/ViaQ/logerr/log/logger.go, vendor/modules.txt
- Updated to v1.0.9 of github.com/ViaQ/logerr
/cc @blockloop @alanconway 
=> Updated to v1.0.9 of github.com/ViaQ/logerr

test/functional/framework.go
=> Fix trivial lint complaint.

hack/create-aws-cluster.sh
=> Allow specifying region in hack/create-aws-cluster

internal/cmd/forwarder-generator/main.go, internal/pkg/generator/forwarder/generator.go, test/functional/framework.go
This PR:
* Modifies the internal bin/forwarder-generator to produce a default conf with no input
* Include legacy forward config
/cc @vimalk78 
=> Modify internal/forwarder-generator to create default conf

test/functional/framework.go, test/functional/logforwarding/message_format_test.go, test/functional/output_forward.go, test/helpers/types/types.go, test/matchers/log_format.go, test/matchers/log_format_test.go
This PR extends log forwarding format testing to include also audit log tests 
- JIRA:
https://issues.redhat.com/browse/LOG-975
=> Functional tests for Logforwarding audit formats

test/helpers/elasticsearch.go, test/helpers/framework.go
This PR fix waitForElasticsearchPods function to make sure that the function really waits for "ready state" containers in elastic-search pods
https://coreos.slack.com/archives/GGUR75P60/p1607246317123600?thread_ts=1607243962.121800&cid=GGUR75P60
=> Check that elastic search containers are ready

docs/HACKING.md, hack/update-pull-secret.sh, pkg/k8shandler/certificates_test.go, test/helpers/elasticsearch.go
- merged improved info from private hacking doc 
- hack/update_pull_secret.sh to automate pull secret updates
- trivial fmt and lint fixes
=> Updated HACKING.md with better pull secret instructions

manifests/4.7/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/4.7/logging.openshift.io_clusterloggings_crd.yaml, pkg/apis/logging/v1/cluster_log_forwarder_types.go
No code changes.
/cc @jcantrill
=> Bug 1888943: update spec doc for url and secret fields.

Dockerfile, Dockerfile.centos.patch, Dockerfile.e2e, hack/common, hack/testing-olm/test-040-eventrouter.sh, olm_deploy/operatorregistry/Dockerfile, olm_deploy/scripts/catalog-deploy.sh
This PR updates the container registry per dev email regarding the decommissioning of the other registry
=> Update container registry to registry.ci.openshift.org

internal/pkg/generator/forwarder/generator.go, pkg/constants/constants.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/clusterloggingrequest.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/forwarding.go
Description
This PR fixes:
* forwarding logs to the managed store and legacy forwarding
* maintains writing to the legacy store when no managed store is defined
/cc @vimalk78 @sichvoge @alanconway
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1921263
=> Bug 1921263: Write to default logstore when legacy forwarding enabled

hack/eventrouter-template.yaml, hack/testing-olm/test-040-eventrouter.sh
Cherry-pick of commit 51215422793eb6f02cd183fcbd0d1a4cf6830b54
Extend the wait time for the eventrouter to deploy.
Update how CI provides IMAGE_FORMAT
Update non CI registry to pull variables
/cc @jcantrill @syedriko 
/assign @jcantrill @syedriko 
- #888
=> Extend the wait time for the eventrouter to deploy.

bundle/manifests/cluster-logging.v5.0.0.clusterserviceversion.yaml, manifests/5.0/cluster-logging.v5.0.0.clusterserviceversion.yaml
Changed 'Cluster Logging' in CSV to 'RedHat OpenShift Logging'
- JIRA: https://issues.redhat.com/browse/LOG-1041
=> LOG-1041: Changed 'Cluster Logging' in CSV to 'Red Hat OpenShift Logging'

Makefile, bundle.Dockerfile, hack/generate-bundle.sh
Update OCP bundle version to run on ocp 4.7
cc @vimalk78
=> fix OCP version to be v4.7

internal/cmd/forwarder-generator/main.go, internal/pkg/generator/forwarder/generator.go, pkg/constants/constants.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/forwarding_test.go
This PR fixes cloudwatch verification
* skips check of URL
* verifies secrets associated with cloudwatch
cc @alanconway @igor-karpukhin 
https://issues.redhat.com/browse/LOG-1155
=> LOG-1155: fix cloudwatch output verification

hack/testing-olm/test-040-eventrouter.sh, must-gather/collection-scripts/gather
This PR adds OLM pod logs to must-gather
cc @vimalk78
=> Gather OLM pod logs

docs/README.md
Provide a useful landing page for this directory.
/cherry-pick 
- Bugzilla:
- JIRA:
=> Create README.md for this docs directory

test/functional/cluster_log_forwarder.go, test/functional/elasticsearch.go, test/functional/framework.go, test/functional/outputs/forward_to_elasticsearch_test.go, test/runtime/pod.go
Log Forwarding test that verifies cluster logging is capable of writing to Elasticsearch 7
https://issues.redhat.com/browse/LOG-699
=> LOG-699 - add forward to elasticsearch functional test

pkg/constants/constants.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_legacy_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/forwarding_test.go
This PR fixes:
* forwarding logs to the managed store and legacy forwarding
* maintains writing to the legacy store when no managed store is defined
replaces #867 
/cc @vimalk78 @sichvoge @alanconway 
* https://bugzilla.redhat.com/show_bug.cgi?id=1911477
4.5 backport of #879
=> Bug 1911477: Write to default logstore when legacy forwarding enabled

Dockerfile
Fixed registry
- Changed registry.svc.ci to registry.ci
/cc 
/cherry-pick
- Bugzilla:
- JIRA:
=> Changed registry.svc.ci to registry.ci

Makefile, bundle.Dockerfile, bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml, bundle/metadata/annotations.yaml, hack/generate-bundle.sh, manifests/5.1/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.1/logging.openshift.io_clusterloggings_crd.yaml, test/functional/normalization/message_format_test.go
This PR fixes bundle generation for upstream 5.1
@vimalk78 I thought you already had a PR to do this?  did we have a bad merge?
=> fix bundle for upstream

Makefile, internal/cmd/forwarder-generator/main.go, internal/pkg/generator/forwarder/generator.go
This PR:
* fixes the internal clf generator to properly deserialize yaml and respect camelcase
* adds Makefile target to compile and test when doing unit tests to ensure it at least runs without error
cc @vimalk78 @alanconway @igor-karpukhin
=> fix internal generator tool and always test

Makefile, internal/cmd/functional-benchmarker/main.go, internal/pkg/generator/forwarder/generator.go, manifests/5.1/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/cluster_log_forwarder_types.go, pkg/apis/logging/v1/output_types.go, pkg/certificates/certificates.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go, pkg/utils/utils.go, test/functional/framework.go, test/functional/normalization/json_parsing_test.go, test/functional/normalization/message_format_test.go, test/functional/output_forward.go, test/helpers.go, test/helpers/fluentd/receiver.go, test/helpers/types/types.go, test/matchers/errors.go
This PR is to implement the Json Forwarding Proposal https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/forwarding-json-structured-logs.md
- Changed the ClusterLogForwarder API
- Generated fluent.conf for doing json parsing based on fluentd parse plugin https://docs.fluentd.org/filter/parser
- Add functional tests
- rebased on latest master
- changed functional benchmarker to use separate config for fluentdForward which adds `epoc_in/epoc_out` which interferes in testing normal functional test cases
/cc @jcantrill @eranra 
/assign @jcantrill @alanconway 
- JIRA: https://issues.redhat.com/browse/LOG-1157
- Enhancement proposal: https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/forwarding-json-structured-logs.md
=> LOG-1157: Implement Json Forwarding: Parse Json Message

must-gather/collection-scripts/gather_cluster_logging_operator_resources, pkg/certificates/certificates.go, pkg/constants/constants.go, pkg/controller/clusterlogging/clusterlogging_controller.go, pkg/k8shandler/certificates.go, pkg/k8shandler/certificates_test.go, pkg/k8shandler/clusterloggingrequest.go, pkg/k8shandler/reconciler.go, test/functional/framework.go, test/helpers/framework.go, vendor/github.com/onsi/gomega/go.mod
CLO will generate an event after updating certificates
- JIRA: https://issues.redhat.com/browse/LOG-1160
=> LOG-1160: Added credentials update event

manifests/5.1/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.1/logging.openshift.io_clusterloggings_crd.yaml, pkg/apis/logging/v1/zz_generated.deepcopy.go, pkg/generators/forwarding/fluentd/generators.go, pkg/k8shandler/certificates.go
A cleanup for the "make check" target
/cc @vimalk78 
/assign @ewolinetz
=> make check cleanup

Makefile, test/functional/framework.go
This PR:
* Fixes the functional-benchmarker to close the client as desired
* Sets up Makefile to test when we do functional tests to ensure it exits correctly
@igor-karpukhin @vimalk78 @alanconway
=> fix functional benchmarker and always test

Dockerfile, Dockerfile.centos.patch, Dockerfile.e2e, hack/common, olm_deploy/operatorregistry/Dockerfile
Replace `registry.svc.ci.openshift.org` with `registry.ci.openshift.org`
/cherry-pick 
N/A
=> Replace registry.svc.ci.openshift.org with registry.ci.openshift.org

pkg/apis/logging/v1/cluster_log_forwarder.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/generators/forwarding/fluentd/helpers.go, pkg/generators/forwarding/fluentd/output_conf_legacy_test.go, pkg/generators/forwarding/fluentd/templates.go
This PR
* fixes routing of application messages by namespace so they end up at the desired outputs
/cc @alanconway @vimalk78 
* https://bugzilla.redhat.com/show_bug.cgi?id=1925361
* https://bugzilla.redhat.com/show_bug.cgi?id=1905615
backport of 5.0 https://github.com/openshift/cluster-logging-operator/pull/976
=> Bug 1925361: fix routing of app logs per namespace

must-gather/collection-scripts/gather_cluster_logging_operator_resources, pkg/controller/forwarding/forwarding_controller.go
CLO will emit events for a valid and invalid CLF pipelines
- JIRA: https://issues.redhat.com/browse/LOG-1161
=> LOG-1161: Added events for valid/invalid pipelines

pkg/constants/constants.go, pkg/k8shandler/certificates_test.go, pkg/k8shandler/forwarding_test.go, scripts/cert_generation.sh
This PR provides a port of the merged fix #972 (Target Version `4.6.z`) for `5.1.0`
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
- JIRA: https://issues.redhat.com/browse/LOG-1327
=> LOG-1327: Port fix to 5.1.0 for BZ-1945168

Dockerfile.centos.patch
Update the CentOS dockerfile patch to align with the latest Dockerfile generated by Dockerfile.in
/cc @alanconway @jcantrill
=> Update the CentOS Dockerfile patch for adjustment

pkg/constants/constants.go, pkg/k8shandler/certificates_test.go, pkg/k8shandler/forwarding_test.go, scripts/cert_generation.sh
This PR provides a port of the merged fix #972 (Target Version `4.6.z`) for `5.0.z`
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
- JIRA: https://issues.redhat.com/browse/LOG-1328
=> LOG-1328: Port fix to 5.0.z for BZ-1945168

pkg/constants/constants.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go
This PR enables the usage of username and password as part of the CLF secret.
/cc @jcantrill
JIRA: https://issues.redhat.com/browse/LOG-974
=> LOG-974: Enable username and password for Kafka and Elastic

must-gather/collection-scripts/gather_cluster_logging_operator_resources
Fixed a part of `must-gather` script that collects events
/cc @jcantrill @vimalk78 
=> Fixed must-gather events collection

must-gather/collection-scripts/gather_install_resources, olm_deploy/scripts/operator-install.sh
This PR:
* captures the EO subscription for must-gather
* Echos the CLO subscription on deployment
cc @vimalk78 
https://issues.redhat.com/browse/LOG-1341
=> Capture eo subscription

manifests/5.2/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/output_types.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/templates.go, test/functional/outputs/forward_to_elasticsearch_index_test.go
In line with updated proposal: https://github.com/openshift/enhancements/pull/780
/cc @vimalk78
/cc @jcantrill
=> LOG-1370 Change name of elasticsearch.indexKey to structuredIndexKey

bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml, manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
Fixed skip range in CLO CSV. in manifest and bundle folders
/cc 
=> Fixed skip range for 5.1

bundle/manifests/cluster-logging.v5.0.0.clusterserviceversion.yaml, manifests/5.0/cluster-logging.v5.0.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1459
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
=> LOG-1459: Annotate with infrastructure features

bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml, manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1458
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
=> LOG-1458: Annotate with infrastructure features

Makefile, bundle.Dockerfile, bundle/metadata/annotations.yaml, hack/generate-bundle.sh, hack/generate-crd.sh
This PR:
* Modifies channel naming to match PE recommendations
* Sets the default channel to use when a dependency is declared
https://issues.redhat.com/browse/LOG-1421
=> LOG-1421: Modify channels to PE recommendations

manifests/5.2/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/output_types.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/functional/cluster_log_forwarder.go, test/functional/elasticsearch.go, test/functional/framework.go, test/functional/normalization/json_parsing_test.go, test/functional/outputs/forward_to_elasticsearch_index_test.go
This is an attempt to fix implementation of json log forwarding based on updated enhancement proposal.
/cc @jcantrill @alanconway 
/cherry-pick 
- Bugzilla:
- JIRA:
- Enhancement proposal: PR https://github.com/openshift/enhancements/pull/780
=> LOG-1400: elasticsearch output should add app- prefix to index names

bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml, manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1420
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
cc @vimalk78
=> LOG-1420: Annotate with infrastructure features

pkg/generators/forwarding/fluentd/templates.go
This is a quick fix for the problem with not working HTTPS and username/password option.
/cc @jcaianirh 
/assign @vparfonov 
- JIRA: https://issues.redhat.com/browse/LOG-1372
=> LOG-1372. Fixed ES username and password for HTTPS

pkg/constants/constants.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go
This is a cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1069 to `release-5.1`
https://issues.redhat.com/browse/LOG-974
=> LOG-974: Fixed username and password feature for ES and Kafka

Makefile, bundle.Dockerfile, bundle/metadata/annotations.yaml, hack/generate-bundle.sh
This PR:
* Modifies channel naming to match PE recommendations
* Sets the default channel to use when a dependency is declared
https://issues.redhat.com/browse/LOG-1463
cc @alanconway @vimalk78 
/hold
=> LOG-1463: Modify channels to PE recommendations

bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.1/logging.openshift.io_clusterlogforwarders_crd.yaml, pkg/apis/logging/v1/output_types.go, pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/functional/cluster_log_forwarder.go, test/functional/elasticsearch.go, test/functional/framework.go, test/functional/normalization/json_parsing_test.go, test/functional/outputs/forward_to_elasticsearch_index_test.go
A manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1039
/cc 
/assign
=> [release-5.1] LOG-1400: elasticsearch output should add app- prefix to index names.

pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/templates.go
This PR reverts the username/password feature for Kafka for `release-5.1`
- JIRA: https://issues.redhat.com/browse/LOG-1369
=> LOG-1369. Revert Kafka username/password feature for release-5.1

hack/registry.sh
Sporadically on AWS `oc registry info --public` returns 0 exit status,
but the next call fails to return a registry string and login fails.
Modify the script to retry until everything works together:
registry info 0 exit status, registry name non-empty, and login succeeds.
/cc @vimalk78
=> Fix race condition in registry.sh

pkg/constants/constants.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/forwarding.go
This PR removes changes added by the following PRs:
https://github.com/openshift/cluster-logging-operator/pull/1074
https://github.com/openshift/cluster-logging-operator/pull/1076
=> Revert LOG-1372, LOG-974 for release-5.1

test/e2e/collection/fluentd/container_security_test.go
This is a fix for the failure of test/e2e/collection/fluentd/container_security_test.go, uncovered by https://github.com/openshift/cluster-logging-operator/pull/979, due to there being multiple containers in the fluentd pods. The fix specifies the container to run probing oc commands in, namely, "fluentd".
/cc @pmoogi-redhat 
=> In the fluentd container security test, account for multiple containers in the fluentd pod

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/generators/forwarding/fluentd/templates.go, test/helpers/framework.go
This PR changes the built-in application behavior to collect all the applications logs.
/cc @alanconway @jcantrill
- https://bugzilla.redhat.com/show_bug.cgi?id=1981579
- backport of 5.0 https://github.com/openshift/cluster-logging-operator/pull/1008
=> Bug 1981579: Fix built-in application to collect all of logs

bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml, manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
Changed 'Cluster Logging' in CSV to 'RedHat OpenShift Logging'
manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/893
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1959444
=> Changed 'Cluster Logging' in CSV to 'RedHat OpenShift Logging

bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml, manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
Changed 'Cluster Logging' in CSV to 'RedHat OpenShift Logging'
manual cherry pick of https://github.com/openshift/cluster-logging-operator/pull/893
/cc 
/assign
=> Changed 'Cluster Logging' in CSV to 'RedHat OpenShift Logging'

bundle.Dockerfile, bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml, bundle/metadata/annotations.yaml, hack/generate-bundle.sh
This PR provides a fix for the default package name used in the bundle annotations.
/cc @vimalk78 
=> Fix bundle package name

pkg/generators/forwarding/fluentd/fluent_conf.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/helpers.go, pkg/generators/forwarding/fluentd/helpers_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/collection.go, pkg/k8shandler/forwarding.go, pkg/k8shandler/forwarding_test.go
This PR:
* adds username/password handling for the ES
* supersedes https://github.com/openshift/cluster-logging-operator/pull/1086 
/cc @igor-karpukhin @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-974
=> LOG-974: Fixed ES username/password feature

bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.2/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.2/logging.openshift.io_clusterloggings_crd.yaml
fix bundle/manifest so it is consistent with /manifest
/cc @vimalk78 
* https://issues.redhat.com/browse/LOG-1683
=> LOG-1683: fix bundle/manifests to include loki

pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go
manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/1149
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-1723
=> LOG-1723:  Output flush_interval only with flush_mode=interval

Makefile, bundle/manifests/cluster-logging.v5.0.0.clusterserviceversion.yaml, manifests/5.0/cluster-logging.v5.0.0.clusterserviceversion.yaml, manifests/5.0/image-references, olm_deploy/scripts/registry-init.sh, test/helpers/fluentd.go, test/helpers/fluentd/receiver.go
This is manual backport of #1152.
To address: https://issues.redhat.com/browse/LOG-1696
/cc @jcantrill @vimalk78 
=> [release-5.0] Use pinned operand image versions from quay.io

test/helpers.go
Fixed generation of unique names in the test package to make test failures like this less likely:
```
• Failure [0.016 seconds]
Helpers
~/go/src/github.com/openshift/cluster-logging-operator/test/helpers_test.go:23
UniqueName
~/go/src/github.com/openshift/cluster-logging-operator/test/helpers_test.go:159
generates unique names [It]
~/go/src/github.com/openshift/cluster-logging-operator/test/helpers_test.go:160
not unique
Expected
<map[string]bool | len:49>: {"x-c37qacr4": true, "x-c37qaifu": true, "x-c37qbbbn": true, "x-c37qal7s": true, "x-c37qbtsl": true, "x-c37qbwpk": true, "x-c37qabwe": true, "x-c37qbzqg": true, "x-c37qaox4": true, "x-c37qabqi": true, "x-c37qaf6u": true, "x-c37qbh7x": true, "x-c37qa6h7": true, "x-c37qbdvn": true, "x-c37qatb5": true, "x-c37qaie5": true, "x-c37qaqpx": …
```
=> Made test.UniqueName generate names that are more unique

Makefile, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/buffer_conf.go, internal/generator/fluentd/output/buffer_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go, internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go, internal/generator/fluentd/output/fluentdforward/output_conf_forward_test.go, internal/generator/fluentd/output/kafka/kafka_test.go, internal/generator/fluentd/output/kafka/output_conf_kafka_test.go, internal/generator/fluentd/output/loki/output_conf_loki_test.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/fluentd/output/syslog/output_conf_syslog_test.go, internal/generator/vector/sources_test.go
This PR fixes https://issues.redhat.com/browse/LOG-1735 by reverting the change to flush buffers at shutdown
cc @vimalk78 @syedriko
=> LOG-1735: Stop flushing buffers at shutdown

files/fluentd/run.sh, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/utils/quantity.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
/cc @jcantrill
/cc @vimalk78
/cherry-pick
Links
Bugzilla: 
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1736
=> LOG-1736:fluentd total_limit_size wrong values echoed

pkg/components/fluentd/run_script.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/utils/quantity.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
Description
/cc @jcantrill
/cc @vimalk78
/cherry-pick
Links
Bugzilla: 
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1737
=> LOG-1737:fluentd total_limit_size wrong values echoed

Dockerfile, Dockerfile.in
This change set ensures that the Dockerfiles are in sync with midstream
To address: https://issues.redhat.com/browse/LOG-1750
/cc @jcantrill @vimalk78 
=> Sync Dockerfile with midstream

files/fluentd/run.sh, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
/cc @vimalk78 
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1976692
- JIRA: https://issues.redhat.com/browse/OCPBUGSM-31512
=> Bug 1976692: fluentd total_limit_size fix  

test/e2e/logforwarding/kafka/forward_to_kafka_test.go
This PR:
* Removes a redundant Kafka e2e test
cc @pmoogi-redhat 
* https://issues.redhat.com/browse/LOG-1752
=> LOG-1752: Remove Kafka e2e test to single topic

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/output_conf_loki_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
This PR fixes https://issues.redhat.com/browse/LOG-1735 by reverting the change to flush buffers at shutdown
cc @vimalk78 @syedriko
* https://issues.redhat.com/browse/LOG-1739
=> LOG-1739: Stop flushing buffers at shutdown

pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go
Manual cherry pick of https://github.com/openshift/cluster-logging-operator/pull/1149
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-1724
* https://bugzilla.redhat.com/show_bug.cgi?id=2000742
=> Bug 2000742: Output flush_interval only with flush_mode=interval

Makefile, bundle.Dockerfile, bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml, bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml, bundle/metadata/annotations.yaml, manifests/5.3/logging.openshift.io_clusterlogforwarders_crd.yaml, manifests/5.3/logging.openshift.io_clusterloggings_crd.yaml
Generated files seem to have gone stale.
Added pre-commit target, to ensure up-to-date do this last thing before a commit:
make pre-commit
=> Update all generated files using current toolset.

Makefile, internal/generator/fluentd/conf.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, internal/generator/fluentd/multiline_detect_exceptions.go, internal/generator/fluentd/multiline_detect_exceptions_test.go, test/functional/normalization/multiline_exception_test.go
This PR:
* Adds configuration generation for muliline error detection to re-assemble lines into a single log entry
* https://issues.redhat.com/browse/LOG-1717
=> LOG-1717: Add multiline error detection

test/functional/normalization/eventrouter_test.go
This PR:
* Makes pod_ip optional when doing message normalization check
* Required to unblock merge of https://github.com/openshift/origin-aggregated-logging/pull/2149
* https://issues.redhat.com/browse/LOG-1390
=> LOG-1390: Allow optional pod_ip for eventrouter tests

pkg/components/fluentd/run_script.go, pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/output_conf_forward_test.go, pkg/generators/forwarding/fluentd/output_conf_kafka_test.go, pkg/generators/forwarding/fluentd/output_conf_loki_test.go, pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, pkg/k8shandler/fluentd.go, pkg/k8shandler/fluentd_test.go, test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
Description
/cc @jcantrill
/cc @vimalk78
/cherry-pick
Links
Bugzilla:
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1738
=> LOG-1738: fluentd total_limit_size sets value beyond available space

internal/components/fluentd/run_script.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/buffer.go, internal/generator/fluentd/output/buffer_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go, internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go, internal/generator/fluentd/output/fluentdforward/output_conf_forward_test.go, internal/generator/fluentd/output/kafka/kafka_test.go, internal/generator/fluentd/output/kafka/output_conf_kafka_test.go, internal/generator/fluentd/output/loki/output_conf_loki_test.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/fluentd/output/syslog/output_conf_syslog_test.go, internal/k8shandler/fluentd.go, internal/k8shandler/fluentd_test.go
Description
/cc @jcantrill
/cc @vimalk78
/cherry-pick
Links
Bugzilla:
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1776
=> LOG-1776:fluentd total_limit_size sets value beyond available space

internal/generator/fluentd/elements/copy.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go, internal/generator/fluentd/pipeline_to_output.go, internal/generator/fluentd/pipeline_to_output_test.go, internal/runtime/pod.go, test/functional/clfyaml, test/functional/cluster_log_forwarder.go, test/functional/cluster_log_forwarder_test.go, test/functional/elasticsearch.go, test/functional/fluent.conf, test/functional/framework.go, test/functional/outputs/forward_to_elasticsearch_index_test.go, test/functional/outputs/multiple/multiple_test.go, test/functional/outputs/multiple/suite_test.go, test/functional/run.sh, test/functional/suite_test.go
This PR:
* deep copies message to outputs to resolve unintended parsing of messages to be delivered to Elasticsearch
* https://issues.redhat.com/browse/LOG-1575
=> LOG-1575: Add deep_copy to fan out to outputs

bundle/manifests/cluster-logging.v5.3.0.clusterserviceversion.yaml, manifests/5.3/cluster-logging.v5.3.0.clusterserviceversion.yaml
This PR fixes the display name of the clusterlogging kind
cc @alanconway 
https://issues.redhat.com/browse/LOG-1903
=> LOG-1903: Fix displayname of clusterlogging

Makefile, internal/cmd/functional-benchmarker/config/config.go, internal/cmd/functional-benchmarker/config/options.go, internal/cmd/functional-benchmarker/main.go, internal/cmd/functional-benchmarker/readme.md, internal/cmd/functional-benchmarker/reports/gnuplot/gnuplot.go, internal/cmd/functional-benchmarker/reports/gnuplot/plot_scripts.go, internal/cmd/functional-benchmarker/reports/report.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/runners/runner.go, internal/cmd/functional-benchmarker/stats/statistics.go, internal/cmd/functional-benchmarker/stats/types.go, test/helpers/oc/logs.go, test/helpers/types/types.go
This PR:
* Updates the collector functional benchmark tool to display latency graph
* Add options used to the report
* Extracts logs to the artifact dir
/assign @alanconway @eranra 
* https://issues.redhat.com/browse/LOG-1907
=> LOG-1907: Enhance functional benchmark tool to add latency

bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml, manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
This PR fixes the display name of the clusterlogging kind
cc @alanconway 
https://issues.redhat.com/browse/LOG-1904
=> [release-5.2] LOG-1903: Fix displayname of clusterlogging

bundle/manifests/cluster-logging.v5.3.0.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, manifests/5.3/cluster-logging.v5.3.0.clusterserviceversion.yaml
This PR:
* Removes reference to vector in the CSV to satisfy CPaaS build checks
cc @vimalk78 
* https://issues.redhat.com/browse/LOG-1912
=> LOG-1912: Remove VECTOR from CSV for CPaaS

pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
https://github.com/openshift/cluster-logging-operator/pull/1122 is cherry-picked for release-5.2.
/cc @jcantrill @alanconway @periklis
- JIRA: https://issues.redhat.com/browse/LOG-1464
=> LOG-1464: Disable audit log source when only legacy syslog forwarding enabled

internal/generator/fluentd/output/cloudwatch/cloudwatch.go, internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go, internal/generator/fluentd/source/tags.go
This PR
* Fixes CW forwarding when multi-line error detection is enabled
/cherrypick master
cc @periklis 
* https://issues.redhat.com/browse/LOG-1939
=> LOG-1939: Fix CW forwarding for multiline error detection

pkg/generators/forwarding/fluentd/fluent_conf_test.go, pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/generators/forwarding/fluentd/output_conf_es_test.go, pkg/generators/forwarding/fluentd/templates.go, test/functional/cluster_log_forwarder.go, test/functional/cluster_log_forwarder_test.go, test/functional/elasticsearch.go, test/functional/framework.go, test/functional/outputs/forward_to_elasticsearch_index_test.go, test/functional/outputs/multiple/multiple_test.go, test/functional/outputs/multiple/suite_test.go, test/functional/suite_test.go, test/runtime/pod.go
This PR:
* deep copies message to outputs to resolve unintended parsing of messages to be delivered to Elasticsearch
* https://issues.redhat.com/browse/LOG-1824
* backport of https://github.com/openshift/cluster-logging-operator/pull/1204
=> LOG-1824: Add deep_copy to fan out to outputs

go.mod, go.sum, vendor/github.com/ViaQ/logerr/log/logger.go, vendor/modules.txt
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1896
=> LOG-1896: Upgrade ViaQ/logerr version to v1.0.11

go.mod, go.sum, vendor/github.com/ViaQ/logerr/log/logger.go, vendor/modules.txt
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1963
=> [release-5.2] LOG-1963: Upgrade ViaQ/logerr version to v1.0.11

pkg/generators/forwarding/fluentd/output_conf_syslog_test.go, pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go, pkg/generators/forwarding/fluentd/templates.go, test/e2e/logforwarding/syslog/forward_to_syslog_test.go, test/functional/outputs/forward_to_syslog_test.go
This PR is:
* 5.2 backport of https://github.com/openshift/cluster-logging-operator/pull/1158
* Fix syslog serialization using json formatting
* https://issues.redhat.com/browse/LOG-1775
=> LOG-1775: Fix syslog serialization using json formatting

internal/cmd/functional-benchmarker/reports/gnuplot/plot_scripts.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/k8shandler/collection.go, internal/k8shandler/priorityclass.go, internal/pkg/generator/forwarder/generator.go, internal/utils/comparators/daemonsets/comparator.go, test/framework/functional/constants.go, test/framework/functional/factory.go, test/framework/functional/fluentd/deploy.go, test/framework/functional/framework.go, test/framework/functional/read.go, test/framework/functional/write.go, test/functional/collection/input_selector_test.go, test/functional/metrics/fluentd_test.go, test/functional/normalization/crio_partial_log_test.go, test/functional/normalization/flatten_labels_test.go, test/functional/normalization/json_parsing_test.go, test/functional/outputs/forward_to_kafka_test.go, test/functional/outputs/forward_to_syslog_test.go, test/functional/outputs/loki/audit_logs_test.go, test/functional/outputs/unavailable_forward_output_test.go, test/helpers/clusterlogging.go
This PR:
* breaks out the functional/framework.go into smaller files
* Adds interface for unique collector deployments
/cc @vimalk78
=> WIP refactor functional framework. introduce collector factory

must-gather/collection-scripts/gather_logstore_resources
This PR:
- is a follow up on https://github.com/openshift/origin-aggregated-logging/pull/2211
/cc @Red-GV @igor-karpukhin 
/cherry-pick 
- Depending on PR(s): https://github.com/openshift/origin-aggregated-logging/pull/2211
- JIRA: https://issues.redhat.com/browse/LOG-1835
=> LOG-1835: Updated /etc path to /var/run in gather logstore resourse

files/dashboards/openshift-logging-dashboard.json
This PR fixes the CPU dashboard graph:
* fixing the metrics
* correcting the container name for collectors
* https://issues.redhat.com/browse/LOG-1925
=> LOG-1925: Fix cpu graph on dashboard

must-gather/collection-scripts/gather_logstore_resources
This PR:
- Reverts openshift/cluster-logging-operator#1266
- pushing this back for later
/cc @periklis 
/assign @periklis
=> Revert "LOG-1835: Updated /etc path to /var/run in gather logstore resourse"

Dockerfile, Dockerfile.in, bundle/manifests/cluster-logging.v5.4.0.clusterserviceversion.yaml, internal/generator/vector/conf_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/elasticsearch/output_conf_es_test.go, internal/generator/vector/pipelines_to_output.go, manifests/5.4/cluster-logging.v5.4.0.clusterserviceversion.yaml, test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/framework/e2e/framework.go, test/helpers/clusterlogging.go
* Enabled Vector in Dockerfile and CSV
* Added "_id" to elasticsearch vector config
* Added Vector component type to e2e test framework, and made one elasticsearch test case to run with both fluentd and vector collector
/cc @jcantrill @ajaygupta978 
/assign
=> Add "_id" to ES vector config; enable ES vector tests

hack/testing-olm/test-040-eventrouter.sh
This PR:
* fixes eventrouter test to not checkout cluster status
=> fix eventrouter test to not checkout health of ES

internal/cmd/forwarder-generator/main.go, internal/k8shandler/clusterloggingrequest.go, internal/k8shandler/forwarding.go, internal/k8shandler/forwarding_test.go, internal/pkg/generator/forwarder/generator.go, test/framework/functional/framework.go
This PR:
* Fixes how outputdefaults are applied to only set them if not defined on the output
* Fixes modifying the output secret if OutputDefaults are applied
* Fixes the forward-generator tool 
* https://issues.redhat.com/browse/LOG-2046
=> LOG-2046: fix wrong certs when OutputDefaults are defined

bundle/manifests/cluster-logging.v5.4.0.clusterserviceversion.yaml, manifests/5.4/cluster-logging.v5.4.0.clusterserviceversion.yaml
Added arm64 as supported arch in CSV
/cc 
/assign 
- JIRA:  https://issues.redhat.com/browse/LOG-2085
=> LOG-2085: Add arm64 as supported arch in CSV

test/e2e/logforwarding/kafka/forward_to_kafka_test.go
This PR:
* Updates the kafka e2e test to only verify communcation with a kafka receiver instead of testing multiplexing of logs
=> [release-5.1] Fix kafka e2e test

pkg/generators/forwarding/fluentd/generators.go, pkg/generators/forwarding/fluentd/generators_test.go, pkg/k8shandler/collection_test.go, pkg/k8shandler/daemonset.go, pkg/k8shandler/forwarding.go, test/e2e/logforwarding/kafka/forward_to_kafka_test.go
Backport of https://github.com/openshift/cluster-logging-operator/pull/1297 to fix the kafka e2e test
=> fix test and format code.  packport of #1297

controllers/clusterlogging/clusterlogging_controller.go, hack/testing-olm/test-010-deploy-via-olm-minimal.sh, internal/k8shandler/clusterloggingrequest.go, internal/k8shandler/reconciler.go, internal/metrics/dashboards.go, internal/metrics/dashboards_test.go, internal/reconcile/configmaps.go, internal/utils/comparators/configmaps/comparator.go, internal/utils/utils.go, main.go
This PR is a forward port of #1293 to fix the dashboard reconciliation in the managed openshift config namespace
* https://issues.redhat.com/browse/LOG-2071
=> LOG-2071: Modify client to also watch cluster config NS

internal/generator/vector/conf_test.go, internal/generator/vector/sources_to_inputs.go
Fixed the expression for app container logs.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2052
=> LOG-2052: Vector: Fix container logs routing

hack/testing-olm/test-040-eventrouter.sh
Try to fix flaky EventRouter e2e test. Add code for waiting elasticsearch deployment will be ready. 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Try to fix flaky EventRouter e2e test

files/dashboards/openshift-logging-dashboard.json
This PR:
- Updates `es_cluster_shards_number` expr
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2156
=> LOG-2156: Updated shards number expression in dashboard file

internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/loki/userpass.go
Fixed configuration for username password in Loki vector config.
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2157
=> LOG-2157: Vector: Fix username config

bundle/manifests/cluster-logging_scheduling.k8s.io_v1_priorityclass.yaml, config/manifests/priority_class.yaml, hack/generate-crd.sh, internal/k8shandler/collection.go, manifests/5.4/cluster-logging_scheduling.k8s.io_v1_priorityclass.yaml
Move PriorityClass to operator manifest 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1834
=> LOG-1834:Move PriorityClass to operator manifest

test/functional/normalization/json_parsing_test.go
This PR:
* Adds a test case to prove writing structured logs to an Elasticsearch output
https://issues.redhat.com/browse/LOG-2105
=> add test to address LOG-2105

internal/generator/vector/conf_test.go, internal/generator/vector/inputs_to_pipeline.go, internal/generator/vector/outputs.go, internal/generator/vector/pipelines_to_output.go, test/e2e/logforwarding/loki/forward_to_loki_test.go
Support adding pipeline labels to Vector produced record.
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2193
=> LOG-2193: Add pipeline labels to Vector produced record

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go, internal/generator/fluentd/source/tags.go, internal/generator/fluentd/sources_to_pipelines_test.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2160
=> LOG-2160: Fix patterns to avoid sent infra log to the app index

test/framework/functional/message_templates.go, test/helpers/types/optional_int.go, test/helpers/types/optional_int_test.go, test/helpers/types/suite_test.go, test/helpers/types/types.go, test/matchers/log_format.go
This PR:
* Adds an OptionalInt type for the message tests in preparation to add an openshift.sequence number
* https://issues.redhat.com/browse/LOG-2099
=> LOG-2099: Add optionalint in prep for fix

internal/generator/vector/conf_test.go, internal/generator/vector/inputs_to_pipeline.go, internal/generator/vector/sources_to_inputs.go, internal/generator/vector/sources_to_pipelines_test.go
Add support for namespace filtering in Vector config.
/cc @jcantrill @alanconway 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2255
=> LOG-2255: Vector: Support Namespace filtering

apis/logging/v1/cluster_log_forwarder_types.go
=> NO-JIRA: Minor update to API doc comments.

Dockerfile, Dockerfile.in
Move source code folders , especially `internal` folder to the bottom.
/cc 
/assign 
/cherry-pick
=> Speedup Dockerfile build

test/helpers/framework.go
This PR:
* updates the deployment status check to ready to try and improve stability
* https://issues.redhat.com/browse/LOG-2340
=> [release-5.2] LOG-2340: Update kafka services to wait for ready state

internal/generator/vector/conf_test.go, internal/generator/vector/elements/elements.go, internal/generator/vector/inputs_to_pipeline.go, internal/generator/vector/metrics.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/outputs.go, internal/generator/vector/pipelines_to_output.go, internal/generator/vector/sources.go, internal/generator/vector/sources_to_inputs.go, internal/generator/vector/sources_to_pipelines_test.go, internal/generator/vector/vrl.go, internal/k8shandler/vector.go, test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/e2e/logforwarding/loki/forward_to_loki_test.go
Cherry-pick few commits from master to release-5.4 , mostly related to Vector Preview.
8b8400be478788415a74665dab6b20fcb7fdce06
2fca2c0bd84d8c53c70bb27ad3c25a5f5c2cad23
f2c735d399248bf98d878756387db9e1eb97656e
84ff5305f3d70c556282f0e83e0e4edbaa7c42e2
0e6fa59ad1b9803231e59d0b492fcf43d9e9b231
dce030bd074d00b9fb61cc09eddac535d434cf4b
a8682f3795cf6737a2308b93c9bc4b2a8ae9493e
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Cherrypick from master

Dockerfile, Dockerfile.in, Dockerfile.patch, Makefile, olm_deploy/operatorregistry/Dockerfile, origin-meta.yaml
This PR:
* Replaces ocp specific base images with those that are publicly available with RH or other subscriptions
* https://issues.redhat.com/browse/LOG-1659
cc @alanconway
=> LOG-1659: Update dev images to use public bases

internal/generator/vector/conf.go
Added missing Normalize container_logs transform for infra logs
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-2381
=> LOG-2381: Vector: Add missing Normalize container_logs transform for infra logs

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, test/functional/normalization/message_format_test.go
Adding new rules to support new level and also modifying existing rules to prioritise patterns.  Please see Jira ticket for details.
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2033
=> LOG_2033: Adding rules to support one more level field 

Makefile, test/framework/functional/cluster_log_forwarder_test.go
This PR:
* Updates the Makefile to run all unit tests under test and to exclude e2e and functional
* Fixes the clusterlogforwarder builder test
=> Ensure all unit tests are running

internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go
Fixed index when both indexKey and indexName are used. Making it same as fluentd.
/cc 
/assign 
- Bugzilla:
- JIRA:
=> LOG-2554: Fixed index when both indexKey and indexName are used

internal/generator/vector/conf_test.go, internal/generator/vector/source/audit_logs.go, internal/generator/vector/sources_test.go, test/framework/functional/constants.go, test/framework/functional/write.go, test/functional/normalization/audit_logs_format_test.go
This PR:
* fixes the collection of openshift-api audit logs
* https://issues.redhat.com/browse/LOG-2172
=> LOG-2171: fix collecting openshift-api audit logs

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, test/functional/normalization/message_format_test.go
This PR:
* fixes missing rules to support new level and also modifying existing rules to prioritize patterns
* 5.4 backport of https://github.com/openshift/cluster-logging-operator/pull/1332
* https://issues.redhat.com/browse/LOG-2033
=> LOG-2033: Adding rules to support one more level field

test/e2e/collection/fluentd/container_security_test.go
This PR:
* attempts to fix the security test to be less flaky
=> change security test to use regex

Makefile, internal/generator/vector/conf_test.go, internal/generator/vector/elements/elements.go, internal/generator/vector/helpers/helpers.go, internal/generator/vector/inputs.go, internal/generator/vector/normalize.go, internal/generator/vector/output/cloudwatch/auth.go, internal/generator/vector/output/cloudwatch/cloudwatch.go, internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/kafka/kafka_test.go, internal/generator/vector/outputs.go, internal/generator/vector/sources.go, internal/generator/vector/sources_to_pipelines_test.go, internal/generator/vector/suite_test.go, test/framework/functional/output_cloudwatch.go, test/framework/functional/write.go, test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
This PR:
- provides phase1 feature parity with fluentd
- forwards logs to cloudwatch using vector
- verifies configuration using unit test
- verifies functional test using a mock AWS server
- https://issues.redhat.com/browse/LOG-2223
/assign @vimalk78
=> LOG-2223: Support vector cloudwatch forwarding

Dockerfile, Dockerfile.in, origin-meta.yaml
This PR:
* syncs the Dockerfile.in from downstream for consistency
cc @Red-GV @alanconway
=> sync Dockerfile.in from downstream

internal/cmd/functional-benchmarker/reports/gnuplot/gnuplot.go, internal/cmd/functional-benchmarker/reports/gnuplot/init.go, internal/cmd/functional-benchmarker/reports/gnuplot/plot_scripts.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/stats/init.go, internal/cmd/functional-benchmarker/stats/loss_stats.go, internal/cmd/functional-benchmarker/stats/loss_stats_test.go, internal/cmd/functional-benchmarker/stats/sample.go, internal/cmd/functional-benchmarker/stats/statistics.go, internal/cmd/functional-benchmarker/stats/suite_test.go
This PR:
* Modifies to the functional benchmarking utility to calculate lost messages
https://issues.redhat.com/browse/LOG-1924
=> LOG-1924: Evaluate log loss in benchmark tool

must-gather/collection-scripts/gather_cluster_logging_operator_resources, must-gather/collection-scripts/gather_collection_resources
1. Fix CSV name
2. Fix command to get events from `openshift-logging` namespace
3. Remove not actual command for not existed resources 
4. Add command to get Vector configuration file `vector.toml`
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1539
=> LOG-1539: fix must-gather scripts

apis/logging/v1/clusterlogging_types.go, config/crd/bases/logging.openshift.io_clusterloggings.yaml, go.mod, go.sum, internal/k8shandler/indexmanagement/index_management.go, internal/k8shandler/logstore_test.go, manifests/5.5/logging.openshift.io_clusterloggings_crd.yaml
This PR:
- Updates go.mod to use the latest EO image
- Updates CLO's retention policy API to include delete by disk percentage functionality
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-2429
=> Consume EO's delete by percentage API changes

must-gather/collection-scripts/gather_cluster_logging_operator_resources
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
1. Fix CSV name
2. Fix command to get events from openshift-logging namespace
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1539
=> [release-5.4]LOG-1539: fix must-gather scripts

controllers/clusterlogging/clusterlogging_controller.go, internal/metrics/dashboards.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:  https://issues.redhat.com/browse/LOG-2243
=> [release-5.4]LOG-2243: remove grafana-dashboard-cluster-logging on removing clusterlogging/instance

files/fluentd/fluentd_prometheus_alerts.yaml
This PR updates the alert to warning
* https://issues.redhat.com/browse/LOG-2588
=> LOG-2588: Update FluentdQueueLengthIncreasing alert to Warning

internal/generator/vector/conf_test.go, internal/generator/vector/normalize.go, internal/generator/vector/output/cloudwatch/cloudwatch.go, internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- Vector feature parity with fluentd
- Add mapping VRL to the 'raw_journal_logs' transform, based on the viaq data model: https://viaq.github.io/documentation/data_model/public/data_model.html#_systemd
- https://issues.redhat.com/browse/LOG-2341
=> LOG-2341: update vector journal logs to follow viaq data model

internal/k8shandler/collection.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2731
=> LOG-2731: Print error message only if error != nil

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/viaq_data_model.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/vector/conf_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, test/client/client.go, test/client/client_test.go, test/functional/normalization/flatten_labels_test.go
This PR:
* removes de dotting of labels from normalization
* https://issues.redhat.com/browse/LOG-2774
=> LOG-2774: Stop de-dot of labels

internal/generator/vector/conf_test.go, internal/generator/vector/normalize.go, internal/generator/vector/normalize_test.go, internal/generator/vector/source/audit_logs.go, internal/generator/vector/sources_test.go
Fixed `hostname` field in audit logs.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: 
=> LOG-2378: fix hostname in audit logs

apis/logging/v1/cluster_log_forwarder_types.go, docs/README.md, docs/how-to-add-new-output.md
=> NO-JIRA: Added doc/how-to-add-new-output to help developers.

Dockerfile.e2e
This PR:
* attempts to vendor dependencies for the image used to run functional and e2e tests
=> Vendor dependencies when creating e2e image

Makefile, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go, test/functional/outputs/loki/application_logs_test.go, test/functional/outputs/loki/application_logs_vector_test.go, test/functional/outputs/loki/audit_logs_test.go, test/helpers/loki/receiver.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2658
=> LOG-2658: Allow save logs events with timestamps that aren’t in strictly chronological order

bundle/metadata/properties.yaml
This PR adds the properties file to the bundle. The properties file is the location where dependencies and specific properties (like the maximum supported OpenShift version) can be defined.
=> Adding properties file

internal/cmd/functional-benchmarker/config/config.go, internal/cmd/functional-benchmarker/config/options.go, internal/cmd/functional-benchmarker/main.go, internal/cmd/functional-benchmarker/reports/gnuplot/gnuplot.go, internal/cmd/functional-benchmarker/reports/gnuplot/plot_scripts.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/runners/runner.go, internal/cmd/functional-benchmarker/stats/loss_stats.go, internal/cmd/functional-benchmarker/stats/loss_stats_test.go, internal/cmd/functional-benchmarker/stats/types.go, internal/runtime/pod.go, test/framework/functional/fluentd/deploy.go, test/framework/functional/framework.go, test/framework/functional/output_forward.go, test/framework/functional/read.go, test/helpers/oc/exec.go
This PR fixes various parts of the functional benchmarker:
* reporting of log loss
* formatting of html for config
* updates default image to 1.14.6
=> fix reporting for functional benchmarker

hack/testing-olm/test-040-eventrouter.sh, internal/collector/fluentd/visitors.go, internal/generator/fluentd/conf.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/ingress.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/viaq_data_model.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/fluentd/prometheus.go, internal/generator/fluentd/source/audit_logs.go, internal/generator/fluentd/source/container_logs.go, internal/generator/fluentd/sources.go, internal/generator/fluentd/sources_test.go, internal/generator/vector/sources.go
This PR:
* Optimizes the fluent conf to address performance issues
* Depends on https://github.com/ViaQ/logging-fluentd/pull/37
* Depends on a fluent image with https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/347
forward port of #1563 
https://issues.redhat.com/browse/LOG-2826
=> LOG-2826: optimize fluent conf for throughput

Makefile, bundle/manifests/cluster-logging.v5.3.0.clusterserviceversion.yaml, config/manager/manager.yaml, docs/configuration.md, hack/gen-olm-artifacts.py, internal/constants/constants.go, manifests/5.3/cluster-logging.v5.3.0.clusterserviceversion.yaml
Manual cherry-pick of #1522 
/cc @vimalk78 
=> Using related images naming scheme

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go, internal/generator/fluentd/output/elasticsearch/viaq_data_model.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go
Manually cherry pick for #1589 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2946
=> [release-5.4] LOG-2946: fix pattern for infrastructure indexing

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/source/audit_logs.go, internal/generator/fluentd/source/container_logs.go, internal/generator/fluentd/sources_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/framework/functional/fluentd/deploy.go
This PR:
* updates fluent evaluation of "IsStarted" to wait for fluent to tell us when it is ready to process messages
cc @alanconway
=> Update functional framework#IsStarted to evaluate process logs

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/source/audit_logs.go, internal/generator/fluentd/source/container_logs.go, internal/generator/fluentd/sources_test.go
This PR:
* adds follow_inodes to resolve [LOG-2792](https://issues.redhat.com//browse/LOG-2994)
https://issues.redhat.com/browse/LOG-2792
backport of #1609
=> LOG-2792: add follow_indode to fix stop of reading logs

internal/runtime/pod.go, test/framework/functional/framework.go
This PR:
* Updates builders to allow setting pull policy on container
=> update builders to allow setting pull policy

test/framework/functional/elasticsearch.go, test/framework/functional/output_elasticsearch7.go, test/framework/functional/read.go, test/functional/collection/input_selector_test.go
This PR:
* Enables the input_selector_test.go functional test for vector
* https://issues.redhat.com/browse/LOG-3013
=> LOG-3013: enable input selector functional test for vector

internal/generator/vector/conf_test.go, internal/generator/vector/normalize.go, internal/generator/vector/normalize_test.go, test/functional/normalization/audit_logs_format_test.go
a manual cherry-pick of #1615 
/cc 
/assign 
- Bugzilla:
- JIRA:  https://issues.redhat.com/browse/LOG-2961
=> [relase-5.5] LOG-2961: Fix 'Unknown Severity' error for audit logs in Google Cloud Logging

internal/runtime/monitoring.go, internal/runtime/runtime_test.go
This PR:
* fixes setting the SM namespace after refactoring
* https://issues.redhat.com/browse/LOG-3109
=> LOG-3109: fix CLO setting wrong ServiceMonitor NS

Dockerfile, Dockerfile.in
Sync Dockerfile in from Downstream
* https://issues.redhat.com/browse/LOG-2933
=> LOG-2933: Sync Dockerfile.in from downstream

hack/testing-olm/test-367-logforwarding.sh, test/framework/e2e/framework.go
This PR:
* fixes the check for DS availability
* Adds wait condition for logforwarding tests
=> add wait and fix check DS availability

Dockerfile, Dockerfile.in
This PR reverts the removal of go mod download
=> revert go mod download

must-gather/collection-scripts/gather_cluster_logging_operator_resources
Add the 'version' file to must-gather archive with product name and product version information
e.g.:
```
Red Hat OpenShift Logging
5.6.0
```
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2962 
=> LOG-2962: add the 'version'  file to Must-Gather archive

hack/testing-olm/test-040-eventrouter.sh, hack/testing-olm/test-050-consoleplugin.sh, test/e2e/consoleplugin/cleanup.sh, test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go, test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go, test/framework/e2e/framework.go, test/runtime/logging.go, test/runtime/runtime_test.go
This PR:
* forces a recreate of ClusterLogging if it exists and is expected to be refreshed for e2e
* updates e2e scripts to cleanup deployment as needed
=> recreate clusterlogging as needed

Makefile, apis/logging/v1/clusterlogforwarder_types_test.go, apis/logging/v1/suite_test.go, controllers/forwarding/forwarding_controller.go, internal/collector/vector/visitors.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/elements/stdout.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/viaq_data_model.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/fluentd/pipeline_to_output.go, internal/generator/fluentd/pipeline_to_output_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/pipelines.go, internal/generator/vector/sources_to_pipelines_test.go, internal/k8shandler/reconciler.go, internal/validations/clusterlogforwarder/suite_test.go, internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch.go, internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch_test.go, internal/validations/clusterlogforwarder/validate_singleton.go, internal/validations/clusterlogforwarder/validate_singleton_test.go, internal/validations/clusterlogforwarder/validations.go, test/framework/functional/cluster_log_forwarder.go, test/framework/functional/cluster_log_forwarder_test.go, test/functional/normalization/json_parsing_test.go, test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go, test/helpers/types/types.go
[LOG-2862](https://issues.redhat.com//browse/LOG-2862): Enable functional JSON parsing test for vector
(cherry picked from commit c16d0035ec11094d0f4c0569d6589053aeefe488)
* https://issues.redhat.com/browse/LOG-3144
* https://github.com/openshift/cluster-logging-operator/pull/1654
=> LOG-3144: Remove message field when parse json is enabled

test/helpers/kafka/broker.go
This PR brings back the RootCA -> IntermediateCA -> Server arrangement for the Kafka functional test
that serves as a guard against regression of the fix made for BZ 1904380 (support for multiple certificates in the CA bundle in the the Kafka Fluentd plugin)
The intermediate CA was removed as part of https://github.com/openshift/cluster-logging-operator/pull/1237.
/cc @vimalk78 
- Depending on PR(s): https://github.com/openshift/cluster-logging-operator/pull/1237
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1904380
- JIRA: https://issues.redhat.com/browse/LOG-3180
=> BZ 1904380: bring back the intermediate CA

internal/collector/collector.go, internal/collector/fluentd/run_script.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/prometheus.go, internal/generator/fluentd/sources_test.go, test/framework/functional/framework.go
the issue [LOG-3162](https://issues.redhat.com//browse/LOG-3162) is a clone of [LOG-3055](https://issues.redhat.com//browse/LOG-3055) for release-5.5
this is a manual cherry pick of 2d4c12fa2e4c8bd6600403940fc2e25558e76531
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-3162
=> [release-5.5] LOG-3162: Detect correct prometheus bind address

hack/testing-olm/assertions, hack/testing-olm/test-367-logforwarding.sh
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Update logforwarding script to fix function evaluation

internal/generator/fluentd/generators_test.go, internal/generator/fluentd/pipeline_to_output.go, internal/generator/fluentd/pipeline_to_output_test.go, test/framework/functional/message_templates.go, test/functional/normalization/audit_logs_format_test.go, test/functional/normalization/eventrouter_test.go
This PR:
* Adds openshift.cluster_id to records collected by fluentd
* git push --set-upstream origin log3112
=> LOG-3112: Add openshift.cluster_id to collection for fluentd

test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
Add some sleep to try to fix tests, it should make tests more stable 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Add some sleep to try fix test

files/dashboards/vector/openshift-logging-dashboard.json
This PR updates the dashboard for vector:
- Summary of log bytes collected and sent
- Rate of logs per type and output
- Identify produced logs by container
- Correct CPU and memory graphs
- Correct running container and open file handle graphs
* https://issues.redhat.com/browse/LOG-3232
=> LOG-3232: Refactor vector dashboard

internal/k8shandler/collection.go
This PR:
* fixes the removal of the servicemonitor associated with fluentd named collector deployment to only occur if the ds/fluentd exists
* https://issues.redhat.com/browse/LOG-3233
=> LOG-3233: fix servicemonitor continually being removed

internal/collector/prometheus_rule.go, internal/k8shandler/collection.go, internal/k8shandler/forwarding.go, internal/k8shandler/prometheus_rule.go, internal/metrics/alerts/fluentd.go, internal/metrics/alerts/vector.go, internal/reconcile/prometheus_rule.go, internal/runtime/prometheus_rule.go
This PR:
* fixes reconcilation of prometheusrule to get before create
*  https://issues.redhat.com/browse/LOG-3223
=> LOG-3223: fix reconciliation of promethusrule to get before create

Makefile, controllers/clusterlogging/clusterlogging_controller.go, controllers/forwarding/forwarding_controller.go, internal/k8shandler/reconciler.go, internal/telemetry/cloteleminfo.go, internal/telemetry/cloteleminfo_test.go
Reset/set metrics at beginning/end of each reconcile function.
=> LOG-2315 Duplicated items in log_logging_info metrics

must-gather/collection-scripts/gather_cluster_logging_operator_resources
This PR fix empty version file after merging #1687
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2962
=> LOG-2962: fix command for getting product version

internal/reconcile/service_account.go
This PR:
* fixes an issue where we are constantly regenerating the SA secret
* https://issues.redhat.com/browse/LOG-3211
=> LOG-3211: fix constant generation of sa secret

bundle/manifests/cluster-logging.v5.4.0.clusterserviceversion.yaml, config/manifests/bases/cluster-logging-operator.clusterserviceversion.yaml, manifests/5.4/cluster-logging.v5.4.0.clusterserviceversion.yaml
Adding valid subscription annotation to metadata
* https://issues.redhat.com/browse/LOG-3252
=> Adding valid subscription annotation to metadata

controllers/clusterlogging/clusterlogging_controller.go, internal/k8shandler/clusterloggingrequest.go, internal/k8shandler/status.go
This PR adds Elasticserch object to the list of watched object to prevent unauthorized changes 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2999
=> LOG-2999:Add watcher for Elasticsearch object

internal/collector/rbac.go, internal/k8shandler/collection.go, internal/k8shandler/logstore_lokistack.go, internal/reconcile/rbac.go
This PR:
* fixes the CLO trying to create an event when reconciling cluster rbac
* https://issues.redhat.com/browse/LOG-3334
=> LOG-3334: fix trying to create event for cluster resource

controllers/clusterlogging/clusterlogging_controller.go, internal/k8shandler/collection_test.go, internal/k8shandler/forwarding.go, internal/k8shandler/forwarding_test.go, internal/k8shandler/logstore_lokistack.go, internal/k8shandler/reconciler.go, internal/migrations/logstore_lokistack_test.go, internal/migrations/migrate_clusterlogforwarder.go, internal/migrations/migrate_clusterlogforwarder_test.go, internal/runtime/logging.go, test/runtime/logging.go
This PR:
* fixes a merge issue where we always validate against an empty spec which causes logging to never deploy
* https://issues.redhat.com/browse/LOG-3342
=> LOG-3342: fix validation on empty spec

internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/elasticsearch/viaq_data_model.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/vector/conf_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, test/functional/normalization/flatten_labels_test.go
This PR:
* replaces dots with underscores for namespace_labels when writing to Elasticsearch
* https://issues.redhat.com/browse/LOG-3341
=> LOG-3341: fix namespace_labels when writing to Elasticsearch

internal/reconcile/scc.go, internal/reconcile/scc_test.go
This PR:
* fixes update usecase to actually update the current to the desired
* replaces #1816 
* https://issues.redhat.com/browse/LOG-3235
=> LOG-3235: Update scc to desired

docs/features/collection.adoc
Update devel documentation with info regarding splunk support
* https://issues.redhat.com/browse/LOG-2913
cc @vparfonov
=> update docs for splunk feature

internal/k8shandler/reconciler.go
This PR:
* fixes the degraded pipeline status when adding default to an existing CLF pipeline
* https://issues.redhat.com/browse/LOG-3477
=> LOG-3477: fix degraded pipeline status

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_logstore_resources
Addressing issue comments on #1854 where gathering the Lokistack custom resource is conditional to existence of one.
/cc @jcantrill
=> Fix conditional gathering of Lokistack cr if any found

bundle/manifests/clusterlogging.clusterserviceversion.yaml, internal/collector/rbac_test.go, internal/runtime/pod.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, olm_deploy/operatorregistry/registry-deployment.yaml
This PR fixes some Pod Security errors and warning in functional and e2e tests.
/cc 
/assign 
/cherry-pick
=> Fix Pod Security errors in functional and e2e tests

apis/logging/v1/cluster_log_forwarder.go, internal/collector/collector.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/output/elasticsearch/elasticsearch.go, internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, internal/generator/vector/conf_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, test/client/test.go, test/framework/functional/builders.go, test/framework/functional/builders_test.go, test/framework/functional/cluster_log_forwarder.go, test/framework/functional/elasticsearch.go, test/framework/functional/framework.go, test/framework/functional/output_elasticsearch.go, test/framework/functional/output_kafka.go, test/framework/functional/write.go, test/functional/normalization/flatten_labels_test.go, test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go, test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go, test/functional/outputs/kafka/forward_to_kafka_test.go
This PR:
* Adds fluentd support for Elasticsearch 8
* Add functionality to functional framework to utilize secrets
* Allows fluentd to verify es version on startup which may lead to transient  error messages
* https://issues.redhat.com/browse/LOG-2544
=> LOG-2544: Add support for Elasticsearch v8 for fluentd

internal/collector/vector/visitors.go
This PR:
- reduce logging verbosity of vector
/cc 
/assign @jcantril 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3435
=> LOG-3435: reduce logging verbosity of vector

docs/features/collection.adoc, docs/features/tls_security_profile.adoc, internal/collector/collector_test.go, internal/collector/daemonset.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/fluentd/sources.go, internal/generator/fluentd/sources_test.go, internal/generator/logging.go, internal/generator/suite_test.go, internal/generator/tls.go, internal/generator/tls_test.go, internal/generator/vector/conf_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/kafka/kafka.go, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/security/security.go, internal/generator/vector/output/splunk/splunk.go, internal/generator/vector/outputs.go, internal/k8shandler/forwarding.go, internal/pkg/generator/forwarder/generator.go, internal/tls/profile.go, internal/tls/tls.go, test/framework/functional/constants.go, test/framework/functional/framework.go, test/framework/functional/output_http.go, test/functional/outputs/tls_security_profile_test.go
This PR:
* Implements TLS Security Profile for vector sinks
* Settings are honored in priority of: output, clusterlogforwarder, cluster
* https://issues.redhat.com/browse/LOG-3567
/hold
=> LOG-3567: Impl TLS Security Profile for vector

hack/gen-olm-artifacts.py
=> Fix namespace metadata in gen-olm-artifacts.py

internal/migrations/migrate_collection.go, internal/migrations/migrate_collection_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3733
=> LOG-3733: Checking on not nil given spec.Collection before migration

docs/administration/troubleshooting.md, docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc
1. This PR adds documentation for creating a `CRD` forwarding to an external Elasticsearch with version 8.x or greater. 
2. It also adds a `FAQ` section to the `CLO` troubleshooting documentation to address the changes in `LOG-3247`.
/cc @cahartma @jcantrill 
=> Updated docs

test/functional/normalization/multiline_exception_test.go
This PR adds functional test for checking JS client exception parsing
/cc 
/assign 
/cherry-pick 
- Depending on PR(s): https://github.com/ViaQ/logging-fluentd/pull/58
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3761
=> LOG-3761: add functional test for checking JS client exception parsing

internal/k8shandler/logstore.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3763
=> LOG-3763: improve k8s error checking before print error message

internal/k8shandler/reconciler.go, internal/logstore/elasticsearch/cleanup.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3759
=> LOG-3759: improve k8s error checking before print error message

internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go, internal/generator/vector/output/gcl/gcl_test.go, internal/generator/vector/output/security/security.go
This PR:
* fixes tls cipher and min version for cloudwatch and gcl
https://issues.redhat.com/browse/LOG-3813
=> LOG-3813: fix cloudwatch,gcl tls security profiles

internal/cmd/forwarder-generator/main.go, internal/pkg/generator/forwarder/generator.go
This PR:
* adds the ability to define secrets when generating config using the forwarder-generator
cc @vimalk78
=> add secrets to forwarder generator

internal/generator/vector/output/loki/loki_conf_test.go
This PR adds unit test with `tls.insecureSkipVerify=true` for Vector as collector and Loki as storage.
Issue was fixed in other PR: https://github.com/openshift/cluster-logging-operator/pull/1921 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-3445: add unit test with tls.insecureSkipVerify=true for Vector as collector and Loki as storage

internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/security/security.go
This PR:
* fixes the min tls and cipher for forwarding to loki
* https://issues.redhat.com/browse/LOG-3824
=> LOG-3824: fix loki tls security profile

internal/visualization/console/feature_map.go, internal/visualization/console/feature_map_test.go
This PR:
* enables all dev console features on 4.13 prerelease versions or greater
* https://issues.redhat.com/browse/LOG-3769
=> LOG-3769: all pre-release when checking devconsole features

Makefile, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/syslog_test.go, internal/generator/vector/outputs.go, test/framework/e2e/syslog.go, test/framework/functional/output_syslog.go, test/functional/outputs/syslog/forward_to_syslog_test.go, test/functional/outputs/syslog/rfc3164_test.go, test/functional/outputs/syslog/rfc5424_test.go
Syslog support in Vector
- JIRA: https://issues.redhat.com/browse/LOG-2288
=> Syslog support in Vector

internal/visualization/console/reconciler.go
This PR:
- Removes the old nginx configuration that was deprecated in 5.6.1
- Fixes the deployment configuration path to properly load the configuration created in a volume
/cc alanconway
/assign jcantrill
- JIRA: https://issues.redhat.com/browse/LOG-3929
=> Fix plugin configuration path when mounting ConfigMap as volume

internal/generator/fluentd/output/kafka/kafka.go, internal/generator/fluentd/output/kafka/kafka_test.go, internal/generator/fluentd/output/kafka/output_conf_kafka_test.go, internal/generator/fluentd/output/output_fluentd_buffer_test.go, test/framework/functional/cluster_log_forwarder.go, test/framework/functional/output_kafka.go, test/functional/outputs/kafka/forward_to_kafka_test.go
This is a manual cherrypick of #1975 
replaces #1979
=> LOG-3458: fix kafka buffer config when topic is same as payload key

docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc
This PR fixes the documentation for forwarding to Elasticsearch.
/cc @cahartma 
=> Update Elasticsearch feature doc

test/helpers/oc/oc_suite_test.go
Mainline fix for the functional tests on 4.14:
```
{"_ts":"2023-05-16T20:08:38.415061727Z","_file:line":"runner.go:103","_level":"9","_component":"oc-
runner","_message":"command result","arguments":"apply -f /tmp/podspec.yaml","error":{"Stderr":null},"output":"Error 
from server (Forbidden): error when creating \"/tmp/podspec.yaml\": pods \"log-generator\" is forbidden: violates
PodSecurity \"restricted:v1.24\": allowPrivilegeEscalation != false (container \"log-generator\" must set
securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"log-generator\" must set
securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"log-generator\" must set
securityContext.runAsNonRoot=true), seccompProfile (pod or container …
```
=> Added a SecurityContext to the test log generator to satisfy OCP 4.14

bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml, config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml, internal/collector/collector.go, internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go
lint corrections for the master branch
/cc @Clee2691 
/assign @cahartma
=> Make lint happy

internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-4184: fix config forwarding to default Loki using vector

internal/generator/vector/inputs.go, internal/generator/vector/sources_to_pipelines_test.go, test/functional/collection/input_selector_test.go
This PR:
* fixes input match labels that contain slash
* https://issues.redhat.com/browse/LOG-4091
=> LOG-4091: fix input matchLabels with slash

apis/logging/v1/clusterlogging_types.go, config/docs/templates/apis/asciidoc/members.tpl, config/docs/templates/apis/asciidoc/pkg.tpl, docs/reference/operator/api.adoc
This fixes our generator to show both CRs in the table
=> fix document generator to show all CRs

docs/features/logforwarding/parse-json-structured-logs.adoc
There has been confusion over the functionality of json parsing and ES index creation.    This document attempts to clear up those support requests.   Will also need to modify our downstream public docs to clear up some confusion over what is required or not.
/cc @syedriko @Clee2691 @vparfonov 
- https://issues.redhat.com/browse/LOG-4031
=> LOG-4031: Add feature doc for JSON parse and ES index creation

OWNERS
Quick update to match our latest releases
/cc @syedriko @Clee2691 @vparfonov
=> [release-5.5] Update owners file for 5.5

internal/runtime/pod.go, test/framework/functional/output_kafka.go
Removed runtime.InitContainerBuilder to avoid code duplication.
/cc @cahartma 
=> Removed runtime.InitContainerBuilder

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml, docs/README.adoc
This PR fix broken links to the documentation after migrates them Markdown to AsciiDoc
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4073
=> LOG-4073: fix link to the documentation

internal/logstore/lokistack/logstore_lokistack.go
Following the [Fine grained logs access enhancement proposal](https://github.com/openshift/enhancements/pull/1419), this PR removes the `logging-all-authenticated-application-logs-reader` ClusterRoleBinding that allows all authenticated users to view application logs in their namespaces.
This PR also introduces three ClusterRoles, one for each of the three log types (`application`, `infrastructure` and `audit`).
/cc @xperimental 
/assign @periklis
- JIRA: [LOG-4293](https://issues.redhat.com/browse/LOG-4293), [LOG-4294](https://issues.redhat.com/browse/LOG-4294)
- Enhancement proposal:  [Fine grained logs access enhancement proposal](https://github.com/openshift/enhancements/pull/1419)
=> Remove default application logs reader role binding

internal/validations/clusterlogforwarder/validations.go
This PR:
* fixes to validations to actually add it to the list
=> LOG-3829: validation to actually be used

internal/k8shandler/clusterloggingrequest.go, internal/k8shandler/finalizer.go, internal/k8shandler/logstore.go, internal/k8shandler/reconciler.go, internal/k8shandler/visualization.go
This PR:
* replaces getClusterLogging with similar loader function
* Removes unused ES cert code
* https://issues.redhat.com/browse/LOG-4315
=> LOG-4315: replace getClusterLogging with loader function

Makefile, internal/cmd/functional-benchmarker/config/options.go, internal/cmd/functional-benchmarker/main.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/runners/runner.go, internal/cmd/functional-benchmarker/stats/loss_stats.go, internal/cmd/functional-benchmarker/stats/loss_stats_test.go, internal/cmd/functional-benchmarker/stats/types.go, internal/cmd/functional-benchmarker/stats/types_test.go, internal/runtime/pod.go, internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go, test/framework/functional/output_forward.go, test/framework/functional/output_http.go
This PR:
* Updates the functional benchmarking tool to support testing of vector
* https://issues.redhat.com/browse/LOG-1913
cc @syedriko @alanconway
=> LOG-1913: Modify functional-bench-marker to support vector

internal/collector/collector.go, internal/collector/collector_test.go, internal/collector/fluentd/visitors.go, internal/collector/service_account.go, internal/collector/vector/visitors.go, internal/k8shandler/collection_test.go, internal/k8shandler/deployment.go, internal/metrics/logfilemetricexporter/factory.go, internal/runtime/pod.go, internal/utils/comparators/scc/comparator_test.go, internal/utils/utils.go, internal/visualization/console/config.go, internal/visualization/console/reconciler.go, test/framework/e2e/fluentd.go, test/framework/e2e/splunk.go, test/framework/e2e/syslog.go, test/framework/functional/framework.go, test/helpers/fluentd/receiver.go, test/helpers/loki/receiver.go, test/runtime/log_generator.go
Replaced GetBool/GetInt* with generic GetPtr, reduced code duplication.
=> Replaced GetBool/GetInt* with generic GetPtr

controllers/clusterlogging/clusterlogging_controller.go, controllers/forwarding/forwarding_controller.go, internal/collector/config.go, internal/k8shandler/clusterloggingrequest.go, internal/k8shandler/collection.go, internal/k8shandler/collection_test.go, internal/k8shandler/finalizer.go, internal/k8shandler/forwarding.go, internal/k8shandler/forwarding_test.go, internal/k8shandler/reconciler.go, internal/metrics/dashboards.go, internal/metrics/dashboards_test.go, internal/metrics/telemetry/cloteleminfo.go, internal/metrics/telemetry/cluster_log_forwarder.go, internal/metrics/telemetry/cluster_logging.go, internal/reconcile/configmaps.go, internal/validations/clusterlogging/validate_clusterlogging_spec.go, main.go
This PR:
* refactors reconciliation of logging to a single method
* fixes collector.spec not applied for multi CLF
* fixes resources not being deleted for multi CLF
* moves some telemetry code into telemetry package
* https://issues.redhat.com/browse/LOG-4427
* https://issues.redhat.com/browse/LOG-4410
cc @anpingli It would be good to do some extra testing of telemetry to ensure I didn't break something
=> Fix Collector reconciliation

internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account_test.go
This PR:
* fixes CLF permission check for custom application inputs
* https://issues.redhat.com/browse/LOG-4450
cc @Clee2691
=> LOG-4450: fix CLF permission check for custom inputs

Makefile, docs/README.adoc, docs/reference/operator/api.adoc, docs/reference/operator/secrets.adoc, internal/datamodels/operator/v1/doc.go, internal/datamodels/operator/v1/secrets.go
This PR:
* Documents the opinionated keys that are recognized for ClusterLogForwarder outputs
* https://issues.redhat.com/browse/LOG-4464
=> LOG-4464: Document keys used for secrets

internal/cmd/functional-benchmarker/config/options.go, internal/cmd/functional-benchmarker/main.go, internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/stats/types.go
This PR:
* fixes the functional benchmarker based on changes to the loader image
=> fix functional generator for 5.7

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_collection_resources
The must-gather looks for any namespaces that has a forwarder and runs the full resources gather on that namespace.   It also gathers for any pods of collectors.
/cc @Clee2691 @syedriko @vparfonov
- https://issues.redhat.com/browse/LOG-4404
=> LOG-4404: Fix must-gather to include multi-clf namespaces and pods

internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go
This PR fixes writing to the default lokistack:
* utilizes the CA associated with the service account
* supercedes #2147 
* changes base upon thread https://github.com/openshift/cluster-logging-operator/pull/2147#discussion_r1310271162
* https://issues.redhat.com/browse/LOG-4476
* introduced by #2138
=> LOG-4476: fix writing to default lokistack

internal/generator/vector/filter/apiaudit/doc.go, test/functional/filters/apiaudit/vrl/compatibility_test.go, test/functional/filters/apiaudit/vrl/exporter_test.go
=> NO-JIRA: Removed refs to non-public URL from code.

internal/k8s/loader/load.go, internal/k8s/loader/load_test.go, internal/k8s/loader/suite_test.go
This PR:
* fixes a nil pointer when trying to fetch CLF without matching CL
* https://issues.redhat.com/browse/LOG-4564
=> LOG-4564: fix nil pointer for CLF without CL

apis/logging/v1/cluster_log_forwarder.go, apis/logging/v1/cluster_log_forwarder_types.go, apis/logging/v1/zz_generated.deepcopy.go, bundle/manifests/clusterlogging.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml, config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml, docs/features/collection.adoc, docs/reference/operator/api.adoc, internal/generator/vector/inputs.go, internal/generator/vector/sources_to_pipelines_test.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go, test/e2e/flowcontrol/flowcontrol_test.go, test/functional/flowcontrol/application_test.go
This PR:
* change limitspec field name to PodLimit
* https://issues.redhat.com/browse/LOG-4568
=> LOG-4568: change limitspec field name to PodLimit

docs/features/logforwarding/filters/api-audit-filter.adoc
Minor fix in example text.
/cc @Pranjal-Gupta2 
=> NO-JIRA: Update api-audit-filter.adoc, add pipeline name in example

internal/metrics/dashboard/openshift-logging-dashboard.json
This PR improves the queries used for the first panels on the logging dashboard created by the operator. This PR is a follow-up of LOG-3846.
I can also create a separate JIRA issue, if needed.
/cc @cahartma @Clee2691
=> Improve logging dashboard overview queries

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-4590: fixing validation for Log Forwarder specification with filters 

apis/logging/v1/cluster_log_forwarder.go, apis/logging/v1/cluster_log_forwarder_types.go, apis/logging/v1/zz_generated.deepcopy.go, bundle/manifests/clusterlogging.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml, config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml, docs/features/collection.adoc, docs/reference/operator/api.adoc, internal/generator/vector/inputs.go, internal/generator/vector/sources_to_pipelines_test.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go, test/e2e/flowcontrol/flowcontrol_test.go, test/functional/flowcontrol/application_test.go
This PR:
* reverts #2184 
* Modifies the api docs to more accurately describe how it applies
* https://issues.redhat.com/browse/LOG-4568
* https://issues.redhat.com/browse/LOG-4592
cc @alanconway @QiaolingTang
=> Revert 4568

olm_deploy/operatorregistry/registry-deployment.yaml
This PR:
* fixes CI tests to properly sub the logging-view-console-plugin from CI registry
* does not fix any underlying issues with the test image
cc @syedriko
=> fix operator bundle for console plugin

controllers/forwarding/forwarding_controller.go, internal/k8shandler/reconciler.go, internal/validations/clusterlogforwarder/validate_http_content_type_headers.go, internal/validations/clusterlogforwarder/validate_http_content_type_headers_test.go, internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch.go, internal/validations/clusterlogforwarder/validate_json_parsing_to_elasticsearch_test.go, internal/validations/clusterlogforwarder/validate_singleton.go, internal/validations/clusterlogforwarder/validate_singleton_test.go, internal/validations/clusterlogforwarder/validate_url_to_output_tls_config.go, internal/validations/clusterlogforwarder/validate_url_to_output_tls_test.go, internal/validations/clusterlogforwarder/validations.go
Backport for https://github.com/openshift/cluster-logging-operator/pull/2191 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4441
=> LOG-4441: set invalid condition when using parse json with without setting structuredTypeKey or structuredTypeName

internal/collector/cloudwatch.go, internal/collector/collector.go, internal/generator/fluentd/output/security/security.go
This PR:
* uses the AWS token from the secret if specified
* https://issues.redhat.com/browse/LOG-4780
cc @cahartma
=> LOG-4780: use AWS token from secret in lieu of SA token

test/e2e/logforwarding/loki/forward_to_loki_test.go, test/e2e/logforwarding/splunk/forward_to_splunk_test.go, test/framework/e2e/framework.go, test/helpers/loki/receiver.go
This PR:
* Cherrypicks several test changes to resolve flakes and race conditions
blocking https://github.com/ViaQ/logging-fluentd/pull/104
cc @syedriko
=> Fix Loki test race condition 

internal/generator/vector/helpers/helpers.go, internal/generator/vector/source/audit_logs.go, internal/generator/vector/source/http_receiver.go, internal/generator/vector/source/journal_log.go, internal/generator/vector/source/kubernetes_logs.go, internal/generator/vector/source/sources.go
This PR:
* adds constructor functions for generator source elements
* https://issues.redhat.com/browse/LOG-4814
cc @syedriko @cahartma
=> LOG-4743: Add constructor functions for source generator elements

internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go, internal/cmd/functional-benchmarker/stats/loss_stats.go, internal/cmd/functional-benchmarker/stats/statistics.go, internal/cmd/functional-benchmarker/stats/types.go, internal/cmd/functional-benchmarker/stats/types_test.go, test/framework/functional/output_http.go
This PR:
* Modifies the functional-benchmarker to reduce the amount of work being done by the utility and offloads some of it to the receiver
* https://issues.redhat.com/browse/LOG-4809
cc @syedriko
=> LOG-4809: reduce stream file size for functional-benchmarker

internal/validations/clusterlogforwarder/validate_clusterlogforwarder_service_account.go
This PR:
* relaxes the need for RBAC for receiver inputs
* https://issues.redhat.com/browse/LOG-4815
cc @alanconway @syedriko
=> LOG-4815: relax the need for permissions on receiver input

internal/generator/vector/conf/complex_otel.toml, internal/generator/vector/normalize/dedot_labels.go, internal/generator/vector/output/cloudwatch/cloudwatch.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/gcl/gcl.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/http/http_test.go, internal/generator/vector/output/kafka/kafka.go, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/metrics/prometheus.go, internal/generator/vector/output/splunk/splunk.go, internal/generator/vector/output/syslog/syslog.go
This PR:
* refactors output elements to add alternate constructors
* refactor all outputs to use MakeID helper methods
* https://issues.redhat.com/browse/LOG-4832
=> LOG-4832: Add constructors for output elements

internal/generator/vector/normalize/schema/otel/transform.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/http/http_test.go
This PR:
* Refactors the OTEL http logic to reduce duplication
* Make use of id helpers for forthcoming refactoring
Blocked by #2266 
* https://issues.redhat.com/browse/LOG-4833
=> Fix otel test

apis/logging/v1/conditions.go, controllers/forwarding/forwarding_controller.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:https://issues.redhat.com/browse/LOG-4821
=> LOG-4821:fix status format for pipeline: set Validation fail reason if miss configuration outputs, inputs or filters

internal/generator/vector/output/loki/loki.go
This is a manual forward port of [LOG-4852](https://github.com/openshift/cluster-logging-operator/pull/2284).
Original description:
This PR addresses forwarding to an internal LokiStack where in the legacy case, if the `pipelines.outputs` is not `default` it will not apply the `logcollector-token` secret's `token` and `ca.crt`. For a CLF named instance it will add the `logcollector` service account token to be used.
- JIRA: https://issues.redhat.com/browse/LOG-4881
=> LOG-4881: Vector collector Pods no longer picks up the log collector SAs Secret as a fallback

Makefile, hack/revert-bundle.sh
This PR:
* reverts the generated CSV if the only change is the "createdAt"
=> revert bundle CSV if only createdAt updated

docs/administration/configuration.md, docs/administration/unmanaged.adoc, hack/logsamples/viaq_audit_kubernetes.json, hack/logsamples/viaq_audit_openshift.json, hack/logsamples/viaq_container.json, hack/logsamples/viaq_journal.json
This PR:
* Adds documentation for Unmanaged
* log samples
cc @alanconway
=> Add Unmanaged docs

internal/generator/vector/source/kubernetes_logs.go, internal/generator/vector/source/kubernetes_logs_test.go, internal/generator/vector/source/label_selector.go, internal/generator/vector/source/label_selector_test.go
This PR:
* Implements input match labels in support of [LOG-2227](https://issues.redhat.com//browse/LOG-2227)
* https://issues.redhat.com/browse/LOG-4867
=> LOG-4867: Impl input match label expressions

apis/logging/v1/input_types.go, bundle/manifests/clusterlogging.clusterserviceversion.yaml, internal/migrations/clusterlogforwarder/migrate_inputs.go, internal/migrations/clusterlogforwarder/migrate_inputs_test.go, internal/validations/clusterlogforwarder/inputs/application.go, internal/validations/clusterlogforwarder/inputs/validate.go, internal/validations/clusterlogforwarder/inputs/validate_test.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR:
* Adds input validations to support log filtering
* https://issues.redhat.com/browse/LOG-4862
cc @cahartma @Clee2691
=> LOG-4862: Add inputSpec validation

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR:
adds infrastructure annotations
#2285
=> LOG-4604: Add infrastructure annotations

must-gather/collection-scripts/gather
The collection scripts can be executed in parallel to save time when running the MG.
Process:
1. Running gather scripts in parallel
2. Waiting for the subprocesses to finish execution.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Running gather scripts in background

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
This PR fix validation for Loki output spec: should fail if URL not provided
/cc 
/cherry-pick /release-5.8
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4822
=> LOG-4822: Loki output without URL should fail validation

internal/generator/vector/outputs.go, internal/generator/vector/outputs_test.go
This PR:
* fixes the case where outputs which define no secret still generate config with the legacy token secret
* Adds a function for secret special handling of generated default loki outputs
* https://issues.redhat.com/browse/LOG-4962
cc @xperimental @Clee2691
=> LOG-4962: fix outputs with no secret adding bearer token

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
manual cherry-pick for #2323
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com//browse/LOG-4893
=> LOG-4893: add validation for checking if provided not secure URL along with TLS configuration

internal/collector/collector.go, internal/collector/daemonset.go, internal/factory/resource_names.go, internal/generator/fluentd/conf.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/forwarder/generator.go, internal/generator/vector/conf.go, internal/generator/vector/conf_test.go, internal/generator/vector/sources.go, internal/k8shandler/collection.go, internal/k8shandler/forwarding.go, internal/pkg/generator/forwarder/generator.go
revert #2332  to give more time for consumption, but I don't see an alternative
=> Revertlog5009

internal/collector/collector.go, internal/collector/daemonset.go, internal/factory/resource_names.go, internal/generator/fluentd/conf.go, internal/generator/fluentd/conf_test.go, internal/generator/fluentd/fluent_conf_test.go, internal/generator/forwarder/generator.go, internal/generator/vector/conf.go, internal/generator/vector/conf_test.go, internal/generator/vector/sources.go, internal/k8shandler/collection.go, internal/k8shandler/forwarding.go, internal/pkg/generator/forwarder/generator.go
This reverts commit ea68926cfe7b4c9f60ea42285d6bd3b960d9e4ca.
=> Revert "Revert "LOG-5009: HTTP receiver service in endless reconcile""

Makefile
=> NO-JIRA: Makefile, fix missing references to $(OPERATOR_SDK)

hack/run-linter, internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_drop_filter.toml, internal/generator/vector/conf/complex_es_no_ver.toml, internal/generator/vector/conf/complex_es_v6.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/complex_otel.toml, internal/generator/vector/normalize/dedot_labels.go, internal/generator/vector/output/azuremonitor/azm_advance.toml, internal/generator/vector/output/azuremonitor/azm_common.toml, internal/generator/vector/output/azuremonitor/azm_skip_tls.toml, internal/generator/vector/output/azuremonitor/azm_tls.toml, internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/factory_test_loki_no_throttle.toml, internal/generator/vector/output/factory_test_loki_with_throttle.toml, internal/generator/vector/output/gcl/gcl_test.go, internal/generator/vector/output/http/http_test.go, internal/generator/vector/output/kafka/kafka_test.go, internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/splunk/splunk_test.go, internal/generator/vector/output/syslog/syslog_test.go, test/framework/functional/vector/deploy.go, test/functional/normalization/message_format_test.go, test/functional/outputs/http/forward_to_http_test.go
This PR:
* Replaces all lua transforms with VRL equivalent
* Adds linter to check use of lua transforms
https://issues.redhat.com/browse/LOG-5028
=> LOG-5028: Replace lua transforms with VRL

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml
5.8 version of changes
- https://issues.redhat.com/browse/LOG-5034
=> [release-5.8] Set annotation to false to remove required role field at sts install

internal/collector/vector/visitors.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4884
=> LOG-4884: explicitly set env variable KUBERNETES_SERVICE_HOST=kubernetes.default.svc

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml
CLO needs to be included in new category in OperatorHub.   Add "observability" to the categories list.
- https://issues.redhat.com/browse/LOG-4691
=> LOG-4691: Add to the observability category in operatorhub

internal/generator/vector/output/factory_test_loki_with_throttle.toml, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/loki/with_custom_bearer_token.toml, internal/generator/vector/output/loki/with_custom_labels.toml, internal/generator/vector/output/loki/with_default_labels.toml, internal/generator/vector/output/loki/with_default_logcollector_bearer_token.toml, internal/generator/vector/output/loki/with_default_tls.toml, internal/generator/vector/output/loki/with_insecure.toml, internal/generator/vector/output/loki/with_insecure_nocert.toml, internal/generator/vector/output/loki/with_tenant_id.toml
This PR adding remap transformation to be ensured that all labels are present, to avoid error in `loki.labels` step.
https://vector.dev/docs/reference/configuration/sinks/loki/#labels. At the moment `labels` section doesn't support fallback feature.
There is opened issue for this but not resolved yet: https://github.com/vectordotdev/vector/issues/1692
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4865
=> LOG-4865: replace loki.labels with remap transformation

api/logging/v1/cluster_log_forwarder.go, api/logging/v1/clusterlogforwarder_types_test.go, api/logging/v1/conditions.go, internal/controller/clusterlogging/clusterlogging_controller.go, internal/controller/forwarding/forwarding_controller.go
/cc 
/assign 
/cherry-pick 
https://issues.redhat.com/browse/LOG-5137
=> LOG-5137: Fix nil pointer exception in Synchronize()

cmd/main.go
This PR:
* Updates controller cache to based upon WATCH_NAMESPACE
to fix the mismatch in behavior between the code and permissions generated by OLM.  This bug was introduced with #2358
* https://issues.redhat.com/browse/LOG-5189
cc @Clee2691
=> LOG-5189: Fix controller runtime cache to evaluate WATCH_NAMESPACE

internal/controller/clusterlogging/clusterlogging_controller.go
This PR:
* fixes CL controller attempting to update status for a CLF that does not exist
https://issues.redhat.com/browse/LOG-5196
cc @xperimental
=> LOG-5196: fix updating CLF status when it does not exist

config/docs/templates/apis/asciidoc/pkg.tpl, docs/reference/operator/api.adoc
Additional updates to fix titles, IDs in the templates and make metadata easier to uncomment for doc team
Will do manual cherrypicks to regenerate doc files.
=> Additional minor updates to templates

config/docs/templates/apis/asciidoc/pkg.tpl, docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2398
Links:
=> [release-5.8] Additional minor updates to templates

config/docs/templates/apis/asciidoc/pkg.tpl, docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2398
Links:
=> [release-5.7] Additional minor updates to templates

config/docs/templates/apis/asciidoc/pkg.tpl, docs/reference/operator/api.adoc
Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/2398
Links:
=> [release-5.6] Additional minor updates to templates

internal/generator/forwarder/generator.go, internal/generator/helpers/formatter.go, internal/generator/helpers/formatter_test.go
This PR:
* Adds a formatter for generated vector.toml
* https://issues.redhat.com/browse/LOG-5195
=> LOG-5195: Add vector config formatter

Makefile, test/functional/normalization/loglevel/container_logs_test.go, test/functional/normalization/loglevel/journal_logs_test.go
This PR:
* enables the container log level functional tests for vector
=> Enable container log_level tests for vector

internal/validations/clusterlogforwarder/outputs/tuning.go, internal/validations/clusterlogforwarder/outputs/tuning_test.go, test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go, test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go, test/functional/outputs/http/forward_to_http_test.go, test/functional/outputs/kafka/forward_to_kafka_test.go, test/functional/outputs/loki/application_logs_vector_test.go, test/functional/outputs/splunk/forward_to_splunk_test.go
This PR adds validation and functional tests for outputs and their supported compression types.
- JIRA:
- https://issues.redhat.com/browse/LOG-5193
- https://issues.redhat.com/browse/LOG-5245
- https://issues.redhat.com/browse/LOG-5246
=> LOG-5245 & LOG-5246 & LOG-5193: output compression validation

test/functional/outputs/loki/application_logs_vector_test.go
This PR fixes the functional test for Loki and compression. It was not setting the tuning parameters as expected.
/cc @cahartma
=> fix loki functional test for compression

internal/validations/clusterlogforwarder/validations.go
This PR adds in the validation to the validations for disk
https://issues.redhat.com/browse/LOG-5166
=> LOG-5166: Wire validation into validations

test/framework/functional/vector/deploy.go, test/functional/normalization/loglevel/journal_logs_test.go
Enable the journal log level test for vector
https://issues.redhat.com/browse/LOG-5255
=> LOG-5155: Enable journal log level tests for vector

internal/generator/vector/output/common/buffer.go, internal/generator/vector/output/config_strategy.go, internal/validations/clusterlogforwarder/outputs/tuning.go, internal/validations/clusterlogforwarder/outputs/tuning_test.go, internal/validations/clusterlogforwarder/validations.go
Revert buffer validation
* https://issues.redhat.com/browse/LOG-5166
=> Revert buffer valid

bundle/metadata/properties.yaml
Quick update based on QE release testing
- https://issues.redhat.com/browse/LOG-5277
=> LOG-5277: Update maxOpenShiftVersion to 4.17

test/e2e/collection/security/container_security_test.go, test/framework/e2e/framework.go, test/framework/e2e/wait.go, test/helpers/oc/runner.go
This fix attempts to address the container security flake
=> another attempt to fix security e2e flake

go.mod, go.sum, test/framework/common/log/buffered_log_writer.go, test/framework/e2e/framework.go, test/framework/functional/framework.go
This PR:
* adds a buffered log writer that is only flushed when logs failed to attempt to clean up the test artifacts when tests fail
=> Impl buffered log writer for tests

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
In this PR, improved the validation logic, for a secure (HTTPS) URL and given TLS configuration for outputs don't require a URL at all (e.g. Amazon CloudWatch or Google Cloud Logging). Also refined error message
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5307
=> LOG-5307: enhancing logic for is URL secure validation

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
cherry-pick for  https://github.com/openshift/cluster-logging-operator/pull/2428
/cc 
/assign 
/cherry-pick 
* https://issues.redhat.com/browse/LOG-5467
=> [release-5.8]LOG-5307: enhancing logic for is URL secure validation

controllers/forwarding/forwarding_controller_test.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go, internal/validations/clusterlogging/validate_clusterlogging_spec.go, internal/validations/clusterlogging/validate_clusterlogging_spec_test.go, internal/validations/clusterlogging/validations.go
Manual cherry-pick of #2394 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> [release-5.8]LOG-5062: align validation with documentation

bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/collector_alerts.yaml
This PR:
* fixes the bundle for the changes introduced by #2438 
* https://issues.redhat.com//browse/LOG-5381
cc @vparfonov @Clee2691
=> LOG-5381: fix bundle to include alert

go.mod, go.sum
Amendment to #2453 to address CVE-2023-45288 in `release-5.9`
/cc @jcantrill
=> [release-5.9] LOG-5440: Address CVE-2023-45288

go.mod, go.sum
Amendments to #2454 to address CVE-2023-45288
/cc @jcantrill
=> Address CVE-2023-45288

OWNERS
=> NO-JIRA: Add @xperimental to approvers

OWNERS
=> [release-5.8] NO-JIRA: Add @xperimental to approvers

OWNERS
=> [release-5.7] NO-JIRA: Add @xperimental to approvers

OWNERS
=> [release-5.9] NO-JIRA: Add @xperimental to approvers

go.mod, go.sum
release-6.0 CLO is failing.  Found a related error and hoping `go mod tidy` resolves.
/cc @Clee2691 @vparfonov @xperimental 
/assign @jcantrill @periklis 
- https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=61130231
- https://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/work/tasks/231/61130231/s390x.log
Blocks:   https://gitlab.cee.redhat.com/openshift-logging/log-collection-midstream/-/merge_requests/3610
=> Fix build issue in midstream CLO

internal/validations/errors/errors.go, internal/validations/errors/errors_test.go
Backport for #2425 
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5514
=> LOG-5514: remove collector daemonset only if 'Not authorized to collect' error occurs

internal/generator/vector/helpers/secrets.go, internal/generator/vector/output/common/auth/auth.go, internal/generator/vector/output/common/auth/basic.go, internal/generator/vector/output/common/auth/bearer_token.go
This PR:
* Refactors Http auth into separate package for reuse
* https://issues.redhat.com/browse/LOG-5515
@Clee2691 @cahartma @vparfonov
=> LOG-5515: Refactor output http auth templates

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_drop_filter.toml, internal/generator/vector/conf/complex_es_no_ver.toml, internal/generator/vector/conf/complex_es_v6.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/complex_otel.toml, internal/generator/vector/conf/complex_prune_filter.toml, internal/generator/vector/conf/container.toml, internal/generator/vector/filter/openshift/viaq/normalize.go, internal/generator/vector/pipeline/adapter_test_drop_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_inNotIn_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_inOnly_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_notIn_only_filter.toml
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5518
=> LOG-5518: fix warning[E900]: unused result for function call

internal/generator/vector/helpers/helpers.go, internal/generator/vector/helpers/secrets.go, internal/generator/vector/output/gcl/gcl.go, internal/generator/vector/output/gcl/gcl_test.go, internal/generator/vector/output/gcl/gcl_with_tls.toml, internal/generator/vector/output/gcl/gcl_with_token.toml, internal/generator/vector/output/gcl/suite_test.go
This PR:
* Refactors GCL output to use observability API
* https://issues.redhat.com/browse/LOG-5515
@Clee2691 @cahartma @vparfonov
=> LOG-5515: Refactor GCL output to use OBS API

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, internal/generator/vector/output/syslog/suite_test.go, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/syslog_test.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tls_with_field_references.toml, internal/generator/vector/output/syslog/udp_with_every_setting.toml, internal/generator/vector/output/syslog/xyz_defaults.toml
This PR:
* Refactors syslog output to use observability API
* https://issues.redhat.com/browse/LOG-5515
@Clee2691 @cahartma @vparfonov
=> LOG-5515: Refactor syslog to use OBS API

config/prometheus/collector_alerts.yaml
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5429
=> [release-5.9]LOG-5429: add namespace label to ElasticsearchDeprecation, FluentdDeprecation, KibanaDeprecation alerts

internal/validations/errors/errors.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5532
=> LOG-5532: fix error handling: make checking case-insensitive

controllers/clusterlogging/clusterlogging_controller.go, internal/visualization/console/coo_compatibility.go, internal/visualization/console/coo_compatibility_test.go, internal/visualization/console/reconciler.go
This is a backport of #2509 to `release-5.8`.
- Depending on PR(s): #2509
- JIRA: [LOG-5463](https://issues.redhat.com//browse/LOG-5463)
=> LOG-5463: Do not deploy logging ConsolePlugin if already managed by COO

api/observability/v1/clusterlogforwarder_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
This PR:
* Adds managementState to the OBS API
* https://issues.redhat.com/browse/LOG-5569
=> LOG-5569: Add managementState to obs API

internal/api/observability/tuning.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA:Fix NPE is output type spec not declared

internal/generator/vector/input/source.go, internal/generator/vector/input/source_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA:Fix NPE if inputs spec not declared

controllers/clusterlogging/clusterlogging_controller.go, internal/visualization/console/coo_compatibility.go, internal/visualization/console/coo_compatibility_test.go, internal/visualization/console/reconciler.go
This is a backport of #2509 to `release-5.7`.
- Depending on PR(s): #2509
- JIRA: [LOG-5464](https://issues.redhat.com//browse/LOG-5464)
=> LOG-5464: Do not deploy logging ConsolePlugin if already managed by COO

api/observability/v1/conditions.go, cmd/main.go, internal/api/context/context.go, internal/api/observability/tls.go, internal/controller/observability/clusterlogforwarder_controller.go, internal/controller/observability/load.go, internal/generator/vector/helpers/secrets.go, internal/validations/observability/common/constants.go, internal/validations/observability/common/suite_test.go, internal/validations/observability/common/validate.go, internal/validations/observability/common/validate_test.go, internal/validations/observability/inputs/receivers.go, internal/validations/observability/inputs/receivers_test.go, internal/validations/observability/inputs/validate.go, internal/validations/observability/validate.go
This PR:
* adds input secret (and configmap) validation for receivers
* Adds utility functions to list keys from an inputTLS spec
* https://issues.redhat.com/browse/LOG-5605
* blocked by #2528 
cc @vparfonov @Clee2691
=> LOG-5605: Add input secret validation

api/observability/v1/conditions.go, internal/validations/observability/pipelines/prune_filter_test.go, internal/validations/observability/pipelines/suite_test.go, internal/validations/observability/pipelines/validate.go, internal/validations/observability/pipelines/validate_test.go, internal/validations/observability/validate.go
This PR:
* Adds pipeline validation to ensure references exist 
* https://issues.redhat.com/browse/LOG-5621
cc @Clee2691 @vparfonov
=> LOG-5621: Add pipeline validations

bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml
This PR fix bundle file to use disk usage alert
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5644
=> LOG-5644: fix CRD for Disk Usage Alert

internal/collector/trust_bundle.go, internal/controller/observability/clusterlogforwarder_controller.go, internal/controller/observability/collector.go, internal/controller/observability/collector_test.go
This PR speeds up the unit tests by removing polling delays
=> speed up unit tests

bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/collector_alerts.yaml
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5645
=> LOG-5645: fix trigger threshold: was (x*100 > 0.15) but must be (x*10 > 15)

internal/api/observability/output_types.go, internal/api/observability/tls.go, internal/collector/cloudwatch.go, internal/collector/collector.go, internal/collector/collector_test.go, internal/collector/common/path.go, internal/generator/vector/output/common/tls/tls.go, internal/generator/vector/output/gcl/gcl.go, test/framework/functional/framework.go
This PR:
* Enables the projected SA volume based upon outputs that require it
* Enables cloudwatch env vars for projected SA tokens
* https://issues.redhat.com/browse/LOG-5570
cc @Clee2691 @vparfonov @cahartma
=> LOG-5570: Enable Projected SA volume and CW env vars

internal/api/observability/tls.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA: fix potential NPE if TLS not configured

internal/validations/observability/validate_permissions.go, internal/validations/observability/validate_permissions_test.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA: fix potential NPE during validation inputs

internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go, test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go
Use` get(object, path)` function to get the value of a given path: e.g.: for label `kubernetes.labels.my-typekey` will use `val = get!(value: ., path: ["kubernetes","labels","my-typekey"])`
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5524
=> LOG-5524: use get(object, path) function to get the value of a given path

internal/controller/clusterlogging/clusterlogging_controller.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5603
=> LOG-5603: cleanup previously set 'deprecated' status if config was fixed

api/logging/v1/clusterlogging_types.go, bundle/manifests/logging.openshift.io_clusterloggings.yaml, config/crd/bases/logging.openshift.io_clusterloggings.yaml
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5373
=> LOG-5373: update validation regex for ocpConsole.timeout according to the ocpPlugin requirements

go.mod, go.sum
This PR fixes up go.mod and go.sum to address issues in productization
=> fix tidy go.mod go.sum

internal/collector/collector.go, internal/collector/collector_test.go
This PR:
* fixes audit volume/volumeMount names that clashed
* updates constant names
cc @cahartma
=> fix audit volume names

Makefile, test/framework/functional/framework.go, test/framework/functional/vector/deploy.go, test/functional/outputs/azuremonitor/forward_to_azuremonitor_test.go, test/runtime/observability/cluster_log_forwarder.go
This test fixes deploying the functional framework and the Azure monitor output test.
- JIRA: https://issues.redhat.com/browse/LOG-5709
=> LOG-5709: Enable AzureMonitor test

Makefile, test/framework/functional/output_http.go, test/functional/outputs/http/forward_to_http_test.go
The PR refactors HTTP output functional tests
- JIRA: https://issues.redhat.com/browse/LOG-5712
=> LOG-5712: Enable http output functional tests

Makefile, internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/container.toml, internal/generator/vector/output/metrics/prometheus.go, test/functional/metrics/metrics_test.go, test/functional/metrics/suite_test.go
This PR:
* refactors the functional metrics test for vector
* refactors the tests to use the obs API
https://issues.redhat.com/browse/LOG-5721
=> LOG-5721: Refactor functional metrics tests

Makefile, test/functional/normalization/loglevel/container_logs_test.go, test/functional/normalization/loglevel/journal_logs_test.go
This PR: enables the functional log level tests
* https://issues.redhat.com/browse/LOG-5723
=> LOG-5723: Enable functional loglevel tests

Makefile, test/functional/pipelines/pipelines_test.go
This PR:
enables the functional pipeline test
* https://issues.redhat.com/browse/LOG-5724
cc @Clee2691
=> LOG-5724: Refactor functional pipeline_test to use obs API

Makefile, test/functional/filters/drop/drop_filter_test.go, test/functional/normalization/loglevel/container_logs_test.go, test/functional/normalization/loglevel/journal_logs_test.go
This PR:
* Refactors the functional drop filter test to use obs API
https://issues.redhat.com/browse/LOG-5717
=> LOG-5717: refactor functional drop filter test to use obs API

Makefile, test/functional/outputs/kafka/forward_to_kafka_test.go
This PR refactors Kafka output functional tests
- JIRA: https://issues.redhat.com/browse/LOG-5713
=> LOG-5713: Enable Kafka output functional tests

internal/generator/vector/output/factory.go
This PR makes the vector generator output factory depend upon the obs API
=> fix make generator output factory depend upon obs API

Makefile, api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, test/framework/functional/output_splunk.go, test/functional/outputs/splunk/forward_to_splunk_test.go
This PR refactors the Splunk functional tests
- JIRA: https://issues.redhat.com/browse/LOG-5715
=> LOG-5715: Enable Splunk output functional tests

Makefile, test/functional/inputs/http/http_input_test.go, test/functional/inputs/syslog/syslog_input_test.go, test/helpers/syslog/sender.go
This PR:
* refactors the functional input receiver tests to use the obs API
https://issues.redhat.com/browse/LOG-5720
=> LOG-5720: Refactor functional input tests to use obs API

Makefile, test/functional/outputs/logstash/forward_to_logstash_test.go, test/functional/outputs/logstash/suite_test.go
This PR refactors the logstash functional test
- JIRA: https://issues.redhat.com/browse/LOG-5741
=> LOG-5741: Refactor logstash functional test

Makefile, test/framework/functional/framework.go, test/functional/outputs/tls_security_profile_test.go, test/functional/outputs/unavailable_forward_output_test.go
This PR refactors the TLS & unavailable output functional tests
/cc @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-5743
=> LOG-5743: Refactor tls, unavailable output functional tests

Makefile, hack/testing-olm/test-040-eventrouter.sh, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/es_with_tls.toml
This PR:
* Enables the e2e event router test
* Fixes ESv6 to require id_key
* Fixes ID to use object UID if it is a kubernetes event
https://issues.redhat.com/browse/LOG-5733
=> LOG-5742: Enable eventrouter e2e test

api/observability/v1/clusterlogforwarder_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
This PR: fixes the SA name validation to allow termination with a number
https://issues.redhat.com/browse/LOG-5728
=> LOG-5728: fix serviceaccount validation failure

internal/collector/collector.go
This PR adds a small helper to the code generating the Volume and VolumeMount structs that sanitizes the volume names by removing dots from the names. The paths are not changed.
- JIRA: [LOG-5753](https://issues.redhat.com//browse/LOG-5753)
=> LOG-5753: Remove dots from volume names

hack/logsamples/otlp_audit_host.json, hack/logsamples/otlp_audit_kube.json, hack/logsamples/otlp_audit_openshift.json, hack/logsamples/otlp_container.json, hack/logsamples/otlp_journal.json, hack/logsamples/viaq_audit_host.json
Sample logs as they are currently grouped, reduced and sent 
- Parent task:  https://issues.redhat.com/browse/LOG-5370
- Sub-task: https://issues.redhat.com/browse/LOG-5477 
- Other tasks:  https://issues.redhat.com/browse/LOG-5476 https://issues.redhat.com/browse/LOG-5478 https://issues.redhat.com/browse/LOG-5479 https://issues.redhat.com/browse/LOG-5480
- Enhancement proposal: https://github.com/openshift/enhancements/pull/1618
=> LOG-5477 Add otlp example logs

Makefile, hack/logsamples/otlp_audit_host.json, hack/logsamples/otlp_audit_kube.json, hack/logsamples/otlp_audit_openshift.json, hack/logsamples/otlp_container.json, hack/logsamples/otlp_journal.json, hack/testing-olm/test-060-flowcontrol.sh, test/e2e/flowcontrol/cleanup.sh, test/e2e/flowcontrol/flowcontrol_test.go, test/e2e/flowcontrol/utils.go
This PR:
* Enables the flow_control e2e test for the observability API
* https://issues.redhat.com/browse/LOG-5736
cc @Clee2691
=> LOG-5736: Enable flowcontrol e2e test for observability API

Makefile, hack/test-e2e-olm.sh, test/e2e/input_selection/input_selection_test.go
This PR:
* enables the e2e input selection test
* https://issues.redhat.com/browse/LOG-5791
=> LOG-5791: Enable input selection e2e test

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/container.toml, internal/generator/vector/filter/openshift/viaq/audit.go, internal/generator/vector/filter/openshift/viaq/common.go, internal/generator/vector/filter/openshift/viaq/filter.go, internal/generator/vector/filter/openshift/viaq/journal.go, internal/generator/vector/pipeline/adapter_test_drop_filter.toml, internal/generator/vector/pipeline/adapter_test_kube_api_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_inNotIn_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_inOnly_filter.toml, internal/generator/vector/pipeline/adapter_test_prune_notIn_only_filter.toml
This PR adds the field "message" to the "_internal" field for all outputs
- https://issues.redhat.com/browse/LOG-5807
- https://issues.redhat.com/browse/LOG-5792
=> LOG-5807: Add message to internal field in viaq remaps

api/observability/v1/clusterlogforwarder_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, internal/validations/observability/filters/validate.go, internal/validations/observability/validate.go, test/e2e/collection/apivalidations/api_validations_test.go, test/e2e/collection/apivalidations/log5788_mulitiline_ex_filter.yaml, test/e2e/collection/apivalidations/log5793_bearer_token_from_sa.yaml, test/e2e/collection/apivalidations/suite_test.go
This PR:
* fixes validation failure for filters
* Adds an apivalidation test
* fixes validation for bearer token from sa
https://issues.redhat.com/browse/LOG-5788
https://issues.redhat.com/browse/LOG-5793
=> LOG-5788: fix api validations

api/observability/v1/clusterlogforwarder_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, test/e2e/collection/apivalidations/log5793_bearer_token_from_sa.yaml
Follow-up to #2637
- JIRA: [LOG-5793](https://issues.redhat.com//browse/LOG-5793)
=> LOG-5793: Fix validation for bearer token source

docs/features/logforwarding/outputs/otlp-forwarding.adoc
subtask of:  
https://issues.redhat.com/browse/LOG-5370
=> LOG-5722:  Add OTLP feature doc

internal/api/observability/tuning.go, internal/api/observability/tuning_test.go
This PR:
* fixes tuning parameters not being propegated to config for GCL
* Adds a supporting unit test
* https://issues.redhat.com/browse/LOG-5811
=> LOG-5811: fix tuning for GCL

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
This PR:
* fixes the auth validation for cloudwatch to require a user to set something
cc @cahartma @vparfonov
=> fix validation to require cloudwatch auth

api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml
this pr fixes the CW auth enum mismatch
cc @cahartma
=> fix mismatched CW enum value

Makefile, test/e2e/input_selection/input_selection_test.go, test/framework/e2e/framework.go
This PR:
* fixes and properly enables the input_selection e2e test
* removes e2e test exclusions
* adds an e2e framework function to allow explicit NS creation for testing
* https://issues.redhat.com/browse/LOG-5791
=> LOG-5791: fix Makefile for e2e input_selection

Makefile, internal/generator/vector/input/receiver.go, internal/generator/vector/output/common/encoding.go, internal/generator/vector/output/common/tls/tls.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/kafka/kafka.go, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/otlp/otlp.go, internal/utils/json/json.go, internal/validations/observability/inputs/application.go, internal/validations/observability/pipelines/validate_test.go, internal/validations/observability/validate_permissions.go, test/e2e/flowcontrol/utils.go, test/framework/e2e/fluentd.go, test/framework/e2e/framework.go, test/functional/filters/prune/prune_filter_test.go
This PR re-enables the linter
https://issues.redhat.com/browse/LOG-5825
cc @Clee2691 @vparfonov @cahartma
=> LOG-5825: Re-enable linter and fix failures

internal/generator/vector/output/cloudwatch/cloudwatch.go, internal/generator/vector/output/cloudwatch/cw_groupname_with_aws_credentials.toml, internal/generator/vector/output/cloudwatch/cw_with_groupname.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_and_default_mintls_ciphers.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec_insecure_verify.toml, internal/generator/vector/output/cloudwatch/cw_with_url.toml
Cleaner stream names by removing pod_id and setting our own specific values per log_type.
- https://issues.redhat.com/browse/LOG-5839
=> LOG-5839: Update cw stream_name to no longer depend on file and tag

internal/generator/vector/output/otlp/otlp_all.toml, internal/generator/vector/output/otlp/transform.go
No jira. Fix adding body to logRecord, when parse filter is applied.
=> Allow structured data to be added to body for otlp output

internal/auth/service_account.go, internal/controller/observability/collector.go, internal/controller/observability/collector_test.go, internal/generator/framework/options.go, internal/generator/vector/output/common/auth/auth.go, internal/generator/vector/output/common/auth/bearer_token.go, internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/loki/loki.go, internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/loki/with_sa_token.toml, internal/generator/vector/output/otlp/otlp.go, internal/runtime/serviceaccount/serviceaccount.go
This PR:
* fixes fetching of bearer token in config
* Creates a sa token if needed
* https://issues.redhat.com/browse/LOG-5808
=> LOG-5808: fix projected sa token in config

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tls_with_field_references.toml, internal/generator/vector/output/syslog/udp_with_every_setting.toml, internal/generator/vector/output/syslog/xyz_defaults.toml, test/functional/outputs/syslog/forward_to_syslog_test.go, test/functional/outputs/syslog/rfc3164_test.go
* Adds syslog enrichment field to the syslog API
* Enable or remove skipped functional tests
https://issues.redhat.com/browse/LOG-5826
=> LOG-5826: Enable skipped RFC syslog test

internal/generator/vector/output/cloudwatch/cloudwatch.go, internal/generator/vector/output/cloudwatch/cw_groupname_with_aws_credentials.toml, internal/generator/vector/output/cloudwatch/cw_with_groupname.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_and_default_mintls_ciphers.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec_insecure_verify.toml, internal/generator/vector/output/cloudwatch/cw_with_url.toml
quick fix
- https://issues.redhat.com/browse/LOG-5849
=> LOG-5849: Fix node log stream names set twice

internal/migrations/observability/api/convert_test.go, internal/migrations/observability/api/output_test.go, internal/migrations/observability/api/outputs.go
This PR adds missing required fields and fixes templating for output index/tenant fields.
- JIRA: https://issues.redhat.com/browse/LOG-5787
=> LOG-5787: The migration process doesn't work.

Makefile
This PR:
* adds a Make target for upgrade testing
* https://issues.redhat.com/browse/LOG-891
=> LOG-891: Add make target for upgrade testing

config/docs/templates/apis/asciidoc/pkg.tpl
Updated docgen template header.
=> Updated docgen template header.

Makefile
=> fix Makefile test-upgrade

docs/contributing/README.adoc, docs/contributing/how-to-add-new-output.md
This PR:
* Updates the contrib docs
https://issues.redhat.com/browse/LOG-5898
=> LOG-5898: Update contrib docs

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, test/e2e/collection/apivalidations/api_validations_test.go, test/e2e/collection/apivalidations/cloudwatch-empty-url.yaml, test/e2e/collection/apivalidations/cloudwatch-invalid-url.yaml, test/e2e/collection/apivalidations/cloudwatch-no-url.yaml, test/e2e/collection/apivalidations/kafka_invalid_broker_url.yaml, test/e2e/collection/apivalidations/kafka_invalid_url.yaml, test/e2e/collection/apivalidations/kafka_no_url_or_brokers.yaml, test/e2e/collection/apivalidations/kafka_valid_url_and_brokers.yaml, test/e2e/collection/apivalidations/log5793_bearer_token_from_sa.yaml
/cc @Clee2691 @cahartma @alanconway 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5884
=> LOG-5884: allow empty URL in validation rules for CloudWatch and Kafka

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/filter/openshift/viaq/audit.go, internal/generator/vector/filter/openshift/viaq/common.go, internal/generator/vector/filter/openshift/viaq/dedot_labels.go, internal/generator/vector/filter/openshift/viaq/journal.go, internal/generator/vector/output/azuremonitor/azm_advance.toml, internal/generator/vector/output/azuremonitor/azm_common.toml, internal/generator/vector/output/azuremonitor/azm_tls.toml, internal/generator/vector/output/cloudwatch/cw_groupname_with_aws_credentials.toml, internal/generator/vector/output/cloudwatch/cw_with_groupname.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_and_default_mintls_ciphers.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec.toml, internal/generator/vector/output/cloudwatch/cw_with_tls_spec_insecure_verify.toml, internal/generator/vector/output/cloudwatch/cw_with_url.toml, internal/generator/vector/pipeline/adapter_test_drop_filter.toml, internal/generator/vector/pipeline/adapter_test_kube_api_filter.toml
Refactor vector config to add openshift.sequence to all logs via the inputType VRL.   
- https://issues.redhat.com/browse/LOG-5892
=> LOG-5892: Add openshift sequence to all input types

internal/generator/vector/output/kafka/kafka_sasl_plaintext_single_topic.toml, internal/generator/vector/output/kafka/kafka_sasl_scram_with_tls.toml, internal/generator/vector/output/kafka/kafka_sasl_with_tls_single_topic.toml, internal/generator/vector/output/kafka/sasl.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5902
=> LOG-5902: set sasl.enabled=true in vector.toml when authentication.sasl properties are defined

internal/api/observability/tuning.go, internal/generator/vector/output/config_strategy_test.go
/cc @Clee2691 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5883
=> LOG-5883: fix setting compression config for Splunk

internal/generator/vector/output/splunk/splunk.go, internal/generator/vector/output/splunk/splunk_sink_with_custom_index_dedot.toml, internal/generator/vector/output/splunk/splunk_sink_with_tls_and_static_index.toml, internal/generator/vector/output/splunk/splunk_test.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5888
=> LOG-5888: fix push logs to Spunk when index template syntax include dot or slash

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_cluster_logging_operator_resources
This PR:
* Adds the CLF.obs to must gather
=> add CLF.obs to must-gather

hack/testing-olm/test-367-logforwarding.sh
This PR:
* cleans up an error message in the e2e logs
=> remove obsolete logic from test

internal/generator/vector/output/kafka/kafka.go, internal/generator/vector/output/kafka/kafka_test.go
/cherry-pick 
- Bugzilla:
- JIRA:
=> [release-5.9]LOG-5139: don't add tls section if broker[] URL don't start with 'tls:'

docs/administration/upgrade/to_v6.0.adoc
This PR:
* Provides a migration guide for administrators
https://issues.redhat.com/browse/LOG-5905
cc @Clee2691 @cahartma @vparfonov
=> LOG-5905: Migration document

docs/administration/upgrade/to_v6.0.adoc, docs/features/logforwarding/filters/api-audit-filter.adoc, docs/features/logforwarding/filters/drop-filter.adoc, docs/features/logforwarding/filters/prune-filter.adoc
This PR:
* Updates the filter docs  for observability
* https://issues.redhat.com/browse/LOG-5915
=> LOG-5915: Update filter docs

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, test/framework/functional/framework.go
This PR:
* fixes the any of the collection e2e tests not being run
* makes kafka topic optional
https://issues.redhat.com/browse/LOG-5903
cc @vparfonov @cahartma @Clee2691
=> LOG-5903: fix kafka topic being required

internal/collector/collector.go, internal/collector/collector_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5900
=> LOG-5900: fix path for Cloudwatch serviceaccount token

test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
This PR:
* enables the forward to CW multiline exception test
* Removes a test that affects any output regarding logtype to wrong outputs which we test elsewhere.  Routing from source to output has changed since this test was introduced
https://issues.redhat.com/browse/LOG-5840
=> LOG-5840: Enable skipped functional test for CW

docs/features/logforwarding/outputs/azure-monitor-log-forwarding.adoc, docs/features/logforwarding/outputs/elasticsearch-forwarding.adoc, docs/features/logforwarding/outputs/google-cloud-forwarding.adoc, docs/features/logforwarding/outputs/send-logs-to-fluentd-http.adoc, docs/features/logforwarding/outputs/splunk-forwarding.adoc
This PR:
* Updates the upstream output docs for observability
https://issues.redhat.com/browse/LOG-5916
@Clee2691 @cahartma @vparfonov please review for correctness for the outputs that you are familiar
=> LOG-5916: Update output docs for observability

internal/generator/vector/filter/drop/filter.go, internal/generator/vector/filter/drop/filter_test.go, internal/generator/vector/pipeline/adapter_test_drop_filter.toml, test/functional/filters/drop/drop_filter_test.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5815
=> LOG-5815:forcibly to_string before match regex to fix working with not string field (e.g. integer)

internal/generator/vector/output/kafka/kafka.go, internal/generator/vector/output/kafka/kafka_not_tls_brokers.toml, internal/generator/vector/output/kafka/kafka_test.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5139
=> [master]LOG-5139: don't add tls section if broker[] URL don't start with 'tls:'

hack/testing-olm/test-030-collection.sh, test/e2e/collection/deployment/collector_as_deployment_test.go, test/e2e/collection/security/container_security_test.go, test/framework/e2e/framework.go, test/framework/e2e/wait.go
=> Enable all e2e collector tests

docs/features/logforwarding/outputs/otlp-forwarding.adoc, internal/generator/vector/output/otlp/otlp_all.toml, internal/generator/vector/output/otlp/transform.go, test/helpers/otlp/attributes.go
Quick update to otel mappings (and doc) based on feedback and further investigation
- https://issues.redhat.com/browse/LOG-5969
=> LOG-5969: Update otlp attributes mapping and feature doc

internal/generator/vector/conf_test/complex.toml, internal/generator/vector/conf_test/complex_custom_data_dir.toml, internal/generator/vector/conf_test/complex_es_no_ver.toml, internal/generator/vector/conf_test/complex_es_v6.toml, internal/generator/vector/conf_test/complex_otel.toml, internal/generator/vector/conf_test/es_pipeline_w_spaces.toml, internal/generator/vector/output/buffer.go, internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/gcl/gcl_test.go, internal/generator/vector/output/http/http_test.go, internal/generator/vector/output/kafka/kafka_test.go, internal/generator/vector/output/loki/loki_conf_test.go, internal/generator/vector/output/splunk/splunk_test.go, internal/generator/vector/outputs_test.go, internal/generator/vector/pipelines_to_output_test.go
This change:
* reverts some of the behavior from [LOG-4536](https://issues.redhat.com//browse/LOG-4536) to block when the buffer is full
* https://issues.redhat.com/browse/LOG-4902
=> LOG-4597: Revert back to default behavior and block when full buffer

bundle/manifests/logging-collector-logs-writer_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/kustomization.yaml, config/rbac/logging-collector-logs-writer.yaml
This PR:
* Adds the logging collector loki writer role to the manifest
https://issues.redhat.com/browse/LOG-5967
=> LOG-5967: Add log writer clusterrole to manifest

internal/api/observability/output_types.go, internal/generator/vector/output/otlp/otlp_test.go, internal/generator/vector/output/otlp/otlp_with_auth_basic.toml, internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml, internal/generator/vector/output/otlp/otlp_with_auth_token.toml
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5980
=> LOG-5980: fix setting token when 'otlp.authentication.token.from: serviceAccount'

Makefile, config/manager/kustomization.yaml, config/manager/manager.yaml
/hold
PR created for code review, discard when done.
=> Add new Make targets for easier deployment using operator-sdk

internal/logstore/lokistack/logstore_lokistack.go, internal/logstore/lokistack/logstore_lokistack_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5639
=> LOG-5639: avoid pipelines name duplication

internal/collector/collector.go, internal/collector/collector_test.go
This PR adds back in the missing PreferredScheduling annotation.
- JIRA: https://issues.redhat.com/browse/LOG-6023
=> LOG-6023: logging collector pod missing PreferredScheduling annotation

bundle/manifests/cluster-logging-write-application-logs_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/cluster-logging-write-audit-logs_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/cluster-logging-write-infrastructure-logs_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/kustomization.yaml, config/rbac/write-application-logs-clusterrole.yaml, config/rbac/write-audit-logs-clusterrole.yaml, config/rbac/write-infrastructure-logs-clusterrole.yaml
Make distinct log writer cluster roles
https://issues.redhat.com/browse/LOG-5967
=> LOG-5967: make distinct log writer roles

internal/generator/fluentd/output/http/http.go, internal/generator/fluentd/output/http/http_test.go
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-5210
=> LOG-5210: fix http timeout config for Fluentd

internal/generator/fluentd/output/http/http.go, internal/generator/fluentd/output/http/http_test.go
/cc  
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6125
=> [release-5.9]LOG-6125: fix http timeout config for Fluentd

internal/validations/observability/validate_permissions.go, internal/validations/observability/validate_permissions_test.go
This is a manual port of [PR2794](https://github.com/openshift/cluster-logging-operator/pull/2794) to master
- Related PR: https://github.com/openshift/cluster-logging-operator/pull/2794
- JIRA: https://issues.redhat.com/browse/LOG-6044
=> Manual port of LOG-6044 to master

config/rbac/kustomization.yaml, config/rbac/logging-collector-logs-writer.yaml
Follow-up of closed #2797, adding back the file to generate the `logging-collector-logs-writer` ClusterRole.
/cc @cahartma
- JIRA: [LOG-5967](https://issues.redhat.com//browse/LOG-5967)
=> Add missing ClusterRole file

internal/generator/vector/output/elasticsearch/elasticsearch.go, internal/generator/vector/output/elasticsearch/elasticsearch_test.go, internal/generator/vector/output/http/http.go, internal/generator/vector/output/loki/loki.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6206
=> LOG-6206: trim newline symbol for username/password

internal/validations/observability/filters/validate_filters.go, internal/validations/observability/filters/validate_filters_test.go
/cc @Clee2691 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6202
=> LOG-6202: disallowed log_source field for prune filter

internal/validations/clusterlogforwarder/inputs/application.go, internal/validations/clusterlogforwarder/inputs/validate_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-6214: add validation for threshold must be more than zero

internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec.go, internal/validations/clusterlogforwarder/validate_clusterlogforwarderspec_test.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-4671: add validation for threshold must be more than zero

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml
backport of #2828 
cc @Clee2691
=> LOG-6266: fix provider so operator is evaluated as official

bundle/manifests/cluster-logging.clusterserviceversion.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml
Forward port of #2828 
cc @Clee2691
=> LOG-5587: fix provider so operator is evaluated as official

internal/controller/observability/clusterlogforwarder_controller.go
**###** Description
This PR:
* updates the CLF to watch and reconcile owned resources to re-enable functionality that existed in prior releases
https://issues.redhat.com/browse/LOG-6264
=> LOG-6264: Watch and reconcile owned resources

bundle/manifests/clusterlogging.clusterserviceversion.yaml, config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR:
* Drops EO installation requirement that it must be installed prior to the CLO
ref: https://issues.redhat.com/browse/LOG-6149
=> LOG-6149: fix the CSV description regarding EO dependency

docs/administration/lokistack.adoc
No Jira.   Quick change to lokistack CR example
/cc @Clee2691 @vparfonov @xperimental
- based on release-6.0 changes:  https://github.com/openshift/cluster-logging-operator/pull/2840
=> Doc update for lokistack spec example

bundle/manifests/cluster-logging-operator-telemetry_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/kustomization.yaml, config/prometheus/telemetry_rules.yaml
Backport of #2823 to `release-6.0`.
- JIRA: [LOG-5131](https://issues.redhat.com//browse/LOG-5131)
=> LOG-5131: Add recording rules for telemetry collection

internal/generator/vector/output/otlp/otlp_all.toml, internal/generator/vector/output/otlp/otlp_tuning.toml, internal/generator/vector/output/otlp/otlp_with_auth_basic.toml, internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml, internal/generator/vector/output/otlp/otlp_with_auth_token.toml, internal/generator/vector/output/otlp/transform.go, test/functional/outputs/otlp/container_test.go, test/functional/outputs/otlp/journal_test.go, test/helpers/types/otlp/attributes.go
This is a fix we are squeezing into 6.1, since the issue presents itself the UI console.
/cc @Clee2691 @vparfonov @xperimental 
- https://issues.redhat.com/browse/LOG-6324
=> LOG-6324: Add level field to otlp logRecord attributes

internal/collector/input_service.go
This PR fixes the input receiver's service constantly being deleted and recreated. This caused secret mounting errors when the collector pods were starting up.
- JIRA: https://issues.redhat.com/browse/LOG-6343
=> LOG-6343: When enabling inputs receivers in CLF, the tls secrets can't be created

api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This PR:
* Adds descriptions to the output types API
https://issues.redhat.com/browse/LOG-6153
/hold
cc @cahartma
=> LOG-6153: Add description to API output types

docs/reference/datamodels/viaq/v1.adoc, docs/reference/operator/api_observability_v1.adoc, test/framework/functional/message_templates.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-6207: update ViaQ datamodel docs with stream (stdout/stderr) information

bundle/manifests/collector_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/collector_alerts.yaml, docs/administration/collector-metrics-and-alerts.adoc
This is a manual port of [LOG-6404](https://issues.redhat.com/browse/LOG-6404) to release-6.1
- JIRA: https://issues.redhat.com/browse/LOG-6466
=> [release-6.1] LOG-6466: Remove irrelevant alerting rules

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_drop_filter.toml, internal/generator/vector/conf/complex_es_no_ver.toml, internal/generator/vector/conf/complex_es_v6.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/complex_otel.toml, internal/generator/vector/conf/complex_prune_filter.toml, internal/generator/vector/input/viaq.go, internal/generator/vector/input/viaq_application.toml, internal/generator/vector/input/viaq_application_exclude_container_from_infra.toml, internal/generator/vector/input/viaq_application_excludes_container.toml, internal/generator/vector/input/viaq_application_includes_container.toml, internal/generator/vector/input/viaq_application_with_excludes.toml, internal/generator/vector/input/viaq_application_with_includes.toml, internal/generator/vector/input/viaq_application_with_includes_excludes.toml, internal/generator/vector/input/viaq_application_with_infra_includes_excludes.toml, internal/generator/vector/input/viaq_application_with_infra_includes_infra_excludes.toml, internal/generator/vector/input/viaq_application_with_matchLabels.toml, internal/generator/vector/input/viaq_application_with_specific_infra_includes_infra_excludes.toml, internal/generator/vector/input/viaq_application_with_throttle.toml
This is a manual port of https://github.com/openshift/cluster-logging-operator/pull/2862 to `release-5.9`
- JIRA: https://issues.redhat.com/browse/LOG-6377
=> LOG-6377: Manual port of LOG-6354 to release-5.9

docs/features/logforwarding/outputs/otlp-forwarding.adoc, internal/generator/vector/output/otlp/otlp.go, internal/generator/vector/output/otlp/otlp_test.go, internal/generator/vector/output/otlp/otlp_tuning.toml
quick update, add a test and minor update to docs and comments
- https://issues.redhat.com/browse/LOG-6278
=> [master] LOG-6278: update docs for compression on otlp

docs/features/logforwarding/outputs/otlp-forwarding.adoc, hack/logsamples/otlp_audit_host.json, hack/logsamples/otlp_audit_kube.json, hack/logsamples/otlp_audit_openshift.json, hack/logsamples/otlp_container.json, hack/logsamples/otlp_journal.json
CLO updates to feature doc and sample log files, based on changes introduced in 6.1
Also updating rhobs/observability-data-model with a few small corrections. https://github.com/rhobs/observability-data-model/pull/9
- https://issues.redhat.com/browse/LOG-6378
=> [master] LOG-6378: Update otlp docs and sample logs

Makefile, bundle.Dockerfile, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, olm_deploy/operatorregistry/cluster-logging.package.yaml, version/version.go
Updates version information in master. Does not update references to other component versions.
- JIRA: [LOG-6610](https://issues.redhat.com//browse/LOG-6610)
=> LOG-6610: Update CLO version to 6.2.0 and update supported version

Makefile, bundle/manifests/cluster-logging.clusterserviceversion.yaml, config/manager/manager.yaml, internal/cmd/functional-benchmarker/config/options.go
Update CLO code to use Vector v0.43.1:
- use upstream implementation of file/directory instead of forked implementation  (see: https://github.com/vectordotdev/vector/pull/21282/)
/cc @xperimental @Clee2691 @cahartma  
/cherry-pick 
- Depending on PR(s): https://github.com/ViaQ/vector/pull/189
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6552
=> LOG-6552:Update CLO code to use Vector v0.43.1

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/container.toml, internal/generator/vector/conf/global_test.go, internal/generator/vector/output/common/secret.go
This PR address to switch fork implementation of Secret to the upstream implementation. 
https://vector.dev/docs/reference/configuration/global-options/#secret.directory  
/cc @cahartma  
/assign @jcantrill @xperimental  
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-6552:Use Vector secret implementations backends from upstream

api/observability/v1/filter_api_audit_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, docs/reference/operator/api_observability_v1.adoc, test/functional/filters/apiaudit/vrl/filter_test.go, test/functional/filters/apiaudit/vrl/log5607_sample.json, test/functional/filters/apiaudit/vrl/suite_test.go
This PR:
* updates the filter API documentation related to how resource and subresource are evaluated
* Adds a functional test for coverage
* https://issues.redhat.com/browse/LOG-5607
=> LOG-5607: Clarify filter documentation for resource

docs/features/logforwarding/outputs/otlp-forwarding.adoc, internal/generator/vector/output/otlp/otlp.go, internal/generator/vector/output/otlp/otlp_test.go, internal/generator/vector/output/otlp/otlp_tuning.toml
No Jira.  This is a manual backport from 6.2.  Quick update, add a test and minor update to docs and comments
- 6.2 fix:  https://issues.redhat.com/browse/LOG-6278
=> [release-6.0] update otlp compression docs

docs/features/logforwarding/outputs/otlp-forwarding.adoc, internal/generator/vector/output/otlp/otlp.go, internal/generator/vector/output/otlp/otlp_test.go, internal/generator/vector/output/otlp/otlp_tuning.toml
No Jira.  This is a manual backport from 6.2.  Quick update, add a test and minor update to docs and comments
- 6.2 fix:  https://issues.redhat.com/browse/LOG-6278
=> [release-6.1] update otlp compression docs

docs/contributing/README.adoc
Updated small typo in target word
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> Updated small typo in word target

Makefile, bundle.Dockerfile, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, olm_deploy/operatorregistry/cluster-logging.package.yaml, version/version.go
This PR:
* updates the code base for version 6.3
https://issues.redhat.com/browse/LOG-6829
cc @xperimental @cahartma
=> LOG-6829: Updates for version to be 6.3.0

api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This is a manual port of https://github.com/openshift/cluster-logging-operator/pull/2987 to the current master branch.
- JIRA: https://issues.redhat.com/browse/LOG-6880
=> [master] LOG-6869: Manual port of LOG-6869 to master

api/observability/v1/filter_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml
This is a manual port of https://github.com/openshift/cluster-logging-operator/pull/2980 to master.
- JIRA: https://issues.redhat.com/browse/LOG-6884
=> LOG-6884: Manual port of LOG-6753 to master

internal/controller/observability/clusterlogforwarder_controller.go
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
=> LOG-6539: use json Patch() instead of Update() in updateStatus func

internal/controller/observability/clusterlogforwarder_controller.go
Back-port of #2976
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6953
=> [release-6.2]LOG-6952: use json Patch() instead of Update() in updateStatus func

bundle/manifests/cluster-logging.clusterserviceversion.yaml, config/rbac/role.yaml
Forward port of #2982 
https://issues.redhat.com/browse/LOG-6879
=> LOG-6879: fix operator permissions to update SCC

hack/logsamples/otlp_audit_ovn.json, hack/logsamples/viaq_audit_ovn.json, internal/generator/vector/output/lokistack/lokistack_otel.toml, internal/generator/vector/output/otlp/otlp_all.toml, internal/generator/vector/output/otlp/otlp_tuning.toml, internal/generator/vector/output/otlp/otlp_with_auth_basic.toml, internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml, internal/generator/vector/output/otlp/otlp_with_auth_token.toml, internal/generator/vector/output/otlp/transform.go, test/framework/functional/write.go, test/functional/outputs/otlp/audit_test.go, test/helpers/types/otlp/attributes.go
This PR addressed to fix issue with forwarding Audit OVN and AuditD logs. 
Detailed description see here: https://github.com/rhobs/observability-data-model/pull/10
/cc @Clee2691 @cahartma @alanconway 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6711
- Enhancement proposal: https://github.com/rhobs/observability-data-model/pull/10
=> LOG-6711: fix audit ovn and auditd log forwarding

hack/logsamples/otlp_audit_ovn.json, hack/logsamples/viaq_audit_ovn.json, internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/filter/openshift/viaq/audit.go, internal/generator/vector/output/lokistack/lokistack_otel.toml, internal/generator/vector/output/otlp/otlp_all.toml, internal/generator/vector/output/otlp/otlp_tuning.toml, internal/generator/vector/output/otlp/otlp_with_auth_basic.toml, internal/generator/vector/output/otlp/otlp_with_auth_sa_token.toml, internal/generator/vector/output/otlp/otlp_with_auth_token.toml, internal/generator/vector/output/otlp/transform.go, test/framework/functional/write.go, test/functional/outputs/otlp/audit_test.go, test/helpers/types/otlp/attributes.go
backport of #3006
/cc @Clee2691 @cahartma
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-6997
=> [release-6.2]LOG-6997: fix audit ovn and auditd log forwarding

docs/features/logforwarding/outputs/splunk-forwarding.adoc
/cc @jcantrill  
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA: small clarification to improve clarity and avoid missing key info

.github/pull_request_template.md
- fix a few typos in `pull_request_template.md`
- hide OPTIONAL `/cherrypick ` command in side comments to prevent failing `openshift-cherrypick-robot` with error:
`cannot checkout 
/cherry-pick 
- Bugzilla:
- JIRA:
=> NO-JIRA: fix a few typos in pull_request_template.md

api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, docs/features/logforwarding/outputs/syslog-forwarding.adoc, hack/logsamples/viaq_audit_kubernetes.json, hack/logsamples/viaq_audit_openshift.json, hack/logsamples/viaq_container.json, hack/logsamples/viaq_journal.json, internal/generator/helpers/optional_pair.go, internal/generator/vector/output/syslog/rfc3164_with_defaults.toml, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/syslog_test.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tcp_with_tuning.toml, internal/generator/vector/output/syslog/tls_with_field_references.toml, internal/generator/vector/output/syslog/udp_with_every_setting.toml, internal/generator/vector/output/syslog/xyz_defaults.toml, test/functional/outputs/syslog/forward_to_syslog_test.go, test/functional/outputs/syslog/rfc3164_test.go, test/functional/outputs/syslog/rfc5424_test.go
Backport for https://github.com/openshift/cluster-logging-operator/pull/3034
- Depending on PR(s): https://github.com/ViaQ/vector/pull/204
- JIRA: https://issues.redhat.com/browse/LOG-7183
=> [release-6.0]LOG-7183: avoid merge data from message to the root of log event

api/observability/v1/output_types.go, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, docs/features/logforwarding/outputs/syslog-forwarding.adoc, hack/logsamples/viaq_audit_kubernetes.json, hack/logsamples/viaq_audit_openshift.json, hack/logsamples/viaq_container.json, hack/logsamples/viaq_journal.json, internal/generator/helpers/optional_pair.go, internal/generator/vector/output/syslog/rfc3164_with_defaults.toml, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/syslog_test.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tcp_with_tuning.toml, internal/generator/vector/output/syslog/tls_with_field_references.toml, internal/generator/vector/output/syslog/udp_with_every_setting.toml, internal/generator/vector/output/syslog/xyz_defaults.toml, test/functional/outputs/syslog/forward_to_syslog_test.go, test/functional/outputs/syslog/rfc3164_test.go, test/functional/outputs/syslog/rfc5424_test.go
Backport for https://github.com/openshift/cluster-logging-operator/pull/3034
/cc 
/assign 
- Depending on PR(s): https://github.com/ViaQ/vector/pull/204
- JIRA: https://issues.redhat.com/browse/LOG-7185
=> [release-6.2]LOG-7185: avoid merge data from message to the root of log event

bundle/manifests/cluster-logging.clusterserviceversion.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml
- JIRA: https://issues.redhat.com/browse/LOG-6760
=> LOG-6760: Provide correct URL in install page

api/observability/v1/output_types.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, docs/features/collection.adoc
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-7131
=> LOG-7131: update documentation Tuning Delivery mode default settings

internal/generator/vector/output/splunk/splunk.go, internal/generator/vector/output/splunk/splunk_sink.toml, internal/generator/vector/output/splunk/splunk_sink_payloadkey.toml, internal/generator/vector/output/splunk/splunk_sink_with_custom_index.toml, internal/generator/vector/output/splunk/splunk_sink_with_custom_index_dedot.toml, internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields.toml, internal/generator/vector/output/splunk/splunk_sink_with_indexed_fields_and_source.toml, internal/generator/vector/output/splunk/splunk_sink_with_tls.toml, internal/generator/vector/output/splunk/splunk_sink_with_tls_and_static_index.toml, internal/generator/vector/output/splunk/splunk_tune.toml, test/functional/outputs/splunk/forward_to_splunk_metadata_test.go
- JIRA: https://issues.redhat.com/browse/LOG-7253
=> LOG-7253: fix host field when payloadKey is specified

internal/generator/vector/output/syslog/rfc3164_with_defaults.toml, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tcp_with_tuning.toml, internal/generator/vector/output/syslog/xyz_defaults.toml, test/functional/outputs/syslog/forward_to_syslog_test.go
Forward-porting for https://github.com/openshift/cluster-logging-operator/pull/3059 
- JIRA: https://issues.redhat.com/browse/LOG-7355
=> LOG-7355: add fallback option if syslog app_name calculation fail

api/observability/v1/output_types.go, api/observability/v1/zz_generated.deepcopy.go, bundle/manifests/observability.openshift.io_clusterlogforwarders.yaml, config/crd/bases/observability.openshift.io_clusterlogforwarders.yaml, internal/generator/vector/output/kafka/kafka_test.go, test/e2e/collection/apivalidations/api_validations_test.go, test/e2e/collection/apivalidations/kafka_valid_url_and_brokers.yaml
- JIRA:https://issues.redhat.com/browse/LOG-7340
=> LOG-7340: add validation  that the Kafka URLs should be tcp or tls

Makefile, bundle.Dockerfile, bundle/manifests/cluster-logging.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/cluster-logging.clusterserviceversion.yaml, olm_deploy/operatorregistry/cluster-logging.package.yaml, test/framework/e2e/lokistack.go, version/version.go
This PR updates the code base for version 6.4
https://issues.redhat.com/browse/LOG-7331
=> LOG-7331: Updates to be 6.4.0 version

internal/generator/vector/output/syslog/rfc3164_with_defaults.toml, internal/generator/vector/output/syslog/syslog.go, internal/generator/vector/output/syslog/tcp_with_defaults.toml, internal/generator/vector/output/syslog/tcp_with_tuning.toml, internal/generator/vector/output/syslog/xyz_defaults.toml, test/functional/outputs/syslog/forward_to_syslog_test.go
Forward-porting for https://github.com/openshift/cluster-logging-operator/pull/3059 
- JIRA: https://issues.redhat.com/browse/LOG-7355
=> [release-6.3] LOG-7355: add fallback option if syslog app_name calculation fail

internal/generator/vector/conf/complex.toml, internal/generator/vector/conf/complex_http_receiver.toml, internal/generator/vector/conf/container.toml, internal/generator/vector/filter/openshift/viaq/v1/normalize.go, internal/generator/vector/input/application.toml, internal/generator/vector/input/application_exclude_container_from_infra.toml, internal/generator/vector/input/application_excludes_container.toml, internal/generator/vector/input/application_includes_container.toml, internal/generator/vector/input/application_with_includes_excludes.toml, internal/generator/vector/input/application_with_infra_includes_excludes.toml, internal/generator/vector/input/application_with_infra_includes_infra_excludes.toml, internal/generator/vector/input/application_with_matchLabels.toml, internal/generator/vector/input/application_with_specific_infra_includes_infra_excludes.toml, internal/generator/vector/input/application_with_throttle.toml, internal/generator/vector/input/audit.toml, internal/generator/vector/input/audit_host.toml, internal/generator/vector/input/audit_ovn.toml, internal/generator/vector/input/infrastructure.toml, internal/generator/vector/input/infrastructure_container.toml, test/functional/normalization/loglevel/container_logs_test.go
backport for https://issues.redhat.com/browse/LOG-7222 
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-7777
=> LOG-7777: Implement multi-stage parsing for log level determination
