- manifests/01-namespace.yaml
This PR preps for cluster-monitoring-operator to scrape cluster-logging to support
https://jira.coreos.com/browse/LOG-176
> add cluster-monitoring annotation to namespace def

- scripts/cert_generation.sh
hardcode SAN DNS names for now
we'll need to get the SAN DNS names from the elasticsearch
service names in the future
> hardcode SAN DNS names for now

- Dockerfile.rhel7
Part of standardizing release tooling
> Add a rhel7 dockerfile and make the centos dockerfile consistent

- pkg/k8shandler/visualization.go
- pkg/utils/utils.go
Addresses https://jira.coreos.com/browse/LOG-233
@spadgett PTAL and confirm this would work. There will always be `kibanaAppHost` and `kibanaInfraHost` entries, even if it is an "all-in-one" configuration where we only create a single `route`.
e.g.
```
oc get configmap -o yaml sharing-config
apiVersion: v1
data:
kibanaAppHost: kibana-app
kibanaInfraHost: kibana-infra
kind: ConfigMap
metadata:
creationTimestamp: 2018-11-30T18:21:05Z
name: sharing-config
ownerReferences:
- apiVersion: logging.openshift.io/v1alpha1
controller: true
kind: ClusterLogging
name: example-cluster-logging
uid: b27ce418-f4cc-11e8-a9ff-0e3a960e086c
resourceVersion: "7727"
```
> Creating shared-config for console to consume

- pkg/k8shandler/curation.go
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1655881
Values based on prior values used in Ansible
> Adding missing curator env vars

- hack/deploy-setup.sh
- pkg/k8shandler/certificates.go
- pkg/k8shandler/curation.go
- scripts/cert_generation.sh
Updates the CLO to no longer require a secret to be created and mounted by customers. Will create a signing CA if one does not exist and store it in a secret.
Addresses https://jira.coreos.com/browse/LOG-255
> Updating to generate own signing CA for Cluster Logging

- manifests/10-service-monitor-fluentd.yaml
fix https://bugzilla.redhat.com/show_bug.cgi?id=1660778
This PR modifies the CA path for the fluent servicemonitor
> bug 1660778 CA path for the fluent servicemonitor

- Makefile
- manifests/05-deployment.yaml
- manifests/image-references
fix https://bugzilla.redhat.com/show_bug.cgi?id=1665824 by prefixing the default image with 'origin' which is required for images published to quay
> Default operator image tag

- pkg/k8shandler/collection.go
- pkg/utils/utils.go
If the log collector is switched from `fluentd` to `rsyslog` or visa-versa we will clean up/remove the old configuration (when we are managing the cluster).
Addresses https://jira.coreos.com/browse/LOG-319
> Log collector switch check

- Makefile
- hack/common
- hack/deploy-image.sh
- hack/deploy.sh
- hack/image-stream-build-config-template.yaml
- hack/undeploy.sh
If USE_IMAGE_STREAM=true, setup a buildconfig and an
image stream in the remote repo, and build the operator image
there from the github source.  This may save a lot of time
as opposed to building the image locally and pushing the image
into the remote registry.
Also allow deploying without first building the image.  This
assumes something like a CI environment where the previous
CI stage builds the images needed to deploy and test.
depends on https://github.com/openshift/elasticsearch-operator/pull/65
> support buildconfigs and no image build deployments

- cmd/cluster-logging-operator/main.go
sdk.ExposeMetricsPort() leaks Service and is deprecated
in future version of the sdk.
For now, we won't be exposing metrics of the operator, but we plan
to do that later. This change has no impact on exposing metrics
of the elasticsearch cluster as a whole.
> Don't use the sdk for exposing operator's metrics

- Makefile
- README.md
- hack/common
- hack/deploy-image.sh
- manifests/03-role.yaml
- manifests/04-role-binding.yaml
- pkg/k8shandler/collection.go
- pkg/utils/types.go
- pkg/utils/utils.go
- test/e2e/clusterlogging_test.go
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1680504 by:
* creates a clusterrole for the logcollector to be able to watch all pods and namespaces
> bug 1680504. Create collector clusterrole to watch pods/ns

- hack/cr-aws.yaml
tests use single es instance so use ZeroRedundancy
create a cr.yaml for use with OCP 4.0 installer on aws
> use ZeroRedundancy for tests - add cr for aws deploys

- scripts/cert_generation.sh
`logging-es` is for the `elasticsearch` svc and `elasticsearch` is for the `elasticsearch-cluster` svc... not sure how we missed this. on my local system it looks like the es pods didn't cluster together this should address that
> expanding the cert dns entry for the es svcs

- docs/configuration.md
- hack/cr-aws.yaml
- hack/cr.yaml
- pkg/apis/logging/v1alpha1/types.go
- pkg/runtime/runtime.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- test/e2e/clusterlogging_test.go
LOG-358. Restrict CL to single instance called "instance"
This PR additionally introduces an abstraction to allow mocking calls to runtime
> Restrict to single instance of CL

- Makefile
- README.md
- hack/deploy-image.sh
- hack/test-e2e.sh
- pkg/k8shandler/collection.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/visualization.go
- test/e2e/clusterlogging_test.go
This PR fixes an issue updating ClusterLogging.Status where it tries to marshal CLO runtime instance which is a function pointer.
```
time="2019-03-25T19:43:20Z" level=error msg="error syncing key (openshift-logging/instance): Unable to create or update logstore for \"instance\": Failed to update Cluster Logging Elasticsearch status: error running MarshalJSON on runtime object: json: unsupported type: runtime.RetryOnConflict"
```
> fix issue trying to marshall CLO runtime abstraction

- files/rsyslog/10-viaq-modules.conf
cannot enable impstats until we have log rotation
> rsyslog - disable impstats until logrotation available

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
- pkg/k8shandler/visualization.go
Defaulting CLO redundancy policy to ZeroRedundancy when omitted and adding unit tests
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1694573
> Bug 1694573 - use ZeroRedundancy esCR policy when omitted from CLO

- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
This PR further address https://bugzilla.redhat.com/show_bug.cgi?id=1693957
by removing the cluster role biding introduced in the original PR
> further revert 1666674 to remove unnecessary cluster role binding

- Makefile
- README.md
- hack/build-image.sh
- hack/common
- hack/deploy-image.sh
Support building UBI based images, and images that need the
private repo for rpms.
Make it easier to build the image and push to a deployed
cluster with the logging images.
> UBI support; allow image build and push with oal logging

- pkg/k8shandler/visualization.go
Correctly setting the replicas for the generated deployment for Kibana based on the `replicas` field for the `clusterlogging` cr.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1699268
> Bug 1699268 - Fixing not setting Kibana replicas on generated deployment

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
Alternative fix vs https://github.com/openshift/cluster-logging-operator/pull/168
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1706134
> Bug 1706134: Allowing scale up past 3 nodes for ES Cr 

- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/k8shandler/rsyslog.go
- pkg/k8shandler/rsyslog_test.go
To address fluentd not being scheduled to nodes where it may have left buffer files causing disk-pressure, allow fluentd to be scheduled on nodes where that taint has been applied so it can attempt to clear its buffer files.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1707465
> Bug 1707465: Adding disk-pressure toleration for fluentd

- pkg/k8shandler/fluentd.go
- pkg/k8shandler/rsyslog.go
This is causing problems with the fluentd image.  Fluentd
has this code:
https://github.com/openshift/origin-aggregated-logging/blob/6820bed406ec080014becc611f95825d98410955/fluentd/configs.d/openshift/input-pre-systemd.conf#L15
```
read_from_head "#{ENV['JOURNAL_READ_FROM_HEAD'] || 'false'}"
```
The intention is to use the value if set to an actual value.
However, the ruby implemenation of `ENV` will return an
empty string, which does not evaulate to `nil`, which means
`read_from_head` will be expanded into the Fluentd configuration
like this
```
read_from_head
```
In Fluentd, a boolean config parameter with an empty value means
to *set* the value to `true`.
There is a PR to correctly handle an `ENV` var with an empty
value: https://github.com/openshift/origin-aggregated-logging/pull/1630 …
> do not output env var with empty values

- files/logrotate/cron.sh
- files/logrotate/logrotate
- files/logrotate/logrotate.sh
- files/logrotate/logrotate_pod.sh
- files/rsyslog/00-global.conf
- files/rsyslog/99-logging.conf
- files/rsyslog/rsyslog.sh
- manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml
- manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml
- manifests/4.2/image-references
- pkg/k8shandler/collection.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/pod.go
- pkg/k8shandler/rsyslog.go
- pkg/k8shandler/rsyslog_test.go
- pkg/k8shandler/visualization.go
Purpose: Adding the logrotation supports to rsyslog to match fluentd.
```
Since rsyslog does not include logrotate capability, use an utility logrotate to do the job.
Logrotate is added as a separate container to the rsyslog pod to share the logging paths.
How to see the rsyslog logs:
oc logs $RSYSLOG_POD -c rsyslog
=============================
Rsyslog logs have been redirected to: /var/log/rsyslog/rsyslog.log
If you want to print out the logs, use command:
oc exec <pod_name> -- logs
=============================
$ oc exec $RSYSLOG_POD -- logs
Defaulting container name to rsyslog.
INFO: Disabling Prometheus endpoint
<DATE> rsyslog-gvcmt rsyslogd-2207: error during parsing file /etc/rsyslog.d/55-elasticsearch.conf, ...
Logrotate is configurable by editing logrotate configmaps and …
```
> LOG-400 rsyslog - support log rotation for rsyslog log files

- Makefile
- cmd/manager/main.go
- hack/deploy-setup.sh
- hack/deploy.sh
- hack/gen-olm-artifacts.sh
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/rsyslog.go
- pkg/utils/utils.go
Allows the use of `make deploy` with oal logging CI to
deploy logging.  Set `IMAGE_OVERRIDE` and `EO_IMAGE_OVERRIDE`
to specify the operator images to use.
This also gets rid of the need to create a `/usr/share/logging`
on the local machine - instead, for test purposes, the env var
`LOGGING_SHARE_DIR` sets the location to the files to load.
If this is not set, the default `/usr/share/logging` is used
(e.g. inside the container).
Depends on https://github.com/openshift/elasticsearch-operator/pull/146
> use make deploy with oal logging CI

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
Don't set cpu limit on elasticsearch. Only request at least 1 CPU and 16Gi of RAM
https://bugzilla.redhat.com/show_bug.cgi?id=1710404
> Bug 1710404: No longer set CPU Limit for default ES resource requirements

- hack/deploy-setup.sh
- hack/deploy.sh
Have to specify `-n $NAMESPACE` when creating manifest objects
during CI testing.
> add namespace for manifest

- files/rsyslog/10-viaq-modules.conf
- files/rsyslog/rsyslog_prometheus_alerts.yaml
- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/rsyslog.go
- test/e2e/clusterlogging_test.go
This configures the rsyslog pod to export prometheus
metrics using the soundcloud rsyslog_exporter via an
omprog output of the impstats.
This requires https://github.com/openshift/origin-aggregated-logging/pull/1643
for full prometheus support.
This replaces https://github.com/openshift/cluster-logging-operator/pull/164
> add rsyslog_exporter for prometheus

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
Also fixing ordering of nodes defined to prevent prior node recreation
Needs to be cherry picked to `release-4.1` as well for https://bugzilla.redhat.com/show_bug.cgi?id=1712955
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1712721
> Bug 1712721 - Fixing checking if nodes are different when scaling from 3 to 4

- files/rsyslog/00-global.conf
- files/rsyslog/rsyslog.sh
- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/rsyslog.go
The default queue.size for memory queues (50000) is too large
for small deployments.  It needs to be based on the amount of
memory available to the pod.  From trial and error it seems
that a value of `memory / 10240` gives good performance and
leaves enough memory for rsyslog and overhead.  Average
record size in testing was about 10k.  Use the env. var.
`RSYSLOG_MAIN_QUEUE_SIZE` to set the main queue size to a
different value than the default.
There is a race condition when switching between fluentd and
rsyslog.  The new collector should be created first, before
removing the old collector.
When switching between fluentd and rsyslog collector,
the service cert signer gets confused because the secret
is deleted and added too quickly - so just avoid the confusion
and use a separate secret …
> rsyslog - set default queue.size; timing issue switching from fluentd

- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/k8shandler/pod_test.go
- pkg/k8shandler/rsyslog.go
- pkg/k8shandler/rsyslog_test.go
We made a change in LOG-411 to allocate logging components to linux
nodes only. However we were wrongly overriding node selectors for
fluentd and rsyslog components after the linux selector was set.
Hence the linux selector was missing for these two components.
This commit also makes relevant testing method reusable across
several testing files.
> Overriding node selectors causing drop of linux selector for fluentd and rsyslog

- manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml
- manifests/art.yaml
- manifests/cluster-logging.package.yaml
aligning w/ similar changes in master: https://github.com/openshift/cluster-logging-operator/pull/206
patch manager: there is no master BZ associated w/ this change because this is cleaning up issues that were specific to the 4.1 resource files.
> Bug 1724833: Cleanup 4.1 manifest content

- files/rsyslog/52-rsyslog-internal-logs.conf
- files/rsyslog/99-logging.conf
https://bugzilla.redhat.com/show_bug.cgi?id=1729316
rsyslog logs were being sent to Elasticsearch.  rsyslog records
are unformatted, so had no @timestamp field, so were causing
indices of the form .operations... to be created.  These logs
should not be sent to Elasticsearch.  The fix is to redirect
these logs to the log file.  This fix also changes rsyslog to
use a JSON format for its logs.  Here is an example:
```json
{"@timestamp":"2019-07-15T21:38:29.966075+00:00", "host":"rsyslog-hp5cm", "level":"info", "facility":"syslog", "syslog-tag":"rsyslogd:", "source":"rsyslogd", "procid":"-", "msgid":"-", "message":" [origin software=\"rsyslogd\" swVersion=\"8.37.0-9.el7\" x-pid=\"13\" x-info=\"http:\/\/www.rsyslog.com\"] start"}
```
> Bug 1729316: rsyslog log collector creating operations index with no date in the name

- files/rsyslog/10-viaq-modules.conf
the msg field is already in JSON format - just print it
> rsyslog - fix impstats file format

- files/rsyslog/rsyslog.sh
Adding a check to rsyslog.sh if bearer_token_file (/var/run/secrets/kubernetes.io/serviceaccount/token)
for the kubernetes api server exists and is not empty.
> Bug 1715370: Some orphaned logs sent to .operations.* index by mistake.

- pkg/k8shandler/visualization.go
https://bugzilla.redhat.com/show_bug.cgi?id=1724053
fix crash associated with missing annotation map when
having to retry oauthclient modification.
> Bug 1724053: Retrieve oauthclient as a cluster resource

- files/rsyslog/20-viaq-templates.conf
- files/rsyslog/60-mmk8s.conf
- files/rsyslog/65-viaq-formatting.conf
- files/rsyslog/67-mmexternal.conf
https://bugzilla.redhat.com/show_bug.cgi?id=1734951
When mmnormalize fails to parse, it will create the fields `originalmsg`
and `unparsed-data` in the record:
https://github.com/rsyslog/liblognorm/blob/master/src/pdag.c#L1680
In this case, we want to remove the fields from the record, just after
where the mmnormalize occurred.
This also ensures that the timestamp we use to generate the index
name is normalized i.e. make sure it is in the form `YYYY-MM-DD`.  If
using `MERGE_JSON_LOG=true`, the user may have already added a
`@timestamp` field to the record which may be in some odd format.
> Bug 1734951: rsyslog with MERGE_JSON_LOG=true does not handle non-JSON data

- files/rsyslog/10-viaq-modules.conf
- files/rsyslog/rsyslog.sh
The default value of the env variable was false, but we want it to be
true.
Additionally, the env variable did not alter anything, since the only
time it was checked, was when deleting a non existing file.
Therefore, I have deleted this unused control block in rsyslog.sh,
and moved the logic to block Prometheus endpoint to the Rsyslog
configuration.
> Bug 1725517: Setting ENABLE_PROMETHEUS_ENDPOINT=false in rsyslog env doesn't take effect.

- files/rsyslog/parse_json.rulebase
- files/rsyslog/parse_json_skip_empty.rulebase
https://bugzilla.redhat.com/show_bug.cgi?id=1735511
Change the json parser to look for leading whitespace
Note: The multiline_json parser doesn't need this because its json
is computer generated by docker, not human generated as in the bz
> Bug 1735511: Rsyslog couldn't parse json log which has prefix space before the json string when set MERGE_JSON_LOG=true

- files/rsyslog/65-viaq-formatting.conf
- files/rsyslog/rsyslog.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1735548 .
Part of that Bugzilla is also Fluentd fix for the same incorrect field. However, the fix requires opening a PR in [Origin Aggregate Logging](https://github.com/openshift/origin-aggregated-logging) repository.
This is the Fluentd PR https://github.com/openshift/origin-aggregated-logging/pull/1718
> Bug 1735548:  pipeline_metadata.collector.ipaddr6 is incorrect when using rsyslog as log collector.

- files/rsyslog/65-viaq-formatting.conf
- files/rsyslog/67-mmexternal.conf
- files/rsyslog/rsyslog.sh
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/rsyslog.go
https://bugzilla.redhat.com/show_bug.cgi?id=1737286
Get rid of the mmnormalize based SKIP_EMPTY processing.  In order
for it to be useful for our case we need to be able to specify
CDM_KEEP_EMPTY_FIELDS since we preserve the empty `message`
field by default.
Add more fluentd functionality - unconditionally delete the
MESSAGE and log fields, ignoring PRESERVE_JSON_LOG.  Keep the
empty message field in the record.
If we have performance problems with the mmexternal based
undefined_field.go, we can revisit adding skip_empty_fields
support to the mmnormalize json parser, or write
undefined_field.go as an rsyslog C module.
> Bug 1737286: The logs collected by rsyslog are not parsed

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
Cherry pick of https://github.com/openshift/cluster-logging-operator/pull/185
Also fixing ordering of nodes defined to prevent prior node recreation
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1712955
> [release-4.1] Bug 1712955: Fixing checking if nodes are different when scaling from 3 to 4

- files/rsyslog/60-mmk8s.conf
https://bugzilla.redhat.com/show_bug.cgi?id=1739558
CRI-o partial logs were not being joined because the endmsg.regex
and multiline parsing requires `escapeLF="off"` - it is on by
default.
This doesn't fix all of the problems in the bz . . .
> Bug 1739558: rsyslog underperforming compared to fluentd

- pkg/k8shandler/secret_test.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746695 by reverting the scope removed in https://github.com/openshift/cluster-logging-operator/pull/234/files#diff-5ff1cbe659b99e0e73d8ba484249c27cL480
> Bug 1746695: Add scope user:list-projects back to proxy

- hack/cr-aws.yaml
The metadata had extra indentation, which it shouldn't have. This way
it'll set the name correctly for the instance.
> Fix metadata from hack/cr-aws.yaml

- Makefile
- pkg/k8shandler/prometheus_rule.go
- pkg/utils/utils.go
gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile; it also fixes a couple of warnings that were found (which were probably not very problematic).
> Introduce gosec for security checks

- cmd/manager/main.go
main.go - adding configv1 to scheme
To get the cluster proxy object, configv1 needs to be added to scheme.  Without it, it fails with the following error:
`Failed to get proxy: no kind is registered for the type v1.Proxy in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61"`
> LOG-464 - Consume global proxy configuration (additional)

- hack/common
[ERROR]
+++ dirname hack/deploy-image.sh
+ skopeo copy --dest-tls-verify=false docker-daemon:quay.io/openshift/origin-cluster-logging-operator:latest docker://127.0.0.1:5000/openshift/origin-cluster-logging-operator:latest
time="..." level=fatal msg="Error trying to reuse blob sha256:... at destination: unable to retrieve auth token: invalid username/password"
> Fixing skopeo auth issue in deploy-image.sh

- hack/testing/test-clo-252-structs-to-pointers.sh
This may have never been passing. Lets skip this temporarily while we
deal with fixing the upgrade test.
> Temporarily skip structs-to-pointers e2e test

- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
Fix issue: `ERROR: metadata.annotations.alm-examples contains invalid json string [4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml]` when pushing manifests to quay.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1768537
> Bug 1768537: metadata.annotations.alm-examples contains invalid json string

- pkg/k8shandler/certificates.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1768685
> Bug 1768685: Improve missing secret message

- files/fluentd/run.sh
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/templates.go
the recent addition of logforwarding did not take into account
the latest changes to fix
Bug 1756920: fluentd pods do not process kubernetes events
https://bugzilla.redhat.com/show_bug.cgi?id=1756920
This commit adds back those fixes
will need to open (reopen?) a bz for 4.3 and backport
> refix eventrouter bug

- pkg/k8shandler/visualization.go
Remove parameter so Kibana re-login does not redirect more then once.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1619479
> Bug 1619479: Remove Kibana oauth-proxy param to allow re-login

- test/helpers/fluentd.go
This secret was being left out. That's fine in CI, but it leaves
leftovers for non-CI environments. So this PR cleans it up.
> Clean up fluent-receiver secret in fluent forwarding e2e test

- Makefile
- hack/testing/test-367-logforwarding.sh
- pkg/apis/logging/v1alpha1/forwarding_types.go
- pkg/apis/logging/v1alpha1/zz_generated.deepcopy.go
- pkg/k8shandler/certificates.go
- pkg/utils/utils.go
- scripts/cert_generation.sh
- test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go
- test/e2e/logforwarding/elasticsearchmanaged/logforwarding_suite_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/logforwarding_suite_test.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/e2e/logforwarding/fluent/logforwarding_suite_test.go
- test/helpers/fluentd.go
- test/helpers/framework.go
This whole test suite was being skipped by accident. This re-enables
that.
This applies the relevant fixes in order to get those tests to work
again:
* Fixing the LogForwardingList CR to take the proper type
* Use the appropraite certificates for elasticsearch
* Fix the cleanup of the fluent-receiver deployment
* Apply a sleep in the log generator so it doesn't overwhelm the
deployment
Co-Authored-By: Jeff Cantrill <jcantril@redhat.com>
> Enable logforwarding e2e test and fix fluentd forwarding test

- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
- pkg/controller/forwarding/forwarding_controller.go
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1768474
> Bug 1768474: Remove collector example from CSV

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/helpers/elasticsearch.go
This takes into use the index that was added to the viaq model in the
following PR https://github.com/ViaQ/fluent-plugin-viaq_data_model/pull/27
This way, when audit log forwarding is enabled, and it attempts to use
elasticsearch, it'll use an index that's specific for audit logs.
> Forward audit logs to their own index in elastic

- pkg/apis/logging/v1alpha1/forwarding_types.go
- pkg/controller/forwarding/forwarding_controller.go
- pkg/k8shandler/forwarding.go
- test/helpers/framework.go
Fix up status messages from:
```status:
LastUpdated: null
outputs:
- lastUpdated: null
name: fluentd-created-by-user
state: Accepted
pipelines:
- conditions:
- Message: ""
Reason: ReservedNameConflict
Status: "False"
Type: Name
lastUpdated: null
name: pipeline[0]
state: Dropped
- conditions:
- Message: ""
Reason: ReservedNameConflict
Status: "False"
Type: Name
lastUpdated: null
name: pipeline[1]
state: Dropped
- lastUpdated: null
name: clo-default-audit-pipeline
state: Accepted
sources:
- logs.audit```
> Cleanup status messages as commented in 1770644

- hack/common
- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
- pkg/constants/constants.go
- pkg/controller/add_controllers.go
- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/controller/collector/collector_controller.go
- pkg/controller/forwarding/forwarding_controller.go
- pkg/controller/proxyconfig/proxyconfig_controller.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/configmap.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/trustedcabundle.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
- pkg/utils/utils.go
- test/helpers/framework.go
clusterlogging_controller.go - Adding watch for cluster proxy
Borrowed the code from cluster-network-operator/pkg/controller/proxyconfig
> Bug 1752725: Log into kibana console get `504 Gateway Time-out The server didn't respond in time. ` when http_proxy enabled

- hack/testing/utils
During testing find that failures essentially went on forever because of inconsistency between use of seconds and milliseconds
> fix timing loops so they expire correctly

- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/controller/proxyconfig/proxyconfig_controller.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/clusterloggingrequest.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/configmap.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/trustedcabundle.go
- pkg/k8shandler/visualization.go
- pkg/utils/utils.go
Addresses: 
* https://bugzilla.redhat.com/show_bug.cgi?id=1768762
* https://bugzilla.redhat.com/show_bug.cgi?id=1766187
TODO: this PR currently just contains clean up for status triggers and unnecessary configmap updates with trustbundle information. Will also add logic to keep the proxy changes in our components.
When we have an event caught by the `proxyconfig_controller` we see that the proxy config info is pushed into the respective components. However, when we do not reconcile an event through there we are using `nil` for the proxy config and trustbundle CA so we then remove it. This is complicated by the fact that status updates can trigger an event being picked up so we were likely removing any proxy changes before the scheduler could process the deployment/daemonset changes.
> Bug 1768762: Persisting proxy config and trustbundle CM info

- files/fluentd/run.sh
Fixed the error when `run.sh` script for Fluentd tried to perform `sed` operations on a read-only FS:
```
sed: couldn't open temporary file /etc/fluent/configs.d/user/sedv62wWH: Read-only file system
```
> Bug 1773847: Fixed fluentd sed error

- hack/testing/assertions
- hack/testing/test-020-olm-upgrade.sh
- hack/testing/test-367-logforwarding.sh
- hack/testing/utils
- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
- pkg/logger/logger.go
- test/e2e/logforwarding/cleanup.sh
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/helpers/clusterlogging.go
- test/helpers/elasticsearch.go
- test/helpers/framework.go
4.3 backport of https://github.com/openshift/cluster-logging-operator/pull/312  which 4.4 is blocked by https://github.com/openshift/cluster-node-tuning-operator/pull/96
> fix lf timing issue

- test/helpers/elasticsearch.go
More updates to make LF testing more reliable
Ref 4.4: https://github.com/openshift/cluster-logging-operator/pull/316
> Allow logforwarding tests to cleanup from go invocation

- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/controller/forwarding/forwarding_controller.go
- pkg/controller/proxyconfig/proxyconfig_controller.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/visualization.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1782740
Able to recreate the master-certs secret and elasticsearch secret being recreated by deploying CLO, creating a log forwarding object, then deleting the CLO pod. No longer observe that with this PR.
> Bug 1782740: Addressing LF causing cert rotation

- Dockerfile
This PR modifies the base image:
* The ART process replaces FROM with what's required for a release
* The ci pipeline replaces FROM based on what's defined in config: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml#L11-L13
This change will allow us to continue to build locally
> replace FROM for local builds

- Makefile
- golangci.yaml
Added `lint` target to Makefile (using `golangci-lint`: https://github.com/golangci/golangci-lint). For now it is just a recommendation. But it is highly recommended to use that as a prerequisite for `make build`
> Added lint target to Makefile

- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
Fix an issue where the cluster-logging-operator couldn't be upgraded because it doesn't match the update_list defined in art.yaml nor configured in correct range.
Similar issue https://github.com/openshift/elasticsearch-operator/pull/237
> Bug 1802934: Fix incorrect olm.skipRange in 4.3 CSV

- hack/common
This PR provides a small fix for a glitch landed by merging the feature-es6 branch back to master. It enables execution of make targets against a development cluster from a local development environment, where basic environment variables are substituted from the manifests.
> Fix make targets for local development environment

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/helpers/elasticsearch.go
This PR:
* resolves https://issues.redhat.com/browse/LOG-599
* updates the fluent config to write to a static index
* blocked by https://github.com/openshift/origin-aggregated-logging/pull/1797 and equivalent into feature branch
> LOG-599: Update fluent config to use static index

- manifests/4.5/logforwardings.crd.yaml
- pkg/apis/logging/v1alpha1/forwarding_types.go
- pkg/generators/factory.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- test/e2e/logforwarding/syslog/deleteme.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/e2e/logforwarding/syslog/logforwarding_suite_test.go
This PR adds the ability to define a pipeline that outputs data to an external syslog server and uses the existing remote-syslog plugin.
An example of specification of syslog output within the `LogForwarding` CR:
```yaml
spec:
outputs:
- name: syslog
type: syslog
endpoint: "10.46.9.101:515"
insecure: true
pipelines:
- name: logsapp
inputSource: logs.audit
outputRefs:
- syslog
```
This will result in the following configuration section for fluentd:
```xml
<label @SYSLOG>
<match **>
@type copy
<store>
@type syslog_buffered
@id syslog
remote_syslog 10.46.9.101
port 515
hostname ${hostname}
facility user
severity debug
remove_tag_prefix
</store>
</match>
</label>
```
Alternatively, the transport protocol can be set to udp by specifying the protocol within the `endpoint`:
```yaml
spec: …
```
> Forwarding to external syslog, based on current fluentd plugin

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
Adds a `"kubernetes.io/os": "linux"` node selector for the ClusterLoggingOperator deployment
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1808986
> Bug 1808986: Adding nodeSelector to operator deployment

- pkg/k8shandler/reconciler.go
Fix for #375. 
Preconditions:
```logging.openshift.io/ClusterLogging``` named "instance" is missing
```config.openshift.io/Proxy``` named "cluster" exists
The CLO comes up, finds the cluster-wide Proxy object, triggers a reconcile and the following call chain builds up:
```go
k8shandler.(*ClusterLoggingRequest).RemoveServiceAccount()
k8shandler(*ClusterLoggingRequest).CreateOrUpdateCollection()
k8shandler.ReconcileForGlobalProxy()
proxyconfig.(*ReconcileProxyConfig).Reconcile()
```
There's no logging.openshift.io/ClusterLogging instance, so in ```ReconcileForGlobalProxy()```, ```getClusterLogging()``` returns an empty object, which on the next line is used to populate clusterLoggingRequest.cluster:
```
clusterLoggingRequest.cluster = clusterLogging
```
In ```RemoveServiceAccount()```, the …
> Fix for #375: Proxyconfig-controller fails to delete logcollector service account

- pkg/k8shandler/status.go
This fix replaces the changing lastTransitionTime for Terminated container statuses with the actual termination time (FinishedAt), thus preventing a hotloop reconcile over status that is known to not change.
> Fix for LOG-676, prevent a hotlooping reconcile for a terminated curator job

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/templates.go
https://bugzilla.redhat.com/show_bug.cgi?id=1816770
> Bug 1816770: Fluentd inserts \'\' into some log messages ingested from container logs

- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/k8shandler/conditions.go
- pkg/k8shandler/forwarding.go
Example output for when we have no logstore nor logforward defined
when invalid:
```
status:
clusterConditions:
- lastTransitionTime: "2020-03-17T19:42:25Z"
message: Collectors are defined but there is no defined LogStore of LogForward
destinations
reason: No defined logstore destination
status: "True"
type: CollectorDeadEnd
```
when valid we remove the condition
> Adding conditions for when log collection is missing destinations

- Makefile
This PR removes `make` dependency on generate to satisfy the ART building process
> Bug 1817592: fix Makefile in order to fix ART builds

- pkg/generators/forwarding/fluentd/generators.go
Fix pretty print of generated fluent.conf. Improve readability.
Example output:
```
<system>
@log_level "#{ENV['LOG_LEVEL'] || 'warn'}"
</system>
<source>
@type prometheus
bind ''
<ssl>
enable true
certificate_path "#{ENV['METRICS_CERT'] || '/etc/fluent/metrics/tls.crt'}"
private_key_path "#{ENV['METRICS_KEY'] || '/etc/fluent/metrics/tls.key'}"
</ssl>
</source>
```
Output before this change:
```
<system>    
@log_level "#{ENV['LOG_LEVEL'] || 'warn'}"    
</system>    
<source>    
@type prometheus    
bind ''    
<ssl>    
enable true    
certificate_path "#{ENV['METRICS_CERT'] || '/etc/fluent/metrics/tls.crt'}"    
private_key_path "#{ENV['METRICS_KEY'] || '/etc/fluent/metrics/tls.key'}"    
</ssl>    
</source>    
```
> Fix pretty print of generated fluent.conf

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- README.md
- bin/README.md
- deploy/crds/logging.openshift.io_clusterloggings_crd.yaml
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/curation_test.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
- pkg/k8shandler/oauthclient.go
- pkg/k8shandler/promtail.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
Changes:
- trivial source file changes from gofmts and to satisfy the linter.
- drop _output file, not necessary and causes confusion.  
- remove unused variables, simplify targets.  
- add dependencies to make targets self-sufficient.
Signed-off-by: Alan Conway <aconway@redhat.com>
> LOG-682: Remove _output directory, simplify Makefile

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR disables verifying ES version at startup so that other collections and outputs may proceed
> turn off ES verification at start to not stop log collection

- manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
Manual cherry-pick of #392
Adds a `"kubernetes.io/os": "linux"` node selector for the ClusterLoggingOperator deployment
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1812920
> Bug 1812920: Adding nodeSelector to operator deployment

- test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
- test/helpers/framework.go
fix logforwading test case flakiness
Make each test case to wait for pods to complete, before starting next test case
> fix logforwading test case flakiness

- olm_deploy/scripts/registry-init.sh
This PR addresses an issue on running E2E olm-based tests locally against a devcluster where the operator is already present on the nodes but a newer image was pushed by the development workflow.
This issue is not present on CI, because IMAGE_FORMAT (e.g. egistry.svc.ci.openshift.org/ci-op-3cfm5kx8/stable:${component}) ensures a stable unique name whether local development usually points to your-registry-of-choice/openshift/origin-cluster-logging-operator:latest.
Transfer from: openshift/elasticsearch-operator#304
> Overwrite pull policy for local olm based E2E tests

- Makefile
- pkg/generators/forwarding/factory.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/trustedcabundle.go
- test/helpers/framework.go
- Formatted cm/fluentd:fluent.conf so it is usable with ```oc get cm/fluentd -oyaml```
- Added build-debug and run-debug targets to the Makefile
- Added error handling during fluent.conf generation
- Made lint happy in test/framework.go
Before:
```
$ oc get cm/fluentd -oyaml
apiVersion: v1
data:
fluent.conf: "## CLO GENERATED CONFIGURATION ###\n# This file is a copy of the fluentd
configuration entrypoint\n# which should normally be supplied in a configmap.\n\n<system>\n
\ @log_level \"#{ENV['LOG_LEVEL'] || 'warn'}\"\n</system>\n\n# In each section
```
After:
```
$ oc get cm/fluentd -oyaml
apiVersion: v1
data:
fluent.conf: |+
<system>
@log_level "#{ENV['LOG_LEVEL'] || 'warn'}"
</system>
...
```
> Formatted cm/fluentd:fluent.conf so it is usable with oc get cm/fluentd -oyaml

- hack/testing-olm/test-999-fluentd-prometheus-metrics.sh
Wait for desired number of fluent instances to be populated in daemonset before waiting for all fluentd instances to be running.
error text found in CI
```
[INFO] Waiting for 0 fluent pods to be available....
```
but it should be 6.
> Fix flaky test fluentd-prometheus-metrics

- manifests/4.5/image-references
This PR intentionally introduces a mismatch in image-references so that ART will not point to productized image: 
https://bugzilla.redhat.com/show_bug.cgi?id=1793551
> Bug 1793551: Intentional promtail image-reference mismatch

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
Team,
I created [this issue](https://github.com/openshift/cluster-logging-operator/issues/439) and created this PR to have the correct path to get the status of ES and Kibana.
Do let me know if any modification is required.
> fixes the issue #439 where the status is not shown and gives a warning message that the field is invalid

- README.md
- hack/testing-olm/test-010-deploy-via-olm-minimal.sh
- hack/testing-olm/test-020-olm-upgrade.sh
- hack/testing-olm/test-367-logforwarding.sh
- hack/testing-olm/test-999-fluentd-prometheus-metrics.sh
- test/e2e/logforwarding/cleanup.sh
This PR uniforms the know to skip clean-up scripts for E2E tests. The environemt variable `DO_CLEANUP` needs to be set explicitly to `false` for this purpose.
> Uniform environment variable to skip cleanup for E2E tests

- hack/testing-olm/test-367-logforwarding.sh
- hack/testing/test-367-logforwarding.sh
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/cleanup.sh
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
- test/helpers/elasticsearch.go
- test/helpers/fluentd.go
- test/helpers/framework.go
- test/helpers/syslog.go
Updated syslog LF testcase for each syslog rfc
- the syslog receiver is created with specific rfc parser (rfc3164, rfc5424)
- the testcase Expect clause checks for specific fields in the received syslog messages
- increased timeout for logforwarding testcase completion, and added `-ginkgo.noColor`
- capturing syslog-receiver logs and configuration in artifacts
> Updated syslog LF testcase for each syslog rfc

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/files/secure-forward.conf
This change limits the fluentd queue length to match the number of chunks on the filesystem.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1780698
Needs backport for: release-4.4 and release 4.3.
> Bug 1780698: Fix disk pressure for fluentd buffer chunks

- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/controller/forwarding/forwarding_controller.go
- pkg/controller/proxyconfig/proxyconfig_controller.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/visualization.go
Manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/323
To address https://bugzilla.redhat.com/show_bug.cgi?id=1813381
Dependent on https://github.com/openshift/cluster-logging-operator/pull/441 to fix failing tests
> [release-4.3] Bug 1813381: addressing lf causing cert reconciliation

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
This PR adds missing permissions to allow the operator to set the owner reference to the metrics service resource.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1817097
> Bug 1817097: Grant perm to set owner ref to metrics Service resource

- hack/testing-olm/test-020-olm-upgrade.sh
- hack/testing-olm/utils
This PR enhances the debugging experience of E2E tests by expanding the log exporter in two ways:
- Adds support to export logs from `initContainers`. This enables capturing errors with inconsistencies between the CSV and the provided CRDs on building the operator registry database by `mutate-csv-and-generate-sqlite-db`, e.g. :
```
time="2020-04-15T14:03:11Z" level=warning msg="permissive mode enabled" error="error loading manifests from directory: error checking provided apis in bundle clusterlogging.v4.5.0: couldn't find logging.openshift.io/v1alpha1/LogForwarding (loggggforwardings) in bundle. found: map[logging.openshift.io/v1/ClusterLogging (clusterloggings):{} logging.openshift.io/v1alpha1/Collector (collectors):{} logging.openshift.io/v1alpha1/LogForwarding (logforwardings):{}]" …
```
> Enhance debug experience for E2E operator registry

- olm_deploy/scripts/registry-init.sh
This PR address an env var hindsight for overriding the kibana image on olm-based deployments, e.g. E2E tests.
> Fix kibana image env var override for olm deployments

- test/helpers/framework.go
- test/helpers/oc/command.go
- test/helpers/oc/doc.go
- test/helpers/oc/exec.go
- test/helpers/oc/exec_test.go
- test/helpers/oc/get.go
- test/helpers/oc/get_test.go
- test/helpers/oc/literal.go
- test/helpers/oc/literal_test.go
- test/helpers/oc/oc_suite_test.go
- test/helpers/oc/runner.go
Added a wrapper over oc to run oc commands from golang
- supports oc.Exec() for 'oc exec'
- supports oc.Get() for 'oc get' 
- supports oc.Literal() for other oc commads which do not have a DSL yet. can be added later.
- added unit test cases
> Added a wrapper over oc to run oc commands from golang

- pkg/k8shandler/status.go
This PR addresses the node count reporting for elasticsearch nodes in the CLO status field. In detail on a setup with more than three nodes the elasticsearch-operator will create more than one deployments. Thus picking up the node count from the spec is not the correct approach.
> Bug 1732698: Fix fetching node count from elastichsearch status

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
- manifests/4.5/image-references
- pkg/k8shandler/logstore.go
- pkg/utils/utils.go
This PR stops specifying the ES image in the elasticsearch CR to avoid image/config mismatch between CLO and EO
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1809498
> Bug 1809498: Stop specifying ES image in CLO

- pkg/k8shandler/visualization.go
This PR modifies clo to not specify the Kibana image.
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1809498
> Bug 1809498: Do not specify Kibana image

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/files/secure-forward.conf
This PR backports a serious issue we have according to multiple customer cases regarding fluentd buffers taking up all the node filesystem until crashing the node itself.
Manual cherry-pick for: #479 because of [reason](https://github.com/openshift/cluster-logging-operator/pull/479#issuecomment-617887451)
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1826861
> [release-4.4] Bug 1826861: Fix disk pressure for fluentd buffer chunks

- pkg/k8shandler/logstore.go
This PR removes trace loglevel for ES that was introduced in error.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1834558
Introduced by: https://github.com/openshift/cluster-logging-operator/pull/423
> Bug 1834558: Remove trace loglevel for ES

- HACKING.md
- Makefile
- README.md
Improved the `make run` target to be self-contained and idempotent.
Consolidated HACKING into README and re-orgainzed to reflect
recent dev experience.
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1833520
> LOG-764: Improved `make run` with self setup, consolidated README.

- Makefile
- pkg/constants/constants.go
- pkg/controller/trustedcabundle/trustedcabundle_controller.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/collection_test.go
- pkg/k8shandler/configmap.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/trustedcabundle.go
This PR addresses several issues on reconciliation of the trusted CA-Bundle config map as well the hash annotation on the fluentd deployment.
To address:
- https://bugzilla.redhat.com/show_bug.cgi?id=1834311
- https://bugzilla.redhat.com/show_bug.cgi?id=1833273
Needs backport to: release-4.4
> Bug 1834311: Fix trusted ca bundle and hash reconciliation

- pkg/k8shandler/collection.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/315
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1826793
> Bug 1826793: Updating kibana update to also check proxy container env

- manifests/4.5/image-references
I think I misunderstood the point of this file, thinking something outside ART cared about it. If we're not looking to replace promtail downstream, I don't see a point in keeping it here -- it just forces us to look up an image and not do anything with it.
I think removing it would be a better solution for https://bugzilla.redhat.com/show_bug.cgi?id=1793551
> bug 1793551: image-references: remove promtail

- pkg/k8shandler/forwarding.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1836044
> Bug 1836044: Log LF generations warnings only on error

- files/fluentd/run.sh
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1838055
> Bug 1838055: Reset NUM_OUTPUTS to 1 when all LF outputs invalid

- pkg/controller/trustedcabundle/trustedcabundle_controller.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/collection_test.go
- pkg/k8shandler/configmap.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/trustedcabundle.go
- pkg/k8shandler/visualization.go
This PR addresses a backport of #517 and openshift/elasticsearch-operator#351 for **release-4.4*. The change set needs to be added manually because Kibana is reconciled by cluster-logging-operator until release 4.4.
To address:
- https://bugzilla.redhat.com/show_bug.cgi?id=1833288
- https://bugzilla.redhat.com/show_bug.cgi?id=1833273
> Bug 1833288: Fix trusted ca bundle and hash reconciliation

- .dockerignore
- Dockerfile
buildah takes more time to execute COPY if there is a .dockerignore file
- add individual COPY statements for copying individual files and folders required for `make build`
- delete .dockerignore
> Speedup build by COPYing less

- test/e2e/collection/fluentd/flatten_labels_test.go
- test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
- test/e2e/logforwarding/kafka/forward_to_kafka_test.go
- test/e2e/logforwarding/multiple_outputs/forward_to_multiple_outputs_test.go
- test/e2e/logforwarding/multiple_outputs/logforwarding_suite_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
- test/helpers/elasticsearch.go
- test/helpers/fluentd.go
- test/helpers/framework.go
- test/helpers/kafka.go
- test/helpers/syslog.go
This PR addresses the case of a LogForwarding CR with multiple outputs. It ensures that all available outputs receive the requests logs according to the defined pipeline.
Depends on: #427
> Ensure LogForwarding works with multiple outputs

- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
When CLO's CR created only with the `collection` section and then removed after some time, CLO will crash trying to reconcile Fluentd. This patch fixes that.
The root cause is that when CLO is triggered to restart fluentd, the `collection` section may not be configured in the CLO's CR.
> Bug 1844445: Fixed CLO crash when reconciling Fluentd

- render_templates
This file is required in the cpaas operator build flow
reference: https://gitlab.sat.engineering.redhat.com/cpaas/documentation/-/blob/building-operators/schema/product/builds/brew_container_operator.adoc#user-content-render-templates
> Added render_templates required for operator brew build using cpaas

- olm_deploy/operatorregistry/Dockerfile
This PR addresses a newly incorporated change in the operator registry image that needs a temporary directory to back the bundles database before migrating. (See operator-framework/operator-registry#332)
**Needs backport:** release-4.5
> Bug 1847413: Fix E2E olm registry migration

- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
This is a backport of https://github.com/openshift/cluster-logging-operator/pull/551 for release-4.5.
Automatic cherry-pick was not possible due to conflicts in test files.
> [release-4.5] Bug 1846482: Fixed CLO crash when reconciling Fluentd

- files/fluentd/run.sh
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/helpers/fluentd.go
This PR:
* removes cli switches to control loglevel favoring a level defined in config.
* corrects system log_level to remove '@' in accordance with the docs
During testing I discovered no logs were being created because the command lineswitch takes precedence over config which hides valueable info
> rely on config to dictate loglevel in lieu of runtime args

- pkg/controller/forwarding/forwarding_controller.go
- pkg/k8shandler/reconciler.go
This PR provides a fix to reconcile the status of ClusterLogFowarder CRs. In detail, the reconciliation runs before updating the status, whereas the order was flipped.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1851680
> Bug 1851680: Fix ClusterLogForwarder status reconciliation

- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/k8shandler/conditions.go
- pkg/k8shandler/forwarding.go
This change set addresses a manual cherry pick for 8d0d82ff to handle cluster logging setups w/o a log store and log forwarding instances. In addition it improves the missing error handling for the else branch in the original commit.
This PR for release 4.4 is different to the parent PR for 4.5 because 8d0d82ff was introduced by a sprint enhancement task w/o noticing the broken feature. In addition the patch for 4.5 as well for 4.6 is a consequence of introducing Elastiscsearch 6. The target release 4.4 is still based on Elasticsearch 5. 
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1851381
> Bug 1851381: Add condition when log collection is missing outputs

- manifests/4.6/cluster-loggings.crd.yaml
- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
Also re-orded the name: sectoin of the ClusterLogForwarding CRD to be consistent.
> Added "cl" short name for ClusterLogging CRD.

- manifests/generate_manifest.py
- manifests/render_templates
- render_templates
- Added manifests/generate_manifest.py
- Added manifests/render_templates
- Added link to manifest/render_templaes to root
- render_templates script is invoked by CPaaS
- generate_manifest.py python scrips reads build-info generated by CPaaS and generates image manifests
> Added Initial CPaaS scripts

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
In order for the cluster-logging-operator to be correctly filtered in
the OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
> Bug 1850546: Add support label for s390x & ppc64le

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
This PR addresses a bump of minKubeVersion to 1.18.3 because cluster-logging-operator is using client-go 1.18.x-only APIs and complies with 1.18.x upstream deprecation removals (See #576)
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1852889
> Bug 1852889: Bump minKubeVersion to 1.18.3

- olm_deploy/scripts/operator-install.sh
This addresses the issue that we need to use labels instead of annotations to allow metrics to be collected for a particular namespace.
> updating to label ns instead of annotate

- Makefile
- bin/README.md
- hack/get-openshift-client.sh
- manifests/4.6/crd-v1-singleton-patch.yaml
- manifests/4.6/kustomization.yaml
- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
- olm_deploy/operatorregistry/Dockerfile
**Description**
This PR addresses the required schema validation for `ClusterLogForwarder` resources to allow where `metadata.name` has value `instance`.
**Solution**
The approach selected is based on patching the generated CRD file with the on-board openshift client utility `oc kustomize`. The reasoning is that CRD openAPI schema generation is based on kubebuilder annotations, which is limited to explicitly declared fields in the CRD go struct fields. Since metadata fields (i.e. `TypeMeta` and `ObjectMeta`) are declared as embedded structs in the CRD go struct, their fields cannot be annotation via comments.
Kustomize is the onboard utility to patch manifests with kubectl/oc, e.g. to add common labels, namespaces and in extend apply patches.
/cc @jcantrill
> Add validation to ClusterLogForwarder name required to be "instance"

- files/fluentd/run.sh
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/files/secure-forward.conf
This PR addresses the performance variance from 4.4:
* Reverts the change to the number of queued chunks: #479
* Cap disk usage based an a percent and total_byte_limit
* modify the rotate_wait parameter to 1.0
* Configure pos_file_compaction_interval to 5m to address
https://bugzilla.redhat.com/show_bug.cgi?id=1833486
> Bug 1833486: Improve fluent performance in comparison to 4.4 

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR provides additional collector config changes to address performance versus 4.4:
* Bumps rotate_wait to allow fluent to continue to collect rotated logs
* Drops the new file interval
* Extends the pos_file_compact_interval which seems to affect dropped messages for short runs with high load
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1833486
> Bug 1833486: Collector config changes to address performance versus 4.4

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
This PR  reverts commit 9f47fcb62f5fa5be7707b30d60c7aa4b4ad50fdf and in extend downgrades the `minKubeVersion` to `1.17.0`, because apiserver on CI is still on `v1.17.0-alpha.0.7867+649a587b0a0f5d-dirty`
> Revert "Bug 1852889: Bump minKubeVersion to 1.18.3"

- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR addresses a fix to use Fluentd EventTime instead of ruby's time for nanosecond precision.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1857206
/cc @jcantrill @vimalk78
> Bug 1857206: Use fluentd event time for processing logs to kafka

- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR addresses the missing conditional configuration for kafka mTLS support. In detail the fluentd configuration sets the client cert and key only if the calculated paths from the secretRef exists on runtime.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1856940
/cc @igor-karpukhin @jcantrill
> Bug 1856940: Add kafka mTLS conditional support

- pkg/k8shandler/visualization.go
This PR addresses a missing backport of the kibana trusted CA bundle hash reconciliation in **release-4.4**. This is a amendment to #524 for the visualization component namely Kibana.
To address:
- https://bugzilla.redhat.com/show_bug.cgi?id=1855220
- https://bugzilla.redhat.com/show_bug.cgi?id=1833273 (Kibana only, as fluentd addressed by #524)
- https://bugzilla.redhat.com/show_bug.cgi?id=1833288 (Kibana only, as fluentd addressed by #524)
The original issue affected the reconciliation of a custom CA bundle for fluentd and kibana. This PR is an extra amendment for #524, that addressed unfortunately only fluentd in **release-4.4**. The reconciliation of Kibana moved in 4.5 from `cluster-logging-operator` to `elasticsearch-operator` w/o breaking any API or user experience. The issue was …
> Bug 1855220: Update trustedCA hash for visualization component

- pkg/generators/forwarding/factory.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
This PR addresses a fix to disable [log forwarding](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-external.html#cluster-logging-collector-log-forward_cluster-logging-external) config generation when one of the two legacy methods is used, i.e. [fluentd legacy forward](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-external.html#cluster-logging-collector-fluentd_cluster-logging-external), [syslog legacy forward](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-external.html#cluster-logging-collector-syslog_cluster-logging-external)).
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1858200
**Needs backport:** release-4.5 and release-4.4
/cc @jcantrill @alanconway @vimalk78
> Bug 1858200: Disable LogFowarding when legacy protocols in use

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
In order for the cluster-logging-operator to be correctly filtered in
the OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
(cherry picked from commit 78e1e2b728a9aeae6400f2e9a8b364bb0df7985b)
> [release-4.5] Bug 1855312: Add support label for s390x & ppc64le

- files/fluentd/fluentd-throttle-config.yaml
- pkg/k8shandler/fluentd.go
This PR
* removes the throttle config which is no longer used in collection conf
cc @alanconway
> Remove obsoete throttle-config

- hack/generate-crd.sh
- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
- pkg/apis/logging/v1/cluster_log_forwarder_types.go
- test/e2e/collection/fluentd/flatten_labels_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/e2e/logforwarding/multiple_outputs/forward_to_multiple_outputs_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
* `URL` parameter of `OutputSpec` for `ClusterLogForwardings` made mandatory
> Bug 1857094: Add validation for URL parameter for LF CR

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR reverts configuration setting to 4.4 values:
* rotate_wait 5 sec
* watch_interval 5 sec
Tested these values with both 1.7.4 of fluent and 1.11.1 and was able to successfully test 2,500 m/s consistently.  Noted with 1.7.4 when changing rotate_wait there was some message duplication
> Bug 1833486: Revert rotate_wait and refresh_interval to 4.4 setting

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/fluentd.go
This PR:
* Removes unused env vars
* Replaces env vars in config in favor of generating defaults where appropriate
The change of interest is the commti for LOG-839
Ref: https://issues.redhat.com/browse/LOG-839
> LOG-839: Remove unused fluent env vars

- manifests/4.5/cluster-logging.v4.5.0.clusterserviceversion.yaml
The Cluster Logging Operator info page in the OCP web console links to the 4.1 version of the Cluster Logging documentation.
> Bug 1811879: Docs URL in the CLO description refers to 4.1, v. 4.5

- manifests/4.3/cluster-logging.v4.3.0.clusterserviceversion.yaml
A fix for the doc URL in the CLO description in the web console
> Bug 1811872: Synced doc version in the CLO description, v 4.3

- manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
A fix for the doc URL in the CLO description in the web console
> Bug 1811870: Synced doc version in the CLO description, v 4.4

- docs/output_url_field.md
- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
- pkg/apis/logging/v1/cluster_log_forwarder_types.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
- pkg/url/url.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
Use url.Parse() for all URL parsing, require that URLs be well formed and absolute
> Use a real URL parser, only accept well-formed absolute URLs for output.url.

- Dockerfile
- README.md
- must-gather/README.md
- must-gather/collection-scripts/common
- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_collection_resources
- must-gather/collection-scripts/gather_curation_resources
- must-gather/collection-scripts/gather_elasticsearch_operator_resources
- must-gather/collection-scripts/gather_install_resources
- must-gather/collection-scripts/gather_logstore_resources
- must-gather/collection-scripts/gather_visualization_resources
This PR provides a must-gather plugin image for the `oc adm must-gather` facility to align cluster-logging's debugging practices within the openshift organization. The implementation is basically a break out of the established [origin-aggregated-logging/logging-dump.sh](https://github.com/openshift/origin-aggregated-logging/blob/master/hack/logging-dump.sh) but with several improvements and benefits:
1. The dump of standard k8s resources and their logs (e.g. deployments, services, secrets, pods, cronjobs, etc.) is automated via `oc adm inspect` and follows a well-known filesystem structure.
2. The former `logging-dump.sh` checks and dumps are grouped in separate `gather_$COMPONENT_resources` scripts and in turn improve maintenance and extensibility.
3. Users can easily identify that our …
> Add must-gather plugin image for cluster-logging stack

- Dockerfile
This PR is a spin off from #635 to update the golang builder to 1.14 first. This is a prerequisite for the Registry-Replacer in openshift/release.
> Bump golang builder to 1.14

- pkg/generators/forwarding/fluentd/generators.go
Note: the "consider preallocating" linter warns if a slice variable is declared using `var x []foo`. If you know up front an upper bound for the size of the slice you can pre-allocate with `x := make([]foo, maxlen)` which is more efficient.  If you are deliberately starting with a 0 length slice use `x := []foo{}` which is equivalent to the `var` form but satisfies the linter.
/cc @jcantrill
> Trivial change to make linter happy.

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR:
Reverts the deletion of the sniffer class to address ssl error experienced by the collector
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1864397
> Bug 1864397: Revert sniffer class deletion for collector es output

- manifests/4.4/cluster-logging.v4.4.0.clusterserviceversion.yaml
In order for the cluster-logging-operator to be correctly filtered in
the OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
(cherry picked from commit 78e1e2b728a9aeae6400f2e9a8b364bb0df7985b)
> [release-4.4] Bug 1855316: Add support label for s390x & ppc64le

- files/fluentd/fluentd_prometheus_alerts.yaml
- pkg/k8shandler/fluentd.go
FluentD error alerts are now based on a % instead of a number to account
for high ingestion rates.
This PR also adds an ability for CLO to update alerting rules.
/cc @ewolinetz @periklis @lukas-vlcek
> Bug 1866020: alert on error rate %

- pkg/k8shandler/visualization.go
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/392
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1852639
> [release-4.4] Bug 1852639: fixing kibana not rolling out with updated secret

- pkg/generators/forwarding/fluentd/output_fluentd_buffer.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
This PR addresses the missing defaults for the `forwarder.fluentd.buffer` spec when an empty spec is given. The defaults need to be re-addressed during template generation because CRD defaulting is only possible after switching to CRD v1 (See #648).
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1867129
/cc @jcantrill @vimalk78
> Bug 1867129: Fix defaults for empty forwarder buffer spec

- Dockerfile
This PR addresses the broken builds of the cluster-logging-operator image including the must-gather scripts with imagebuilder.
/cc @jcantrill @alanconway
> Fix must-gather copy script directives for imagebuilder

- pkg/k8shandler/indexmanagement/index_management.go
- pkg/k8shandler/indexmanagement/indexmanagement_test.go
- pkg/k8shandler/logstore_test.go
This PR:
* Defaults the retention policy so that CLO spec's indexManagement for all source types for LogForwarding
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1866619
cc @mburke5678 @alanconway 
Will need a 4.5 backport
> Bug 1866619: Default logstore retention policy so default LogForwarding is setup correctly

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
The `use_record true` setting is trying to use the "level" from the k8s
audit log which [is Metadata](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy). I believe we need to relabel k8s audit logs
"level" field to "k8s_audit_level" so that fluentd doesn't try to use it
as the severity and we can retain the original information.
> Bug 1852341: fix legacy syslog k8s Metadata

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
This PR is a manual cherry-pick of #604 to address: https://bugzilla.redhat.com/show_bug.cgi?id=1861013
The manual cherry-pick is justified here, because the underlying issue conflicts with different releases of the log forwarding API. In release 4.5 the API is called `LogFowarding` and is TechPreview. OTOH in release 4.6 the API is called `ClusterLogForwarder` and will be GA when the release lands for public consumption. However, the fix addresses how both APIs work together with our legacy support of ConfigMap based forwarding methods, i.e. `fluent forward`and `syslog`. Both methods are declared legacy since release 4.3 and should be used exclusive to either `LogFowarding` TechPreview or `ClusterLogFowarder` GA. 
The issue addressed here is re-establishing this exclusive usage to allow …
> Bug 1861013: Disable LogFowarding when legacy protocols in use

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
This PR reverts a change in https://github.com/openshift/cluster-logging-operator/pull/580 that breaks watching clusterlogging
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1870898
cc @ecordell please advise how we can watch target NS for one kind but watch global for a different cluster scoped resource
> Bug 1870898: Revert WATCH_NAMESPACE to unbreak clusterlogging

- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/utils/comparators/daemonsets/comparator.go
- pkg/utils/comparators/daemonsets/comparator_test.go
- pkg/utils/comparators/daemonsets/suite_test.go
This PR:
* Evaluates daemonset init containers when reconciling the collector
* Refactors daemonset comparison to no longer mutate incoming daemonsets
* Renames the method to retrieve the TrustedCAHash to be a getter instead of getter/mutator
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1868068
> Bug 1868068: Evaluate daemonset init containers during reconciliation

- pkg/apis/logging/v1/cluster_log_forwarder_types.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/source.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/collection/fluentd/namespace_filtering_test.go
- test/helpers/framework.go
- vendor/github.com/onsi/gomega/go.mod
Earlier implementation of application namespace filtering was based on selectively scrapping logs for namespaces in CLF spec.inputs.application.namespaces
CLF approach is to scrape all container logs, and then generate fluent conf according to the CLF spec.pipeline.
Now if namespaces are specified in spec.inputs.application, then <match> filter is used to send only the namespace logs to pipeline.
The logic for dispatching application logs is:
```
if .CollectAppLogs
if .AppNamespace
<match $ns>  // tags for namespace only
@type relabel
@label @_APPLICATION
</match>
else
<match k8s.**>
@type relabel
@label @_APPLICATION
</match>      
fi
else
<match k8s.**>
@null
</match>
fi
```
/cc @alanconway @jcantrill
> Bug 1862367: fixed application namespace filtering

- bundle/manifests/cluster-logging.v4.6.0.clusterserviceversion.yaml
- bundle/manifests/crd-v1-clusterloggings-patches.yaml
- bundle/manifests/kustomization.yaml
- bundle/manifests/logforwardings.crd.yaml
- bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml
- bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml
- hack/generate-crd.sh
- manifests/4.6/crd-v1-clusterloggings-patches.yaml
- manifests/4.6/kustomization.yaml
- manifests/4.6/logging.openshift.io_clusterloggings_crd.yaml
- olm_deploy/operatorregistry/Dockerfile
This PR addresses a recommended upgrade of the `apiVersion` of cluster-logging-operator managed CRDs from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`. Former is deprecated in upcoming k8s release 1.19 and very likely removed in 1.20. In extent addressing this upgrade sooner than later frees the operator upgrade procedure from limbo to enable installation of version `N` on an OCP cluster version `N-1`, where the cluster version has dropped the deprecated versions.
/cc @jcantrill @ewolinetz
> Bug 1871737:  Upgrade CRD apiVersion apiextensions.k8s.io from v1beta1 to v1

- hack/common
- hack/testing-olm/test-030-collection.sh
- hack/testing-olm/test-367-logforwarding.sh
Removing the -v flag from go test prevents Go from printing any of the
t.Log messages unless the test fails.
/cc @igor-karpukhin
> make tests less verbose

- test/e2e/collection/cleanup.sh
- test/e2e/collection/fluentd/namespace_filtering_test.go
- test/helpers/fluentd.go
The test case was failing randomly because fluent-receiver receives logs generated in previous test cases. So added a check for logs generated from this test case.
Added cleanup function for fluent-receiver.
/cc @jcantrill @alanconway
> Fixed namespace filtering test case

- pkg/generators/forwarding/fluentd/templates.go
https://bugzilla.redhat.com/show_bug.cgi?id=1873611
> Bug 1873611: Fixed pretty print of fluentd.conf in cm/fluentd

- hack/testing-olm/test-999-fluentd-prometheus-metrics.sh
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/utils/comparators/daemonsets/comparator_test.go
- test/matchers/envvar.go
This PR:
* Modifies fluent conf to bind prometheus endpoint to the podIP to satisfy ipv4 and ipv6
* Removes dead collector code to satisfy linter
* Adds gomega matchers for v1.EnvVar
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1862050
> Bug 1862050: Bind fluentd metrics to POD_IP to support ipv4 and ipv6

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
because the placeholder is within the `record` block we only use it's name
/cc @ewolinetz
> Bug 1852341: fix k8s_audit_level placeholder

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1875461 by making changes based on:
Per slide 6 suggestion - 
```
Add “urn:alm:descriptor:io.kubernetes:StorageClass” specDescriptor in CSV for “logStore.elasticsearch.storage.storageClassName“
Now the template is hard coded as “gp2”, which tripped GCP users up without obvious error messages surface on the UI or in YAML. 
Hence, a dropdown menu for choosing “StorageClass” may help.
```
Per slide 8 suggestion -
```
Drop the “Inc” from provider
```
> Bug 1875461: Updating CLO csv per operator one-click report

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
Also depends on
https://github.com/openshift/origin-aggregated-logging/pull/1978
This change along with the OAL above provides the following output.
This was tested by creating rsyslog, configuring LF -> rsyslog, and
setting rsyslog to log to stdout
```
2020-09-04T16:26:44+00:00 fluentd-94rcl fluentd: kind:Event#011apiVersion:audit.k8s.io/v1#011level:info#011auditID:a0fad62d-99f1-4cbd-97a0-0f5b7d37039b#011stage:ResponseComplete#011requestURI:/apis/batch/v1beta1/namespaces/openshift-logging/cronjobs/elasticsearch-delete-app/status#011verb:update#011user:{"username"=>"system:serviceaccount:kube-system:cronjob-controller", "uid"=>"c9f0cc6f-90d6-4c2a-829e-3dbcf6585242", "groups"=>["system:serviceaccounts", "system:serviceaccounts:kube-system", …
```
> Bug 1852341: fix syslog k8s audit level conflict

- hack/generate-crd.sh
- manifests/4.6/crd-v1-clusterloggings-patches.yaml
- manifests/4.6/logging.openshift.io_clusterloggings_crd.yaml
- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/k8shandler/status.go
- removed crd generation patch which was making an empty status in CRD
- fixed package name for `ClusterConditions` type. This was causing generated CRD to have a `$ref` field, which fails validation
- updated clusterlogging status in clusterlogging controller at the end of Reconcile function
- fixed elasticsearch pod state to return empty array if status not available for a state type, this was causing error like `status.logStore.elasticsearchStatus.pods.client.failed in body must be of type array`
Getting status as:
```
status:
clusterConditions:
- lastTransitionTime: "2020-09-08T20:54:00Z"
status: "False"
type: CollectorDeadEnd
collection:
logs:
fluentdStatus:
daemonSet: fluentd
nodes:
fluentd-hzjk7: crc-fd5nx-master-0
pods:
failed: []
notReady: []
ready:
- fluentd-hzjk7
curation: …
```
> Bug 1874746: Fixed ClusterLogging CR status

- hack/testing-olm/utils
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_elasticsearch_operator_resources
`oc must-gather` produces about 6000 lines of output while gathering for one failed test case.
This PR redirects the output of `oc must-gather` to `must-gather.log`
Also added back commands to get logging resources in must-gather scripts
> redirect must-gather output to a file

- Makefile
This PR adds a placeholder for functional tests so that we can enable CI
> Add placeholder for functional Makefile target

- files/fluentd/run.sh
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
This PR addresses a manual cherry-pick of #625 due to merge conflicts (see [here](https://github.com/openshift/cluster-logging-operator/pull/625#issuecomment-679119028)). In detail the PR backports the fix to allow using `LogForwarding` exclusively from legacy forward methods for syslog and fluentd-forward.
The merge-conflicts mentioned above manifest in the following features added to `release-4.5` and upwards and not present in `release-4.4`. The features are applied in the fluentd configuration generation and thus test development in upwards branches need to be slimmed down in downwards branches. Features in play (See expected fluentd configs `output_conf_legacy_test.go `):
- Filtering application logs per namespace
- Switch of the data model to static indices, e.g. `infra-write`
- …
> Bug 1861224: Disable LogFowarding when legacy protocols in use

- hack/testing-olm/utils
- test/e2e/logforwarding/cleanup.sh
- test/e2e/utils.go
- test/helpers/elasticsearch.go
- test/helpers/fluentd.go
- test/helpers/framework.go
- test/helpers/kafka.go
- test/helpers/syslog.go
1. Changed `cat /shared/consumed.logs` to `tail -n 5000 /shared/consumed.logs` to limit the logs are fetched from pod
2. fixed closure in wait.Poll to return nil if the command in closure gets an error
3. fixed location of `must-gather.log`
4. fixed log generator namespace already exists error
> Fixing test flakes

- hack/testing-olm/test-999-fluentd-prometheus-metrics.sh
- test/helpers/fluentd.go
- test/helpers/framework.go
- test/helpers/kafka.go
This PR rebuilds the e2d test framework kubeclient everytime to avoid issues in watches waiting for deployments
> make e2e framework watches more resilient

- go.mod
- go.sum
- vendor/github.com/onsi/gomega/go.mod
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/apimachinery/pkg/util/net/http.go
- vendor/modules.txt
The following deps were updated:
* api
* apimachinery
> Bug 1878123: Bump client-go v1.18.3 to v1.18.8

- pkg/apis/logging/v1/cluster_log_forwarder_types_test.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/k8shandler/forwarding_test.go
- test/matchers/diff.go
- test/matchers/diff_test.go
Move all our custom matchers into the 'matchers' package.
Ginko convention uses anonymous imports, but that's a bad idea for anything
else. Therefore Gingko extensions must be in a separate package from other code.
/cc @jcantrill
> Bug 1880012: Move custom Ginkgo matchers to matchers package.

- .gitignore
- pkg/k8shandler/visualization.go
Fixed app panic when dereferencing annotations for kibana deployment
Backport of openshift/elasticsearch-operator#492
> Bug 1881493: Fixed app panic when dereferencing annotations for kibana deployment

- pkg/k8shandler/collection.go
- pkg/k8shandler/rbac.go
This PR addresses a mismatch in using `ownerReferences` for ClusterLogging CR dependents. Based on the following list the operator reconciler cluster-scoped dependents that poison the kubernetes gargbage collector cache. In turn the ClusterLogging CR and its namespace dependents get deleted as discussed in this upstream [PR](https://github.com/kubernetes/kubernetes/issues/65200) as well as noted on the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents).
```
"Service/fluentd"
"CronJob/curator"
"ConfigMap/curator"
"ConfigMap/fluentd"
"ConfigMap/fluentd-trusted-ca-bundle"
"Secret/curator"
"Secret/elasticsearch"
"Secret/fluentd"
"Secret/kibana"
"Secret/kibana-proxy"
"Secret/master-certs"
"ServiceAccount/curator" …
```
> Bug 1880926: Fix owner references for ClusterLogging CR

- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR resolves a missing method by returning empty string if a cert file does not exist
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1883079
Depends on https://github.com/fluent/fluent-plugin-kafka/pull/374 long term
> Bug 1883079: Resolve missing 'use_nil'

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR resolves legacy syslog forwarding and is 4.5 backport of:
* #659 
* #684 
* #690
Depends upon https://github.com/openshift/origin-aggregated-logging/pull/1995
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1881996
cc @blockloop  please review for correctness.
> Bug 1881996: fix legacy syslog k8s Metadata

- bundle/manifests/cluster-logging.v4.6.0.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/4.6/logging.openshift.io_clusterloggings_crd.yaml
This PR addresses the missing update of the bundle manifests after reverting CLF from cluster-scoped  to namespace-scoped. This is mandatory to provide an up2date 4.6.0 bundle image.
- Depending on PR(s):  #720
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1884275
> Bug 1884477: Update bundle manifests for namespaced CLF

- pkg/k8shandler/defaults.go
The current default memory requests and limits for elasticsearch-proxy are set to 64Mi. This is a too tight budget according to openshift/elasticsearch-operator#523
In turn this results into container restarts that have impact on serving elasticsearch requests reliably. This PR addresses this issue by bumping the elasticsearch-proxy request/limits from `64Mi` to `256Mi`
/cherry-pick release-4.6
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1886856
> Bug 1886856: Increase es proxy default memory resources to 256Mi

- Dockerfile
Updating cluster-logging-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-logging-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating cluster-logging-operator builder & base images to be consistent with ART

- hack/generate-crd.sh
- hack/get-openshift-client.sh
- save some time during the build process
- avoid 404 if the file has already downloaded
> Minor fix to the scripts under ./hack 

- pkg/factory/service.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/service.go
- pkg/utils/comparators/services/comparator.go
- pkg/utils/comparators/services/comparator_test.go
- pkg/utils/comparators/services/suite_test.go
- test/helpers/fluentd.go
- test/helpers/kafka/broker.go
- test/helpers/kafka/zookeeper.go
- test/helpers/syslog.go
This PR addresses tech debt to:
* Constantly reconcile services to the state desired by the operator
* Move service constructor into an appropriately named factory package
* Add service comparator into the utils pkge
https://issues.redhat.com/browse/LOG-949
> LOG-949: Always reconcile services to desired state

- manifests/4.6/cluster-logging.v4.6.0.clusterserviceversion.yaml
This removes a specified `storageClassName` from the pre-populated example from the CSV.
From a usability perspective, if you are provisioning a new `ClusterLogging` and you are using OCP on AWS, you can click "Create" right after bringing the example up and it will provision. If you are on a non-AWS cloud, you won't have the `gp2` storage class, and things will stall out provisioning. Recovery from this is a little complex, as you need to manually remove all the PVCs (as they won't get deleted, even if you delete the `ClusterLogging` CR).
> Remove default storageclass from example

- docs/HACKING.md
> Remove "use docker" tip from HACKING, outdated and unreliable.

- Dockerfile.centos.patch
- Makefile
- docs/HACKING.md
The default Dockerfile is using RHEL8 repositories that are not accessible to all.
This will be fixed, but meantime, this enables optional built with CentOS packages:
PATCH=Dockerfile.centos.patch make ...
/cc @periklis
> Patch Dockerfile to use CentOS images.

- pkg/k8shandler/logstore.go
- pkg/k8shandler/logstore_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1879150
This change works to preserve the number of es nodes we create in the `es/elasticsearch` object managed by CLO to prevent EO flagging the change as invalid due to nodes missing.
This allows us to scale from `4 -> 3` nodes (and in theory `n -> 0` however EO will prevent this since the cluster would not have the required number of data or master nodes though to clear a cluster one should delete the elasticsearch CR)
> Bug 1879150: Updating how we scale down ES nodes in CR to preserve the number of es node definitions

- pkg/k8shandler/collection.go
- pkg/k8shandler/rbac.go
This PR is a manual backport of #713 . It removes all namespace-scoped owners from cluster-scoped resources' `ownerReferences` field. In turn this resolves random GC collection of ClusterLogging CR owned resources, e.g. deployments, Elasticsearch CR.
/cc @vimalk78  
/cherry-pick release-4.4
- Depending on PR(s):  #713
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1883777
> Bug 1883777: Fix owner references for ClusterLogging CR

- Makefile
- docs/HACKING.md
- hack/generate-crd.sh
This PR updates the Makefile to:
* decouple make run  from automatically deploying EO (doesn't handle already deployed operator nor should it need to)
* remove a non-existent dependent target
* fix CRD to rely on `oc` in the path
cc @alanconway
> make run does not deploy-eo

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR is using the `http_backend typhoeus` configuration for elasticsearch store to enable keep-alive.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1886856
- Depending PRs: openshift/origin-aggregated-logging#2010
> Bug 1886856: Add keep-alive backend for elasticsearch store

- olm_deploy/operatorregistry/Dockerfile
This PR reduces the size of the cluster-logging-operator-registry image from 1.1 GB to 333 MB:
```
$ podman image tree 308e10de91df
Image ID: 308e10de91df
Tags:     [127.0.0.1:5000/openshift/cluster-logging-operator-registry:latest]
Size:     1.118GB
Image Layers
├──  ID: 613be09ab3c0 Size: 211.1MB
├──  ID: 7da2b7b70275 Size: 840.7MB Top Layer of: [registry.svc.ci.openshift.org/openshift/release:golang-1.12]
├──  ID: fbb3dfca0f9f Size: 93.18kB
├──  ID: 0b886c8657e8 Size: 6.656kB
├──  ID: 4b7d0e54bc4b Size: 4.608kB
├──  ID: b9fc83ae7f75 Size: 27.92MB
├──  ID: 790d6e04469e Size: 28.63MB
└──  ID: c1041eb51c25 Size:  9.93MB Top Layer of: [127.0.0.1:5000/openshift/cluster-logging-operator-registry:latest]
```
```
$ podman image tree 127.0.0.1:5000/openshift/cluster-logging-operator-registry:lat …
```
> Reduce the footprint of the cluster-logging-operator-registry image

- go.mod
- go.sum
- vendor/github.com/ViaQ/logerr/kverrors/doc.go
- vendor/github.com/ViaQ/logerr/kverrors/kverrors.go
- vendor/github.com/ViaQ/logerr/log/doc.go
- vendor/github.com/ViaQ/logerr/log/log.go
- vendor/github.com/ViaQ/logerr/log/logger.go
- vendor/modules.txt
This PR:
* updated viaq/logerr to  v1.0.3 to resolve:
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2020-10-27T13:41:17.243934783Z goroutine 1559 [running]:
2020-10-27T13:41:17.243934783Z k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15deca0, 0x232cb40)
2020-10-27T13:41:17.243934783Z 	/go/src/github.com/openshift/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
2020-10-27T13:41:17.243934783Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-10-27T13:41:17.243934783Z 	/go/src/github.com/openshift/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
2020-10-27T13:41:17.243934783Z panic(0x15deca0, …
```
> Update ViaQ/logerr to resolve nil pointer

- Dockerfile
- Makefile
- pkg/certificates/certificates.go
- pkg/constants/constants.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/visualization.go
- pkg/utils/utils.go
- scripts/cert_generation.sh
- test/functional/framework.go
- test/helpers/framework.go
This PR updates the certificate generation code to:
* Add info message why certs are being (re)generated
* Adds a mutex to the cert code to ensure changes are made in a single threaded fashion
* Moves stashing of generated certs to the "master-certs" secret
/assign @syedriko @alanconway 
* https://bugzilla.redhat.com/show_bug.cgi?id=1888958
> Bug 1888958: Store secrets in one place and utilize mutex

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR add input source metrics for fluent collector so we may start understand what's happening at the collection piont
* adds `cluster_logging_collector_input_record_total{tag:, hostname:}`
* adds `cluster_logging_collector_input_record_bytes{tag:, hostname:}` this is an approximation
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1888420
cc @blockloop
> Bug 1888420: Add collector source input metrics

- Makefile
- pkg/utils/utils.go
Use the current working directory to locate /cluster-logging-operator/files.
Drop the env var LOGGING_SHARE_DIR.
Allows all tests to run directly with `go test`, with no extra environment settings.
/cc @blockloop
> Remove need for LOGGING_SHARE_DIR in tests.

- Dockerfile.centos.patch
Updated the Dockerfile patch based on CentOS for upstream builds to align better with the downstream - Go 1.15 and CentOS 8.
> Updated the CentOS Dockerfile patch

- Makefile
Made behavior of `make image` surprise-free as to which Dockerfile is used to build the CLO image. Before this change, the first Dockefile patch used to build CLO image would "stick" in Dockerfile.local and subsequent invocations of `[PATCH=...] make image` would keep using the same Dockerfile.local, regardless of the value of PATCH. Here's an illustration:
```
First image build, building with the CentOS base image, correct behavior:
[syedriko@localhost cluster-logging-operator]$ PATCH=Dockerfile.centos.patch make image
...
STEP 16: FROM centos:centos8 AS centos
...
Building with the default PATCH, expecting the OCP 4.7 base image, getting CentOS
[syedriko@localhost cluster-logging-operator]$ make image
...
STEP 16: FROM centos:centos8 AS centos
...
Building with the explicit PATCH for …
```
> Make it predictable which Dockerfile is used for CLO image build

- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
- pkg/utils/comparators/servicemonitor/comparator.go
- pkg/utils/comparators/servicemonitor/comparator_test.go
- pkg/utils/comparators/servicemonitor/suite_test.go
- Reconcile ServiceMonitor to the state desired by the operator
-  Add comparator 
/cc  @jcantrill 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-954
> LOG-954: Reconcile Service Monitor

- manifests/5.0/0100_clusterroles.yaml
- manifests/5.0/0110_clusterrolebindings.yaml
- manifests/5.0/cluster-logging.v5.0.0.clusterserviceversion.yaml
- manifests/5.0/image-references
- manifests/5.0/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/5.0/logging.openshift.io_clusterloggings_crd.yaml
- Logging productization will build logging versions 5.0 onwards.
- To build logging operator bundle images, we need CSV with 5.0 version.
*Note* : This should not interfere with ART builds, as ocp-build-data only configures 4.7 version
/cc @jcantrill @syedriko 
> Add manifests/5.0 folder for cpaas builds

- Dockerfile.e2e
This PR bumps the Dockerfile.e2e to rely upon the ES 4.7 source image
> Bump Dockerfile.e2e to 4.7

- pkg/generators/forwarding/fluentd/generators.go
- test/functional/framework.go
- test/helpers/oc/runner.go
Attempt a fix to functional test flake
- wait for fluentd service to be ready before curl-ing it
- fixed "odd number of arguments" to structured logging in oc/runner
The metrics functional test fails because `curl` to the metrics endpoint fails. So wait for the service endpoint to have IPs before attempting to curl it.
> Attempt a fix to functional test flake

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
Remove from configuration default username and password
/cc 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-965
> LOG-965: remove username and password from fluentd conf

- Dockerfile
For productization purposes we had added a `manifests/5.0` folder in upstream. So the `cluster-logging-operator-registry` is loading both CSVs.
```
time="2020-11-21T12:45:08Z" level=info msg=directory dir=/manifests file=manifests load=bundles
time="2020-11-21T12:45:08Z" level=info msg=directory dir=/manifests file=4.7 load=bundles
time="2020-11-21T12:45:08Z" level=info msg="found csv, loading bundle" dir=/manifests file=cluster-logging.v4.7.0.clusterserviceversion.yaml load=bundles
time="2020-11-21T12:45:08Z" level=info msg="loading bundle file" dir=/manifests/4.7 file=0100_clusterroles.yaml load=bundle name=clusterlogging.v4.7.0
time="2020-11-21T12:45:08Z" level=info msg="loading bundle file" dir=/manifests/4.7 file=0110_clusterrolebindings.yaml load=bundle name=clusterlogging.v4.7.0 …
```
> Prevent adding manifests/5.0 to clo image

- test/functional/framework.go
- test/functional/normalization/flatten_labels_test.go
Not sure why I got these errors, feel free to close it if I missed something and PR not accurate
This PR fix:
- test/functional/framework.go:169:3: singleCaseSwitch: should rewrite witch statement to if statement (gocritic)
- test/functional/normalization/flatten_labels_test.go:17:3: `sampleMetric` is unused (varcheck)
/assign 
/cherry-pick
> singleCaseSwitch: should rewrite witch statement to if statement (gocritic)

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
This PR lowers the default max_retry_wait to resolve cases where it appears fluent is functional but not pushing messages.  The current retry algo is an exponential backoff that will cause fluent to not retry try soon enough
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1894634
/assign @vimalk78 @alanconway 
backport of https://github.com/openshift/cluster-logging-operator/pull/799
> Bug 1894634: lower default max_retry_wait

- Makefile
Adding environment variable GODEBUG to make file with value x509ignoreCN=0 so that `/home/eranra/go/src/github.com/openshift/cluster-logging-operator/pkg/k8shandler/certificates_test.go` will work
> Fix `make check`

- hack/logforwarder.yaml
- pkg/k8shandler/clusterloggingrequest.go
- pkg/k8shandler/clusterloggingrequest_test.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/visualization.go
This PR modifies the reconciliation loop to:
* skip reconciliation of storage, visualization and curation if the managed store is not defined
*Note*: while testing it was observed
* storage et al will fail (as expected) to deploy if the EO is not deployed
* It is possible to see the following error message in the logs if you deploy eo, logging, and then remove eo, logging, and delete the CRD
```
E1123 19:13:13.053559       1 reflector.go:178] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.Elasticsearch: the server could not find the requested resource (get elasticsearches.logging.openshift.io)
```
Deleting the CRD is a manual step which is unlikely to be done unless a user explicitly does so
/assign @alanconway @vimalk78 
* …
> Bug 1891738: Make operator not depend on elasticsearch-operator

- Dockerfile
- Makefile
- pkg/certificates/certificates.go
- pkg/constants/constants.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/visualization.go
- pkg/utils/utils.go
- scripts/cert_generation.sh
- test/helpers/framework.go
(cherry picked from commit 02e1cea8a0930101db016d0e1376b38e1023701e)
Description
This PR updates the certificate generation code to:
Add info message why certs are being (re)generated
Adds a mutex to the cert code to ensure changes are made in a single threaded fashion
Moves stashing of generated certs to the "master-certs" secret
/assign @syedriko @alanconway
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1895607
* https://github.com/openshift/cluster-logging-operator/pull/765
> Bug 1895607: Store secrets in one place and utilize mutex

- Makefile
- must-gather/collection-scripts/gather
- test/e2e/logforwarding/cleanup.sh
- test/e2e/logforwarding/kafka/forward_to_kafka_test.go
- test/functional/framework.go
- test/helpers/framework.go
- test/helpers/kafka.go
- test/helpers/oc/runner.go
- test/helpers/types.go
- test/helpers/types_test.go
- test/runtime/runtime.go
- We have 6 type of logs. (AppContainer, InfraContainer, Journal, LinuxAudit, K8sAudit, Openshift Audit)
- Added Go struct for each type of logs
- Added tests to decode each type of log with example for each log
- Kafka test improvement: all logs in same topic test assertion improved
- Fixed log statements after structured logging changes (depends on ViaQ/logerr library changes)
- Test Cleanup also cleans the fluentd POS files, so that next testcase has higher chances of receiving logs
- captured more resources in must-gather
- modified functional tests RunCommand to use oc helper utility
/cc @eranra @alanconway 
/assign @jcantrill @igor-karpukhin
> Test improvements

- must-gather/collection-scripts/gather_collection_resources
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/client/test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
- test/functional/framework.go
There are 3 types of audit logs:
- linux audit logs generated by operating system
- kubernetes audit logs generated by kube-api server
- openshift audit logs generated by openshift-apiserver
see examples below.
The k8s and openshift audit logs are json structured, and contain a field called `level`
The presence of this field conflicts with the `use_record` feature of the legacy way of sending logs to syslog.
When `use_record` is enabled in legacy syslog, the value of `level` field is used as the SEVERITY fields of syslog. But audit logs have this fields for some other purpose than setting the value of syslog field. so the value of `level` when used as SEVERITY generates an UNRECOVERABLE error in fluentd and we get the logs reported in the BZ.
So as a solution, the `level` field is renamed …
> Bug 1892511: Renamed `level' field in k8s/openshift audit logs

- pkg/k8shandler/collection.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/visualization.go
This PR is a 4.6 backport of https://github.com/openshift/cluster-logging-operator/pull/709 to resolve some chattiness of the CLO
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1892794
> Bug 1892794: Remove status update message

- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
This PR resolves the issue where the master-certs are not re-created when deleted by:
* Writing the secret when it changes or when it was not found initially
/cc @syedriko 
/assign @vimalk78 @igor-karpukhin 
* https://bugzilla.redhat.com/show_bug.cgi?id=1901869
> Bug 1901869: Recreate master-certs if deleted

- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
- test cases updated
This PR adds an additional condition check of the elasticsearch nodecount before setting the kibana replica to 1.
/cc @lukas-vlcek 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901424
> Bug 1901424: Skip setting kibana replicas to 1 with zero es node

- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/k8shandler/logstore.go
This PR bubbles up errors from reconciling the logstore that were lost in a prior commit in order to expose more information to admins
/assign @alanconway @vimalk78 
*https://bugzilla.redhat.com/show_bug.cgi?id=1903784
> Bug 1903784: Bubble up errors from logstore reconciliation

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/functional/cluster_log_forwarder.go
- test/functional/framework.go
- test/functional/outputs/suite_test.go
- test/functional/outputs/unavailable_forward_output_test.go
- test/runtime/pod.go
This PR
*  sets the fluentd forward heartbeat to "none" to avoid dns resolution issues from stopping the pod from starting
* Expands the functional framework to add visitors in order to test this issue
```
2020-11-23 20:26:38 +0000 [error]: unexpected error error_class=SocketError error="getaddrinfo: Name or service not known"
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `getaddrinfo'
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `resolve_dns!'
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:666:in `resolved_host'
2020-11-23 20:26:38 +0000 [error]: …
```
> Bug 1901096: Set forward heartbeat to none

- pkg/certificates/certificates.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
- scripts/cert_generation.sh
This PR
* Corrects the cert extraction logic to extract all certs from the master-cert secret
* Reformats the cert gen script output to be parsable to allow explicit understandying of why certs were regenerated
* Adds a test to expose the issue
/cc @anpingli 
/assign @ewolinetz @vimalk78 
* https://bugzilla.redhat.com/show_bug.cgi?id=1905910
> Bug 1905910: Correctly extract master-certs to workind directory

- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
This PR only deploys an init container for fluentd if the logstore has a node count greater then 0
/cc @igor-karpukhin @vimalk78 
/cherry-pick 
* https://bugzilla.redhat.com/show_bug.cgi?id=1903912
> Bug 1903912: Deploy fluent init container when logstore.nodecount > 0

- bundle.Dockerfile
This PR enables deployment of 4.7 logging on OCP 4.6
/cc @vimalk78 @igor-karpukhin 
https://bugzilla.redhat.com/show_bug.cgi?id=1915454
/cherrypick release-4.6
> Bug 1915454: Enable deployment on OCP v4.6

- pkg/certificates/certificates.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
- scripts/cert_generation.sh
This PR
* Corrects the cert extraction logic to extract all certs from the master-cert secret
* Reformats the cert gen script output to be parsable to allow explicit understandying of why certs were regenerated
* Adds a test to expose the issue
* Writing the secret when it changes or when it was not found initially
/cc @anpingli 
/assign @ewolinetz @vimalk78 
4.6 Backports for https://github.com/openshift/cluster-logging-operator/pull/819 and https://github.com/openshift/cluster-logging-operator/pull/847
https://bugzilla.redhat.com/show_bug.cgi?id=1906641
https://bugzilla.redhat.com/show_bug.cgi?id=1901869
> Bug 1906641: Correctly extract master-certs to working directory

- pkg/controller/clusterlogging/clusterlogging_controller.go
- pkg/k8shandler/logstore.go
(cherry picked from commit 86ecc8970b36696781ae41d3766278e60701d712)
This PR bubbles up errors from reconciling the logstore that were lost in a prior commit in order to expose more information to admins
/cc @igor-karpukhin @vimalk78 
This PR replaces https://github.com/openshift/cluster-logging-operator/pull/833 because of test errors and is a manual cherrypick of 1905819
https://bugzilla.redhat.com/show_bug.cgi?id=1905819
> Bug 1905819: Bubble up errors from logstore reconciliation

- hack/logforwarder.yaml
- pkg/k8shandler/clusterloggingrequest.go
- pkg/k8shandler/clusterloggingrequest_test.go
- pkg/k8shandler/curation.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/logstore.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/visualization.go
This PR modifies the reconciliation loop to:
* skip reconciliation of storage, visualization and curation if the managed store is not defined
*Note*: while testing it was observed
* storage et al will fail (as expected) to deploy if the EO is not deployed
* It is possible to see the following error message in the logs if you deploy eo, logging, and then remove eo, logging, and delete the CRD
```
E1123 19:13:13.053559       1 reflector.go:178] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.Elasticsearch: the server could not find the requested resource (get elasticsearches.logging.openshift.io)
```
Deleting the CRD is a manual step which is unlikely to be done unless a user explicitly does so
/assign @alanconway @vimalk78 
* …
> Bug 1901256: Make operator not depend on elasticsearch-operator

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
This PR lowers the default max_retry_wait to resolve cases where it appears fluent is functional but not pushing messages. The current retry algo is an exponential backoff that will cause fluent to not retry try soon enough
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1894639
/assign @vimalk78 @alanconway
> Bug 1894639: lower default max_retry_wait

- manifests/4.7/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/5.0/logging.openshift.io_clusterlogforwarders_crd.yaml
- pkg/apis/logging/v1/output_types.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/helpers/framework.go
- A fix for bug [1891886](https://bugzilla.redhat.com/show_bug.cgi?id=1891886).
- Added a field in LF CRD `AddLogSource`, which when enabled, adds namespace_name, pod_name, container_name to the `message` field of the record.
- This can be further used with `PayloadKey` set to `"message"` to achieve the same behavior as older syslog plugin.
- The solution is to add a `record_modifier` section in the fluent config, which copies the `namespace_name` , `pod_name` , `container_name` from the `kubernetes` section, and copies it into `message`
- also fixed two lint issues in funtional tests
```
<15>1 2020-11-15T17:06:14+00:00 fluentd-9hkb4 mytag - - -  {"msgcontent"=>"My life is my message", "timestamp"=>"2020-11-15 17:06:09", "tag_key"=>"rec_tag", "index"=>56}
```
```
<15>1 …
```
> Bug 1891886: Support Adding log source info to log message

- Makefile
- hack/test-e2e-olm.sh
- hack/testing-olm/test-367-logforwarding.sh
This PR modifies Makefile and e2e scripts to allow selectively running tests for cases like the EO that only needs to be gated on the managed ES test
https://issues.redhat.com/browse/LOG-1034
cc @ewolinetz
> LOG-1034: Allow selectively running e2e tests for EO

- bundle.Dockerfile
This reverts commit 46dd7a6b0f888b79cd39f37c415272897f20c2d2.
cc @vimalk78 
ref https://bugzilla.redhat.com/show_bug.cgi?id=1915454
> Revert "Bug 1915454: Enable deployment on OCP v4.6"

- Makefile
- hack/test-e2e-olm.sh
- hack/testing-olm/test-367-logforwarding.sh
Backport of #871 to allow selectively running e2e tests
https://issues.redhat.com/browse/LOG-1034
> Log1034 for46

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
(cherry picked from commit 0aa032a3a9f193fb754bca2ca7526b33ba33dcb1)
This PR
*  sets the fluentd forward heartbeat to "none" to avoid dns resolution issues from stopping the pod from starting
* Expands the functional framework to add visitors in order to test this issue
```
2020-11-23 20:26:38 +0000 [error]: unexpected error error_class=SocketError error="getaddrinfo: Name or service not known"
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `getaddrinfo'
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `resolve_dns!'
2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:666:in `resolved_host' …
```
> Bug 1906479: Set forward heartbeat to none

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/templates.go
Remove from fluentd configuration the default username and password
/cc @vparfonov 
- Depending on PR(s): https://github.com/openshift/cluster-logging-operator/pull/802
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1927537
- JIRA: https://issues.redhat.com/browse/LOG-965
> [release-4.5] Bug 1927537: LOG-965: remove username and password from fluentd conf

- hack/eventrouter-template.yaml
- hack/testing-olm/test-040-eventrouter.sh
This PR
* Extend the wait time for the eventrouter to deploy.
* Update how CI provides IMAGE_FORMAT
* Update non CI registry to pull variables
Various CI failures demonstrate via logs the pod is not crashing but test times out waiting for the pod deploy.
Crashes should be resolved by https://github.com/openshift/origin-aggregated-logging/pull/2059
cc @syedriko
> Extend timeout waiting for eventrouter to deploy

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/functional/logforwarding/message_format_test.go
Fix regex for correct formatting if log message contains 'stderr|stdout'
Add test for checking 
/cc @jcantrill
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1889595
> Bug 1889595: Fix regex for correct formatting if log message contains 'stderr|stdout'

- hack/cr-unmanaged.yaml
- hack/testing-olm/assertions
- hack/testing-olm/test-010-deploy-via-olm-minimal.sh
- pkg/k8shandler/clusterloggingrequest.go
- pkg/k8shandler/reconciler.go
Rework checking for 'managementState' to make deployment working if it set to "unmanagement" or not set at all
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-784
> LOG-784: Rework checking for 'managementState' to make deployment working if it set

- pkg/k8shandler/collection.go
CRC does not start monitoring by default, so this was causing fluentd instance to not start on CRC.
Not creating prometheus rules should not block deployment, but only mark the operator as "degraded"
This PR:
- Removes the error caused by Fluentd Prometheus Rule.
- The fluentd instance will be up and running successfully.
/cc @vimalk78  
/assign
> fluentd instance not getting created in CRC error fix

- pkg/k8shandler/reconciler.go
Replace fmt.Printf() with log.Error() or log.Info() 
/cherry-pick
> Replace fmt.Print with log.Error

- hack/eventrouter-template.yaml
- hack/testing-olm/test-040-eventrouter.sh
Update how CI provides IMAGE_FORMAT
Update non CI registry to pull variables
(cherry picked from commit 51215422793eb6f02cd183fcbd0d1a4cf6830b54)
5.0 backport of https://github.com/openshift/cluster-logging-operator/pull/888/ to fix eventrouter timeout
/cc @vimalk78 @alanconway @igor-karpukhin 
/assign
> Extend the wait time for the eventrouter to deploy.

- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
fix using the CLF spec'd secret instead of assuming its the same as the output name
/cc @igor-karpukhin @vimalk78 
https://issues.redhat.com/browse/LOG-1143
> LOG-1143: fix using spec'd secret in config instead of output name

- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
This PR reverts the original PR https://github.com/openshift/cluster-logging-operator/pull/895 because the original issue did not exist as it was mis-identifed.
https://issues.redhat.com/browse/LOG-1143
cc @anpingli @alanconway @vimalk78
> Revert LOG-1143

- OWNERS
Downstream images do not get built from upstream Dockerfiles. So we need a mechanism to trace changes to upstream Dockerfiles to decide if a corresponding change is needed in Downstream Dockerfile.
Any PR which changes a file matching the go regex `Dockerfile` will be added with label `downstream`.
If a change is required in downstream Dockerfile, the reviewer should ensure same change gets done in Downstream, either by putting a hold on the upstream PR, or by any other means.
/cherry-pick release-5.0
> Add 'downstream' PR label for Dockerfile changes

- olm_deploy/scripts/catalog-deploy.sh
From 5.0 onwards, the logging CI images changed pull spec to
registry.ci.openshift.org/logging/5.0:cluster-logging-operator etc
The script is changed to reflect this.
/cc @pmoogi-redhat 
/cherry-pick
> Fix catalog-deploy script

- olm_deploy/scripts/catalog-deploy.sh
- olm_deploy/scripts/registry-init.sh
This PR
* removes IMAGE_FORMAT in deference to images defined via env vars
* IMAGE_FORMAT has been deprecated for over a year
* CI was modified to tag in image refs via "pipelines" that are consumable by env vars
* update logging imagestream
* remove unused images
/cc @vimalk78 @igor-karpukhin 
/cherrypick release-5.0
/cherrypick tech-preview
> use image env vars instead of IMAGE_FORMAT

- internal/pkg/generator/forwarder/generator.go
- pkg/k8shandler/collection_test.go
- test/functional/framework.go
- test/functional/message_templates.go
- test/functional/normalization/eventrouter_test.go
- test/functional/output_forward.go
- test/functional/outputs/forward_to_logstash_test.go
Code fixes for the "check" make target to run cleanly.
Fixes "go fmt" issues and 
```
test/functional/normalization/eventrouter_test.go:63:40: Using the variable on range scope `verb` in function literal (scopelint)
newEventData := NewEventDataBuilder(verb, podRef)
```
> Cleanup of make check

- pkg/constants/constants.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/clusterloggingrequest.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/forwarding.go
(cherry picked from commit 1597789cd86de024c3cb50485a6d501c0e374ff3)
This PR fixes:
* forwarding logs to the managed store and legacy forwarding
* maintains writing to the legacy store when no managed store is defined
/cc @alanconway @igor-karpukhin @vimalk78 
/assign 
* 4.6 backport of https://github.com/openshift/cluster-logging-operator/pull/879
* https://bugzilla.redhat.com/show_bug.cgi?id=1928949
> Bug 1928949: Write to default logstore when legacy forwarding enabled

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
Bug 1892511: Renamed level field in k8s/openshift audit logs
/cc 
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1892511
> Bug 1892511: Renamed level field in k8s/openshift audit logs

- art.repo
The `art.repo` file contains pulp repos URL used in the Dockerfile STEP which runs `yum install`
EXD changed pulp host. So need to update pulp host in `art.repo`
/cc 
/cherry-pick release-4.6
/cherry-pick tech-preview
> Change pulp host in art.repo

- internal/cmd/forwarder-generator/main.go
- pkg/constants/constants.go
- pkg/generators/factory.go
- pkg/generators/forwarding/factory.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
- pkg/url/url.go
- test/e2e/logforwarding/fluent/forward_to_fluent_test.go
- test/files/secure-forward.conf
- test/helpers/elasticsearch.go
- test/helpers/fluentd.go
- test/helpers/framework.go
- test/helpers/kafka.go
- test/helpers/syslog.go
The fix adds secrets during validation, changes the generate signature
and so touches a lot of files.
/cc @alanconway @vimalk78 
* 4.6 backport of https://github.com/openshift/cluster-logging-operator/pull/823
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1929420
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1929419
> Bug 1929420: ClusterLogForwarder with Output.Secret causes fluentd crash loop

- hack/testing-olm/test-367-logforwarding.sh
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/helpers/framework.go
This fixes the following flake:
```
{"_ts":"2021-03-18T19:52:14.094739921Z","_file:line":"forward_to_syslog_test.go:304","_level":"3","_component":"test","_message":"Waiting for ","component":"Collector"}
{"_ts":"2021-03-18T19:52:14.529118966Z","_level":"0","_component":"test","_message":"command output","arguments":"-n openshift-logging get daemonset/fluentd -o jsonpath={.status.numberReady}","output":"6"}
{"_ts":"2021-03-18T19:52:15.865822899Z","_level":"0","_component":"test","_message":"command output","arguments":"-n openshift-logging get daemonset/fluentd -o jsonpath={.status.numberReady}","output":"6"}
{"_ts":"2021-03-18T19:52:16.866539769Z","_level":"0","_component":"test","_message":"command output","arguments":"-n openshift-logging get daemonset/fluentd -o …
```
> Fix for forward_to_syslog test flake

- Makefile
- hack/common
- hack/testing-olm/test-040-eventrouter.sh
- Fixed the eventrouter e2e test failure due to bad image name when running in dev env
- Removed noise from the output of the eventrouter e2e test. The events for debugging can be found in the artifacts dir.
- Simplified Logging version detection
> Cleanup of the eventrouter e2e test

- pkg/apis/logging/v1/cluster_log_forwarder.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/generators_test.go
- pkg/generators/forwarding/fluentd/helpers.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR
* fixes routing of application messages by namespace so they end up at the desired outputs
/cc @alanconway @vimalk78 
/cherrypick release-5.0
https://issues.redhat.com/browse/LOG-1223
> LOG-1123: fix routing of app logs per namespace

- docs/HACKING.md
- hack/gen-olm-artifacts.py
This PR:
* re-introduces a script from 4.2 to generate a list of kubernetes resources from the CSV to provide an alternate deployment method to hack cluster logging operator
/cc @sichvoge  @alanconway 
* https://issues.redhat.com/browse/LOG-679
> LOG-1238: Add hack script to create deployment list

- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
Addresses issue seen in https://bugzilla.redhat.com/show_bug.cgi?id=1942609 where the operator is changing the replica count for the Kibana CR which is unexpected for users.
Will link the bz to the 4.6.z cherry pick of this.
> Removing logic to control replicas for kibana CR

- Makefile
- hack/testing-olm/test-367-logforwarding.sh
Cleaned up pattern matching for the logforwarding e2e tests.
The CLF_TEST_INCLUDES env variable takes a PCRE that directories in test/e2e/logforwarding are matched against. Examples:
- CLF_TEST_INCLUDES=syslog matches syslog and sysloglegacy
- CLF_TEST_INCLUDES=syslog|fluent matches syslog, sysloglegacy, fluent and fluentlegacy
- CLF_TEST_INCLUDES=^syslog$ matches just syslog
> Cleaned up pattern matching for selective running of logforwarding e2e tests

- files/dashboards/openshift-logging-dashboard.json
This PR address creating total bytes logged by go-watcher and total bytes collected by fluentd. 
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1165
> Adding container chart LOG-1165-Dashboard

- hack/testing-olm/test-367-logforwarding.sh
- test/client/client.go
- test/client/pod.go
- test/e2e/logforwarding/fluent/fixture_test.go
- test/e2e/logforwarding/fluent/fluent_secure_test.go
- test/e2e/logforwarding/fluent/fluent_test.go
Fixes for the sporadic failures of the e2e logforwarding fluent test:
- serialized manipulations with the fluentd DS
- made fluentd ports for different tests unique to exclude cross-contamination
- added cleanup of fluentd on-disk buffers between tests
These are not final fixes for all the ills with this test, but they make it much more stable without altering its logic.
/cc @vimalk78 
/assign @ewolinetz
> E2E logforwarding fluent flake fixes

- pkg/apis/logging/v1/cluster_log_forwarder.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/generators_test.go
- pkg/generators/forwarding/fluentd/helpers.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR
* fixes routing of application messages by namespace so they end up at the desired outputs
/cc @alanconway @vimalk78 
https://issues.redhat.com/browse/LOG-1224
backport of https://github.com/openshift/cluster-logging-operator/pull/955
> LOG-1124: fix routing of app logs per namespace

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR adds keepalive=true for all forward configurations.
Currently keepalive defaults to false which means a new socket is created for every chunk sent.  This change ensures connections are reused.
fixes #829
> Add forward keepalive

- files/dashboards/openshift-logging-dashboard.json
In #954  PR we have added OCP dashboard chart which shows top 10 log producing  containers. In the chart label `namespace` is also added to identify container. 
Also based on https://github.com/openshift/cluster-logging-operator/pull/979#issuecomment-820427833  metric name also changed from `fluentd_input_status_total_bytes_logged` to `log_logged_bytes_total`
/cherry-pick 
- Depending on PR(s): 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1271
> Renaming Metric names and adding namespace label

- files/dashboards/openshift-logging-dashboard.json
This PR  creates a OCP dashboard chart which shows top 10 containers showing logs collected by fluentd.
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1269
> Adding logs collected chart LOG-1269

- pkg/k8shandler/indexmanagement/index_management.go
- pkg/k8shandler/indexmanagement/indexmanagement_test.go
This PR fixes CLO behaviour when retention time (`RetentionPolicy.MaxAge`) is set to `0(m | h | d | w | M | Y)`
/cc @jcantrill @vimalk78 @vparfonov 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1936998
- JIRA: https://issues.redhat.com/browse/LOG-1201
> LOG-1201: Fixed zero minutes/days/etc. retention time

- bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml
- manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
- olm_deploy/operatorregistry/registry-deployment.yaml
- pkg/k8shandler/daemonset.go
- pkg/k8shandler/deployment.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> Add management workload annotations

- pkg/constants/constants.go
- pkg/k8shandler/certificates.go
- pkg/k8shandler/certificates_test.go
- pkg/k8shandler/forwarding_test.go
- scripts/cert_generation.sh
This PR provides a small fix for OCP environments with custom internal DNS, where using `cluster.local` for accessing Elasticsearch from Fluentd is not valid.
**Note:** Needs porting to 5.0.x and 5.1.x
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
> Bug 1945168: Remove hardcoded cluster local domain

- files/fluentd/fluentd_prometheus_alerts.yaml
1. Change `FluentdQueueLengthIncreasing` alert expression. Fluentd buffering logs when it can't push to an output. This can be happened at startup because logstore not ready yet or in case log spamming. To prevent firing alerts if this is not necessary and system works well need to tune expression for buffer usage. Going to use [deriv() function](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv) for buffer increase calculation
2. Remove `FluentdQueueLengthBurst` at all, because this alert was related to our internal store which do not seem to apply for now.
/cc @alanconway @blockloop 
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1891623
> Bug1891623: Change expression for Fluentd file buffer usage

- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/k8shandler/visualization.go
- pkg/k8shandler/visualization_test.go
Manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/965
/cc @jcantrill @igor-karpukhin 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1942609
> Bug 1942609: removing logic to control replicas for kibana

- Makefile
- hack/generate-crd.sh
All versioned artifacts now go under manifests/$LOGGING_VERSION.  Redundant OCP_VERSION was removed.
> Replace OCP_VERSION with LOGGING_VERSION

- bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml
- manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
Curator is removed in 5.1
Removed remaining references of curator5 from CSV
> Removed curator5 references from 5.1 CSV

- pkg/apis/logging/v1/conditions.go
> LOG-1012 Clarify meaning of Ready and Degraded conditions.

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR changes the default input behavior to collect  records from all namespaces and pods.
The current log filtering by pod labels and namespaces only collects non matching records("anything left over").
For example, 
```
metadata:
name: instance
spec:
inputs:
- name: application-logs1
application:
namespaces:
- my-project
outputs:
- name: syslog1
...
pipelines:
- name: syslog-app-logs1
inputRefs:
- application-logs1
outputRefs:
- syslog1
- name: app-default
inputRefs:
- application
outputRefs:
- default
```
The "app-default" pipeline won't collect logs from "my-project" namespace in the customized input.
The concept of "application" was discussed in …
> Fix built-in application behavior to collect all of logs

- files/dashboards/openshift-logging-dashboard.json
There was a slight change to indices statistics metrics. We also need
to get rid of label filter (it does not make sense now).
Additional change was done to Prometheus metric calculation itself.
We changed "rate()/irate()" to "rate()/rate()".
Context – useful resource about rate and irate metrics: <https://www.robustperception.io/irate-graphs-are-better-graphs>
- JIRA: https://issues.redhat.com/browse/LOG-1354
> LOG-1354: No datapoints found on Elastic Query/Fetch Latency dashboard

- manifests/5.1/logging.openshift.io_clusterlogforwarders_crd.yaml
- pkg/apis/logging/v1/output_types.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- test/functional/outputs/forward_to_elasticsearch_index_test.go
In line with updated proposal: https://github.com/openshift/enhancements/pull/780
/cc @vimalk78
/assign @jcantril
> LOG-1370 Change name of elasticsearch.indexKey to structuredIndexKey

- pkg/k8shandler/priorityclass.go
`APIRemovedInNextReleaseInUse` alerts for priorityclasses because priorityclasses.v1beta1.scheduling.k8s.io is completely removed in 1.22. Replaced by priorityclasses.v1.scheduling.k8s.io.
/cc jcantrill
/assign ewolinetz
* https://issues.redhat.com/browse/LOG-1385
> LOG-1385: priorityclasses.v1beta1.scheduling.k8s.io is removed in 1.22 and replaced by priorityclasses.v1.scheduling.k8s.io

- Makefile
- bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml
- docs/deploy-event-router.md
- hack/eventrouter-template.yaml
- hack/testing-olm/utils
- internal/cmd/functional-benchmarker/main.go
- manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
- manifests/5.2/image-references
- must-gather/README.md
- olm_deploy/scripts/registry-init.sh
- test/helpers/fluentd.go
- test/helpers/fluentd/receiver.go
Logging images are being mirrored to logging's own namespace in Quay, `quay.io/openshift-logging`. 
This PR attempts to update the CI built logging image references in the repo.
/cc 
> Update references to CI build images

- bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml
- manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
PR #973 added annotations
required for supporting the workload partitioning feature for ocp 4.8.
However, OLM has a bug in processing the annotations (BZ 1950047).
This PR provides a workaround necessary to release the workload
partitioning in OCP 4.8.
/cc @lack @imiller0 
<!-- Provide links to depending PRs, Bugzilla or JIRA issue addressed or enhancement proposal that gets implemented by this 
- Depending on PR(s): 973
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1950047
- https://issues.redhat.com/browse/LOG-1440
> LOG-1440: Add OLM bug workaround for workload partitioning

- scripts/cert_generation.sh
Corrected how Kibana session secret is generated. Prior to the fix, `hexdump` parameters allowed for deviation from the "1 byte -> 2 hex nibbles" scheme for some byte sequences.
Specifically, without `-v`, `hexdump` abbreviated repeating bytes with * and without `1/1`, it defaulted to processing bytes in groups of 2 and dropping leading zeros in the process.
`while [ $(head -c 16 < /dev/urandom | tee bin | hexdump -e '"%02X"' | tee hex | wc -c) -eq 32 ]; do echo; done`
Sequence `70 70 70` becomes `70*\n`, length of `hex` is 30:
```
$ od -v -A n -t x1  bin
75 70 93 8e 4b 67 aa 2a 70 70 70 86 52 29 42 31
$ cat hex 
7570938E4B67AA2A70*
8652294231
$ 
```
length of `hex` is 31:
```
$ od -v -A n -t x1  bin
db 03 0e be cd ea 53 ba 33 b4 9a 75 2d be 5a 05
$ cat hex
BE 0E 03 DB
BA 53 EA CD
75 9A …
```
> LOG-1446: kibana-proxy CrashLoopBackoff with error Invalid configuration cookie_secret must be 16, 24, or 32 bytes to create an AES cipher

- bundle/manifests/cluster-logging.v5.0.0.clusterserviceversion.yaml
- manifests/5.0/cluster-logging.v5.0.0.clusterserviceversion.yaml
- olm_deploy/operatorregistry/registry-deployment.yaml
- pkg/k8shandler/daemonset.go
- pkg/k8shandler/deployment.go
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
In addition:
This PR provides a workaround necessary to release the workload
partitioning in OCP 4.8 ([LOG-1442](https://issues.redhat.com/browse/LOG-1442))
/cc @lack @imiller0 
https://github.com/openshift/cluster-logging-operator/pull/1042
https://github.com/openshift/cluster-logging-operator/pull/973
> [Release-4.8] LOG-1442: Add mgmt workload annotations, OLM bug workaround

- .gitignore
- Makefile
My last Makefile change broke things for AWS users or anywhere that the registry is not exposed by default (it is on CRC, my bad)
Makefile now exposes the registry if needed. Tested on AWS and CRC.
> Fix broken Makefile - expose cluster registry route explicitly.

- Makefile
- bundle/manifests/cluster-logging.v5.1.0.clusterserviceversion.yaml
- docs/deploy-event-router.md
- hack/eventrouter-template.yaml
- hack/testing-olm/utils
- internal/cmd/functional-benchmarker/main.go
- manifests/5.1/cluster-logging.v5.1.0.clusterserviceversion.yaml
- manifests/5.1/image-references
- must-gather/README.md
- olm_deploy/scripts/registry-init.sh
- test/helpers/fluentd.go
- test/helpers/fluentd/receiver.go
Logging images are being mirrored to logging's own namespace in Quay, quay.io/openshift-logging.
This PR attempts to update the CI built logging image references in the 5.1 branch.
/cc 
This is a manual cherry-pick of #1040 
/cherry-pick 
- Bugzilla:
- JIRA:
> release-5.1 Update references to CI build images

- manifests/4.6/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/4.6/logging.openshift.io_clusterloggings_crd.yaml
- pkg/apis/logging/v1/output_types.go
- pkg/apis/logging/v1/zz_generated.deepcopy.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/helpers/framework.go
This is a manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/790 
- A fix for bug 1891886.
- Added a field in LF CRD `AddLogSource`, which when enabled
adds namespace_name, pod_name, container_name to the `message` field of the record.
- This can be further used with `PayloadKey` set to `"message"` to achieve the same
behavior as older syslog plugin.
- fixed hostname to be cluster's node name, rather than fluentd's podname
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> Bug 1971003: [release-4.6] Support Adding log source info to log message

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR fixes the [LOG-974](https://issues.redhat.com/browse/LOG-974) feature of a username and password auth for Kafka and ES:
* Elasticsearch supports HTTP with username/password OR HTTPS with tls.key and tls.cert
* Kafka supports username/password with sasl_plain/sasl_over_ssl (put sasl_over_ssl into the secret to enable ssl) OR with tls.key and tls.cert
https://issues.redhat.com/browse/LOG-1372
https://issues.redhat.com/browse/LOG-1373
> LOG-974: Fixed username and password feature for ES and Kafka

- test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go
This PR fixes a flake in test. Test requires a log-generator pod with specific labels. The command to add the labels sometimes fails by saying that the labels already exist.
PR fixes that by adding `--owerwrite=true` flag to `oc` command.
/cc 
/assign 
/cherry-pick release-5.1
> LOG 1400: Fix flaky test case

- Makefile
Fix for pulling non-existent registry.ci.openshift.org/ocp/5.1:oauth-proxy. OCP_VERSION is used for OpenShift version in ES olm_deploy scripts.
/assign @ewolinetz
> Removed references to OCP_VERSION env var

- Makefile
- hack/registry.sh
Script enables public registry route the first time it is needed.
Automatically called when expanding Makefile REGISTRY_ variables.
This is safer than the previous solution using dependencies because a) you can forget them and b) it depends on gmake's ordering rules for evaluating dependencies and  variables, which are very hard to follow. By moving the activate-if-needed logic to a script it is much easier to follow how it works.
/cc @jcantrill
> Safer script for OC registry info and login from Makefile.

- go.sum
- pkg/constants/constants.go
- pkg/k8shandler/collection.go
- pkg/k8shandler/fluentd.go
Modify CLO to accommodate the log file exporter - 
JIRA Reference  -- OpenShift Logging/LOG-1188, Implement Go implementation log file exporter/LOG-1359
Task Name: Modify CLO to accommodate the log file exporter
/cc @jcantrill @alanconway @vimalk78
- Depending on PR(s): new fluentd image that enables go based log-file-metric-exporter running as a background service
- Bugzilla: NA
- Github issue: NA
- JIRA: https://issues.redhat.com/browse/LOG-1359
- Enhancement proposal:  Currently Collector is found to have issue with tracking each and every file rotation. It misses out logs when log files are rotated at a faster pace (typically > 2 rotations per second as observed in performance simulations). There is a need for publishing new metrics on how much actually total bytes …
> Go implementation log file exporter jira ticket log 1188 - log 1357 with new service within fluentd container

- files/dashboards/openshift-logging-dashboard.json
Description
This PR adds tables that displays the top 10 containers of logs produced and logs collected.
Links
Depending on PR(s): #979, openshift/origin-aggregated-logging#2070
Bugzilla:
Github issue:
JIRA: [Log-1270](https://issues.redhat.com/browse/Log-1270)
Previous PR: https://github.com/openshift/cluster-logging-operator/pull/994/  (There was commit issues so previous PR would be closed. One should refer it for historical feature discussion)
> Adding tables for top 10 container producing/collecting logs [Log-1270]

- hack/registry.sh
This PR avoids running  the `hack//registry.sh` script in CI environments.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> Fix hack/registry.sh for CI

- manifests/5.2/logging.openshift.io_clusterloggings_crd.yaml
- pkg/apis/logging/v1/clusterlogging_types.go
- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/output_conf_kafka_test.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR:
* Modifies buffer retry to drop log messages after 10 minutes
* Adds API to buffer tuning section to allow configuration of retry
* Ref: https://issues.redhat.com/browse/LOG-1500
> LOG-1500: Discard messages after 60m instead of retry forever

- Dockerfile
- Dockerfile.in
- origin-meta.yaml
Since downstream builds do not use ART images anymore, need to update base images in Dockerfile.in to match the images used in CPaaS.
Also added an extra LABEL step in Dockerfile to update the name LABEL as per downstream requirements
- updated Dockerfile.in
- updated origin-meta.yaml
- updated generated Dockerfile
/cc 
/cherry-pick release-5.1
> Updated Dockerfile.in to not use ART images

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR:
* Explicitly forces messages to be converted to utf-8
* Replaces any invalid characters with a char that can be consumed by Elasticsearch
Tested by:
* using hexedit to change a message line to have 0x92 in it
* setup fluent.conf to write to elasticsearch
* include filter in conf to explicitly convert before writing to elasticsearch
* demonstrated ES rejection without conversion and acceptance with conversion
* https://issues.redhat.com/browse/LOG-1499
> LOG-1499: Force encoding to utf-8 and replace invalid chars

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/generators_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR changes the built-in `application` behavior to collect all the applications logs.
As for release-5.1, the namespace filtering feature is changed based on label router plugin.
So we can not cherry-pick https://github.com/openshift/cluster-logging-operator/pull/999.
This PR suggests the following change without depending on https://github.com/openshift/cluster-logging-operator/pull/999:
```
spec:
inputs:
- name: myInput
application:
namespaces: 
- project1-namespace
outputs:
- name: apps-es-1
...
- name: apps-es-2
...
pipelines:
- name: my-default-pipeline
inputRefs:
- application
outputRefs:
- app-es-1
- name: apps-pipeline
inputRefs:
- myInput
outputRefs:
- app-es-2
```
```
<label @_APPLICATION>
<match kubernetes.**_project1-namespace_**>
@type copy
<store>
@type relabel
@label …
```
> LOG-1572: Fix built-in application behavior to collect all of logs

- bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml
- manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
- olm_deploy/operatorregistry/registry-deployment.yaml
- olm_deploy/scripts/catalog-deploy.sh
- pkg/constants/constants.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
- pkg/utils/utils.go
Summary
Implement an independent process to monitor CRIO container log file rotations that can be used to publish total_bytes_logged metrics in prometheus format. The motivation for moving away from a Ruby implementation is Ruby is not efficient in tracking file rotations. Also collectors can change over time so making metric computation outside of fluentd for logging total_bytes_logged is more preferred.
Exposes metric endpoint that is consumable by Prometheus at port :2112
Exposes metric of total_bytes_logged
/cc @alanconway @jcantrill 
- Related PR(s): origin-aggregated-logging:Metric-for-inbound-log-data-loss-at-the-collector-JIRA-ticket-[LOG-1032](https://issues.redhat.com/browse/LOG-1032)
Got in_tail and prometheus plugin changes which enable …
> Go implementation log file exporter jira ticket log 1188

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR:
* Reverts UTF-8 conversion introduced by [LOG-1499](https://issues.redhat.com/browse/LOG-1499)
* Drops any utf-8 conversion under the assumptions:
* The existing filter uses #force_encoding that fundamentally has no impact
* The point at which error occurs there is no place where a fix can be made by the collector
* The record will be dropped for ES based on the latest changes to the fluent es plugin
* Trying to force the encoding assuming ascii-8bit results in [LOG-1499](https://issues.redhat.com/browse/LOG-1499)
* Resolves https://issues.redhat.com/browse/LOG-1576 for 5.2
* Revert utf8 change of https://issues.redhat.com/browse/LOG-1499
* https://github.com/openshift/cluster-logging-operator/pull/1090
* 5.2 PR for https://github.com/openshift/cluster-logging-operator/pull/1100
> Log499revert

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_es_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR:
* Reverts UTF-8 conversion introduced by [LOG-1569](https://issues.redhat.com/browse/LOG-1569)
* Drops any utf-8 conversion under the assumptions:
* The existing filter uses #force_encoding that fundamentally has no impact
* The point at which error occurs there is no place where a fix can be made by the collector
* The record will be dropped for ES based on the latest changes to the fluent es plugin
* Trying to force the encoding assuming ascii-8bit results in [LOG-1569](https://issues.redhat.com/browse/LOG-1569)
* https://issues.redhat.com/browse/LOG-1576
* Revert utf8 change of https://issues.redhat.com/browse/LOG-1569
> LOG-1576: Revert utf-8 encoding and revert LOG-1569

- pkg/generators/forwarding/fluentd/output_conf_forward_test.go
- pkg/generators/forwarding/fluentd/templates.go
If secret contain `passphrase` key, the value of it will be added as `tls_client_private_key_passphrase` to the `forward` section of `fluent.conf` file.
It will be work only in case well configured `tls.key` and `tls.crt`. See more: https://docs.fluentd.org/output/forward#tls_client_private_key_passphrase
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1525
> LOG-1525: Allow use private key protected by the passphrase

- olm_deploy/scripts/registry-init.sh
This PR:
* fixes deployment script to use the image passed by CI for log-file-metric-exporter
/cc @pmoogi-redhat 
/assign @vimalk78 @alanconway
> fix CI deployment of log-file-metric-exporter

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/templates.go
fixing fluent.conf generation for new fluent plugin working. This plugin publishes log_collected_bytes_total metric.
/cc @vimalk78 
- JIRA:https://issues.redhat.com/browse/LOG-1623
> fix for LOG-1623 -  Metric  log_collected_bytes_total is not exposed

- bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/5.2/logging.openshift.io_clusterlogforwarders_crd.yaml
- pkg/apis/logging/v1/output_types.go
- pkg/generators/forwarding/fluentd/fluent_conf.go
- pkg/generators/forwarding/fluentd/output_conf_syslog_test.go
- pkg/generators/forwarding/fluentd/syslog_conf.go
- pkg/generators/forwarding/fluentd/templates.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
The current syslog forwarding can not report who outputted logs in journal log when configuring addLogSource field.
To identify the daemon name, the "systemd.u.SYSLOG_IDENTIFIER" in journal log record is what information we want. 
So fluentd can pick their daemon names from journal log records.
This PR enhances the addLogSource field in Log Forwarding API by splitting  infrastructure stream into journal log and pod log and injecting daemon names into the journal log stream.
So this change is limited to the addLogSource field related code.
This PR picks the originating process name and id(known as the "pid") from the record and injects them into the header field.
There are three type messages in the journal log and the process information are injected like the following:
1. System messages …
>  LOG-1286: Pick daemon names when configuring addLogSource field

- bundle/manifests/cluster-logging.v5.2.0.clusterserviceversion.yaml
- manifests/5.2/cluster-logging.v5.2.0.clusterserviceversion.yaml
Added get/list/watch perms for config.openshift.io/infrastructures to the cluster-logging-operator SA, the Cloudwatch forwarding code needs it here https://github.com/openshift/cluster-logging-operator/blob/e598ed31aa9672de8e3db0206b84d338c6dc2970/pkg/k8shandler/forwarding.go#L100
- JIRA: https://issues.redhat.com/browse/LOG-1173
> Added read perms for config.openshift.io/infrastructures, needed for cloudwatch

- pkg/components/fluentd/run_script.go
- pkg/generators/forwarding/fluentd/output_fluentd_buffer.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/fluentd.go
- pkg/k8shandler/fluentd_test.go
This PR changes:
- Encapsulate ChunkLimitSize and TotalLimitSize to remove if/else statements from template for clean-up purpose
- Echo correct chunkLimitSize which is set in ClusterLogging CR
- Add a 'TOTAL_LIMIT_SIZE' environment variable on fluentd pod
- Use the specified 'TOTAL_LIMIT_SIZE' to calculate 'queued_chunks_limit_size' when specifying 'totalLimitSize' in ClusterLogging CR
/cc @alanconway @jcantrill 
- JIRA: https://issues.redhat.com/browse/LOG-1411
> LOG-1411: Calculate recommended queued_chunks_limit_size with fluentd tuning parameters

- pkg/generators/forwarding/fluentd/output_cloudwatch_test.go
- pkg/generators/forwarding/fluentd/templates.go
- pkg/k8shandler/forwarding.go
- pkg/k8shandler/forwarding_test.go
- For Cloudwatch forwarding output, added enforcement of output type spec
- Added .strip to reading of AWS access keys to prevent HTTP headers with CR/LF
- JIRA: https://issues.redhat.com/browse/LOG-1102
> LOG-1102: Finalize Log forwarding to Cloudwatch for GA

- hack/test-e2e-olm.sh
This PR addresses preparation issues to resolve openshift/release#20604. In detail it adds a conditional to install EO from a sibling repository. As per EO's upstream CI configuration moving to CI-managed operator installation via bundles, this PR adds a configuration option to make EO's CLO-gating job to use the CI-managed operator installation via bundles, too.
> Add conditional for EO setup in e2e tests

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR delays in_tail file refresh watcher at startup to allow the metrics endpoint to bind and complete initialization.
cc @vimalk78 @syedriko 
* https://issues.redhat.com/browse/LOG-1681
* https://github.com/fluent/fluent-plugin-prometheus/issues/92
* 5.2 port of https://github.com/openshift/cluster-logging-operator/pull/1133
> LOG-1681: Delay refresh to allow startup to bind metrics listener

- hack/run-linter
This PR adds lint check to ensure consistency between bundle/manifest and manifest
/cc @vimalk78 
https://issues.redhat.com/browse/LOG-1684
> LOG-1684: Update lint to check manifest dir vs bundle/manifest

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR delays in_tail file refresh watcher at startup to allow the metrics endpoint to bind and complete initialization.
cc @vimalk78 @syedriko 
* https://github.com/openshift/cluster-logging-operator/pull/1134
* https://github.com/fluent/fluent-plugin-prometheus/issues/92
* 5.1 port of https://github.com/openshift/cluster-logging-operator/pull/1133
> LOG-1685: Delay refresh to allow startup to bind metrics listener

- pkg/generators/forwarding/fluentd/generators.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go.rej
The current legacy syslog forwarding keeps sending empty audit messages to an external rsyslog server.
This issue is caused by the behavior of the legacy method which doesn't skip to send an empty string.
As for k8s audit records, the value of "message" field is always empty string and the legacy syslog forwarding 
tries to use the "message" field from records to set payload by default. 
As a result, the external rsyslog server receives the empty audit log. This is the reason why this issue happens.
This PR disables audit log source when only legacy syslog forwarding is enabled.
There are several options to fix this issue:
1. Fix the behavior of out_syslog and out_syslog_buffered plugins to skip to send empty string
2. Transform audit fluentd records to inject audit information into the …
> LOG-1464: Disable audit log source when only legacy syslog forwarding enabled

- pkg/generators/forwarding/fluentd/fluent_conf_test.go
- pkg/generators/forwarding/fluentd/output_conf_legacy_test.go
- pkg/generators/forwarding/fluentd/source_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR delays in_tail file refresh watcher at startup to allow the metrics endpoint to bind and complete initialization.
cc @vimalk78 @syedriko 
* https://bugzilla.redhat.com/show_bug.cgi?id=1929363
* https://github.com/fluent/fluent-plugin-prometheus/issues/92
> Bug 1929363: Delay refresh to allow startup to bind metrics listener

- must-gather/collection-scripts/gather_collection_resources
Added a command to capture all fluentd pods buffer sizes for every output pipeline as after configuring CLF, multiple output pipelines are created with respect to buffer directory. This helps in troubleshooting.
Modified file: gather_collection_resources
Added commands: 
~~~
echo "$pod" >> $collector_folder/output-buffer-size.txt
echo "---------------" >> $collector_folder/output-buffer-size.txt
oc -n openshift-logging exec $pod -- bash -c ' du -sh /var/lib/fluentd/*' >> $collector_folder/output-buffer-size.txt
~~~
> Collecting buffer size inside fluentd pods for every output pipeline

- hack/gen-olm-artifacts.py
OCP 4.9 will be based on Kubernetes 1.22, which removes several v1beta1 APIs:  https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. This task is about migrating CLO code using the APIs to be removed in Kubernetes 1.22 to their v1 versions.
/cc @vimalk78
https://issues.redhat.com/browse/LOG-1709
> LOG-1709: Migrate off v1beta1 Kube APIs deprecated in 1.22

- pkg/generator/fluentd/output/buffer.go
- pkg/generator/fluentd/output/buffer_conf.go
- pkg/generator/fluentd/output/buffer_conf_test.go
- pkg/generator/fluentd/output/output_fluentd_buffer_test.go
- pkg/generator/fluentd/output/syslog/syslog.go
- pkg/generator/generator.go
- pkg/generator/keyval.go
1. Added an Optional Element, to support optional buffer conf fields
2. Fixed bug [LOG-1392](https://issues.redhat.com/browse/LOG-1392), Output flush_interval only with flush_mode=interval
/assign 
manually cherry-pick 
*release-5.2
*release-4.6
- JIRA: https://issues.redhat.com/browse/LOG-1392
> LOG-1392: Output flush_interval only with flush_mode=interval

- must-gather/README.md
- must-gather/collection-scripts/gather_logstore_resources
Adding new resources:
- Adding [_nodes](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/cluster-nodes-info.html)
- Adding [hot_threads](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/cluster-nodes-hot-threads.html)
Extending curl timout to 20 sec:
We are experiencing empty resource logs in must-gather archives. Instead of expected content they only contain message referencing to "timeout error code (28)".
Completing the documentation.
Adding suffix to each type of resource.
- .json is a json content (can be directly processed by jq)
- .cat is output of _cat endpoint (can be processed by awk or sed)
- .txt is non-structural text format
/cc @btaani
- JIRA: https://issues.redhat.com/browse/LOG-1733
> LOG-1733: Improve must-gather for ES store

- Makefile
- internal/generator/vector/sources_test.go
This PR:
* adds `internal` package into unit tests that was missed after sdk bump
* Skips vector generator tests
cc @vimalk78 @vparfonov
> Add internal to test-unit after sdk bump

- Makefile
- hack/testing-olm/assertions
- internal/constants/constants.go
- internal/k8shandler/certificates_test.go
- internal/k8shandler/collection.go
- internal/k8shandler/collection_test.go
- internal/k8shandler/fluentd.go
- internal/k8shandler/fluentd_test.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/status.go
- internal/utils/utils.go
- must-gather/collection-scripts/gather_cluster_logging_operator_resources
- must-gather/collection-scripts/gather_collection_resources
- must-gather/collection-scripts/gather_install_resources
- test/e2e/collection/cleanup.sh
- test/e2e/collection/fluentd/collector_only_test.go
- test/e2e/collection/fluentd/container_security_test.go
- test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go
- test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/e2e/logforwarding/fluent/fixture_test.go
- test/e2e/logforwarding/fluentlegacy/forward_to_fluent_test.go
- test/e2e/logforwarding/multiple_outputs/forward_to_multiple_outputs_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/e2e/logforwarding/sysloglegacy/forward_to_syslog_test.go
- test/functional/framework.go
- test/functional/metrics/fluentd_test.go
- test/functional/outputs/loki/application_logs_test.go
- test/helpers/framework.go
This PR:
* Does the minimal work to prep CLO to migrate to a new collector by naming the deployed objects as "collector" in lieu of "fluentd"
* Follow-on work should be done to remove "fluentd" from source ref as appropriate
* https://issues.redhat.com/browse/LOG-1337
> LOG-1337: Prep CLO for collector migration

- Dockerfile
- Dockerfile.in
- Makefile
- bundle.Dockerfile
- bundle/metadata/annotations.yaml
- hack/generate-bundle.sh
This PR provides a small fix to the bundle annotations for `release-5.3`, i.e. the channels are set to `stable,stable-5.3` and the package name to `cluster-logging`.
To address: https://issues.redhat.com/browse/LOG-1749
> Fix bundle annotations for release 5.3

- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
- internal/generator/fluentd/output/syslog/syslog.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/functional/outputs/forward_to_syslog_test.go
Syslog plugin uses LTSV formatter https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/vendored_gem_src/fluentd/lib/fluent/plugin/formatter_ltsv.rb to format the record sent to syslog.
This formatter produces a <key:value> set separated by TAB. The key-values are the first level values from record. If the value is a ruby Hash, it gets encoded as string representation of Hash which contains '=>' characters. Further when the logs are sent to rsyslog, rsyslog replaces tabs with "#11" characters which explains the log formatting we see in output.
This PR generates configuration for syslog plugin to use correct formatter. It generates config to use `json` formatter in the default case, and `single_json_value` (instead of `single_value` formatter) in specific cases. …
> LOG-1494: Use "json", "single_json_value" formatter to fix syslog output

- bundle/metadata/annotations.yaml
This PR pins in retrospect all upcoming `4.6.z` bundles to be available only on OCP 4.6.z registries.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=2005955 (https://issues.redhat.com/browse/LOG-1751)
More info:
- [Managing OpenShift versions](https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory/managing-openshift-versions)
- [Slack conversation](https://coreos.slack.com/archives/GGUR75P60/p1631773045120500)
> Bug 2005955: Limit cluster-logging-operator bundle only on OCP 4.6.z

- Makefile
- apis/logging/v1/cluster_log_forwarder_types.go
- apis/logging/v1/output_types.go
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/constants/constants.go
- internal/generator/fluentd/output/kafka/kafka.go
- internal/generator/fluentd/output/kafka/output_conf_kafka_test.go
- internal/generator/fluentd/output/security/security.go
- internal/generator/fluentd/output/security/security_test.go
Common keys are documented in the Secret section of the CLF Go spec.
Output-specific keys are documented in configuration field for that output.
/hold
Open questions:
- is it too late to rename "passphrase" as "tls.key.passphrase"?
- just "passphrase" doensn't tell you what it is a passphrase for...
- is it too late to drop "sasl_over_ssl" in favour of "sasl.enable"?
- if not we can maybe keep sasl_over_ssl as a hidden alias of sasl.enable.
- SASL can be used with or without SSL, some sasl mechs do their own encryption.
- should output specific keys be listed at the end of the main Secret doc?
- I put them with the output-config field, but I dithered over which to do.
/cc @periklis
/cc @vimalkum
> LOG-1725 Summarize Recognized Auth Keys.

- test/functional/normalization/eventrouter_test.go
This PR:
* Makes pod_ip optional when doing message normalization check
* Required to unblock merge of https://github.com/openshift/origin-aggregated-logging/pull/2149
* https://issues.redhat.com/browse/LOG-1390
> [release-5.2] LOG-1390: Allow optional pod_ip for eventrouter tests

- test/functional/normalization/eventrouter_test.go
This PR:
* Makes pod_ip optional when doing message normalization check
* Required to unblock merge of https://github.com/openshift/origin-aggregated-logging/pull/2149
* https://issues.redhat.com/browse/LOG-1390
> [release-5.1] LOG-1390: Allow optional pod_ip for eventrouter tests

- test/functional/framework.go
In release-5.1, add a 1s sleep between log lines to avoid flaky functional tests. This sleep is there on the release-5.2 and master branches. Functional test flakes on the release-5.1 branch interfere with https://github.com/openshift/origin-aggregated-logging/pull/2189
- JIRA:  https://issues.redhat.com/browse/LOG-1033
- PR: https://github.com/openshift/origin-aggregated-logging/pull/2189
> Add a 1s sleep between log line output to avoid flaky functional tests

- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- test/framework/functional/cluster_log_forwarder.go
This PR:
* Fixes fluent conf generation to Elasticsearch when a secure scheme is defined without providing a secret
* https://issues.redhat.com/browse/LOG-1235
> LOG-1235: Fix output scheme to ES for https w/o secret

- hack/testing-olm/test-030-collection.sh
- hack/testing-olm/test-367-logforwarding.sh
This PR bumps the slow threshold warning so successful, long running e2e test do not pollute the test run with unnecessary log information
```
• [SLOW TEST:195.994 seconds]
[Collection] Namespace filtering
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/collection/fluentd/namespace_filtering_test.go:20
should send logs from one namespace only
/go/src/github.com/openshift/cluster-logging-operator/test/e2e/collection/fluentd/namespace_filtering_test.go:97
```
> Bump slow spec threshold for e2e tests to cleanup logs

- files/fluentd/fluentd_prometheus_alerts.yaml
This PR:
* Fixes the job name for the prometheus alert
cc @anpingli 
https://issues.redhat.com/browse/LOG-1918
> LOG-1918: Fix the collector alert job name

- files/fluentd/fluentd_prometheus_alerts.yaml
1 hour of grace period after starting before this alert can be triggered
From prometheus, the rate of change seems always spike after the pod
has been started/restarted so this change will give a grace period
before this alert can be triggered
/cc @jcantrill
- JIRA: https://issues.redhat.com/browse/OSD-8403
> Tweaked alert for "FluentdQueueLengthIncreasing" and give fluend nodes

- internal/generator/vector/conf_test.go
- internal/generator/vector/helpers/helpers.go
- internal/generator/vector/inputs_to_pipeline.go
- internal/generator/vector/output/elasticsearch/basic.go
- internal/generator/vector/output/elasticsearch/ca-file.go
- internal/generator/vector/output/elasticsearch/cert-key.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/elasticsearch/output_conf_es_test.go
- internal/generator/vector/output/elasticsearch/userpass.go
- internal/generator/vector/outputs.go
- internal/generator/vector/sources_to_inputs.go
This PR generates configuration for vector log collector.
/cc @vimalk78 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1491
Added support for elastic search as output. 
Sample conf:
```
[sources.raw_container_logs]
type = "kubernetes_logs"
auto_partial_merge = true
exclude_paths_glob_patterns = ["/var/log/pods/openshift-logging_collector-*/*/*.log", "/var/log/pods/openshift-logging_elasticsearch-*/*/*.log", "/var/log/pods/openshift-logging_kibana-*/*/*.log"]
[sources.raw_journal_logs]
type = "journald"
[sources.host_audit_logs]
type = "file"
ignore_older_secs = 600
include = ["/var/log/audit/audit.log"]
[sources.k8s_audit_logs]
type = "file"
ignore_older_secs = 600
include = …
```
> LOG-1491:Adding support for elastic-search as output in vector conf generator

- internal/k8shandler/collection.go
- internal/k8shandler/fluentd.go
- internal/k8shandler/serviceaccount.go
- internal/runtime/core.go
- test/framework/e2e/fluentd.go
- test/framework/e2e/syslog.go
This PR:
* Moves SA construction to use a single package
Ref: https://issues.redhat.com/browse/LOG-2027
> LOG-2027: Move SA constructor to use runtime package

- Makefile
- olm_deploy/operatorregistry/registry-deployment.yaml
For local development and debugging, many times it is needed to deploy logging from different branches to compare a feature across branches, and need to switch back again. Since the images are tagged `latest`, the same image pull spec cannot be used across branches even though the image has been pushed to cluster.
This PR attempts to tag the images in the cluster with branch name so that images in cluster do not get overwritten.
```
> git checkout release-5.3
> make deploy
> oc delete ns openshift-logging openshift-operators-redhat
> git checkout master
> make deploy
$ oc -n openshift get is/origin-cluster-logging-operator -o jsonpath='{.status.tags[*].tag}' 
master release-5.3
> oc delete ns openshift-logging openshift-operators-redhat
> git checkout release-5.3
> make deploy-catalog
> …
```
> Makefile: tag images with branch name

- internal/cmd/forwarder-generator/main.go
- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/pkg/generator/forwarder/generator.go
- test/framework/functional/framework.go
(cherry picked from commit 7dd9b001082a2e5ed56f9af539277ff09d0eeb06)
This PR:
* Fixes how outputdefaults are applied to only set them if not defined on the output
* Fixes modifying the output secret if OutputDefaults are applied
* Fixes the forward-generator tool 
5.4 forward port of https://github.com/openshift/cluster-logging-operator/pull/1282
* https://issues.redhat.com/browse/LOG-2056
> LOG-2056: fix wrong certs when OutputDefaults are defined

- files/dashboards/openshift-logging-dashboard.json
This PR:
* fixes the namespace for top producing and collected containers
* modifies the table titles
* displays bytes collected/produced in Megabytes over 24 hrs
* Adds in the section headers which were only partially visible
* https://issues.redhat.com/browse/LOG-2051
> LOG-2051: fix dashboard namespace and formating

- internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go
- internal/cmd/functional-benchmarker/runners/runner.go
- internal/constants/constants.go
- internal/runtime/pod.go
- test/framework/functional/framework.go
This PR:
* Refactors the functional-benchmarker to mount the host filesystem to take advantage of CRIO rollover instead of mimicking it
This will make our tests more accurate and additionally allow us to add logic to check for log loss due to load and file rotation.
/cc @alanconway @syedriko 
* https://issues.redhat.com/browse/LOG-1910
> LOG-1910: Mount host filesystem to leverage CRIO rollover

- internal/generator/test_common.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- test/functional/outputs/multiple/multiple_test.go
Collector pods fail to start when a ClusterLogForwarder instance is created to forward logs to multiple log stores
/cc @vimalk78 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2072
> LOG_2072: Collector fails with multiple log stores

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- test/e2e/logforwarding/loki/forward_to_loki_test.go
Fixed tenant id field generation in vector config.
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2130
> LOG-2130: fixed loki tenant-id generation

- Makefile
- bundle/manifests/cluster-logging-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- config/prometheus/monitor.yaml
- controllers/clusterlogging/clusterlogging_controller.go
- internal/k8shandler/reconciler.go
- internal/telemetry/cloteleminfo.go
- internal/telemetry/cloteleminfo_test.go
- internal/utils/safemap.go
- internal/utils/safemap_test.go
- main.go
- manifests/5.4/cluster-logging-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- test/e2e/telemetry/clometrics_test.sh
Story
As a member of the OpenShift Logging Team, I want telemetry metrics of the CLO
so that we have a better understanding of how CLF is being utilized by customers (e.g. which outputs)
Acceptance Criteria
Verifying telemetry metrics are available from the CLO metrics endpoint in prometheus
/cc @jcantrill @alanconway 
/assign 
- JIRA:  https://issues.redhat.com/browse/LOG-1926
> Implement logging telemetry log 1926 

- controllers/clusterlogging/clusterlogging_controller.go
- hack/testing-olm/test-010-deploy-via-olm-minimal.sh
- internal/k8shandler/clusterloggingrequest.go
- internal/k8shandler/reconciler.go
- internal/metrics/dashboards.go
- internal/metrics/dashboards_test.go
- internal/reconcile/configmaps.go
- internal/utils/comparators/configmaps/comparator.go
- internal/utils/utils.go
- main.go
This PR:
* Fixes configmap dashboard reconciliation by configuring API client to watch openshift-config-managed NS
ref: https://issues.redhat.com/browse/LOG-2066
> LOG-2066: Modify client to also watch cluster config NS

- go.mod
- vendor/modules.txt
cachito fails with
```
The command "go list -find ./..." failed with: package github.com/openshift/cluster-logging-operator/internal/telemetry imports github.com/prometheus/client_golang/prometheus from implicitly required module; to add missing requirements, run:
go get github.com/prometheus/client_golang@v1.11.0
```
this PR is to make it happy. This is new for Go 1.17.
/cc @vimalk78 
> make "go list" happy wrt github.com/prometheus/client_golang/prometheus

- internal/k8shandler/fluentd.go
- internal/k8shandler/vector.go
Journal logs are collected by `journalctl` utility. By default (as per `/etc/systemd/journald.conf`) `journalctl` reads from path `/run/log/journal`. But container has persistent journal logs in path `/var/log/journal`. So collector needs to be configured with the correct path. 
For `fluentd`, the configuration is
```
<source>
@type systemd
path '/var/log/journal'
</source>
```
But vector 0.14's `journald` does not have configuration to set the path. A config parameter `journal_directory` is present in latest version, but not in v0.14
So a workaround is used in this PR to mount host's `/var/log/journal` as `/run/log/journal`. This fixes reading journal logs in vector container.
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2052
> LOG-2052: Vector: Fix capturing journal logs

- internal/k8shandler/reconciler.go
- internal/metrics/dashboards.go
- internal/metrics/dashboards_test.go
This PR:
* removes the ownerref from the dashboard configmap since this is invalid across namespaces (Not obvious)
(https://issues.redhat.com/browse/LOG-2163)
cc @anpingli
> LOG-2163: Remove ownerRef for invalid across namespace ownership

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
When different log types are sent to different stores vector configuration is incorrect.  Please see attached Jira ticket to see an example. 
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-2166
> LOG-2166: Fail when different type logs to different log stores

- test/functional/normalization/json_parsing_test.go
This PR:
* Adds a test case to prove writing structured logs to an Elasticsearch output
https://issues.redhat.com/browse/LOG-2105
> [release-5.4] add test to address LOG-2105

- must-gather/collection-scripts/gather_elasticsearch_operator_resources
This fix will update the gather_elasticsearch_operator_resources script so it captures the elasticsearch-operator logs instead of failing with the error message: error: "a container name must be specified for pod elasticsearch-operator-<id>".
/cc jcantrill
- Github issue: https://github.com/openshift/cluster-logging-operator/issues/1329
> Specify elasticsearch-operator container to collect logs [issue 1329]

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/multiline_detect_exceptions.go
- test/framework/functional/cluster_log_forwarder.go
- test/functional/normalization/multiline_exception_test.go
This PR:
* fixes an error in the fluent log where multiple multiline plugin configurations have the same id
* https://issues.redhat.com/browse/LOG-2241
> LOG-2241: fix multiline error detection for multiple pipelines

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/k8shandler/vector.go
read value of `kubernetes.host` label from `VECTOR_SELF_NODE_NAME` environment variable
read value of `kubernetes.namespace_name` label from `kubernetes.pod_namespace`
/cc 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2249#add-comment
> LOG-2249: Vector: Fix loki pod labels

- hack/testing-olm/test-367-logforwarding.sh
This PR:
* Allows us to specify e2e ginkgo options (e.g. skipping vector testing if needed)
cc @vimalk78
> add env var to allow specifying ginko options

- test/functional/message_templates.go
- test/helpers/types/optional_int.go
- test/helpers/types/optional_int_test.go
- test/helpers/types/suite_test.go
- test/helpers/types/types.go
- test/matchers/log_format.go
(cherry picked from commit 00333246a3d6812ef8c0f0860e8cfa9f4bb89e34)
backport of #1334
> [release-5.1] LOG-2099: Add optionalint in prep for fix

- internal/generator/vector/conf_test.go
- internal/generator/vector/elements/elements.go
- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/sources_to_inputs.go
- internal/generator/vector/sources_to_pipelines_test.go
- internal/generator/vector/vrl.go
Support Pod Label based routing of Application logs
/cc @jcantrill @alanconway 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2255
> LOG-2255: Vector: Support Pod Label based routing

- internal/generator/vector/conf_test.go
- internal/generator/vector/metrics.go
- internal/generator/vector/outputs.go
- internal/generator/vector/sources.go
- Enabled `internal-metrics` of vector
- Exposed these metrics using prometheus exporter sink
The metrics are prefixed with `vector_`. 
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2263
> LOG-2263: Vector: Added prometheus_exporter sink

- internal/generator/vector/sources_to_inputs.go
The Route transform was added for each input with user defined inputs. Just one Route transform is sufficient with a map for each user defined input.
/assign 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2259
> LOG-2259: Vector: Add Route transform for application routing only once

- test/e2e/collection/fluentd/fluentd_suite_test.go
- test/e2e/logforwarding/elasticsearchmanaged/logforwarding_suite_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/logforwarding_suite_test.go
- test/e2e/logforwarding/syslog/logforwarding_suite_test.go
- test/framework/functional/suite_test.go
- test/functional/collection/suite_test.go
- test/functional/metrics/suite_test.go
- test/functional/normalization/suite_test.go
- test/functional/outputs/loki/suite_test.go
- test/functional/outputs/multiple/suite_test.go
- test/functional/outputs/suite_test.go
- test/matchers/suite_test.go
> LOG-2117 Remove deprecated Ginkgo custom reporters

- hack/run-linter
This PR:
* Adds a lint check to determine if a focused test slipped into a commit (e.g. FIt, FDescribe, etc)
cc @vimalk78 @alanconway
> Add linter to check if focused tests are defined

- internal/generator/forwarder/format_test.go
- internal/generator/forwarder/generator.go
- internal/generator/forwarder/suite_test.go
This PR:
* Standardizes the format of fluent.conf after generation to remove inconsistencies with indents and newlines
* https://issues.redhat.com/browse/LOG-2276
> LOG-2276: Format fluent.conf after generation

- Dockerfile
- Dockerfile.in
- internal/k8shandler/collection.go
- internal/k8shandler/vector.go
- test/e2e/logforwarding/loki/forward_to_loki_test.go
- test/helpers/clusterlogging.go
Added an annotation check while deploying collector.
Need to add `logging.openshift.io/preview-vector-collector: enabled` annotation to `ClusterLogging` to deploy vector as a collector. 
- JIRA: https://issues.redhat.com/browse/LOG-2281
> LOG-2281: Feature Gate Vector to enable for preview

- internal/pkg/generator/forwarder/format_test.go
- internal/pkg/generator/forwarder/generator.go
- internal/pkg/generator/forwarder/suite_test.go
(cherry picked from commit 2fb57d8647d7fe86fe5e31f28b32d0c47e1753b0)
This PR:
* Standardizes the format of fluent.conf after generation to remove inconsistencies with indents and newlines
* 5.4 backport of #1352 
* https://issues.redhat.com/browse/LOG-2319
> [release-5.4] LOG-2319: Format fluent.conf after generation

- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
Before the events are sent to Elasticsearch sink, a Lua script is used to substitute `.` with `_` in the pod_labels.
The lua script logic does a check for presence of `kubernetes` field in the record, and proceeds to do `DeDot` only if this field is present. The event was not emitted if this field was not present.
Fixed lua script to emit the event if `kubernetes` field is not found.
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-2333
> LOG-2333: Fix ES DeDot lua script dropping Journal logs

- internal/generator/helpers/debug.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/kafka/kafka.go
- internal/k8shandler/collection.go
- internal/k8shandler/forwarding.go
- internal/pkg/generator/forwarder/generator.go
To debug records reaching a log store, we need to observe what records are being sent out from output sinks.
This PR adds a `stdout` sink instead of the output sink configured in the forwarder, and all the records are logged in the vector's logs.
```
[sinks.<output-name>]
inputs = ["test-app"]
type = "console"
target = "stdout"
[sinks.<output-name>.encoding]
codec = "json"
```
This feature can be controlled by adding an annotation `logging.openshift.io/debug-output: "true"`  to the ClusterLogForwarder 
```
apiVersion: "logging.openshift.io/v1"    
kind: "ClusterLogForwarder"    
metadata:    
name: "instance"    
namespace: "openshift-logging"    
annotations:    
logging.openshift.io/debug-output: "true"    
spec:    
outputs:    
- name: kafka-app    
url: …
```
> Vector: Add annotation controlled stdout sink conf generation

- test/e2e/collection/fluentd/container_security_test.go
This PR extends the e2e container security test timeout to 3 min since there is evidence of a possible timing issue.  The test times out at 60s and the pod shows an age of 72s
/assign @syedriko
> Extend the container security e2e test timeout to 3 min

- internal/k8shandler/collection.go
This PR adds a Status if vector is used as collector and preview annotation is missing
```
status:
clusterConditions:
- lastTransitionTime: "2022-03-15T09:14:45Z"
message: 'Add annotation "logging.openshift.io/preview-vector-collector: enabled"
to ClusterLogging CR'
reason: Vector as collector not enabled via annotation on ClusterLogging
status: "True"
type: CollectorDeadEnd
```
/cc @alanconway @jcantrill 
/cherry-pick release-5.4
- JIRA: https://issues.redhat.com/browse/LOG-2375
> LOG-2375: Vector: Added Status for missong preview annotation

- internal/components/fluentd/run_script.go
- test/e2e/collection/fluentd/container_security_test.go
[LOG-2176](https://issues.redhat.com/browse/LOG-2176): /var/lib/fluentd is world-readable. Limit access to fluentd buffers on disk.
- JIRA: https://issues.redhat.com/browse/LOG-2176
- Depends on: https://github.com/ViaQ/logging-fluentd/pull/11
> LOG-2176: /var/lib/fluentd is world-readable

- hack/testing-olm/test-010-deploy-via-olm-minimal.sh
This PR introduces a similar change from master to check for unmananged logging before managed.  This change was made in an effort to fix issues like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/ViaQ_logging-fluentd/12/pull-ci-ViaQ-logging-fluentd-v1.7.4-cluster-logging-operator-e2e-5-2/1502645978719588352 which is otherwise a successful test
/assign @vimalk78 @alanconway 
* should unblock https://github.com/ViaQ/logging-fluentd/pull/12
> update minimal test to check unmanaged CL first

- test/helpers/types/optional_int.go
- test/helpers/types/optional_int_test.go
- test/matchers/log_format.go
- test/matchers/log_format_test.go
This PR provides additional fixes to test code:
* Properly defining OptionalInt("") to mean accept anything including a missing value
* Add tests to verify OptionalInt expectations
* Blocks https://github.com/ViaQ/logging-fluentd/pull/20 and associated bugs
* Follows-up https://github.com/openshift/cluster-logging-operator/pull/1334
/assign @vimalk78 @cahartma 
* https://issues.redhat.com/browse/LOG-2291
> LOG-2291: Fix OptionalInt type

- internal/components/fluentd/run_script.go
- test/e2e/collection/fluentd/container_security_test.go
[LOG-2185](https://issues.redhat.com/browse/LOG-2185): /var/lib/fluentd is world-readable. Limit access to fluentd buffers on disk.
Unlike Fluentd 1.14, Fluentd 1.7 is umask-transparent and doesn't need umask fixes. Meaning Fluentd 1.7 adopts the umask set in the shell that execs it.
- JIRA: https://issues.redhat.com/browse/LOG-2185
> LOG-2185: /var/lib/fluentd is world-readable

- internal/k8shandler/reconciler.go
- internal/telemetry/cloteleminfo.go
- internal/telemetry/cloteleminfo_test.go
- main.go
Fixes for the below QE raised issues on CLO Telemetry metrics:
[LOG-2320](https://issues.redhat.com/browse/LOG-2320) : Should report as default when outputRefs to default 
[LOG-2313](https://issues.redhat.com/browse/LOG-2313): The CLO shouldn't expose metrics when no clusterlogging/instance 
[LOG-2315](https://issues.redhat.com/browse/LOG-2315): Duplicated items in log_logging_info metrics 
[LOG-2318](https://issues.redhat.com/browse/LOG-2318): Two items for metrics  log_forwarder_input_info  and log_forwarder_output_info 
- JIRA: https://issues.redhat.com/browse/LOG-2313, https://issues.redhat.com/browse/LOG-2315, https://issues.redhat.com/browse/LOG-2318, https://issues.redhat.com/browse/LOG-2320
> fixes for CLO Telemetry metrics LOG-710 issues - LOG-2013,LOG-2315,LOG-2018, LOG-2320

- internal/constants/constants.go
- internal/generator/fluentd/output/loki/bearer-token-file.go
- internal/generator/fluentd/output/loki/ca-file.go
- internal/generator/fluentd/output/loki/cert-key.go
- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
- internal/generator/fluentd/output/loki/userpass.go
- internal/generator/fluentd/output/security/security.go
This PR:
- fixes loki output url parse method.
- add support for bearer_token in secrets.
- rename `elasticsearch` -> `loki` in all loki templates.
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-2393, https://issues.redhat.com/browse/LOG-2392
> LOG-2393: Fix loki output url parse and add bearer_token support

- test/functional/normalization/message_format_test.go
- test/helpers/types/types.go
This PR:
* updates OVN audit log test to expect sequence number
* https://issues.redhat.com/browse/LOG-2291
> LOG-2291: Fix OVN audit test to expect sequence no

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/sources_test.go
[LOG-1033](https://issues.redhat.com/browse/LOG-1033): Update fluentd to the latest version (1.14.1). Prometheus listener needs `<transport tls>` configuration to enable async HTTP server instead of Webrick. Otherwise, no functional changes.
- JIRA: https://issues.redhat.com/browse/LOG-1033
- GitHub: https://github.com/ViaQ/logging-fluentd/pull/22
> LOG-1033: <transport tls> Prometheus config for fluentd 1.14

- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
A manual cherry pick of https://github.com/openshift/cluster-logging-operator/pull/1371 [LOG-2333](https://issues.redhat.com/browse/LOG-2333) 
A partial manual cherry pick of https://github.com/openshift/cluster-logging-operator/pull/1401/commits/80e5e27f86bfc9da3998a54c7357b5bb4176ae92 for fixing ES DeDot lua script which rejects records if ot does not contain pod labels.
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-2398
> LOG-2398: Fix ES DeDot lua script dropping Journal logs

- internal/components/fluentd/run_script.go
This PR provides an additional change from https://github.com/openshift/cluster-logging-operator/pull/1320 to 5.4 to unblock
moving fluent 1.14.5 into logging 5.4
/assign @syedriko
> LOG-2176: Additional change to support fluent 1.14.5

- internal/constants/constants.go
- internal/k8shandler/forwarding_test.go
Make Elastic's DNS name just "elasticsearch" as opposed to "elasticsearch.openshift-logging.svc" in order to avoid extra DNS queries from fluentd.
- JIRA: https://issues.redhat.com/browse/LOG-1909
> LOG-1099: Fluentd firing far too many dns requests

- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
- test/e2e/logforwarding/elasticsearchmanaged/clo_managed_logstore_test.go
- test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go
- test/framework/e2e/framework.go
This PR add the feature to change the elasticsearch index as per OutputDefaults for Elasticsearch output.
This feature is already implemented for fluentd, and this PR adds it for vector.
To have feature parity between fluentd and vector for feature "Changing index based on labels defined `structuredTypeKey`" we need pod labels to be presented in the same way for fluentd or vector.
Currently, for vector the pod labels are added under `kubernetes.pod_labels` which is different from fluentd `kubernetes.labels` 
So this PR changes `kubernetes_logs` config to change the way labels are captured. This may require higher version of vector than currently used. 
This PR also configures `kubernetes_logs` to produce `namespace_name` in place of `pod_namespace` and removes the VRL code which changes …
> LOG-2476: Change ES index as per OutputDefaults

- internal/generator/vector/conf_test.go
- internal/generator/vector/source/journal_log.go
- internal/generator/vector/sources_test.go
set the path of journal logs for `journalctl` to scrape.
/cc @cahartma @jcantrill 
/assign 
- Bugzilla:
- Github issue: https://issues.redhat.com/browse/LOG-2549
- JIRA:
> LOG-2549: Fix journal logs in vector v0.21-rh

- Makefile
- internal/cmd/functional-benchmarker/runners/cluster/cluster_runner.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/inputs.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/sources.go
- internal/generator/vector/sources_test.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/framework/functional/elasticsearch.go
- test/framework/functional/framework.go
- test/functional/normalization/audit_logs_format_test.go
- test/functional/normalization/message_format_test.go
This PR:
* fixes the path used by oauthapi audit logs
* adds ovn audit logs to log collection
cc @vimalk78 
*https://issues.redhat.com/browse/LOG-2172
> LOG-2172: fix ovn and oauthapi audit log collection

- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/source/tags.go
- test/framework/functional/output_cloudwatch.go
- test/framework/functional/write.go
- test/functional/normalization/multiline_exception_test.go
- test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
- test/functional/outputs/syslog/rfc3164_test.go
fixes issue where infra container logs were being captured by the application log group
/assign @vimalk78 @jcantrill 
- https://issues.redhat.com/browse/LOG-2455
- related to: https://issues.redhat.com/browse/LOG-2160
- related to: https://issues.redhat.com/browse/LOG-2275
> LOG-2455: fix infra logs showing in app log group

- test/functional/metrics/fluentd_test.go
This PR:
* Adds a test to verify metrics are available even when outputs are down
* https://issues.redhat.com/browse/LOG-2557
> LOG-643: Add metric test when fluent output is down

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- test/framework/functional/message_templates.go
- test/framework/functional/write.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
This PR:
* fixes the case where structured logging is enabled and infra source logs are sent to an application structured index
* https://issues.redhat.com/browse/LOG-2134
> LOG-2134: Always send infra logs to infra indices

- internal/collector/collector.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/ingress.go
- test/framework/functional/fluentd/deploy.go
- test/functional/normalization/logs
This PR:
* fixes sending logs to separate indices from the same container when the pod is annotated after the collector boots
* enables watch for the metadata plugin to refresh the info
* Adds env var to restrict the watch to the pods on the node
* https://issues.redhat.com/browse/LOG-2525
> LOG-2525: enable metadata watch to fix spliting logs

- Makefile
- internal/k8shandler/collection_test.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- test/e2e/logforwarding/fluent/fluent_secure_test.go
This PR:
* fixes collector deployment when only a collector is defined and there is no CLF
* Stops deployment of either fluent or vector 
* Refactors one test to be ginkgo table driven
* https://issues.redhat.com/browse/LOG-2063
> LOG-2063: fix deploying a collector with no CLF

- files/fluentd/fluentd_prometheus_alerts.yaml
/cc jcantrill
/assign jcantrill
When firing the "FluentdNodeDown" alert, the instance label is always empty in the messages due to "absent()" function which eliminates the label. As adding a condition for partial failures, the messages can show the partial failure instances instead of empty one.
Version:
```
$ oc get csv 
NAME                                     DISPLAY                                          VERSION     REPLACES                                 PHASE
cluster-logging.5.4.0-138                Red Hat OpenShift Logging                        5.4.0-138   cluster-logging.5.3.5-20                 Succeeded
elasticsearch-operator.5.4.0-152         OpenShift Elasticsearch Operator                 5.4.0-152   elasticsearch-operator.5.3.5-20          Succeeded
```
Definition of …
> OCPBUGSM-44068: Fix missing labels.instance in messages

- internal/collector/collector_test.go
- internal/constants/constants.go
- internal/utils/utils.go
- internal/utils/utils_test.go
fluentd and vector are unable to ship logs to elasticsearch when cluster-wide proxy is in effect. This is due to https://github.com/openshift/cluster-logging-operator/pull/1407. The fix is to add `elasticsearch,` to the `NO_PROXY` and `no_proxy` env variables in case those are set and make sure we do not try to talk to elasticsearch through the proxy.
- JIRA: https://issues.redhat.com/browse/LOG-2609
> LOG-2609: fluentd and vector are unable to ship logs to elasticsearch when cluster-wide proxy is in effect

- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/source/tags.go
- test/framework/functional/output_cloudwatch.go
- test/framework/functional/write.go
- test/functional/normalization/multiline_exception_test.go
- test/functional/outputs/cloudwatch/forward_to_cloudwatch_test.go
- test/functional/outputs/syslog/rfc3164_test.go
5.4 version of fix for issue where infra container logs were being captured by the application log group - clone of [LOG-2455](https://issues.redhat.com//browse/LOG-2455)
/assign @vimalk78 @jcantrill 
- clone of: https://issues.redhat.com/browse/LOG-2455
- related to: https://issues.redhat.com/browse/LOG-2160
- related to: https://issues.redhat.com/browse/LOG-2275 
Additional Note:
This includes the same 7 files as the PR we just merged for [LOG-2455](https://issues.redhat.com//browse/LOG-2455):  https://github.com/openshift/cluster-logging-operator/pull/1431   The only difference should be the absence of sts cloudwatch tests.
> LOG-2589: fix infra logs showing in app group 

- Dockerfile
- Dockerfile.in
- go.mod
- go.sum
- origin-meta.yaml
This PR:
* Updates golang v1.17 to unblock https://issues.redhat.com/browse/LOG-2522
* https://issues.redhat.com/browse/LOG-2622
> LOG-2622: update golang to v1.17

- files/fluentd/fluentd_prometheus_alerts.yaml
This PR:
* fixes the alerting rule for clusterlogforwarder to take into account the output
* https://issues.redhat.com/browse/LOG-2588
Note without fix the metrics console shows:
> LOG-2588: fix alerting rule for CLF

- internal/collector/fluentd/run_script.go
- internal/k8shandler/collection.go
LOG:2159 cluster logging pods in crash loop back off
- Bugzilla:
- Github issue: 
- JIRA: https://issues.redhat.com/browse/LOG-2159
> Fix LOG:2159 cluster logging pods in crash loop back off 

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/elements/record_modifier.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/outputs.go
Add to the `fluent.conf` for `Elasticsearch` and `Cloudwatch` storage:
```
<filter **>
@type record_modifier
char_encoding ascii-8bit:utf-8
</filter>
```
to be ensured  utf8 and replace bad chars
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2203
> LOG-2203:Add ability to encoding bad characters for elasticsearch and cloudwatch

- Makefile
- internal/generator/vector/conf_test.go
- internal/generator/vector/normalize.go
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
- internal/runtime/pod.go
- test/framework/functional/message_templates.go
- test/framework/functional/output_cloudwatch.go
- test/framework/functional/vector/deploy.go
- test/functional/doc.go
- test/functional/fluentd.go
- test/functional/functional.go
- test/functional/normalization/audit_logs_format_test.go
- test/functional/normalization/crio_partial_log_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go
- test/functional/vector.go
- test/helpers/types/types.go
This PR
- fixes functional framework to make `kubernetes_logs` start scraping application logs created by functional framework, enables debug logs for vector
- adds go test tags based selection of collector for functional test framework.
- use `go test --tag=fluentd` to set a global variable `"FrameworkType"` to "fluentd"
- use `go test --tag=vector` to set a global variable `"FrameworkType"` to "vector"
which can be used to create framework in the tests.
- fixes app log data model to conform to functional test app log template
- relaxes message template to accommodate both fluentd and vector based record creation
- enables outputs/elasticsearch tests to run for both fluentd and vector
/cc @jcantrill @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-2587
> LOG-2587: Fix ES functional tests for vector, using go tags

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/elements/record_modifier.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/outputs.go
Add to the `fluent.conf` for `Elasticsearch` and `Cloudwatch` storage:
```
<filter **>
@type record_modifier
char_encoding ascii-8bit:utf-8
</filter>
```
to be ensured  utf8 and replace bad chars
/cc 
/assign 
/cherry-pick 
Manually cherry-picked https://github.com/openshift/cluster-logging-operator/pull/1465
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2657
> LOG-2657:Add ability to encoding bad characters for elasticsearch and cloudwatch

- Makefile
- controllers/clusterlogging/clusterlogging_controller.go
- controllers/forwarding/forwarding_controller.go
- internal/constants/constants.go
- internal/k8shandler/reconciler.go
- internal/telemetry/cloteleminfo.go
- main.go
[LOG-2439](https://issues.redhat.com//browse/LOG-2439): fix for healthStatus and managedStatus update #1445
issues notified by QE
CL healthStatus and managedStatus now treated as below
UnHealthyStatus = "0"
HealthyStatus   = "1"
UnManagedStatus = "0"
ManagedStatus   = "1"
version is set to operator_version =  version.Version value as per the telemetry specification for CLO
Any early exit from reconciler with error is treated as un healthy status for CL.  Fixed this in the internal/k8handler/reconciler.go
/assign  @alanconway 
Links
Bugzilla:
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-2439
> LOG-2439: fix for healthStatus and managedStatus update

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/source/tags.go
- internal/generator/fluentd/sources_to_pipelines_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/inputs.go
- internal/generator/vector/sources_to_pipelines_test.go
Fix the condition in [transforms.route_container_logs] in the configuration file for Vector. 
All container logs from namespaces which name start with  `kube-`, `openshift-` or equals `default`, `openshift` should be treated as infra logs,  otherwise are application logs.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2596
> LOG-2596: Fix the condition in [transforms.route_container_logs] in the configuration file for Vector 

- internal/generator/vector/output/cloudwatch/cloudwatch.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
Fixes an issue found shortly after merge of the feature.   Infrastructure logs need to include and use `hostname` rather than the removed `kubernetes.pod_node_name` annotation.
- https://issues.redhat.com/browse/LOG-2223
> LOG-2223: Vector cloudwatch support fix stream names for infra log group

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/ingress.go
- internal/generator/vector/conf.go
- internal/generator/vector/conf_test.go
This PR:
fixes 'critical' log level eval to expect a match from beginning of capture
adds critical to vector to address for [LOG-2033](https://issues.redhat.com//browse/LOG-2033) for vector
Links
https://issues.redhat.com/browse/LOG-2677
> LOG-2677: Update critical normalization to be like others

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/output/buffer_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/pipeline_to_output_test.go
- internal/generator/fluentd/sources_test.go
- internal/generator/fluentd/sources_to_pipelines_test.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/loki/loki_conf_test.go
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
- test/helpers/generator.go
This PR:
* Enables forward container logs to separate indices for vector
* https://issues.redhat.com/browse/LOG-2545
/assign @vimalk78
> LOG-2545: forward container logs to separate indices for vector

- hack/generate-crd.sh
This PR adds [these lines](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.18.0/#support-image-digests-instead-of-tags) to the script `./hack/generate-crd.sh`, to fix the `bundle` target, (these lines were mistakenly dropped after the rebase of the previous PR (#1472))
- Depending on PR(s): #1472
> Support image digests instead of tags for operator-sdk update

- pkg/generators/forwarding/fluentd/output_cloudwatch_test.go
- pkg/generators/forwarding/fluentd/templates.go
This PR corrects the config to remove the colon so it is actually used
https://issues.redhat.com/browse/LOG-2635
> LOG-2635: Remove colon from config parameter

- bundle/manifests/logging.openshift.io_clusterlogforwarders_crd.yaml
- bundle/manifests/logging.openshift.io_clusterloggings_crd.yaml
- internal/k8shandler/indexmanagement/index_management.go
- internal/k8shandler/indexmanagement/indexmanagement_test.go
- manifests/5.5/logging.openshift.io_clusterlogforwarders_crd.yaml
- manifests/5.5/logging.openshift.io_clusterloggings_crd.yaml
This PR is a followup to a similar one for Elasticsearch operator, where the support of `y` and `M` time units is removed from the retention policy time fields in CRDs
- Depending on PR(s): https://github.com/openshift/elasticsearch-operator/pull/874
- JIRA: [LOG-2418](https://issues.redhat.com/browse/LOG-2418)
> Remove support of 'years' and 'months' timeunits from CRD

- controllers/clusterlogging/clusterlogging_controller.go
- internal/metrics/dashboards.go
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2243
> LOG-2243: remove grafana-dashboard-cluster-logging on removing clusterlogging/instance

- Makefile
- internal/generator/forwarder/generator.go
- internal/generator/vector/conf_test.go
- internal/generator/vector/output/elasticsearch/cert-key.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/output/kafka/ca-file.go
- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/kafka/sasl.go
- internal/generator/vector/output/security/security.go
- test/e2e/logforwarding/fluent/fluent_secure_test.go
- test/e2e/logforwarding/fluent/fluent_test.go
- test/functional/outputs/kafka/forward_to_kafka_test.go
- test/functional/outputs/kafka/suite_test.go
Fixes Kafka Sasl for vector.
Tested scenarios
- sasl
- sasl + ssl
- ssl
- mutual ssl
- without tls
/cc @alanconway @jcantrill 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-2169, https://issues.redhat.com/browse/LOG-2167
> LOG-2169: Fix Kafka sasl-plaintext/sasl-ssl

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/buffer_conf.go
- internal/generator/fluentd/output/buffer_conf_test.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/fluentdforward/output_conf_forward_test.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/kafka/output_conf_kafka_test.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
This PR:
* Disables chunk backup for all output types in order to not fill the node disk
* https://issues.redhat.com/browse/LOG-2746
> LOG-2746: Disable chunk backup for all outputs

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
Currently the vector configuration generator for the Loki output does not provide an option for setting a custom bearer token. The only way of setting a bearer-token to authenticate to Loki is to leave the secret blank and use the token issues to the `logcollector` ServiceAccount.
This PR enables the use of bearer-tokens with custom secrets.
- JIRA: Related to [LOG-2323](https://issues.redhat.com/browse/LOG-2323)
> Fix handling of custom bearer token for vector Loki output

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
Currently the cluster-logging-operator automatically uses the logcollector ServiceAccount's token when no custom secret is specified in the Loki output configuration. This PR extends this behaviour by also injecting the CA-bundle that is present by default on the ServiceAccount, enabling vector to validate certificates issued by the internal service CA.
- JIRA: References [LOG-2323](https://issues.redhat.com/browse/LOG-2323)
> Use service CA when using default token in vector Loki output

- Makefile
- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manager/manager.yaml
- docs/configuration.md
- hack/gen-olm-artifacts.py
- internal/constants/constants.go
This PR adds the images under the `relatedImages` section. 
/cc @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-2751
> LOG-2751: Using related images naming scheme

- internal/generator/fluentd/output/loki/bearer-token-file.go
- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
Currently the fluentd and vector config generators for the Loki output treat the contents of the `token` value of the provided secret differently. The vector generator treats the value as the literal token, while the fluentd generator treats it as a path to a file containing the token.
Looking at how secrets are usually used, the approach the vector configuration generator uses seems more adequate, making it possible to give the collector a secret without having additional files in the container. It also makes the secret configuration compatible with secrets backed by a ServiceAccount which, to me, sounds like a often-used use-case.
As this changes existing behaviour it might be problematic to be backported to 5.4, but I'd like to open discussion on that topic anyway, because I would see …
> Do not treat token as path in fluentd Loki config generator

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/buffer_conf.go
- internal/generator/fluentd/output/buffer_conf_test.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go
- internal/generator/fluentd/output/fluentdforward/fluentdforward_test.go
- internal/generator/fluentd/output/fluentdforward/output_conf_forward_test.go
- internal/generator/fluentd/output/kafka/kafka_test.go
- internal/generator/fluentd/output/kafka/output_conf_kafka_test.go
- internal/generator/fluentd/output/loki/loki_conf_test.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/output/syslog/output_conf_syslog_test.go
This PR:
* Disables chunk backup for all output types in order to not fill the node disk
* https://issues.redhat.com/browse/LOG-2768
* backport of #1520
> LOG-2768: Disable chunk backup

- internal/generator/vector/conf_test.go
- internal/generator/vector/elements/elements.go
- internal/generator/vector/inputs.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- internal/generator/vector/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/vector/output/elasticsearch/elasticsearch.go
- internal/generator/vector/output/elasticsearch/elasticsearch_test.go
- internal/generator/vector/sources.go
- internal/generator/vector/sources_test.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/normalization/audit_logs_format_test.go
- Added VRL to parse host audit logs
- changed VRL source to use toml multiline literal strings, (delimited with `'''` instead of `"""`)
- some audit logs refactoring 
/cc @jcantrill @cahartma 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2378
> LOG-2378: Normalize Host Audit Logs

- files/dashboards/openshift-logging-dashboard.json
This PR updates the dashboard file to show all active shards instead of only primary ones, to comply with what's described in the [documentation](https://docs.openshift.com/container-platform/4.9/logging/cluster-logging-dashboards.html#:~:text=Table%201.%20OpenShift%20Logging%20charts).
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2749
> fix shard number expression in dashboard file

- internal/k8shandler/indexmanagement/index_management.go
Remove redundant line  [index_management.go#L165](https://github.com/openshift/cluster-logging-operator/blob/e8965fc78962fe67352c8d80ebc1c972bd04c5fb/internal/k8shandler/indexmanagement/index_management.go#L165) because value already set in [index_management.go#L156](https://github.com/openshift/cluster-logging-operator/blob/e8965fc78962fe67352c8d80ebc1c972bd04c5fb/internal/k8shandler/indexmanagement/index_management.go#L156)
/cc 
/cherry-pick 
- Bugzilla:
- JIRA:
> code cleanup: remove redundant(duplicate) line

- internal/generator/fluentd/output/loki/loki.go
- internal/generator/fluentd/output/loki/output_conf_loki_test.go
- internal/generator/fluentd/outputs.go
There's currently a difference in behavior between the configuration generators for fluentd and vector when generating configuration for a Loki output: When generating the configuration for a Loki output on vector, the cluster-logging-operator will automatically fall back to the credentials in the `logcollector` ServiceAccount when no user-provided secret is available while the fluentd generator will not use credentials at all.
This PR changes the behavior of the fluentd configuration generator to match the one of the vector config generator, so that for both collectors it is possible to use a Loki output and authenticate using the `logcollector` ServiceAccount.
- JIRA: Related to [LOG-1803](https://issues.redhat.com/browse/LOG-1803)
> Default to collector service-account for fluentd Loki output

- test/e2e/logforwarding/fluent/fluent_secure_test.go
A [previous PR](https://github.com/openshift/cluster-logging-operator/pull/1536) broke this e2e test by automatically injecting a default secret. While it is possible to inject the default secret only for specific output types to keep the behavior of `fluentdForwarder` as it currently is, during the discussion about the workaround we came to the conclusion that it would be worth investing a bit of time making the "disable verify" flag an explicit configuration option.
This PR only disables the offending e2e test without actually introducing the new option just to unblock the CI for the other PRs as quickly as possible.
> Temporarily skip insecure fluentd forwarder test

- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch_secret_test.go
This PR:
* fixes parsing of STS arn role when the partition is not 'aws'
* https://issues.redhat.com/browse/LOG-2772
cc @cahartma
> LOG-2772: fix parsing of STS role

- internal/factory/daemonset.go
The cluster-logging-operator uses a DaemonSet to manage the collector instances running on all cluster nodes.
Currently the default deployment strategy of the DaemonSet is used, which only allows a single instance to be "unavailable" at once, similar to a Deployment rollout.
While this strategy does make sense for deployments with more than once instance for high-availability reasons, it's unnecessary for the DaemonSet as each collector is responsible for its own node and no HA is done between the instances. The current strategy effectively only slows down the application of a new configuration.
The aim of this change is to replace the current configuration of the deployment strategy used by the DaemonSet with one that allows all instances to be replaced at once.
- JIRA: …
> LOG-2785: Replace all collector instances at once

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
Suppress high number of type deprecation logs, like:
`[types removal] Specifying types in bulk requests is deprecated.`
More details here: https://github.com/uken/fluent-plugin-elasticsearch/issues/766
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2664
> LOG-2664: suppress type_name deprecation warnings

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
Suppress high number of type deprecation logs, like:
`[types removal] Specifying types in bulk requests is deprecated.`
More details here: https://github.com/uken/fluent-plugin-elasticsearch/issues/766
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:
> [release-5.4] LOG-2664: suppress type_name deprecation warnings

- files/dashboards/fluentd/openshift-logging-dashboard.json
- files/dashboards/vector/openshift-logging-dashboard.json
- internal/k8shandler/reconciler.go
- internal/metrics/dashboards.go
- internal/metrics/dashboards_test.go
This PR adds a dashboard which gets deployed when vector is used as the collector. It shows metrics obtained from vector.
The dashboard consists of the following sections.
1. Overview.
This shows total bytes processed for container , audit, journald logs. and total bytes sent for the cluster.
2. Machine
This shows the CPU usage, memory usage, and open files of vector.
3. Throughput
This shows error distribution by error type, and buffer usage by component type
4. Produced logs.
This shows top producing containers bytes/sec, and a table of top producing containers in last 24 hours.
Known issues:
- vector does not add node name with the metric labels, so many graphs do not have node information, but rather the legends show pod names
- this is a initial set of graphs/tables, more can be …
> LOG-2583: Add vector dashboard

- apis/logging/v1/output_types.go
- internal/collector/cloudwatch.go
- internal/constants/constants.go
- internal/generator/fluentd/output/cloudwatch/aws.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch.go
- internal/generator/fluentd/output/cloudwatch/cloudwatch_secret_test.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/security/security.go
- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
When using sts to authenticate with cloudwatch, we should additionally accept the secret format created from a credential request.   We will  accept `credentials` as a valid secret key.    The original story and feature implementation only accepted the `role_arn` as a valid key.  (must also contain a correctly formatted valid role arn)
/assign @jcantrill @vimalk78 
/cc @syedriko 
- https://issues.redhat.com/browse/LOG-2767
> LOG-2767: sts cloudwatch secret should accept format from credrequest

- internal/generator/vector/conf_test.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/sources_test.go
- Removed `ignore_older_secs` from audit log [source] configuration for vector. 
This PR addresses an issue with audit logs not being forwarded when using Vector. The problem stemmed from a configuration parameter for Vector called `ignore_older_secs` which "Ignores files with a data modification date older than the specified number of seconds." 
Originally this was set to 600 seconds. Removing the parameter from the audit log configurations should resolve this issue.
/cc @cahartma @jcantrill 
- [LOG-2662](https://issues.redhat.com/browse/LOG-2662)
> LOG-2662: Losing audit logs may happen when using Vector

- controllers/clusterlogging/clusterlogging_controller.go
- internal/k8shandler/logstore_lokistack.go
- internal/k8shandler/reconciler.go
As per fix for LOG-2063, fluentd/vector only CL instance deployments should be stopped when CLF is missing. In the scenario where CLF is deleted, Collector DaemonSets are not removed/terminated.
- https://issues.redhat.com/browse/LOG-2703
> LOG-2703: Remove collector when no forwarder or logStore

- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- internal/generator/vector/conf_test.go
- internal/generator/vector/source/audit_logs.go
- internal/generator/vector/source/kubernetes_logs.go
- internal/generator/vector/sources_test.go
Summary:
- Changed `glob_minimum_cooldown_ms` from the default of 60s to 15s for audit and kubernetes logs when forwarding with Vector.
Details:
This PR addresses the issue where Vector sometimes reports "Failed to annotate event with pod metadata" errors. The proposed fix is to change `glob_minimum_cooldown_ms` to 15s instead of the default of 60s.
/cc @jcantrill @cahartma 
- https://issues.redhat.com/browse/LOG-2648
> LOG-2648: glob_minimum_cooldown_ms of vector is too big (60000ms)

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/sources_test.go
This PR:
updates the metrics server to bind to the default interface
* https://issues.redhat.com/browse/LOG-2821
> LOG-2821: Allow metrics to bind to default interface

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/elements/record_modifier.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/cloudwatch/output_cloudwatch_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- test/framework/functional/factory.go
- test/framework/functional/write.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_test.go
- test/functional/outputs/loki/audit_logs_test.go
Checks and replace not valid UTF-8 symbols 
```
<filter pattern>
@type record_modifier
char_encoding utf-8:utf-8
</filter>
```
/assign 
/cherry-pick release-5.4 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2784
> LOG-2784: checking is symbols valid 'utf-8', if not replace to the valid one

- internal/k8shandler/collection.go
- internal/k8shandler/forwarding.go
Starting with Kubernetes 1.24 (OCP 4.11), ServiceAccounts will no longer automatically have an associated secret containing a token. The cluster-logging-operator currently looks for a secret containing a token associated with the `logcollector` ServiceAccount it creates for the collector DaemonSet. This secret is used for "default credentials" for the log forwarders. Failing to find the secret results in some forwarder configurations no longer having valid credentials.
This PR introduces a manually created secret to the cluster-logging-operator which then can be used like the automatically-created one before.
- JIRA: https://issues.redhat.com/browse/LOG-2778
> LOG-2778: Create secret for logcollector serviceaccount manually

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/elements/copy.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go
- internal/generator/fluentd/pipeline_to_output_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/sources_test.go
1. Prometheus listener needs <transport tls> configuration to enable async HTTP server instead of Webrick.
2. Should fix: `2022-04-14 05:43:19 +0000 [warn]: 'deep_copy' parameter is deprecated: use 'copy_mode' parameter instead`
/cc 
/assign  @jcantrill  
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2464
> [release-5.4]LOG-2464: replace deprecated configuration parameter

- internal/generator/vector/conf_test.go
- internal/generator/vector/inputs.go
- internal/generator/vector/normalize.go
- internal/generator/vector/normalize_test.go
- internal/generator/vector/sources_to_pipelines_test.go
- test/functional/normalization/audit_logs_format_test.go
Fixes issue where the OVN audit logs are missing the level field when using Vector as collector,   I've updated the if/else logic to leave the field if it exists, in order to match current fluentd functionality.
Additionally, the hostname field was consolidated and moved to the audit remap.
/assign @vimalk78 @syedriko  @vparfonov 
- https://issues.redhat.com/browse/LOG-2793
> LOG-2793: Vector ovn audit logs missing level field

- internal/generator/fluentd/elements/copy.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/pipeline_to_output_test.go
Should fix 
`2022-04-14 05:43:19 +0000 [warn]: 'deep_copy' parameter is deprecated: use 'copy_mode' parameter instead`
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2464
> LOG-2464: replace deprecated configuration parameter

- internal/generator/vector/output/loki/loki.go
- internal/generator/vector/output/loki/loki_conf_test.go
This PR addresses a problem with `Vector` forwarding logs to the `Loki` with the error
``` 
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=A non-successful status returned: 404 Not Found component_kind="sink" component_type="loki" component_id=loki_infra component_name=loki_infra
x Health check for "loki_infra" failed
```
Since logs are still forwarded to `Loki` even with this healthcheck error, it was decided to disable the healthcheck in the `[sink] ` portion of vector's config file, `vector.toml` with the configuration `healthcheck.enabled = false`.
/cc @cahartma @jcantrill 
/assign @jcantrill @vimalk78 
https://issues.redhat.com/browse/LOG-2763
> LOG-2763: Vector's healthcheck fails when forwarding logs to Lokistack

- hack/testing-olm/test-040-eventrouter.sh
- internal/generator/fluentd/conf.go
- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/ingress.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/output_conf_es_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
- internal/generator/fluentd/prometheus.go
- internal/generator/fluentd/source/audit_logs.go
- internal/generator/fluentd/source/container_logs.go
- internal/generator/fluentd/sources.go
- internal/generator/fluentd/sources_test.go
- internal/generator/vector/sources.go
- internal/k8shandler/fluentd.go
- test/e2e/logforwarding/fluent/fluent_secure_test.go
- test/e2e/logforwarding/fluent/fluent_test.go
- test/framework/functional/message_templates.go
- test/functional/normalization/eventrouter_test.go
- test/functional/normalization/message_format_test.go
- test/functional/outputs/forward_to_elasticsearch_test.go
This PR:
* Optimizes the fluent conf to address performance issues
* Depends on https://github.com/ViaQ/logging-fluentd/pull/37
* Depends on a fluent image with https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/347
* https://issues.redhat.com/browse/LOG-2770
based on rudamentary testing of viaq optimizations which enable only features that are being used:
```
filtering                rate m/s
---------                ---------
no filtering             100,000
as-is                     28,000
remove es_index           35,000   *
remove debug state        30,000
remove prune_labels       28,000
remove flat_labels        31,000   *
remove rename_time        15,000   ?
remove delete emtpy       45,000    
remove openshift.sequenc  30,000
remove handle_undefined …
```
> LOG-2770: optimize fluent conf for throughput

- internal/k8shandler/collection.go
- internal/k8shandler/forwarding.go
Starting with Kubernetes 1.24 (OCP 4.11), ServiceAccounts will no longer automatically have an associated secret containing a token. The cluster-logging-operator currently looks for a secret containing a token associated with the logcollector ServiceAccount it creates for the collector DaemonSet. This secret is used for "default credentials" for the log forwarders. Failing to find the secret results in some forwarder configurations no longer having valid credentials.
This PR introduces a manually created secret to the cluster-logging-operator which then can be used like the automatically-created one before.
- Backport of #1561 
- JIRA: [LOG-2840](https://issues.redhat.com//browse/LOG-2840)
> [release-5.4] LOG-2840: Create secret for logcollector serviceaccount manually

- test/e2e/consoleplugin/smoke_test/consoleplugin_test.go
Add missing cleanup actions to the console e2e test, suspected to be the cause of logforwarding e2e test flakes.
/cc @xperimental
/cc @periklis
> LOG-2667: Fix test flake caused by console test.

- internal/k8shandler/forwarding.go
- internal/k8shandler/forwarding_test.go
- internal/k8shandler/logstore_lokistack.go
- internal/k8shandler/logstore_lokistack_test.go
Currently the LokiStack integration always creates two outputs, one for each of the log streams that is forwarded by default (`application` and `infrastructure`). While these outputs are called `default` and `default-infra`, they do not behave like the `default` output that is available when using the ElasticSearch log storage.
This PR changes the behaviour of the `default` output reference when using LokiStack, so that it is internally split into different outputs depending on the log stream forwarded into it. This should ensure that an input is always forwarded into the correct tenant, thus enforcing the correct authorization. Additionally this enables the use of custom `ClusterLogForwarder` configurations that were usable with the ElasticSearch log storage, for example to forward …
> LOG-2864: Compatibility with ES default output

- internal/collector/collector.go
- internal/collector/collector_test.go
This PR:
* fixes vector deployments to honor the spec'd memory
* https://issues.redhat.com/browse/LOG-2873
> LOG-2873: fix resources for vector when spec'd

- bundle/manifests/clusterlogging.clusterserviceversion.yaml
- config/manifests/bases/clusterlogging.clusterserviceversion.yaml
This PR adds the `operators.openshift.io/valid-subscription` annotation to the operator metadata.
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-2924
> LOG-2924: Adding valid subscription annotation to metadata

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/output/elasticsearch/elasticsearch_test.go
- internal/generator/fluentd/output/elasticsearch/viaq_data_model.go
- internal/generator/fluentd/output/output_fluentd_buffer_test.go
After adding multiline error detection in #1192, `kubernetes` prefix tag removed, so pattern for infrastructure index not match all logs going to the application index 
/cc @cahartma 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2801
> LOG-2801: fix pattern for infrastructure indexing

- Dockerfile.e2e
- test/framework/functional/framework.go
- test/helpers/oc/logs.go
This PR:
* Dumps container logs upon functional test failure
Trying to unblock https://github.com/openshift/cluster-logging-operator/pull/1602
> dump container logs on functional failure

- apis/logging/v1/cluster_log_forwarder.go
- controllers/forwarding/forwarding_controller.go
This PR addresses `LOG-1300: The invalid event can't be collected` in the `ClusterLogForwarder` instance. Any invalid events in the `ClusterLogForwarder` instance will now display when `oc get events` is performed on the CLF instance. These events can also be seen on the openshift console.
/cc  @cahartma 
- https://issues.redhat.com/browse/LOG-1300
> LOG-1300: The invalid event can't be collected.

- Dockerfile
- Dockerfile.in
- origin-meta.yaml
This PR:
* fixes CVE-2022-30631 cluster-logging-operator-container: golang: compress/gzip: stack exhaustion in Reader.Read
* https://issues.redhat.com/browse/LOG-2886
> LOG-2886: fix CVE-2022-30631

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- test/client/test.go
- test/client/test_test.go
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/framework/functional/common/loglevel.go
- test/framework/functional/fluentd/deploy.go
- test/framework/functional/framework.go
- test/framework/functional/message_templates.go
- test/framework/functional/vector/deploy.go
- test/framework/functional/write.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
This PR:
* Enables functional testing of infrastructure logs for vector, specifically those related to JSON parsing
* Add API validation to reject invalid structured type configuration
* Moves test of invalid structure type from functional to e2e in order to test API validation 
* https://issues.redhat.com/browse/LOG-2862
> LOG-2862: Enable function JSON parsing tests for vector

- test/e2e/logforwarding/elasticsearchmanaged/forwarding_with_defaults_test.go
- test/e2e/logforwarding/loki/forward_to_loki_test.go
- test/e2e/logforwarding/syslog/forward_to_syslog_test.go
- test/framework/e2e/framework.go
- test/framework/functional/framework.go
- test/helpers/oc/runner.go
This PR:
* extends the timeout to determine if fluent is started to account for slow pod boot
* refactors e2e test in effort to make it consistent
> extend functional timeout to account for slow pod startup

- internal/generator/vector/output/kafka/kafka.go
- internal/generator/vector/output/kafka/kafka_test.go
- internal/generator/vector/output/kafka/security.go
During #1548 I failed to realize that the Kafka output for vector does not use the common `tls.*` options for disabling validation of the certificate.
This PR fixes two issues with the Kafka output:
- TLS was not enabled if the URL contained a `tls://` scheme but the secret did not contain any other TLS options
- Use Kafka's custom option to disable verification of the certificate
/cc @cahartma 
- JIRA: [LOG-2285](https://issues.redhat.com//browse/LOG-2285)
> LOG-2285: Fix disabling certificate validation for Kafka output

- internal/generator/fluentd/conf_test.go
- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/ingress.go
- test/functional/normalization/audit_logs_format_test.go
- test/matchers/log_format.go
This PR:
* sets the timestamp field that was broken with fluentd viaq plugin refactoring
* https://issues.redhat.com/browse/LOG-2923
> LOG-2923: fix timestamp field for kube and openshift event audit logs

- files/fluentd/fluentd_prometheus_alerts.yaml
This PR:
* fixes fluent alert compliance by adding namespace to the alerts
https://issues.redhat.com/browse/LOG-1823
> LOG-1823: fix fluent alerts style compliance

- internal/generator/vector/conf_test.go
- internal/generator/vector/metrics.go
- internal/generator/vector/outputs.go
Metrics generated by Vector lack a label whose value is the name opf the kubernetes node on which the collector runs. best available now is hostname which is same as pod name. But podname is not suitable because it is transient. this name changes every time collector is re-deloyed.
This PR adds a new label to the emitted metrics whose value is same as the value of environment variable `${VECTOR_SELF_NODE_NAME}`
The new label will also help in determining correct values to raise an alert, and clear an alert.
metric after this change
```
{
"name": "internal_metrics_cardinality_total",
"namespace": "vector",
"tags": {
"host": "collector-7vkk5",
"hostname": "ip-10-0-140-184.ec2.internal"
},
"timestamp": "2022-09-12T11:59:20.964479613Z",
"kind": "absolute",
"counter": {
"value": 305.0
}
}
``` …
> LOG-2911: Add nodename label to vector metrics

- apis/logging/v1/output_types.go
- bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml
- config/crd/bases/logging.openshift.io_clusterlogforwarders.yaml
- test/e2e/logforwarding/elasticsearchunmanaged/forward_to_unmanaged_elasticsearch_test.go
- test/functional/outputs/elasticsearch/forward_to_elasticsearch_index_test.go
This PR:
* reverts the api validation and restriction that was introduced as part of https://github.com/openshift/cluster-logging-operator/pull/1622
* https://issues.redhat.com/browse/LOG-3051
> LOG-3501: revert api validation for structuredTypeKey

- files/fluentd/fluentd_prometheus_alerts.yaml
A `FluentdNodeDown` critical alert is raised as soon as fluentd is deployed.
The associated query `up{job="collector"}` results in metrics which also include `logfilemetricexporter` , this could be messing up the logic for alerting
This PR 
- adds `container="collector"` label filter
- fixes alert labels to use `service="collector"` instead of `service="fluentd"`
/cc 
/assign 
/cherry-pick release-5.5
/cherry-pick release-5.4
- JIRA: https://issues.redhat.com/browse/LOG-3055
> LOG-3055: Fix Fluentd Alert query expr and labels

- internal/generator/fluentd/fluent_conf_test.go
- internal/generator/fluentd/pipeline_to_output.go
- internal/generator/fluentd/pipeline_to_output_test.go
- test/framework/functional/framework.go
- test/functional/normalization/json_parsing_test.go
Add to the fluentd configuration:
` emit_invalid_record_to_error false`
This will suspend the warning in case fluentd detecting a non-JSON message, but logs will still be forwarded to the non-JSON index.
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-1806
> LOG-1806: ParserError warning message suppressed, but logs will still be forwarded to the non-JSON index
